# コホート定義 {#CohortDefinitions}

この付録には、本書全体で使用されるコホート定義が含まれています。

## ACE阻害薬 {#AceInhibitors}

#### 初回イベントコホート {.unnumbered}

以下のいずれかを持つ人：

-   その人の履歴において初回の*ACE阻害薬*（表 \@ref(tab:aceInhibitors)）への曝露

かつ、インデックス日から遡って少なくとも365日前からインデックス日0日後の間の連続した観察があり、初期イベントを以下に限定します：その個人における全てのイベント。

適格コホートとしてイベントを次のように限定します：その個人における全てのイベント。

#### 終了日の考え方 {.unnumbered}

カスタム薬剤曝露期間の終了基準：ここでは、指定されたコンセプトセットで見つかったコードから薬剤曝露期間を作成します。インデックスイベントが曝露期間内で見つかった場合、コホート終了日はその曝露期間の終了日を使用します。そうでない場合、そのインデックスイベントを含む観察期間の終了日を使用します。

*ACE阻害薬*（表 \@ref(tab:aceInhibitors)）の曝露期間終了日を使用

-   曝露期間の間隔は30日を許容
-   曝露期間終了後に0日を追加

#### コホート圧縮の考え方 {.unnumbered}

30日間のギャップによりコホートを圧縮します。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名     | 除外   | 下位層 | マッピング元 |
|:-------------|:-----------------|:-------|:-------|:-------------|
| 1308216      | リシノプリル     | いいえ | はい   | いいえ       |
| 1310756      | モエキシプリル   | いいえ | はい   | いいえ       |
| 1331235      | キナプリル       | いいえ | はい   | いいえ       |
| 1334456      | ラミプリル       | いいえ | はい   | いいえ       |
| 1335471      | ベナゼプリル     | いいえ | はい   | いいえ       |
| 1340128      | カプトプリル     | いいえ | はい   | いいえ       |
| 1341927      | エナラプリル     | いいえ | はい   | いいえ       |
| 1342439      | トランドラプリル | いいえ | はい   | いいえ       |
| 1363749      | フォシノプリル   | いいえ | はい   | いいえ       |
| 1373225      | ペリンドプリル   | いいえ | はい   | いいえ       |

: (#tab:aceInhibitors) ACE阻害薬

## ACE阻害薬単剤療法新規ユーザー {#AceInhibitorsMono}

#### 初回イベントコホート {.unnumbered}

以下のいずれかを持つ人：

-   その人の履歴において初回の*ACE阻害薬*（表 \@ref(tab:aceInhibitorsMono)）への曝露

かつ、インデックス日から遡って少なくとも365日前からインデックス日0日後の間の連続した観察があり、初期イベントを以下に限定します：その個人における最も早いイベント。

#### 選択ルール {.unnumbered}

選択基準#1：治療開始前1年間に高血圧の診断を受けています。

以下の全ての基準を満たします：

-   インデックス開始日から遡って365日前からインデックス開始日0日後の間に少なくとも1回の*高血圧性障害*（表 \@ref(tab:hypertensionAceMono)）のコンディションが出現します。

選択基準#2：病歴に高血圧治療薬の使用がありません。

以下の全ての基準を満たします：

-   インデックス開始日1日前までのすべての日に始まる*高血圧薬*（表 \@ref(tab:htnDrugsAceMono)）の薬物使用が完全に0回です。

選択基準#3：ACE単剤療法のみを受けており、併用治療を行っていません。

以下のすべての基準を満たします：

-   インデックス開始日0日前から7日後の間に始まる*高血圧薬*（表 \@ref(tab:htnDrugsAceMono)）の明確な薬物曝露期間の出現がちょうど1回です。

適格コホートとしてイベントを次のように限定します：その個人における最も早いイベント。

#### 終了日の考え方 {.unnumbered}

カスタム薬剤曝露期間の終了の基準：この考え方は、指定されたコンセプトセットで見つかったコードから薬剤曝露期間を作成します。インデックスイベントが曝露期間内で見つかった場合、コホートの終了日はその曝露期間の終了日を使用します。そうでない場合、インデックスイベントを含む観察期間の終了日を使用します。

*ACE阻害薬*の曝露期間の終了日 (表 \@ref(tab:aceInhibitorsMono))

-   薬剤曝露間隔が30日を許容します。
-   薬剤曝露終了後0日追加します。

#### コホート圧縮の考え方 {.unnumbered}

0日間のギャップサイズで期間によりコホート圧縮します。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名     | 除外   | 下位層 | マッピング元 |
|:-------------|:-----------------|:-------|:-------|:-------------|
| 1308216      | リシノプリル     | いいえ | はい   | いいえ       |
| 1310756      | モエキシプリル   | いいえ | はい   | いいえ       |
| 1331235      | キナプリル       | いいえ | はい   | いいえ       |
| 1334456      | ラミプリル       | いいえ | はい   | いいえ       |
| 1335471      | ベナゼプリル     | いいえ | はい   | いいえ       |
| 1340128      | カプトプリル     | いいえ | はい   | いいえ       |
| 1341927      | エナラプリル     | いいえ | はい   | いいえ       |
| 1342439      | トランドラプリル | いいえ | はい   | いいえ       |
| 1363749      | フォシノプリル   | いいえ | はい   | いいえ       |
| 1373225      | ペリンドプリル   | いいえ | はい   | いいえ       |

: (#tab:aceInhibitorsMono) ACE阻害薬

| コンセプトID | コンセプト名 | 除外   | 下位層 | マッピング元 |
|:-------------|:-------------|:-------|:-------|:-------------|
| 316866       | 高血圧性障害 | いいえ | はい   | いいえ       |

: (#tab:hypertensionAceMono) 高血圧性障害

| コンセプトID | コンセプト名         | 除外   | 下位層 | マッピング元 |
|:-------------|:---------------------|:-------|:-------|:-------------|
| 904542       | トリアムテレン       | いいえ | はい   | いいえ       |
| 907013       | メトラゾン           | いいえ | はい   | いいえ       |
| 932745       | ブメタニド           | いいえ | はい   | いいえ       |
| 942350       | トルセミド           | いいえ | はい   | いいえ       |
| 956874       | フロセミド           | いいえ | はい   | いいえ       |
| 970250       | スピロノラクトン     | いいえ | はい   | いいえ       |
| 974166       | ヒドロクロロチアジド | いいえ | はい   | いいえ       |
| 978555       | インダパミド         | いいえ | はい   | いいえ       |
| 991382       | アミロリド           | いいえ | はい   | いいえ       |
| 1305447      | メチルドパ           | いいえ | はい   | いいえ       |
| 1307046      | メトプロロール       | いいえ | はい   | いいえ       |
| 1307863      | ベラパミル           | いいえ | はい   | いいえ       |
| 1308216      | リシノプリル         | いいえ | はい   | いいえ       |
| 1308842      | バルサルタン         | いいえ | はい   | いいえ       |
| 1309068      | ミノキシジル         | いいえ | はい   | いいえ       |
| 1309799      | エプレレノン         | いいえ | はい   | いいえ       |
| 1310756      | モエキシプリル       | いいえ | はい   | いいえ       |
| 1313200      | ナドロール           | いいえ | はい   | いいえ       |
| 1314002      | アテノロール         | いいえ | はい   | いいえ       |
| 1314577      | ネビボロール         | いいえ | はい   | いいえ       |
| 1317640      | テルミサルタン       | いいえ | はい   | いいえ       |
| 1317967      | アリスキレン         | いいえ | はい   | いいえ       |
| 1318137      | ニカルジピン         | いいえ | はい   | いいえ       |
| 1318853      | ニフェジピン         | いいえ | はい   | いいえ       |
| 1319880      | ニソルジピン         | いいえ | はい   | いいえ       |
| 1319998      | アセブトロール       | いいえ | はい   | いいえ       |
| 1322081      | ベタキソロール       | いいえ | はい   | いいえ       |
| 1326012      | イスラジピン         | いいえ | はい   | いいえ       |
| 1327978      | ペンブトロール       | いいえ | はい   | いいえ       |
| 1328165      | ジルチアゼム         | いいえ | はい   | いいえ       |
| 1331235      | キナプリル           | いいえ | はい   | いいえ       |
| 1332418      | アムロジピン         | いいえ | はい   | いいえ       |
| 1334456      | ラミプリル           | いいえ | はい   | いいえ       |
| 1335471      | ベナゼプリル         | いいえ | はい   | いいえ       |
| 1338005      | ビソプロロール       | いいえ | はい   | いいえ       |
| 1340128      | カプトプリル         | いいえ | はい   | いいえ       |
| 1341238      | テラゾシン           | いいえ | はい   | いいえ       |
| 1341927      | エナラプリル         | いいえ | はい   | いいえ       |
| 1342439      | トランドラプリル     | いいえ | はい   | いいえ       |
| 1344965      | グアンファシン       | いいえ | はい   | いいえ       |
| 1345858      | ピンドロール         | いいえ | はい   | いいえ       |
| 1346686      | エプロサルタン       | いいえ | はい   | いいえ       |
| 1346823      | カルベジロール       | いいえ | はい   | いいえ       |
| 1347384      | イルベサルタン       | いいえ | はい   | いいえ       |
| 1350489      | プラゾシン           | いいえ | はい   | いいえ       |
| 1351557      | カンデサルタン       | いいえ | はい   | いいえ       |
| 1353766      | プロプラノロール     | いいえ | はい   | いいえ       |
| 1353776      | フェロジピン         | いいえ | はい   | いいえ       |
| 1363053      | ドキサゾシン         | いいえ | はい   | いいえ       |
| 1363749      | フォシノプリル       | いいえ | はい   | いいえ       |
| 1367500      | ロサルタン           | いいえ | はい   | いいえ       |
| 1373225      | ペリンドプリル       | いいえ | はい   | いいえ       |
| 1373928      | ヒドララジン         | いいえ | はい   | いいえ       |
| 1386957      | ラベタロール         | いいえ | はい   | いいえ       |
| 1395058      | クロルタリドン       | いいえ | はい   | いいえ       |
| 1398937      | クロニジン           | いいえ | はい   | いいえ       |
| 40226742     | オルメサルタン       | いいえ | はい   | いいえ       |
| 40235485     | アジルサルタン       | いいえ | はい   | いいえ       |

: (#tab:htnDrugsAceMono) 高血圧治療薬

## 急性心筋梗塞（AMI） {#Ami}

#### 初回イベントコホート {.unnumbered}

以下のいずれかを持つ人：

-   *急性心筋梗塞*（表 \@ref(tab:ami)）のコンディション出現

かつ、インデックス日から遡って少なくとも0日前からインデックス日0日後の間の連続した観察があり、インデックスイベントを以下に限定します：その個人における全てのイベント。

主要イベントがありとなるのは、以下のいずれかの基準を満たす人：

-   インデックス日から遡るすべての日から0日後の間に始まり、ビジット終了日がインデックス開始日0日後からインデックス開始日後の全ての日の間に終了すると一致する*入院または救急室ビジット* (表 \@ref(tab:inpatientOrErAmi))のビジット出現が少なくとも1件。

インデックスイベントのコホート次のように限定します：その個人における全てのイベント。

#### 終了日の考え方 {.unnumbered}

日付オフセット終了基準：

このコホート定義の終了日は、インデックスイベントの開始日から7日後とします。

#### コホート圧縮の考え方 {.unnumbered}

180日間のギャップサイズで期間によりコホートを圧縮します。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名   | 除外   | 下位層 | マッピング元 |
|:-------------|:---------------|:-------|:-------|:-------------|
| 314666       | 陳旧性心筋梗塞 | はい   | はい   | いいえ       |
| 4329847      | 心筋梗塞       | いいえ | はい   | いいえ       |

: (#tab:ami) 急性心筋梗塞

| コンセプトID | コンセプト名             | 除外   | 下位層 | マッピング元 |
|:-------------|:-------------------------|:-------|:-------|:-------------|
| 262          | 救急室および入院ビジット | いいえ | はい   | いいえ       |
| 9201         | 入院ビジット             | いいえ | はい   | いいえ       |
| 9203         | 救急室ビジット           | いいえ | はい   | いいえ       |

: (#tab:inpatientOrErAmi) 入院または救急室ビジット

## 血管性浮腫 {#Angioedema}

#### 初回イベントコホート {.unnumbered}

以下のいずれかを持つ人：

-   *血管性浮腫*のコンディション出現（表 \@ref(tab:angioedema)）

イベント発生日の前と後少なくとも0日間の連続した観察期間を持ち、初回イベントを次のように限定します：その個人における全てのイベント。

主要イベントがありとなるのは、以下のいずれかの基準を満たす人：

-   *入院または救急室ビジット* インデックス日前全ての日と後0日の間に開始し、インデックス日前0日と後全ての日の間に終了する(表 \@ref(tab:inpatientOrEr))で特定されるビジットが少なくとも1回発生します。

初回イベントのコホートを次のように限定します：各個人の全てのイベント。

適格なコホートを次のように限定します：各個人の全てのイベント。

#### 終了日の考え方 {.unnumbered}

このコホート定義の終了日はインデックスイベントの開始日から7日後とします。

#### コホート圧縮の考え方 {.unnumbered}

30日間のギャップサイズで期間によりコホートを圧縮します。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名 | 除外   | 下位層 | マッピング元 |
|:-------------|:-------------|:-------|:-------|:-------------|
| 432791       | 血管性浮腫   | いいえ | はい   | いいえ       |

: (#tab:angioedema) 血管性浮腫

| コンセプトID | コンセプト名             | 除外   | 下位層 | マッピング元 |
|:-------------|:-------------------------|:-------|:-------|:-------------|
| 262          | 救急室および入院ビジット | いいえ | はい   | いいえ       |
| 9201         | 入院ビジット             | いいえ | はい   | いいえ       |
| 9203         | 救急室ビジット           | いいえ | はい   | いいえ       |

: (#tab:inpatientOrEr) 入院または救急室ビジット

## サイアザイド様利尿薬単剤療法の新規ユーザー使用者 {#ThiazidesMono}

#### 初回イベントコホート {.unnumbered}

以下のいずれかを持つ人：

-   その人の履歴において初回の*サイアザイドまたはサイアザイド様利尿薬*（表 \@ref(tab:thiazidesMono)）への曝露

かつ、インデックス日からの遡って少なくとも365日間からインデックス日0日後の間の連続した観察があり、初回イベントを次のように限定します：その個人における最も早いイベント。

#### 選択ルール {.unnumbered}

選択基準1：治療前の1年間に高血圧の診断をうけています。

以下の全ての基準を満たします：

-   インデックス開始日から遡って365日前からインデックス開始日0日後の間に少なくとも1回の *高血圧性障害* (表 \@ref(tab:hypertensionThzMono))のコンディションが出現します。

選択基準#2：病歴に高血圧治療薬の使用がありません。

以下の全ての基準を満たします：

-   インデックス開始日1日前までのすべての日に始まる*高血圧薬*(表 \@ref(tab:htnDrugsThzMono))の薬物使用が完全に0回です。

選択基準#3：ACE単剤療法のみを受けており、併用治療を行っていません。

以下のすべての基準を満たします：

-   インデックス開始日0日前から7日後の間に始まる*高血圧薬*(表 \@ref(tab:htnDrugsThzMono))の明確な薬物曝露期間の出現がちょうど1回です。

適格コホートとしてイベントを次のように限定します：その個人における最も早いイベント。

#### 終了日の考え方 {.unnumbered}

カスタム薬剤曝露期間の終了の基準：この考え方は、指定されたコンセプトセットで見つかったコードから薬剤曝露期間を作成します。インデックスイベントが曝露期間内で見つかった場合、コホートの終了日はその曝露期間の終了日を使用します。そうでない場合、インデックスイベントを含む観察期間の終了日を使用します。

*サイアザイドまたはサイアザイド様利尿薬*（表 \@ref(tab:thiazidesMono)）の曝露期間の終了日

-   薬剤曝露間隔が30日を許容します。
-   薬剤曝露終了後0日追加します。

#### コホート圧縮の考え方 {.unnumbered}

0日間のギャップによりコホートを圧縮します。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名         | 除外   | 下位層 | マッピング元 |
|:-------------|:---------------------|:-------|:-------|:-------------|
| 907013       | メトラゾン           | いいえ | はい   | いいえ       |
| 974166       | ヒドロクロロチアジド | いいえ | はい   | いいえ       |
| 978555       | インダパミド         | いいえ | はい   | いいえ       |
| 1395058      | クロルタリドン       | いいえ | はい   | いいえ       |

: (#tab:thiazidesMono) サイアザイドまたはサイアザイド様利尿薬

| コンセプトID | コンセプト名 | 除外   | 下位層 | マッピング元 |
|:-------------|:-------------|:-------|:-------|:-------------|
| 316866       | 高血圧性障害 | いいえ | はい   | いいえ       |

: (#tab:hypertensionThzMono) 高血圧性障害

| コンセプトID | コンセプト名         | 除外   | 下位層 | マッピング元 |
|:-------------|:---------------------|:-------|:-------|:-------------|
| 904542       | トリアムテレン       | いいえ | はい   | いいえ       |
| 907013       | メトラゾン           | いいえ | はい   | いいえ       |
| 932745       | ブメタニド           | いいえ | はい   | いいえ       |
| 942350       | トルセミド           | いいえ | はい   | いいえ       |
| 956874       | フロセミド           | いいえ | はい   | いいえ       |
| 970250       | スピロノラクトン     | いいえ | はい   | いいえ       |
| 974166       | ヒドロクロロチアジド | いいえ | はい   | いいえ       |
| 978555       | インダパミド         | いいえ | はい   | いいえ       |
| 991382       | アミロライド         | いいえ | はい   | いいえ       |
| 1305447      | メチルドパ           | いいえ | はい   | いいえ       |
| 1307046      | メトプロロール       | いいえ | はい   | いいえ       |
| 1307863      | ベラパミル           | いいえ | はい   | いいえ       |
| 1308216      | リシノプリル         | いいえ | はい   | いいえ       |
| 1308842      | バルサルタン         | いいえ | はい   | いいえ       |
| 1309068      | ミノキシジル         | いいえ | はい   | いいえ       |
| 1309799      | エプレレノン         | いいえ | はい   | いいえ       |
| 1310756      | モエキシプリル       | いいえ | はい   | いいえ       |
| 1313200      | ナドロール           | いいえ | はい   | いいえ       |
| 1314002      | アテノロール         | いいえ | はい   | いいえ       |
| 1314577      | ネビボロール         | いいえ | はい   | いいえ       |
| 1317640      | テルミサルタン       | いいえ | はい   | いいえ       |
| 1317967      | アリスキレン         | いいえ | はい   | いいえ       |
| 1318137      | ニカルディピン       | いいえ | はい   | いいえ       |
| 1318853      | ニフェジピン         | いいえ | はい   | いいえ       |
| 1319880      | ニソルジピン         | いいえ | はい   | いいえ       |
| 1319998      | アセブトロール       | いいえ | はい   | いいえ       |
| 1322081      | ベタキソール         | いいえ | はい   | いいえ       |
| 1326012      | イスラジピン         | いいえ | はい   | いいえ       |
| 1327978      | ペンブトロール       | いいえ | はい   | いいえ       |
| 1328165      | ジルチアゼム         | いいえ | はい   | いいえ       |
| 1331235      | キナプリル           | いいえ | はい   | いいえ       |
| 1332418      | アムロジピン         | いいえ | はい   | いいえ       |
| 1334456      | ラミプリル           | いいえ | はい   | いいえ       |
| 1335471      | ベナゼプリル         | いいえ | はい   | いいえ       |
| 1338005      | ビソプロロール       | いいえ | はい   | いいえ       |
| 1340128      | カプトプリル         | いいえ | はい   | いいえ       |
| 1341238      | テラゾシン           | いいえ | はい   | いいえ       |
| 1341927      | エナラプリル         | いいえ | はい   | いいえ       |
| 1342439      | トランドラプリル     | いいえ | はい   | いいえ       |
| 1344965      | グアンファシン       | いいえ | はい   | いいえ       |
| 1345858      | ピンドロール         | いいえ | はい   | いいえ       |
| 1346686      | エプロサルタン       | いいえ | はい   | いいえ       |
| 1346823      | カルベジロール       | いいえ | はい   | いいえ       |
| 1347384      | イルベサルタン       | いいえ | はい   | いいえ       |
| 1350489      | プラゾシン           | いいえ | はい   | いいえ       |
| 1351557      | カンデサルタン       | いいえ | はい   | いいえ       |
| 1353766      | プロプラノロール     | いいえ | はい   | いいえ       |
| 1353776      | フェロジピン         | いいえ | はい   | いいえ       |
| 1363053      | ドキサゾシン         | いいえ | はい   | いいえ       |
| 1363749      | フォシノプリル       | いいえ | はい   | いいえ       |
| 1367500      | ロサルタン           | いいえ | はい   | いいえ       |
| 1373225      | ペリンドプリル       | いいえ | はい   | いいえ       |
| 1373928      | ヒドララジン         | いいえ | はい   | いいえ       |
| 1386957      | ラベタロール         | いいえ | はい   | いいえ       |
| 1395058      | クロルタリドン       | いいえ | はい   | いいえ       |
| 1398937      | クロニジン           | いいえ | はい   | いいえ       |
| 40226742     | オルメサルタン       | いいえ | はい   | いいえ       |
| 40235485     | アジルサルタン       | いいえ | はい   | いいえ       |

: (#tab:htnDrugsThzMono) 高血圧治療薬

## 高血圧のための第一選択治療を開始する患者 {#HTN1yrFO}

#### 初回イベントコホート {.unnumbered}

以下のいずれかを持つ人：

-   その人の履歴において初回の*第一選択高血圧治療薬*（表 \@ref(tab:HTN1yrFO1stLine)）への曝露

かつ、インデックス日から遡って少なくとも365日前からインデックス日365日後の間の連続した観察があり、初期イベントを次のように限定します：その個人における最も早いイベント。

#### 選択ルール {.unnumbered}

以下の全ての基準を満たすこと：

-   インデックス開始日1日前までのすべての日に少なくとも1回の*高血圧治療薬*（表 \@ref(tab:HTN1yrFODrugs)）の薬剤への曝露がちょうど0回出現します。
-   かつ、インデックス開始日からさかのぼって365日と後0日までの間に*高血圧性障害*（表 \@ref(tab:HTN1yrFOHypertensiveDisorder)）のコンディションがが少なくとも1回出現します。

初回イベントのコホートを次のように限定します：その個人における最も早いイベント。 適格コホートとしてイベントを次のように限定します：その個人における最も早いイベント。

#### 終了日の考え方 {.unnumbered}

終了日の考え方は選択されません。デフォルトでは、コホート終了日はインデックスイベントを含む観察期間の終了日になります。

#### コホート圧縮の考え方 {.unnumbered}

0日間のギャップによりコホートを圧縮します。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名         | 除外 | 下位層 | マッピング元 |
|:-------------|:---------------------|:-----|:-------|:-------------|
| 907013       | メトラゾン           | NO   | YES    | NO           |
| 974166       | ヒドロクロロチアジド | NO   | YES    | NO           |
| 978555       | インダパミド         | NO   | YES    | NO           |
| 1307863      | ベラパミル           | NO   | YES    | NO           |
| 1308216      | リシノプリル         | NO   | YES    | NO           |
| 1308842      | バルサルタン         | NO   | YES    | NO           |
| 1310756      | モエキシプリル       | NO   | YES    | NO           |
| 1317640      | テルミサルタン       | NO   | YES    | NO           |
| 1318137      | ニカルジピン         | NO   | YES    | NO           |
| 1318853      | ニフェジピン         | NO   | YES    | NO           |
| 1319880      | ニソルジピン         | NO   | YES    | NO           |
| 1326012      | イスラジピン         | NO   | YES    | NO           |
| 1328165      | ジルチアゼム         | NO   | YES    | NO           |
| 1331235      | キナプリル           | NO   | YES    | NO           |
| 1332418      | アムロジピン         | NO   | YES    | NO           |
| 1334456      | ラミプリル           | NO   | YES    | NO           |
| 1335471      | ベナゼプリル         | NO   | YES    | NO           |
| 1340128      | カプトプリル         | NO   | YES    | NO           |
| 1341927      | エナラプリル         | NO   | YES    | NO           |
| 1342439      | トランドラプリル     | NO   | YES    | NO           |
| 1346686      | エプロサルタン       | NO   | YES    | NO           |
| 1347384      | イルベサルタン       | NO   | YES    | NO           |
| 1351557      | カンデサルタン       | NO   | YES    | NO           |
| 1353776      | フェロジピン         | NO   | YES    | NO           |
| 1363749      | ホシノプリル         | NO   | YES    | NO           |
| 1367500      | ロサルタン           | NO   | YES    | NO           |
| 1373225      | ペリンドプリル       | NO   | YES    | NO           |
| 1395058      | クロルタリドン       | NO   | YES    | NO           |
| 40226742     | オルメサルタン       | NO   | YES    | NO           |
| 40235485     | アジルサルタン       | NO   | YES    | NO           |

: (#tab:HTN1yrFO1stLine) 第一選択高血圧治療薬

| コンセプトID | コンセプト名         | 除外 | 下位層 | マッピング元 |
|:-------------|:---------------------|:-----|:-------|:-------------|
| 904542       | トリアムテレン       | NO   | YES    | NO           |
| 907013       | メトラゾン           | NO   | YES    | NO           |
| 932745       | ブメタニド           | NO   | YES    | NO           |
| 942350       | トルセミド           | NO   | YES    | NO           |
| 956874       | フロセミド           | NO   | YES    | NO           |
| 970250       | スピロノラクトン     | NO   | YES    | NO           |
| 974166       | ヒドロクロロチアジド | NO   | YES    | NO           |
| 978555       | インダパミド         | NO   | YES    | NO           |
| 991382       | アミロイド           | NO   | YES    | NO           |
| 1305447      | メチルドパ           | NO   | YES    | NO           |
| 1307046      | メトプロロール       | NO   | YES    | NO           |
| 1307863      | ベラパミル           | NO   | YES    | NO           |
| 1308216      | リシノプリル         | NO   | YES    | NO           |
| 1308842      | バルサルタン         | NO   | YES    | NO           |
| 1309068      | ミノキシジル         | NO   | YES    | NO           |
| 1309799      | エプレレノン         | NO   | YES    | NO           |
| 1310756      | モエキシプリル       | NO   | YES    | NO           |
| 1313200      | ナドロール           | NO   | YES    | NO           |
| 1314002      | アテノロール         | NO   | YES    | NO           |
| 1314577      | ネビボロール         | NO   | YES    | NO           |
| 1317640      | テルミサルタン       | NO   | YES    | NO           |
| 1317967      | アリスキレン         | NO   | YES    | NO           |
| 1318137      | ニカルジピン         | NO   | YES    | NO           |
| 1318853      | ニフェジピン         | NO   | YES    | NO           |
| 1319880      | ニソルジピン         | NO   | YES    | NO           |
| 1319998      | アセブトロール       | NO   | YES    | NO           |
| 1322081      | ベタキソロール       | NO   | YES    | NO           |
| 1326012      | イスラジピン         | NO   | YES    | NO           |
| 1327978      | ペンブトロール       | NO   | YES    | NO           |
| 1328165      | ジルチアゼム         | NO   | YES    | NO           |
| 1331235      | キナプリル           | NO   | YES    | NO           |
| 1332418      | アムロジピン         | NO   | YES    | NO           |
| 1334456      | ラミプリル           | NO   | YES    | NO           |
| 1335471      | ベナゼプリル         | NO   | YES    | NO           |
| 1338005      | ビソプロロール       | NO   | YES    | NO           |
| 1340128      | カプトプリル         | NO   | YES    | NO           |
| 1341238      | テラゾシン           | NO   | YES    | NO           |
| 1341927      | エナラプリル         | NO   | YES    | NO           |
| 1342439      | トランドラプリル     | NO   | YES    | NO           |
| 1344965      | グアンファシン       | NO   | YES    | NO           |
| 1345858      | ピンドロール         | NO   | YES    | NO           |
| 1346686      | エプロサルタン       | NO   | YES    | NO           |
| 1346823      | カルベジロール       | NO   | YES    | NO           |
| 1347384      | イルベサルタン       | NO   | YES    | NO           |
| 1350489      | プラゾシン           | NO   | YES    | NO           |
| 1351557      | カンデサルタン       | NO   | YES    | NO           |
| 1353766      | プロプラノロール     | NO   | YES    | NO           |
| 1353776      | フェロジピン         | NO   | YES    | NO           |
| 1363053      | ドキサゾシン         | NO   | YES    | NO           |
| 1363749      | ホシノプリル         | NO   | YES    | NO           |
| 1367500      | ロサルタン           | NO   | YES    | NO           |
| 1373225      | ペリンドプリル       | NO   | YES    | NO           |
| 1373928      | ヒドララジン         | NO   | YES    | NO           |
| 1386957      | ラベタロール         | NO   | YES    | NO           |
| 1395058      | クロルタリドン       | NO   | YES    | NO           |
| 1398937      | クロニジン           | NO   | YES    | NO           |
| 40226742     | オルメサルタン       | NO   | YES    | NO           |
| 40235485     | アジルサルタン       | NO   | YES    | NO           |

: (#tab:HTN1yrFODrugs) 高血圧治療薬

| コンセプトID | コンセプト名 | 除外 | 下位層 | マッピング元 |
|:-------------|:-------------|:-----|:-------|:-------------|
| 316866       | 高血圧性障害 | NO   | YES    | NO           |

: (#tab:HTN1yrFOHypertensiveDisorder) 高血圧性障害

## 追跡期間が3年以上ある高血圧のための第一選択治療を開始する患者 {#HTN3yrFO}

*コホート定義* \@ref(HTN1yrFO) と同じだが、インデックス日から遡って少なくとも365日前から**1095日**後の連続した観察がある。

## ACE阻害薬の使用 {#ACEiUse}

#### 初回イベントコホート {.unnumbered}

以下のいずれかを持つ人：

-   *ACE阻害薬*（表 \@ref(tab:ACEiUseACE)）の薬物への曝露

かつ、インデックス日から遡って少なくとも0日前から０日後の間の連続した観察があり、初回イベントを次のように限定します：その個人のすべてのイベント。

適格なコホートを個人ごとのすべてのイベントに限定します。

#### 終了日の考え方 {.unnumbered}

この考え方は、指定されたコンセプトセットで見つかったコードから薬剤曝露期間を作成します。インデックスイベントが曝露期間内で見つかった場合、コホートの終了日はその曝露期間の終了日を使用します。そうでない場合、インデックスイベントを含む観察期間の終了日を使用します。

*ACE阻害薬*の曝露期間の終了日（表 \@ref(tab:ACEiUseACE)）

-   薬剤曝露間隔が30日を許容します。
-   薬剤曝露終了後0日追加します。

#### コホート圧縮の考え方 {.unnumbered}

30日間のギャップサイズで期間によりコホート圧縮します。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名     | 除外 | 下位層 | マッピング元 |
|:-------------|:-----------------|:-----|:-------|:-------------|
| 1308216      | リシノプリル     | NO   | YES    | NO           |
| 1310756      | モエキシプリル   | NO   | YES    | NO           |
| 1331235      | キナプリル       | NO   | YES    | NO           |
| 1334456      | ラミプリル       | NO   | YES    | NO           |
| 1335471      | ベナゼプリル     | NO   | YES    | NO           |
| 1340128      | カプトプリル     | NO   | YES    | NO           |
| 1341927      | エナラプリル     | NO   | YES    | NO           |
| 1342439      | トランドラプリル | NO   | YES    | NO           |
| 1363749      | ホシノプリル     | NO   | YES    | NO           |
| 1373225      | ペリンドプリル   | NO   | YES    | NO           |

: (#tab:ACEiUseACE) ACE阻害薬

## アンジオテンシン受容体拮抗薬（ARB）の使用 {#ARBUse}

*コホート定義* \@ref(ACEiUse) と同じですが、*アンジオテンシン受容体拮抗薬（ARB）*（表 \@ref(tab:ARBUseARBs)）が*ACE阻害薬*（表 \@ref(tab:ACEiUseACE)）の代わりに使用されます。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名   | 除外 | 下位層 | マッピング元 |
|:-------------|:---------------|:-----|:-------|:-------------|
| 1308842      | バルサルタン   | NO   | YES    | NO           |
| 1317640      | テルミサルタン | NO   | YES    | NO           |
| 1346686      | エプロサルタン | NO   | YES    | NO           |
| 1347384      | イルベサルタン | NO   | YES    | NO           |
| 1351557      | カンデサルタン | NO   | YES    | NO           |
| 1367500      | ロサルタン     | NO   | YES    | NO           |
| 40226742     | オルメサルタン | NO   | YES    | NO           |
| 40235485     | アジルサルタン | NO   | YES    | NO           |

: (#tab:ARBUseARBs) アンジオテンシン受容体拮抗薬（ARB）

## サイアザイドおよびサイアザイド様利尿薬の使用 {#THZUse}

*コホート定義* \@ref(ACEiUse) と同じですが、*サイアザイドおよびサイアザイド様利尿薬*（表 \@ref(tab:THZUseTHZ)）が*ACE阻害薬*（表 \@ref(tab:ACEiUseACE)）の代わりに使用されます。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名         | 除外 | 下位層 | マッピング元 |
|:-------------|:---------------------|:-----|:-------|:-------------|
| 907013       | メトラゾン           | NO   | YES    | NO           |
| 974166       | ヒドロクロロチアジド | NO   | YES    | NO           |
| 978555       | インダパミド         | NO   | YES    | NO           |
| 1395058      | クロルタリドン       | NO   | YES    | NO           |

: (#tab:THZUseTHZ) サイアザイドおよびサイアザイド様利尿薬

## ジヒドロピリジン系カルシウムチャネル遮断薬（DCCB）の使用 {#dCCBUse}

*コホート定義* \@ref(ACEiUse) と同じですが、*ジヒドロピリジン系カルシウムチャネル遮断薬（DCCB）*（表 \@ref(tab:dCCBUsedCBB)）が*ACE阻害薬*（表 \@ref(tab:ACEiUseACE)）の代わりに使用されます。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名 | 除外 | 下位層 | マッピング元 |
|:-------------|:-------------|:-----|:-------|:-------------|
| 1318137      | ニカルジピン | NO   | YES    | NO           |
| 1318853      | ニフェジピン | NO   | YES    | NO           |
| 1319880      | ニソルジピン | NO   | YES    | NO           |
| 1326012      | イスラジピン | NO   | YES    | NO           |
| 1332418      | アムロジピン | NO   | YES    | NO           |
| 1353776      | フェロジピン | NO   | YES    | NO           |

: (#tab:dCCBUsedCBB) ジヒドロピリジン系カルシウムチャネル遮断薬（DCCB）

## 非ジヒドロピリジン系カルシウムチャネル遮断薬（NDCCB）の使用 {#ndCCBUse}

*コホート定義* \@ref(ACEiUse) と同じですが、*非ジヒドロピリジン系カルシウムチャネル遮断薬（NDCCB）*（表 \@ref(tab:ndCCBUsendCCB)）が*ACE阻害薬*（表 \@ref(tab:ACEiUseACE)）の代わりに使用されます。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名 | 除外 | 下位層 | マッピング元 |
|:-------------|:-------------|:-----|:-------|:-------------|
| 1307863      | ベラパミル   | NO   | YES    | NO           |
| 1328165      | ジルチアゼム | NO   | YES    | NO           |

: (#tab:ndCCBUsendCCB) 非ジヒドロピリジン系カルシウムチャネル遮断薬（NDCCB）

## ベータ遮断薬使用 {#BBUse}

*コホート定義* \@ref(ACEiUse) と同じですが、*ベータ遮断薬* (表 \@ref(tab:BBUseBB)) が *ACE阻害剤* (表 \@ref(tab:ACEiUseACE))の代わりに使用されます。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名     | 除外 | 下位層 | マッピング元 |
|:-------------|:-----------------|:-----|:-------|:-------------|
| 1307046      | メトプロロール   | NO   | YES    | NO           |
| 1313200      | ナドロール       | NO   | YES    | NO           |
| 1314002      | アテノロール     | NO   | YES    | NO           |
| 1314577      | ネビボロール     | NO   | YES    | NO           |
| 1319998      | アセブトロール   | NO   | YES    | NO           |
| 1322081      | ベタキソロール   | NO   | YES    | NO           |
| 1327978      | ペンブトロール   | NO   | YES    | NO           |
| 1338005      | ビソプロロール   | NO   | YES    | NO           |
| 1345858      | ピンドロール     | NO   | YES    | NO           |
| 1346823      | カルベジロール   | NO   | YES    | NO           |
| 1353766      | プロプラノロール | NO   | YES    | NO           |
| 1386957      | ラベタロール     | NO   | YES    | NO           |

: (#tab:BBUseBB) ベータ遮断薬

## ループ利尿薬使用 {#DLoopUse}

*ACE阻害剤使用* \@ref(ACEiUse) と同じですが、*ループ利尿薬* (表 \@ref(tab:DLoopUseDLoops)) が*ACE阻害剤* (表 \@ref(tab:ACEiUseACE)) の代わりに使用されます。

#### コンセプトセット定義 {.unnumbered}

| コンセプトID | コンセプト名 | 除外 | 下位層 | マッピング元 |
|:-------------|:-------------|:-----|:-------|:-------------|
| 932745       | ブメタニド   | NO   | YES    | NO           |
| 942350       | トルセミド   | NO   | YES    | NO           |
| 956874       | フロセミド   | NO   | YES    | NO           |

: (#tab:DLoopUseDLoops) ループ利尿薬

## カリウム保持性利尿薬使用 {#DPUse}

*ACE阻害剤使用* \@ref(ACEiUse) と同じですが、*カリウム保持性利尿薬* (表 \@ref(tab:DPUseDPs)) が *ACE阻害剤* (表 \@ref(tab:ACEiUseACE)) の代わりに使用されます。

#### コンセプトセットの定義 {.unnumbered}

| コンセプトID | コンセプト名   | 除外 | 下位層 | マッピング元 |
|:-------------|:---------------|:-----|:-------|:-------------|
| 904542       | トリアムテレン | NO   | YES    | NO           |
| 991382       | アミロライド   | NO   | YES    | NO           |

: (#tab:DPUseDPs) カリウム保持性利尿薬

## アルファ1遮断薬使用 {#A1BUse}

*ACE阻害剤使用* \@ref(ACEiUse) と同じですが、*アルファ1遮断薬* (表 \@ref(tab:A1BUseA1Bs)) が *ACE阻害剤* (表 \@ref(tab:ACEiUseACE))の代わりに使用されます。

#### コンセプトセットの定義 {.unnumbered}

| コンセプトID | コンセプト名 | 除外 | 下位層 | マッピング元 |
|:-------------|:-------------|:-----|:-------|:-------------|
| 1341238      | テラゾシン   | NO   | YES    | NO           |
| 1350489      | プラゾシン   | NO   | YES    | NO           |
| 1363053      | ドキサゾシン | NO   | YES    | NO           |

: (#tab:A1BUseA1Bs) アルファ1遮断薬
