# (APPENDIX) 付録 {.unnumbered}

# 用語集 {#Glossary}

ACHILLES

:   データベースレベルの特性評価レポート。

ARACHNE

:   連携ネットワーク研究のオーケストレーションおよび実行を可能にするために開発されているOHDSIプラットフォーム。

ATLAS

:   患者レベルの臨床データからリアルワールドエビデンスを創生するための観察データの分析のデザインおよび実行を支援するために、参加施設にインストールされるウェブベースのアプリケーション。

バイアス（Bias）

:   誤差（真の値と推定値の差）の期待値。

ブーリアン変数（Boolean）

:   2つの値（真または偽）のみを持つ変数。

医療施設（Care site）

:   医療提供が実施される一意に識別された制度上（物理的または組織的）の単位（外来、病棟、病院、クリニックなど）。

症例対照（研究）（Case control）

:   集団レベルの効果推定のためのレトロスペクティブ研究デザインの一種。症例対照研究には、ターゲットとなるアウトカムを有する「症例」と有しない「対照」をマッチングさせる。過去に遡って、症例と対照における曝露のオッズを比較する。

因果効果（Causal effect）

:   集団レベルの推定が関心を寄せるもの。「因果効果」を、ターゲットとする集団における「個人レベル因果効果」の平均とする定義もある。個人レベル因果効果は、個人が曝露された場合のアウトカムと、されなかった場合（またはAに曝露された場合とBに曝露された場合）のアウトカムとの対比である。

特性評価（Characterization）

:   コホートまたは全データベースの記述的研究。詳細は第 \@ref(Characterization) 章参照。

保険請求データ（Claims data）

:   医療保険会社への請求目的で作成されたデータ。

臨床試験（Clinical trial）

:   介入臨床研究。

コホート（Cohort）

:   ある期間内に、1つ以上の選択基準を満たす個人の集団。詳細は第\@ref(Cohorts)章参照。

コンセプト（Concept）

:   医学用語で定義された表現（コードが付随する）（例：SNOMED CT）。詳細は第 \@ref(StandardizedVocabularies) 章参照。

コンセプトセット（Concept set）

:   様々な分析で再利用可能な構成要素として使用できるコンセプトのリストによる表現。詳細は第 \@ref(Cohorts) 章参照。

共通データモデル（Common Data Model, CDM）

:   分析のポータビリティ（同じ分析を変更なしで複数のデータセットで実行できる）を可能にするための医療データの表現規約。詳細は第 \@ref(DataAnalyticsUseCases) 章参照。

比較効果（Comparative Effectiveness）

:   関心のあるアウトカムに対する2つの異なる曝露の効果の比較。詳細は第 \@ref(PopulationLevelEstimation) 章参照。

コンディション（Condition）

:   医療提供者が観察したまたは患者が報告した診断、徴候、または症状。

交絡（Confounding）

:   主たる関心の曝露が、アウトカムと関連する他の要因と混同されるときに発生する推定された関連性尺度の歪み（不正確さ）。

共変量（Covariate）

:   独立変数として統計モデルで使用されるデータ要素（例：体重）。

データ品質（Data quality）

:   そのデータが特定の用途に適していると判断するためのデータの完全性、妥当性、一貫性、適時性、正確性の状態。

デバイス（Device）

:   化学作用を超えた機序によって診断または治療の目的で使用される異物または器具。デバイスには、植込み物（例：ペースメーカー、ステント、人工関節）、医療機器および補助材料（例：包帯、松葉杖、注射器）、医療処置で使用される他の器具（例：縫合糸、除細動器）および臨床ケアで使用される材料（例：接着剤、生体用材料、歯科材料、外科材料）が含まれる。

薬剤（Drug）

:   人に投与されたときに特定の生理学的効果を発揮するように調製された生化学物質。薬剤には処方薬と市販薬、ワクチン、バイオ製剤が含まれる。局所的に摂取または適用する放射性デバイスは薬剤に含まない。

ドメイン（Domain）

:   共通データモデルのテーブルにおける標準化フィールドに対して使用が許容される一連のコンセプト一式の定義。例えば、「コンディション（Condition）」ドメインは患者の状態を説明するコンセプトを含み、これらのコンセプトはCONDITION_OCCURRENCEおよびCONDITION_ERAテーブルのcondition_concept_idフィールドにのみ格納できる。

電子健康記録（Electronic Health Record, EHR）

:   医療の過程で生成され、電子システムに記録されるデータ。

疫学（Epidemiology）

:   一定の集団における健康および疾患の分布、パターン、および決定要因の研究。

エビデンスに基づく医療（Evidence-based medicine）

:   個々の患者の医療に関する意思決定において実証的および科学的エビデンスを使用すること。

ETL（Extract-Transform-Load）

:   データをある形式から別の形式に変換するプロセス（例：ソース形式から共通データモデルへの変換）。詳細は第\@ref(ExtractTransformLoad)章参照。

マッチング（Matching）

:   多くの集団レベルの効果推定のためのアプローチは、曝露された患者のアウトカムを曝露されていない患者（または曝露Bに対して曝露A）と比較することよって、曝露の因果効果を特定しようとする。これらの2つの患者群が曝露以外の点で異なる可能性があるため、「マッチング」は曝露および非曝露群を設定する際に、少なくとも測定された患者特性に関してできる限り同じにしようとする。

測定値（Measurement）

:   患者または患者の検体の体系的かつ標準化された診察または検査を通じて得られる構造化された値（数値またはカテゴリカル）。

測定誤差（Measurement error）

:   記録された測定値（例：血圧、患者の年齢、治療期間）が対応する真の測定値と異なる場合に発生する。

メタデータ（Metadata）

:   他のデータについて説明し、情報を提供するデータの一式。メタデータには、記述メタデータ、構造メタデータ、管理メタデータ、参照メタデータ、統計メタデータがある。

Methods Library

:   観察研究を実行するためにOHDSIコミュニティによって開発された一連のRパッケージ。

モデルの誤特定（Model misspecification）

:   多くのOHDSIで用いる方法は、比例ハザード回帰やランダムフォレストなどの統計モデルを採用している。データ生成メカニズムが想定モデルから逸脱する限り、モデルは「誤特定」である。

陰性対照（Negative control）

:   曝露がアウトカムを引き起こさないまたは予防しないと信じられる曝露-アウトカムの組み合わせ。効果推定が真実に沿った結果を生成するかどうかを評価するために使用される。詳細は第 \@ref(MethodValidity) 章参照。

観察（Observation）

:   診察、問診または処置のコンテキストで得られた患者に関する臨床上の事実。

観察期間（Observation period）

:   患者がソースシステム内で臨床イベントの有無にか関わらず（状態の良い患者が医療に関与しない場合を含めて）臨床イベントを記録する可能性がある期間。

観察研究（Observational study）

:   研究者が介入を制御しない研究。

OHDSI SQL

:   RパッケージSqlRenderを使用して様々な他のSQLダイアレクト（方言）に自動変換できるSQLダイアレクト。OHDSI SQLは主にSQL Server SQLのサブセットであるが、追加のパラメータ化が可能である。詳細は第 \@ref(SqlAndR) 章参照。

オープンサイエンス（Open science）

:   科学研究（パブリケーション、データ、物理的サンプル、ソフトウェアを含む）およびその普及を、要求のあった社会、アマチュア、専門家のすべてのレベルでアクセス可能にする運動。詳細は第 \@ref(OpenScience) 章参照。

アウトカム（Outcome）

:   分析の焦点となる観察。例えば、患者レベルの予測モデルは、アウトカム「脳卒中」を予測するのかもしれない。または集団レベルの推定は、薬剤がアウトカム「頭痛」に及ぼす因果効果を推定するかもしれない。

患者レベルの予測（Patient-level prediction）

:   ベースライン特性に基づいて将来のアウトカムを経験する患者固有の確率を生成する予測モデルの開発と適用。

フェノタイプ（Phenotype）

:   身体的特性の説明。これには、体重や髪の色のような可視的な特徴だけでなく、全体的な健康状態、病歴、行動も含まれる。

集団レベル推定（Population-level estimation）

:   因果効果の研究。平均（集団レベル）の効果の大きさを推定する。

陽性対照（Positive control）

:   曝露がアウトカムを引き起こすまたは予防すると信じられる曝露-アウトカムの組み合わせ。効果推定方法が真実に沿った結果を生成するかどうかを評価するために使用される。詳細は第 \@ref(MethodValidity) 章参照。

処置（Procedure）

:   患者に対して診断または治療目的で医療提供者によって命じられまたは実行される活動またはプロセス。

傾向スコア（Propensity score, PS）

:   観察研究において、2つの治療群間の均衡をとり無作為化を模倣するために集団レベル推定で用いられる単一の指標。傾向スコアは、観察された一連のベースライン共変量の関数として患者が関心のある治療を受ける確率を示す。最もよく使われるのは、二値アウトカムはターゲット治療を受ける群を1、比較対照治療を受ける群を0に設定したロジスティック回帰モデルを使用した計算である。詳細は第 \@ref(PopulationLevelEstimation) 章参照。

プロトコル（Protocol）

:   研究のデザインを完全に指定するドキュメントで、人が読んで理解できるもの。

Rabbit-in-a-Hat

:   ソース形式から共通データモデルへのETLを定義を支援するインタラクティブなソフトウェアツール。White Rabbitによって生成されたデータベースプロファイルを入力として使用する。詳細は第 \@ref(DataAnalyticsUseCases) 章参照。

選択バイアス（Selection bias）

:   データ内の患者集団が統計分析を歪める形で母集団の患者から逸脱した場合に発生するバイアス。

自己対照デザイン（Self-controlled designs）

:   同一患者内で異なる曝露期間中のアウトカムを比較する研究デザイン。

感度分析（Sensitivity analysis）

:   不確実性が存在する分析に関する選択の影響を評価するために研究の主たる分析のバリエーション。

SNOMED

:   臨床ドキュメントおよび報告書で使用するため、コード、用語、同義語および定義を提供する体系化されたコンピュータ処理可能な医療用語集。

研究診断（Study diagnostics）

:   特定の分析アプローチが特定の研究質問に対する回答に使用できるかどうか（あるいは、妥当かどうか）を判断することを目的とする分析手順のセット。詳細は第 \@ref(MethodValidity) 章参照。

研究パッケージ（Study package）

:   研究を完全に実行するコンピュータ実行プログラム。詳細は第 \@ref(SoftwareValidity) 章参照。

ソースコード（Source code）

:   ソースデータベースで使用されるコード。例えば、ICD-10コード。

標準コンセプト（Standard Concept）

:   妥当であると指定され、共通データモデルに含めることができるコンセプト。

THEMIS

:   共通データモデル仕様に関して高い粒度と詳細を持つデータ形式に取り組むOHDSIワークグループ。

ビジット（Visit）

:   医療システム内で特定の設定の医療施設において、1人以上の医療提供者から継続して医療サービスを受ける期間。

ボキャブラリ（Vocabulary）

:   通常アルファベット順に並べられ、定義または翻訳された単語や語句のリスト。詳細は第 \@ref(StandardizedVocabularies) 章参照。

White Rabbit

:   共通データモデルへのETLを定義する前にデータベースをプロファイリングするソフトウェアツール。詳細は第 \@ref(ExtractTransformLoad) 章参照。
