<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>第 13 章 患者レベルの予測 | –翻訳作業中–　OHDSIの本</title>
  <meta name="description" content="The Observational Health Data Sciences and Informatics (OHDSI) についての本。OHDSIのコミュニティ、オープンスタンダードとオープンソースソフトウェアについて詳述しています。" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="第 13 章 患者レベルの予測 | –翻訳作業中–　OHDSIの本" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://ohdsi.github.io/TheBookOfOhdsiInJapanese/images/Cover/Cover.png" />
  <meta property="og:description" content="The Observational Health Data Sciences and Informatics (OHDSI) についての本。OHDSIのコミュニティ、オープンスタンダードとオープンソースソフトウェアについて詳述しています。" />
  <meta name="github-repo" content="OHDSI/TheBookOfOhdsiInJapanese" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="第 13 章 患者レベルの予測 | –翻訳作業中–　OHDSIの本" />
  
  <meta name="twitter:description" content="The Observational Health Data Sciences and Informatics (OHDSI) についての本。OHDSIのコミュニティ、オープンスタンダードとオープンソースソフトウェアについて詳述しています。" />
  <meta name="twitter:image" content="https://ohdsi.github.io/TheBookOfOhdsiInJapanese/images/Cover/Cover.png" />

<meta name="author" content="Observational Health Data Sciences and Informatics (OHDSI)" />


<meta name="date" content="2025-03-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="PopulationLevelEstimation.html"/>
<link rel="next" href="EvidenceQuality.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104086677-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-104086677-2');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">OHDSIの本 </a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>序章</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#この本の目標"><i class="fa fa-check"></i>この本の目標</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#本書の構成"><i class="fa fa-check"></i>本書の構成</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#貢献者"><i class="fa fa-check"></i>貢献者</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ソフトウェアのバージョン"><i class="fa fa-check"></i>ソフトウェアのバージョン</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ライセンス"><i class="fa fa-check"></i>ライセンス</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#本書が作成された方法"><i class="fa fa-check"></i>本書が作成された方法</a></li>
</ul></li>
<li class="part"><span><b>I OHDSI コミュニティ</b></span></li>
<li class="chapter" data-level="1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html"><i class="fa fa-check"></i><b>1</b> OHDSI コミュニティ</a>
<ul>
<li class="chapter" data-level="1.1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#データからエビデンスへの旅"><i class="fa fa-check"></i><b>1.1</b> データからエビデンスへの旅</a></li>
<li class="chapter" data-level="1.2" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#観察医療アウトカムパートナーシップomop"><i class="fa fa-check"></i><b>1.2</b> 観察医療アウトカムパートナーシップ（OMOP）</a></li>
<li class="chapter" data-level="1.3" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#オープンサイエンスの協働組織としてのohdsi"><i class="fa fa-check"></i><b>1.3</b> オープンサイエンスの協働組織としてのOHDSI</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#我々の使命"><i class="fa fa-check"></i><b>1.3.1</b> 我々の使命</a></li>
<li class="chapter" data-level="1.3.2" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#我々のビジョン"><i class="fa fa-check"></i><b>1.3.2</b> 我々のビジョン</a></li>
<li class="chapter" data-level="1.3.3" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#我々の目標"><i class="fa fa-check"></i><b>1.3.3</b> 我々の目標</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#ohdsiの進展"><i class="fa fa-check"></i><b>1.4</b> OHDSIの進展</a></li>
<li class="chapter" data-level="1.5" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#ohdsiにおける協力"><i class="fa fa-check"></i><b>1.5</b> OHDSIにおける協力</a></li>
<li class="chapter" data-level="1.6" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#まとめ"><i class="fa fa-check"></i><b>1.6</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="WhereToBegin.html"><a href="WhereToBegin.html"><i class="fa fa-check"></i><b>2</b> どこから始めようか</a>
<ul>
<li class="chapter" data-level="2.1" data-path="WhereToBegin.html"><a href="WhereToBegin.html#旅に参加しよう"><i class="fa fa-check"></i><b>2.1</b> 旅に参加しよう</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiフォーラム"><i class="fa fa-check"></i><b>2.1.1</b> OHDSIフォーラム</a></li>
<li class="chapter" data-level="2.1.2" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiイベント"><i class="fa fa-check"></i><b>2.1.2</b> OHDSIイベント</a></li>
<li class="chapter" data-level="2.1.3" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiコミュニティコール"><i class="fa fa-check"></i><b>2.1.3</b> OHDSIコミュニティコール</a></li>
<li class="chapter" data-level="2.1.4" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiワークグループ"><i class="fa fa-check"></i><b>2.1.4</b> OHDSIワークグループ</a></li>
<li class="chapter" data-level="2.1.5" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi地域支部"><i class="fa fa-check"></i><b>2.1.5</b> OHDSI地域支部</a></li>
<li class="chapter" data-level="2.1.6" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi研究ネットワーク"><i class="fa fa-check"></i><b>2.1.6</b> OHDSI研究ネットワーク</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="WhereToBegin.html"><a href="WhereToBegin.html#どこにフィットするか"><i class="fa fa-check"></i><b>2.2</b> どこにフィットするか</a></li>
<li class="chapter" data-level="2.3" data-path="WhereToBegin.html"><a href="WhereToBegin.html#まとめ-1"><i class="fa fa-check"></i><b>2.3</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="OpenScience.html"><a href="OpenScience.html"><i class="fa fa-check"></i><b>3</b> オープンサイエンス</a>
<ul>
<li class="chapter" data-level="3.1" data-path="OpenScience.html"><a href="OpenScience.html#オープンサイエンス"><i class="fa fa-check"></i><b>3.1</b> オープンサイエンス</a></li>
<li class="chapter" data-level="3.2" data-path="OpenScience.html"><a href="OpenScience.html#オープンサイエンスの実践-study-a-thon"><i class="fa fa-check"></i><b>3.2</b> オープンサイエンスの実践: Study-a-Thon</a></li>
<li class="chapter" data-level="3.3" data-path="OpenScience.html"><a href="OpenScience.html#オープンスタンダード"><i class="fa fa-check"></i><b>3.3</b> オープンスタンダード</a></li>
<li class="chapter" data-level="3.4" data-path="OpenScience.html"><a href="OpenScience.html#オープンソース"><i class="fa fa-check"></i><b>3.4</b> オープンソース</a></li>
<li class="chapter" data-level="3.5" data-path="OpenScience.html"><a href="OpenScience.html#オープンデータ"><i class="fa fa-check"></i><b>3.5</b> オープンデータ</a></li>
<li class="chapter" data-level="3.6" data-path="OpenScience.html"><a href="OpenScience.html#オープンな議論"><i class="fa fa-check"></i><b>3.6</b> オープンな議論</a></li>
<li class="chapter" data-level="3.7" data-path="OpenScience.html"><a href="OpenScience.html#ohdsiとfairガイディングプリンシプルズ"><i class="fa fa-check"></i><b>3.7</b> OHDSIとFAIRガイディングプリンシプルズ</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="OpenScience.html"><a href="OpenScience.html#序論"><i class="fa fa-check"></i><b>3.7.1</b> 序論</a></li>
<li class="chapter" data-level="3.7.2" data-path="OpenScience.html"><a href="OpenScience.html#検索可能性findability"><i class="fa fa-check"></i><b>3.7.2</b> 検索可能性（Findability）</a></li>
<li class="chapter" data-level="3.7.3" data-path="OpenScience.html"><a href="OpenScience.html#アクセシビリティaccessibility"><i class="fa fa-check"></i><b>3.7.3</b> アクセシビリティ（Accessibility）</a></li>
<li class="chapter" data-level="3.7.4" data-path="OpenScience.html"><a href="OpenScience.html#相互運用性interoperability"><i class="fa fa-check"></i><b>3.7.4</b> 相互運用性（Interoperability）</a></li>
<li class="chapter" data-level="3.7.5" data-path="OpenScience.html"><a href="OpenScience.html#再利用性reusability"><i class="fa fa-check"></i><b>3.7.5</b> 再利用性（Reusability）</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II 共通データモデル</b></span></li>
<li class="chapter" data-level="4" data-path="CommonDataModel.html"><a href="CommonDataModel.html"><i class="fa fa-check"></i><b>4</b> 共通データモデル</a>
<ul>
<li class="chapter" data-level="4.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#デザイン原則"><i class="fa fa-check"></i><b>4.1</b> デザイン原則</a></li>
<li class="chapter" data-level="4.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#データモデルの規約"><i class="fa fa-check"></i><b>4.2</b> データモデルの規約</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#model-Conv"><i class="fa fa-check"></i><b>4.2.1</b> モデルの一般的な規約</a></li>
<li class="chapter" data-level="4.2.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#スキーマの一般的な規約"><i class="fa fa-check"></i><b>4.2.2</b> スキーマの一般的な規約</a></li>
<li class="chapter" data-level="4.2.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#データテーブルの一般的な規約"><i class="fa fa-check"></i><b>4.2.3</b> データテーブルの一般的な規約</a></li>
<li class="chapter" data-level="4.2.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#domains"><i class="fa fa-check"></i><b>4.2.4</b> ドメインの一般的な規約</a></li>
<li class="chapter" data-level="4.2.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#コンテンツのコンセプトによる表現"><i class="fa fa-check"></i><b>4.2.5</b> コンテンツのコンセプトによる表現</a></li>
<li class="chapter" data-level="4.2.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#フィールドの一般的な命名規約"><i class="fa fa-check"></i><b>4.2.6</b> フィールドの一般的な命名規約</a></li>
<li class="chapter" data-level="4.2.7" data-path="CommonDataModel.html"><a href="CommonDataModel.html#concepts-Sources"><i class="fa fa-check"></i><b>4.2.7</b> コンセプトとソース値の違い</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#cdm標準化テーブル"><i class="fa fa-check"></i><b>4.3</b> CDM標準化テーブル</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#実際の例-子宮内膜症"><i class="fa fa-check"></i><b>4.3.1</b> 実際の例: 子宮内膜症</a></li>
<li class="chapter" data-level="4.3.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#person"><i class="fa fa-check"></i><b>4.3.2</b> PERSONテーブル</a></li>
<li class="chapter" data-level="4.3.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#observationPeriod"><i class="fa fa-check"></i><b>4.3.3</b> OBSERVATION_PERIODテーブル</a></li>
<li class="chapter" data-level="4.3.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#visitOccurrence"><i class="fa fa-check"></i><b>4.3.4</b> VISIT_OCCURRENCE</a></li>
<li class="chapter" data-level="4.3.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#conditionOccurrence"><i class="fa fa-check"></i><b>4.3.5</b> CONDITION_OCCURRENCE</a></li>
<li class="chapter" data-level="4.3.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#drugExposure"><i class="fa fa-check"></i><b>4.3.6</b> DRUG_EXPOSURE</a></li>
<li class="chapter" data-level="4.3.7" data-path="CommonDataModel.html"><a href="CommonDataModel.html#procedureOccurrence"><i class="fa fa-check"></i><b>4.3.7</b> PROCEDURE_OCCURRENCE</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#追加情報"><i class="fa fa-check"></i><b>4.4</b> 追加情報</a></li>
<li class="chapter" data-level="4.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#まとめ-2"><i class="fa fa-check"></i><b>4.5</b> まとめ</a></li>
<li class="chapter" data-level="4.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#演習"><i class="fa fa-check"></i><b>4.6</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html"><i class="fa fa-check"></i><b>5</b> 標準化ボキャブラリ</a>
<ul>
<li class="chapter" data-level="5.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#なぜボキャブラリが必要でなぜ標準化が必要なのか"><i class="fa fa-check"></i><b>5.1</b> なぜボキャブラリが必要で、なぜ標準化が必要なのか</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#標準化ボキャブラリの構築"><i class="fa fa-check"></i><b>5.1.1</b> 標準化ボキャブラリの構築</a></li>
<li class="chapter" data-level="5.1.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#accessVocabularies"><i class="fa fa-check"></i><b>5.1.2</b> 標準化ボキャブラリへのアクセス</a></li>
<li class="chapter" data-level="5.1.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#ボキャブラリの元-採用するか構築するか"><i class="fa fa-check"></i><b>5.1.3</b> ボキャブラリの元: 採用するか構築するか</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプト"><i class="fa fa-check"></i><b>5.2</b> コンセプト</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプトid"><i class="fa fa-check"></i><b>5.2.1</b> コンセプトID</a></li>
<li class="chapter" data-level="5.2.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプト名"><i class="fa fa-check"></i><b>5.2.2</b> コンセプト名</a></li>
<li class="chapter" data-level="5.2.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptDomains"><i class="fa fa-check"></i><b>5.2.3</b> ドメイン</a></li>
<li class="chapter" data-level="5.2.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#ボキャブラリ"><i class="fa fa-check"></i><b>5.2.4</b> ボキャブラリ</a></li>
<li class="chapter" data-level="5.2.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプトクラス"><i class="fa fa-check"></i><b>5.2.5</b> コンセプトクラス</a></li>
<li class="chapter" data-level="5.2.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#standardConcepts"><i class="fa fa-check"></i><b>5.2.6</b> 標準コンセプト</a></li>
<li class="chapter" data-level="5.2.7" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#非標準コンセプト"><i class="fa fa-check"></i><b>5.2.7</b> 非標準コンセプト</a></li>
<li class="chapter" data-level="5.2.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#分類コンセプト"><i class="fa fa-check"></i><b>5.2.8</b> 分類コンセプト</a></li>
<li class="chapter" data-level="5.2.9" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプトコード"><i class="fa fa-check"></i><b>5.2.9</b> コンセプトコード</a></li>
<li class="chapter" data-level="5.2.10" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptLifeCycle"><i class="fa fa-check"></i><b>5.2.10</b> ライフサイクル</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#関係"><i class="fa fa-check"></i><b>5.3</b> 関係</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptMapping"><i class="fa fa-check"></i><b>5.3.1</b> マッピング関係</a></li>
<li class="chapter" data-level="5.3.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#階層関係"><i class="fa fa-check"></i><b>5.3.2</b> 階層関係</a></li>
<li class="chapter" data-level="5.3.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#異なるボキャブラリーのコンセプト間の関係"><i class="fa fa-check"></i><b>5.3.3</b> 異なるボキャブラリーのコンセプト間の関係</a></li>
<li class="chapter" data-level="5.3.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#同一ボキャブラリーのコンセプト間の関係"><i class="fa fa-check"></i><b>5.3.4</b> 同一ボキャブラリーのコンセプト間の関係</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptAncestor"><i class="fa fa-check"></i><b>5.4</b> 階層</a></li>
<li class="chapter" data-level="5.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#内部参照テーブル"><i class="fa fa-check"></i><b>5.5</b> 内部参照テーブル</a></li>
<li class="chapter" data-level="5.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#specialSituations"><i class="fa fa-check"></i><b>5.6</b> 特別な状況</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#性別"><i class="fa fa-check"></i><b>5.6.1</b> 性別</a></li>
<li class="chapter" data-level="5.6.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#人種と民族"><i class="fa fa-check"></i><b>5.6.2</b> 人種と民族</a></li>
<li class="chapter" data-level="5.6.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#診断コーディング体系とomopコンディション"><i class="fa fa-check"></i><b>5.6.3</b> 診断コーディング体系とOMOPコンディション</a></li>
<li class="chapter" data-level="5.6.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#プロシージャーコーディング体系"><i class="fa fa-check"></i><b>5.6.4</b> プロシージャーコーディング体系</a></li>
<li class="chapter" data-level="5.6.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#デバイス"><i class="fa fa-check"></i><b>5.6.5</b> デバイス</a></li>
<li class="chapter" data-level="5.6.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#ビジットとサービス"><i class="fa fa-check"></i><b>5.6.6</b> ビジットとサービス</a></li>
<li class="chapter" data-level="5.6.7" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#医療従事者と専門分野"><i class="fa fa-check"></i><b>5.6.7</b> 医療従事者と専門分野</a></li>
<li class="chapter" data-level="5.6.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#特別な要件を持つ治療領域"><i class="fa fa-check"></i><b>5.6.8</b> 特別な要件を持つ治療領域</a></li>
<li class="chapter" data-level="5.6.9" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#rxNormExtension"><i class="fa fa-check"></i><b>5.6.9</b> 薬剤ドメインにおける標準コンセプト</a></li>
<li class="chapter" data-level="5.6.10" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#nullのバリエーション"><i class="fa fa-check"></i><b>5.6.10</b> NULLのバリエーション</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#まとめ-3"><i class="fa fa-check"></i><b>5.7</b> まとめ</a></li>
<li class="chapter" data-level="5.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#演習-1"><i class="fa fa-check"></i><b>5.8</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html"><i class="fa fa-check"></i><b>6</b> ETL（抽出-変換-読込）</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#はじめに"><i class="fa fa-check"></i><b>6.1</b> はじめに</a></li>
<li class="chapter" data-level="6.2" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#ステップ-1-etlのデザイン"><i class="fa fa-check"></i><b>6.2</b> ステップ 1: ETLのデザイン</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#white-rabbit"><i class="fa fa-check"></i><b>6.2.1</b> White Rabbit</a></li>
<li class="chapter" data-level="6.2.2" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#rabbit-in-a-hat"><i class="fa fa-check"></i><b>6.2.2</b> Rabbit-In-a-Hat</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#ステップ2-コードマッピングの作成"><i class="fa fa-check"></i><b>6.3</b> ステップ2: コードマッピングの作成</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#usagi"><i class="fa fa-check"></i><b>6.3.1</b> Usagi</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#ステップ-3-etlの実装"><i class="fa fa-check"></i><b>6.4</b> ステップ 3: ETLの実装</a></li>
<li class="chapter" data-level="6.5" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#ステップ-4-品質管理"><i class="fa fa-check"></i><b>6.5</b> ステップ 4: 品質管理</a></li>
<li class="chapter" data-level="6.6" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#etlの規約とthemis"><i class="fa fa-check"></i><b>6.6</b> ETLの規約とTHEMIS</a></li>
<li class="chapter" data-level="6.7" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#CDMandETLMaintenance"><i class="fa fa-check"></i><b>6.7</b> CDMおよびETLのメンテナンス</a></li>
<li class="chapter" data-level="6.8" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#etlに関する最終的な考察"><i class="fa fa-check"></i><b>6.8</b> ETLに関する最終的な考察</a></li>
<li class="chapter" data-level="6.9" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#まとめ-4"><i class="fa fa-check"></i><b>6.9</b> まとめ</a></li>
<li class="chapter" data-level="6.10" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#演習-2"><i class="fa fa-check"></i><b>6.10</b> 演習</a></li>
</ul></li>
<li class="part"><span><b>III データ解析</b></span></li>
<li class="chapter" data-level="7" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html"><i class="fa fa-check"></i><b>7</b> データ解析の使用例</a>
<ul>
<li class="chapter" data-level="7.1" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#特性評価"><i class="fa fa-check"></i><b>7.1</b> 特性評価</a></li>
<li class="chapter" data-level="7.2" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#集団レベルの推定"><i class="fa fa-check"></i><b>7.2</b> 集団レベルの推定</a></li>
<li class="chapter" data-level="7.3" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#患者レベルの予測"><i class="fa fa-check"></i><b>7.3</b> 患者レベルの予測</a></li>
<li class="chapter" data-level="7.4" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#高血圧症におけるユースケース"><i class="fa fa-check"></i><b>7.4</b> 高血圧症におけるユースケース</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#特性評価に関する問い"><i class="fa fa-check"></i><b>7.4.1</b> 特性評価に関する問い</a></li>
<li class="chapter" data-level="7.4.2" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#集団レベルの推定問題"><i class="fa fa-check"></i><b>7.4.2</b> 集団レベルの推定問題</a></li>
<li class="chapter" data-level="7.4.3" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#患者レベルの予測問題"><i class="fa fa-check"></i><b>7.4.3</b> 患者レベルの予測問題</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#観察研究の限界"><i class="fa fa-check"></i><b>7.5</b> 観察研究の限界</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#誤ったデータ"><i class="fa fa-check"></i><b>7.5.1</b> 誤ったデータ</a></li>
<li class="chapter" data-level="7.5.2" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#欠損データ"><i class="fa fa-check"></i><b>7.5.2</b> 欠損データ</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#まとめ-5"><i class="fa fa-check"></i><b>7.6</b> まとめ</a></li>
<li class="chapter" data-level="7.7" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#演習-3"><i class="fa fa-check"></i><b>7.7</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html"><i class="fa fa-check"></i><b>8</b> OHDSI 分析ツール</a>
<ul>
<li class="chapter" data-level="8.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#analysisImplementation"><i class="fa fa-check"></i><b>8.1</b> 分析の実装</a></li>
<li class="chapter" data-level="8.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#分析戦略"><i class="fa fa-check"></i><b>8.2</b> 分析戦略</a></li>
<li class="chapter" data-level="8.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#atlas"><i class="fa fa-check"></i><b>8.3</b> ATLAS</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#セキュリティ"><i class="fa fa-check"></i><b>8.3.1</b> セキュリティ</a></li>
<li class="chapter" data-level="8.3.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#ドキュメント"><i class="fa fa-check"></i><b>8.3.2</b> ドキュメント</a></li>
<li class="chapter" data-level="8.3.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#インストール方法"><i class="fa fa-check"></i><b>8.3.3</b> インストール方法</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#methods-library"><i class="fa fa-check"></i><b>8.4</b> Methods Library</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#大規模分析サポート"><i class="fa fa-check"></i><b>8.4.1</b> 大規模分析サポート</a></li>
<li class="chapter" data-level="8.4.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#BigDataSupport"><i class="fa fa-check"></i><b>8.4.2</b> ビッグデータ対応</a></li>
<li class="chapter" data-level="8.4.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#ドキュメント-1"><i class="fa fa-check"></i><b>8.4.3</b> ドキュメント</a></li>
<li class="chapter" data-level="8.4.4" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#システム要件"><i class="fa fa-check"></i><b>8.4.4</b> システム要件</a></li>
<li class="chapter" data-level="8.4.5" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#installR"><i class="fa fa-check"></i><b>8.4.5</b> インストール方法</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#展開戦略"><i class="fa fa-check"></i><b>8.5</b> 展開戦略</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#broadsea"><i class="fa fa-check"></i><b>8.5.1</b> Broadsea</a></li>
<li class="chapter" data-level="8.5.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#amazon-aws"><i class="fa fa-check"></i><b>8.5.2</b> Amazon AWS</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#まとめ-6"><i class="fa fa-check"></i><b>8.6</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="SqlAndR.html"><a href="SqlAndR.html"><i class="fa fa-check"></i><b>9</b> SQLとR</a>
<ul>
<li class="chapter" data-level="9.1" data-path="SqlAndR.html"><a href="SqlAndR.html#SqlRender"><i class="fa fa-check"></i><b>9.1</b> SqlRender</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="SqlAndR.html"><a href="SqlAndR.html#sqlのパラメータ設定"><i class="fa fa-check"></i><b>9.1.1</b> SQLのパラメータ設定</a></li>
<li class="chapter" data-level="9.1.2" data-path="SqlAndR.html"><a href="SqlAndR.html#他のsql表現への置換"><i class="fa fa-check"></i><b>9.1.2</b> 他のSQL表現への置換</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="SqlAndR.html"><a href="SqlAndR.html#DatabaseConnector"><i class="fa fa-check"></i><b>9.2</b> DatabaseConnector</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="SqlAndR.html"><a href="SqlAndR.html#接続の作成"><i class="fa fa-check"></i><b>9.2.1</b> 接続の作成</a></li>
<li class="chapter" data-level="9.2.2" data-path="SqlAndR.html"><a href="SqlAndR.html#クエリの実行"><i class="fa fa-check"></i><b>9.2.2</b> クエリの実行</a></li>
<li class="chapter" data-level="9.2.3" data-path="SqlAndR.html"><a href="SqlAndR.html#ffdfオブジェクトを使用したクエリの実行"><i class="fa fa-check"></i><b>9.2.3</b> ffdfオブジェクトを使用したクエリの実行</a></li>
<li class="chapter" data-level="9.2.4" data-path="SqlAndR.html"><a href="SqlAndR.html#同じsqlを用いて異なるプラットフォームにクエリを実行する"><i class="fa fa-check"></i><b>9.2.4</b> 同じSQLを用いて異なるプラットフォームにクエリを実行する</a></li>
<li class="chapter" data-level="9.2.5" data-path="SqlAndR.html"><a href="SqlAndR.html#テーブルの挿入"><i class="fa fa-check"></i><b>9.2.5</b> テーブルの挿入</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="SqlAndR.html"><a href="SqlAndR.html#QueryTheCdm"><i class="fa fa-check"></i><b>9.3</b> CDMへのクエリ</a></li>
<li class="chapter" data-level="9.4" data-path="SqlAndR.html"><a href="SqlAndR.html#クエリ実行時にボキャブラリを使用する"><i class="fa fa-check"></i><b>9.4</b> クエリ実行時にボキャブラリを使用する</a></li>
<li class="chapter" data-level="9.5" data-path="SqlAndR.html"><a href="SqlAndR.html#querylibrary"><i class="fa fa-check"></i><b>9.5</b> QueryLibrary</a></li>
<li class="chapter" data-level="9.6" data-path="SqlAndR.html"><a href="SqlAndR.html#簡単な研究のデザイン"><i class="fa fa-check"></i><b>9.6</b> 簡単な研究のデザイン</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="SqlAndR.html"><a href="SqlAndR.html#問題の定義"><i class="fa fa-check"></i><b>9.6.1</b> 問題の定義</a></li>
<li class="chapter" data-level="9.6.2" data-path="SqlAndR.html"><a href="SqlAndR.html#曝露"><i class="fa fa-check"></i><b>9.6.2</b> 曝露</a></li>
<li class="chapter" data-level="9.6.3" data-path="SqlAndR.html"><a href="SqlAndR.html#アウトカム"><i class="fa fa-check"></i><b>9.6.3</b> アウトカム</a></li>
<li class="chapter" data-level="9.6.4" data-path="SqlAndR.html"><a href="SqlAndR.html#リスク期間"><i class="fa fa-check"></i><b>9.6.4</b> リスク期間</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="SqlAndR.html"><a href="SqlAndR.html#sqlとrを使用した研究の実施"><i class="fa fa-check"></i><b>9.7</b> SQLとRを使用した研究の実施</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="SqlAndR.html"><a href="SqlAndR.html#曝露コホート"><i class="fa fa-check"></i><b>9.7.1</b> 曝露コホート</a></li>
<li class="chapter" data-level="9.7.2" data-path="SqlAndR.html"><a href="SqlAndR.html#アウトカムコホート"><i class="fa fa-check"></i><b>9.7.2</b> アウトカムコホート</a></li>
<li class="chapter" data-level="9.7.3" data-path="SqlAndR.html"><a href="SqlAndR.html#発症率の計算"><i class="fa fa-check"></i><b>9.7.3</b> 発症率の計算</a></li>
<li class="chapter" data-level="9.7.4" data-path="SqlAndR.html"><a href="SqlAndR.html#クリーンアップ"><i class="fa fa-check"></i><b>9.7.4</b> クリーンアップ</a></li>
<li class="chapter" data-level="9.7.5" data-path="SqlAndR.html"><a href="SqlAndR.html#互換性"><i class="fa fa-check"></i><b>9.7.5</b> 互換性</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="SqlAndR.html"><a href="SqlAndR.html#まとめ-7"><i class="fa fa-check"></i><b>9.8</b> まとめ</a></li>
<li class="chapter" data-level="9.9" data-path="SqlAndR.html"><a href="SqlAndR.html#演習-4"><i class="fa fa-check"></i><b>9.9</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="Cohorts.html"><a href="Cohorts.html"><i class="fa fa-check"></i><b>10</b> コホートの定義</a>
<ul>
<li class="chapter" data-level="10.1" data-path="Cohorts.html"><a href="Cohorts.html#コホートとは"><i class="fa fa-check"></i><b>10.1</b> コホートとは？</a></li>
<li class="chapter" data-level="10.2" data-path="Cohorts.html"><a href="Cohorts.html#ルールベースのコホート定義"><i class="fa fa-check"></i><b>10.2</b> ルールベースのコホート定義</a></li>
<li class="chapter" data-level="10.3" data-path="Cohorts.html"><a href="Cohorts.html#conceptSets"><i class="fa fa-check"></i><b>10.3</b> コンセプトセット</a></li>
<li class="chapter" data-level="10.4" data-path="Cohorts.html"><a href="Cohorts.html#確率的コホート定義"><i class="fa fa-check"></i><b>10.4</b> 確率的コホート定義</a></li>
<li class="chapter" data-level="10.5" data-path="Cohorts.html"><a href="Cohorts.html#コホート定義の妥当性"><i class="fa fa-check"></i><b>10.5</b> コホート定義の妥当性</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="Cohorts.html"><a href="Cohorts.html#ohdsi-ゴールドスタンダードフェノタイプライブラリ"><i class="fa fa-check"></i><b>10.5.1</b> OHDSI ゴールドスタンダードフェノタイプライブラリ</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="Cohorts.html"><a href="Cohorts.html#高血圧のコホート定義"><i class="fa fa-check"></i><b>10.6</b> 高血圧のコホート定義</a></li>
<li class="chapter" data-level="10.7" data-path="Cohorts.html"><a href="Cohorts.html#atlasを用いたコホートの実装"><i class="fa fa-check"></i><b>10.7</b> ATLASを用いたコホートの実装</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="Cohorts.html"><a href="Cohorts.html#初期イベント基準"><i class="fa fa-check"></i><b>10.7.1</b> 初期イベント基準</a></li>
<li class="chapter" data-level="10.7.2" data-path="Cohorts.html"><a href="Cohorts.html#コンセプトセットの定義"><i class="fa fa-check"></i><b>10.7.2</b> コンセプトセットの定義</a></li>
<li class="chapter" data-level="10.7.3" data-path="Cohorts.html"><a href="Cohorts.html#初期イベントの追加基準"><i class="fa fa-check"></i><b>10.7.3</b> 初期イベントの追加基準</a></li>
<li class="chapter" data-level="10.7.4" data-path="Cohorts.html"><a href="Cohorts.html#適格基準"><i class="fa fa-check"></i><b>10.7.4</b> 適格基準</a></li>
<li class="chapter" data-level="10.7.5" data-path="Cohorts.html"><a href="Cohorts.html#コホート離脱基準"><i class="fa fa-check"></i><b>10.7.5</b> コホート離脱基準</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="Cohorts.html"><a href="Cohorts.html#sqlを使用したコホートの実装"><i class="fa fa-check"></i><b>10.8</b> SQLを使用したコホートの実装</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="Cohorts.html"><a href="Cohorts.html#データベースへの接続-1"><i class="fa fa-check"></i><b>10.8.1</b> データベースへの接続</a></li>
<li class="chapter" data-level="10.8.2" data-path="Cohorts.html"><a href="Cohorts.html#コンセプトの指定"><i class="fa fa-check"></i><b>10.8.2</b> コンセプトの指定</a></li>
<li class="chapter" data-level="10.8.3" data-path="Cohorts.html"><a href="Cohorts.html#初回使用の発見"><i class="fa fa-check"></i><b>10.8.3</b> 初回使用の発見</a></li>
<li class="chapter" data-level="10.8.4" data-path="Cohorts.html"><a href="Cohorts.html#日の事前観察が必要"><i class="fa fa-check"></i><b>10.8.4</b> 365日の事前観察が必要</a></li>
<li class="chapter" data-level="10.8.5" data-path="Cohorts.html"><a href="Cohorts.html#高血圧の前診断が必要"><i class="fa fa-check"></i><b>10.8.5</b> 高血圧の前診断が必要</a></li>
<li class="chapter" data-level="10.8.6" data-path="Cohorts.html"><a href="Cohorts.html#治療の無前使用が必要"><i class="fa fa-check"></i><b>10.8.6</b> 治療の無前使用が必要</a></li>
<li class="chapter" data-level="10.8.7" data-path="Cohorts.html"><a href="Cohorts.html#単剤療法"><i class="fa fa-check"></i><b>10.8.7</b> 単剤療法</a></li>
<li class="chapter" data-level="10.8.8" data-path="Cohorts.html"><a href="Cohorts.html#コホート離脱"><i class="fa fa-check"></i><b>10.8.8</b> コホート離脱</a></li>
<li class="chapter" data-level="10.8.9" data-path="Cohorts.html"><a href="Cohorts.html#クリーンアップ-1"><i class="fa fa-check"></i><b>10.8.9</b> クリーンアップ</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="Cohorts.html"><a href="Cohorts.html#要約"><i class="fa fa-check"></i><b>10.9</b> 要約</a></li>
<li class="chapter" data-level="10.10" data-path="Cohorts.html"><a href="Cohorts.html#演習-5"><i class="fa fa-check"></i><b>10.10</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Characterization.html"><a href="Characterization.html"><i class="fa fa-check"></i><b>11</b> 特性評価</a>
<ul>
<li class="chapter" data-level="11.1" data-path="Characterization.html"><a href="Characterization.html#データベースレベルの特性評価"><i class="fa fa-check"></i><b>11.1</b> データベースレベルの特性評価</a></li>
<li class="chapter" data-level="11.2" data-path="Characterization.html"><a href="Characterization.html#コホート特性評価"><i class="fa fa-check"></i><b>11.2</b> コホート特性評価</a></li>
<li class="chapter" data-level="11.3" data-path="Characterization.html"><a href="Characterization.html#治療経路"><i class="fa fa-check"></i><b>11.3</b> 治療経路</a></li>
<li class="chapter" data-level="11.4" data-path="Characterization.html"><a href="Characterization.html#発生率"><i class="fa fa-check"></i><b>11.4</b> 発生率</a></li>
<li class="chapter" data-level="11.5" data-path="Characterization.html"><a href="Characterization.html#高血圧症患者の特性評価"><i class="fa fa-check"></i><b>11.5</b> 高血圧症患者の特性評価</a></li>
<li class="chapter" data-level="11.6" data-path="Characterization.html"><a href="Characterization.html#atlasにおけるデータベースの特性評価"><i class="fa fa-check"></i><b>11.6</b> ATLASにおけるデータベースの特性評価</a></li>
<li class="chapter" data-level="11.7" data-path="Characterization.html"><a href="Characterization.html#atlasにおけるコホート特性分析"><i class="fa fa-check"></i><b>11.7</b> ATLASにおけるコホート特性分析</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="Characterization.html"><a href="Characterization.html#デザイン"><i class="fa fa-check"></i><b>11.7.1</b> デザイン</a></li>
<li class="chapter" data-level="11.7.2" data-path="Characterization.html"><a href="Characterization.html#実行"><i class="fa fa-check"></i><b>11.7.2</b> 実行</a></li>
<li class="chapter" data-level="11.7.3" data-path="Characterization.html"><a href="Characterization.html#結果"><i class="fa fa-check"></i><b>11.7.3</b> 結果</a></li>
<li class="chapter" data-level="11.7.4" data-path="Characterization.html"><a href="Characterization.html#カスタム特徴量の定義"><i class="fa fa-check"></i><b>11.7.4</b> カスタム特徴量の定義</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="Characterization.html"><a href="Characterization.html#rでのコホートの特性評価"><i class="fa fa-check"></i><b>11.8</b> Rでのコホートの特性評価</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="Characterization.html"><a href="Characterization.html#コホートのインスタンス化"><i class="fa fa-check"></i><b>11.8.1</b> コホートのインスタンス化</a></li>
<li class="chapter" data-level="11.8.2" data-path="Characterization.html"><a href="Characterization.html#データ抽出"><i class="fa fa-check"></i><b>11.8.2</b> データ抽出</a></li>
<li class="chapter" data-level="11.8.3" data-path="Characterization.html"><a href="Characterization.html#事前に指定された分析の使用"><i class="fa fa-check"></i><b>11.8.3</b> 事前に指定された分析の使用</a></li>
<li class="chapter" data-level="11.8.4" data-path="Characterization.html"><a href="Characterization.html#集約共変量の作成"><i class="fa fa-check"></i><b>11.8.4</b> 集約共変量の作成</a></li>
<li class="chapter" data-level="11.8.5" data-path="Characterization.html"><a href="Characterization.html#出力形式"><i class="fa fa-check"></i><b>11.8.5</b> 出力形式</a></li>
<li class="chapter" data-level="11.8.6" data-path="Characterization.html"><a href="Characterization.html#カスタム共変量"><i class="fa fa-check"></i><b>11.8.6</b> カスタム共変量</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="Characterization.html"><a href="Characterization.html#atlasにおけるコホート経路分析"><i class="fa fa-check"></i><b>11.9</b> ATLASにおけるコホート経路分析</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="Characterization.html"><a href="Characterization.html#デザイン-1"><i class="fa fa-check"></i><b>11.9.1</b> デザイン</a></li>
<li class="chapter" data-level="11.9.2" data-path="Characterization.html"><a href="Characterization.html#実行-1"><i class="fa fa-check"></i><b>11.9.2</b> 実行</a></li>
<li class="chapter" data-level="11.9.3" data-path="Characterization.html"><a href="Characterization.html#結果の表示"><i class="fa fa-check"></i><b>11.9.3</b> 結果の表示</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="Characterization.html"><a href="Characterization.html#atlas-における発生率分析"><i class="fa fa-check"></i><b>11.10</b> ATLAS における発生率分析</a>
<ul>
<li class="chapter" data-level="11.10.1" data-path="Characterization.html"><a href="Characterization.html#デザイン-2"><i class="fa fa-check"></i><b>11.10.1</b> デザイン</a></li>
<li class="chapter" data-level="11.10.2" data-path="Characterization.html"><a href="Characterization.html#実行-2"><i class="fa fa-check"></i><b>11.10.2</b> 実行</a></li>
<li class="chapter" data-level="11.10.3" data-path="Characterization.html"><a href="Characterization.html#結果の表示-1"><i class="fa fa-check"></i><b>11.10.3</b> 結果の表示</a></li>
</ul></li>
<li class="chapter" data-level="11.11" data-path="Characterization.html"><a href="Characterization.html#まとめ-8"><i class="fa fa-check"></i><b>11.11</b> まとめ</a></li>
<li class="chapter" data-level="11.12" data-path="Characterization.html"><a href="Characterization.html#演習-6"><i class="fa fa-check"></i><b>11.12</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html"><i class="fa fa-check"></i><b>12</b> 集団レベルの推定</a>
<ul>
<li class="chapter" data-level="12.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#CohortMethod"><i class="fa fa-check"></i><b>12.1</b> コホートメソッドの設計</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#傾向スコア"><i class="fa fa-check"></i><b>12.1.1</b> 傾向スコア</a></li>
<li class="chapter" data-level="12.1.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#VariableSelection"><i class="fa fa-check"></i><b>12.1.2</b> 変数選択</a></li>
<li class="chapter" data-level="12.1.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#カリパー"><i class="fa fa-check"></i><b>12.1.3</b> カリパー</a></li>
<li class="chapter" data-level="12.1.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#オーバーラップ選好スコア"><i class="fa fa-check"></i><b>12.1.4</b> オーバーラップ：選好スコア</a></li>
<li class="chapter" data-level="12.1.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#バランス"><i class="fa fa-check"></i><b>12.1.5</b> バランス</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#自己対照コホートデザイン"><i class="fa fa-check"></i><b>12.2</b> 自己対照コホートデザイン</a></li>
<li class="chapter" data-level="12.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#症例対照デザイン"><i class="fa fa-check"></i><b>12.3</b> 症例対照デザイン</a></li>
<li class="chapter" data-level="12.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#ケースクロスオーバーデザイン"><i class="fa fa-check"></i><b>12.4</b> ケース・クロスオーバーデザイン</a></li>
<li class="chapter" data-level="12.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#自己対照症例シリーズデザイン"><i class="fa fa-check"></i><b>12.5</b> 自己対照症例シリーズデザイン</a></li>
<li class="chapter" data-level="12.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#高血圧症研究のデザイン"><i class="fa fa-check"></i><b>12.6</b> 高血圧症研究のデザイン</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#問題の定義-1"><i class="fa fa-check"></i><b>12.6.1</b> 問題の定義</a></li>
<li class="chapter" data-level="12.6.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#対象および比較対照"><i class="fa fa-check"></i><b>12.6.2</b> 対象および比較対照</a></li>
<li class="chapter" data-level="12.6.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#アウトカム-1"><i class="fa fa-check"></i><b>12.6.3</b> アウトカム</a></li>
<li class="chapter" data-level="12.6.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#リスク期間-1"><i class="fa fa-check"></i><b>12.6.4</b> リスク期間</a></li>
<li class="chapter" data-level="12.6.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#モデル"><i class="fa fa-check"></i><b>12.6.5</b> モデル</a></li>
<li class="chapter" data-level="12.6.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#研究要約"><i class="fa fa-check"></i><b>12.6.6</b> 研究要約</a></li>
<li class="chapter" data-level="12.6.7" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#コントロールクエスチョン"><i class="fa fa-check"></i><b>12.6.7</b> コントロールクエスチョン</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#PleAtlas"><i class="fa fa-check"></i><b>12.7</b> ATLASを使用した研究の実施</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#ComparisonSettings"><i class="fa fa-check"></i><b>12.7.1</b> 比較コホート設定</a></li>
<li class="chapter" data-level="12.7.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#効果推定の分析設定"><i class="fa fa-check"></i><b>12.7.2</b> 効果推定の分析設定</a></li>
<li class="chapter" data-level="12.7.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#evaluationSettings"><i class="fa fa-check"></i><b>12.7.3</b> 評価の設定</a></li>
<li class="chapter" data-level="12.7.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#研究パッケージの実行"><i class="fa fa-check"></i><b>12.7.4</b> 研究パッケージの実行</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#pleR"><i class="fa fa-check"></i><b>12.8</b> Rを使用した研究の実施</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#コホートのインスタンス化-1"><i class="fa fa-check"></i><b>12.8.1</b> コホートのインスタンス化</a></li>
<li class="chapter" data-level="12.8.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#データ抽出-1"><i class="fa fa-check"></i><b>12.8.2</b> データ抽出</a></li>
<li class="chapter" data-level="12.8.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#研究集団の定義"><i class="fa fa-check"></i><b>12.8.3</b> 研究集団の定義</a></li>
<li class="chapter" data-level="12.8.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#傾向スコア-1"><i class="fa fa-check"></i><b>12.8.4</b> 傾向スコア</a></li>
<li class="chapter" data-level="12.8.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#アウトカムモデル"><i class="fa fa-check"></i><b>12.8.5</b> アウトカムモデル</a></li>
<li class="chapter" data-level="12.8.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#MultipleAnalyses"><i class="fa fa-check"></i><b>12.8.6</b> 複数の分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#studyOutputs"><i class="fa fa-check"></i><b>12.9</b> 研究の結果</a>
<ul>
<li class="chapter" data-level="12.9.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#傾向スコアとモデル"><i class="fa fa-check"></i><b>12.9.1</b> 傾向スコアとモデル</a></li>
<li class="chapter" data-level="12.9.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#共変量のバランス"><i class="fa fa-check"></i><b>12.9.2</b> 共変量のバランス</a></li>
<li class="chapter" data-level="12.9.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#フォローアップとパワー"><i class="fa fa-check"></i><b>12.9.3</b> フォローアップとパワー</a></li>
<li class="chapter" data-level="12.9.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#カプランマイヤー"><i class="fa fa-check"></i><b>12.9.4</b> カプラン・マイヤー</a></li>
<li class="chapter" data-level="12.9.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#効果量の推定"><i class="fa fa-check"></i><b>12.9.5</b> 効果量の推定</a></li>
</ul></li>
<li class="chapter" data-level="12.10" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#まとめ-9"><i class="fa fa-check"></i><b>12.10</b> まとめ</a></li>
<li class="chapter" data-level="12.11" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#演習-7"><i class="fa fa-check"></i><b>12.11</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html"><i class="fa fa-check"></i><b>13</b> 患者レベルの予測</a>
<ul>
<li class="chapter" data-level="13.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#予測課題"><i class="fa fa-check"></i><b>13.1</b> 予測課題</a></li>
<li class="chapter" data-level="13.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#データ抽出-2"><i class="fa fa-check"></i><b>13.2</b> データ抽出</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#データ抽出の例"><i class="fa fa-check"></i><b>13.2.1</b> データ抽出の例</a></li>
<li class="chapter" data-level="13.2.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#負の値と欠損"><i class="fa fa-check"></i><b>13.2.2</b> 負の値と欠損</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#modelFitting"><i class="fa fa-check"></i><b>13.3</b> モデルの適合</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#正則化ロジスティック回帰"><i class="fa fa-check"></i><b>13.3.1</b> 正則化ロジスティック回帰</a></li>
<li class="chapter" data-level="13.3.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#勾配ブースティングマシン"><i class="fa fa-check"></i><b>13.3.2</b> 勾配ブースティングマシン</a></li>
<li class="chapter" data-level="13.3.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#ランダムフォレスト"><i class="fa fa-check"></i><b>13.3.3</b> ランダムフォレスト</a></li>
<li class="chapter" data-level="13.3.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#k-近傍法"><i class="fa fa-check"></i><b>13.3.4</b> K-近傍法</a></li>
<li class="chapter" data-level="13.3.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#ナイーブベイズ"><i class="fa fa-check"></i><b>13.3.5</b> ナイーブベイズ</a></li>
<li class="chapter" data-level="13.3.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#adaboost"><i class="fa fa-check"></i><b>13.3.6</b> AdaBoost</a></li>
<li class="chapter" data-level="13.3.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#決定ツリー"><i class="fa fa-check"></i><b>13.3.7</b> 決定ツリー</a></li>
<li class="chapter" data-level="13.3.8" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#多層パーセプトロン"><i class="fa fa-check"></i><b>13.3.8</b> 多層パーセプトロン</a></li>
<li class="chapter" data-level="13.3.9" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#深層学習"><i class="fa fa-check"></i><b>13.3.9</b> 深層学習</a></li>
<li class="chapter" data-level="13.3.10" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#その他のアルゴリズム"><i class="fa fa-check"></i><b>13.3.10</b> その他のアルゴリズム</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#予測モデルの評価"><i class="fa fa-check"></i><b>13.4</b> 予測モデルの評価</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#評価の種類"><i class="fa fa-check"></i><b>13.4.1</b> 評価の種類</a></li>
<li class="chapter" data-level="13.4.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#performance"><i class="fa fa-check"></i><b>13.4.2</b> 性能指標</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#患者レベル予測研究のデザイン"><i class="fa fa-check"></i><b>13.5</b> 患者レベル予測研究のデザイン</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#問題の定義-2"><i class="fa fa-check"></i><b>13.5.1</b> 問題の定義</a></li>
<li class="chapter" data-level="13.5.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究集団の定義-1"><i class="fa fa-check"></i><b>13.5.2</b> 研究集団の定義</a></li>
<li class="chapter" data-level="13.5.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデル開発の設定"><i class="fa fa-check"></i><b>13.5.3</b> モデル開発の設定</a></li>
<li class="chapter" data-level="13.5.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデル評価"><i class="fa fa-check"></i><b>13.5.4</b> モデル評価</a></li>
<li class="chapter" data-level="13.5.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究概要"><i class="fa fa-check"></i><b>13.5.5</b> 研究概要</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#atlasでの研究の実装"><i class="fa fa-check"></i><b>13.6</b> ATLASでの研究の実装</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#予測の問題設定"><i class="fa fa-check"></i><b>13.6.1</b> 予測の問題設定</a></li>
<li class="chapter" data-level="13.6.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#分析設定"><i class="fa fa-check"></i><b>13.6.2</b> 分析設定</a></li>
<li class="chapter" data-level="13.6.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#実行の設定"><i class="fa fa-check"></i><b>13.6.3</b> 実行の設定</a></li>
<li class="chapter" data-level="13.6.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#トレーニングの設定"><i class="fa fa-check"></i><b>13.6.4</b> トレーニングの設定</a></li>
<li class="chapter" data-level="13.6.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究のインポートとエクスポート"><i class="fa fa-check"></i><b>13.6.5</b> 研究のインポートとエクスポート</a></li>
<li class="chapter" data-level="13.6.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究パッケージのダウンロード"><i class="fa fa-check"></i><b>13.6.6</b> 研究パッケージのダウンロード</a></li>
<li class="chapter" data-level="13.6.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究の実行"><i class="fa fa-check"></i><b>13.6.7</b> 研究の実行</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#rでの研究実施"><i class="fa fa-check"></i><b>13.7</b> Rでの研究実施</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#コホートのインスタンス化-2"><i class="fa fa-check"></i><b>13.7.1</b> コホートのインスタンス化</a></li>
<li class="chapter" data-level="13.7.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#データ抽出-3"><i class="fa fa-check"></i><b>13.7.2</b> データ抽出</a></li>
<li class="chapter" data-level="13.7.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#追加の適格基準"><i class="fa fa-check"></i><b>13.7.3</b> 追加の適格基準</a></li>
<li class="chapter" data-level="13.7.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデル開発"><i class="fa fa-check"></i><b>13.7.4</b> モデル開発</a></li>
<li class="chapter" data-level="13.7.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#内部バリデーション"><i class="fa fa-check"></i><b>13.7.5</b> 内部バリデーション</a></li>
<li class="chapter" data-level="13.7.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#外部バリデーション"><i class="fa fa-check"></i><b>13.7.6</b> 外部バリデーション</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#結果の公表"><i class="fa fa-check"></i><b>13.8</b> 結果の公表</a>
<ul>
<li class="chapter" data-level="13.8.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデル性能"><i class="fa fa-check"></i><b>13.8.1</b> モデル性能</a></li>
<li class="chapter" data-level="13.8.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデルの比較"><i class="fa fa-check"></i><b>13.8.2</b> モデルの比較</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#患者レベルの予測に関する追加の機能"><i class="fa fa-check"></i><b>13.9</b> 患者レベルの予測に関する追加の機能</a>
<ul>
<li class="chapter" data-level="13.9.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#学術誌論文の生成"><i class="fa fa-check"></i><b>13.9.1</b> 学術誌論文の生成</a></li>
</ul></li>
<li class="chapter" data-level="13.10" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#まとめ-10"><i class="fa fa-check"></i><b>13.10</b> まとめ</a></li>
<li class="chapter" data-level="13.11" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#演習-8"><i class="fa fa-check"></i><b>13.11</b> 演習</a></li>
</ul></li>
<li class="part"><span><b>IV エビデンスの質</b></span></li>
<li class="chapter" data-level="14" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html"><i class="fa fa-check"></i><b>14</b> エビデンスの質</a>
<ul>
<li class="chapter" data-level="14.1" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#信頼できるエビデンスの属性"><i class="fa fa-check"></i><b>14.1</b> 信頼できるエビデンスの属性</a></li>
<li class="chapter" data-level="14.2" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#エビデンスの質の理解"><i class="fa fa-check"></i><b>14.2</b> エビデンスの質の理解</a></li>
<li class="chapter" data-level="14.3" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#エビデンスの質の伝達"><i class="fa fa-check"></i><b>14.3</b> エビデンスの質の伝達</a></li>
<li class="chapter" data-level="14.4" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#まとめ-11"><i class="fa fa-check"></i><b>14.4</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="DataQuality.html"><a href="DataQuality.html"><i class="fa fa-check"></i><b>15</b> データ品質</a>
<ul>
<li class="chapter" data-level="15.1" data-path="DataQuality.html"><a href="DataQuality.html#データ品質問題の原因"><i class="fa fa-check"></i><b>15.1</b> データ品質問題の原因</a></li>
<li class="chapter" data-level="15.2" data-path="DataQuality.html"><a href="DataQuality.html#一般的なデータ品質"><i class="fa fa-check"></i><b>15.2</b> 一般的なデータ品質</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="DataQuality.html"><a href="DataQuality.html#データ品質チェック"><i class="fa fa-check"></i><b>15.2.1</b> データ品質チェック</a></li>
<li class="chapter" data-level="15.2.2" data-path="DataQuality.html"><a href="DataQuality.html#etlUnitTests"><i class="fa fa-check"></i><b>15.2.2</b> ETL（抽出-変換-読込）単体テスト</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="DataQuality.html"><a href="DataQuality.html#研究特有のチェック"><i class="fa fa-check"></i><b>15.3</b> 研究特有のチェック</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="DataQuality.html"><a href="DataQuality.html#マッピングのチェック"><i class="fa fa-check"></i><b>15.3.1</b> マッピングのチェック</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="DataQuality.html"><a href="DataQuality.html#achillesInPractice"><i class="fa fa-check"></i><b>15.4</b> 実践におけるACHILLES</a></li>
<li class="chapter" data-level="15.5" data-path="DataQuality.html"><a href="DataQuality.html#dqdInPractice"><i class="fa fa-check"></i><b>15.5</b> Data Quality Dashboardの実践</a></li>
<li class="chapter" data-level="15.6" data-path="DataQuality.html"><a href="DataQuality.html#特定の研究チェックの実践"><i class="fa fa-check"></i><b>15.6</b> 特定の研究チェックの実践</a></li>
<li class="chapter" data-level="15.7" data-path="DataQuality.html"><a href="DataQuality.html#まとめ-12"><i class="fa fa-check"></i><b>15.7</b> まとめ</a></li>
<li class="chapter" data-level="15.8" data-path="DataQuality.html"><a href="DataQuality.html#演習-9"><i class="fa fa-check"></i><b>15.8</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html"><i class="fa fa-check"></i><b>16</b> 臨床的妥当性</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#CharacteristicsOfDatabase"><i class="fa fa-check"></i><b>16.1</b> 医療データベースの特性</a></li>
<li class="chapter" data-level="16.2" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#CohortValidation"><i class="fa fa-check"></i><b>16.2</b> コホートバリデーション</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#コホート評価指標"><i class="fa fa-check"></i><b>16.2.1</b> コホート評価指標</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#ソースレコード検証"><i class="fa fa-check"></i><b>16.3</b> ソースレコード検証</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#ソースレコード検証の例"><i class="fa fa-check"></i><b>16.3.1</b> ソースレコード検証の例</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#phevaluator"><i class="fa fa-check"></i><b>16.4</b> PheValuator</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#phevaluatorによる検証例"><i class="fa fa-check"></i><b>16.4.1</b> PheValuatorによる検証例</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#GeneralizabilityOfEvidence"><i class="fa fa-check"></i><b>16.5</b> エビデンスの一般化可能性</a></li>
<li class="chapter" data-level="16.6" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#まとめ-13"><i class="fa fa-check"></i><b>16.6</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html"><i class="fa fa-check"></i><b>17</b> ソフトウェアの妥当性</a>
<ul>
<li class="chapter" data-level="17.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#研究コードの妥当性"><i class="fa fa-check"></i><b>17.1</b> 研究コードの妥当性</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#automation"><i class="fa fa-check"></i><b>17.1.1</b> 再現性のための自動化の必要性</a></li>
<li class="chapter" data-level="17.1.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#プログラミングのベストプラクティス"><i class="fa fa-check"></i><b>17.1.2</b> プログラミングのベストプラクティス</a></li>
<li class="chapter" data-level="17.1.3" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#コードの検証"><i class="fa fa-check"></i><b>17.1.3</b> コードの検証</a></li>
<li class="chapter" data-level="17.1.4" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#methods-libraryの使用"><i class="fa fa-check"></i><b>17.1.4</b> Methods Libraryの使用</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#methods-librarのソフトウェア開発プロセス"><i class="fa fa-check"></i><b>17.2</b> Methods Librarのソフトウェア開発プロセス</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#ソースコード管理"><i class="fa fa-check"></i><b>17.2.1</b> ソースコード管理</a></li>
<li class="chapter" data-level="17.2.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#ドキュメンテーション"><i class="fa fa-check"></i><b>17.2.2</b> ドキュメンテーション</a></li>
<li class="chapter" data-level="17.2.3" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#現行および過去のアーカイブバージョンの利用可能性"><i class="fa fa-check"></i><b>17.2.3</b> 現行および過去のアーカイブバージョンの利用可能性</a></li>
<li class="chapter" data-level="17.2.4" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#メンテナンスサポートおよびリタイアメント"><i class="fa fa-check"></i><b>17.2.4</b> メンテナンス、サポート、およびリタイアメント</a></li>
<li class="chapter" data-level="17.2.5" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#有資格者"><i class="fa fa-check"></i><b>17.2.5</b> 有資格者</a></li>
<li class="chapter" data-level="17.2.6" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#物理的および論理的セキュリティ"><i class="fa fa-check"></i><b>17.2.6</b> 物理的および論理的セキュリティ</a></li>
<li class="chapter" data-level="17.2.7" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#災害復旧"><i class="fa fa-check"></i><b>17.2.7</b> 災害復旧</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#methods-libraryのテスト"><i class="fa fa-check"></i><b>17.3</b> Methods Libraryのテスト</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#ユニットテスト"><i class="fa fa-check"></i><b>17.3.1</b> ユニットテスト</a></li>
<li class="chapter" data-level="17.3.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#シミュレーション"><i class="fa fa-check"></i><b>17.3.2</b> シミュレーション</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#まとめ-14"><i class="fa fa-check"></i><b>17.4</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="MethodValidity.html"><a href="MethodValidity.html"><i class="fa fa-check"></i><b>18</b> 方法の妥当性</a>
<ul>
<li class="chapter" data-level="18.1" data-path="MethodValidity.html"><a href="MethodValidity.html#デザイン特有の診断"><i class="fa fa-check"></i><b>18.1</b> デザイン特有の診断</a></li>
<li class="chapter" data-level="18.2" data-path="MethodValidity.html"><a href="MethodValidity.html#推定のための診断"><i class="fa fa-check"></i><b>18.2</b> 推定のための診断</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="MethodValidity.html"><a href="MethodValidity.html#NegativeControls"><i class="fa fa-check"></i><b>18.2.1</b> ネガティブコントロール</a></li>
<li class="chapter" data-level="18.2.2" data-path="MethodValidity.html"><a href="MethodValidity.html#PositiveControls"><i class="fa fa-check"></i><b>18.2.2</b> ポジティブコントロール</a></li>
<li class="chapter" data-level="18.2.3" data-path="MethodValidity.html"><a href="MethodValidity.html#metrics"><i class="fa fa-check"></i><b>18.2.3</b> 実証的評価</a></li>
<li class="chapter" data-level="18.2.4" data-path="MethodValidity.html"><a href="MethodValidity.html#p値のキャリブレーション"><i class="fa fa-check"></i><b>18.2.4</b> P値のキャリブレーション</a></li>
<li class="chapter" data-level="18.2.5" data-path="MethodValidity.html"><a href="MethodValidity.html#信頼区間のキャリブレーション"><i class="fa fa-check"></i><b>18.2.5</b> 信頼区間のキャリブレーション</a></li>
<li class="chapter" data-level="18.2.6" data-path="MethodValidity.html"><a href="MethodValidity.html#医療機関をまたいだ複製"><i class="fa fa-check"></i><b>18.2.6</b> 医療機関をまたいだ複製</a></li>
<li class="chapter" data-level="18.2.7" data-path="MethodValidity.html"><a href="MethodValidity.html#感度分析"><i class="fa fa-check"></i><b>18.2.7</b> 感度分析</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="MethodValidity.html"><a href="MethodValidity.html#実践におけるメソッド検証"><i class="fa fa-check"></i><b>18.3</b> 実践におけるメソッド検証</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="MethodValidity.html"><a href="MethodValidity.html#ネガティブコントロールの選択"><i class="fa fa-check"></i><b>18.3.1</b> ネガティブコントロールの選択</a></li>
<li class="chapter" data-level="18.3.2" data-path="MethodValidity.html"><a href="MethodValidity.html#コントロールを含めること"><i class="fa fa-check"></i><b>18.3.2</b> コントロールを含めること</a></li>
<li class="chapter" data-level="18.3.3" data-path="MethodValidity.html"><a href="MethodValidity.html#実証されたパフォーマンス"><i class="fa fa-check"></i><b>18.3.3</b> 実証されたパフォーマンス</a></li>
<li class="chapter" data-level="18.3.4" data-path="MethodValidity.html"><a href="MethodValidity.html#p値のキャリブレーション-1"><i class="fa fa-check"></i><b>18.3.4</b> P値のキャリブレーション</a></li>
<li class="chapter" data-level="18.3.5" data-path="MethodValidity.html"><a href="MethodValidity.html#信頼区間のキャリブレーション-1"><i class="fa fa-check"></i><b>18.3.5</b> 信頼区間のキャリブレーション</a></li>
<li class="chapter" data-level="18.3.6" data-path="MethodValidity.html"><a href="MethodValidity.html#データベース間の異質性"><i class="fa fa-check"></i><b>18.3.6</b> データベース間の異質性</a></li>
<li class="chapter" data-level="18.3.7" data-path="MethodValidity.html"><a href="MethodValidity.html#感度分析-1"><i class="fa fa-check"></i><b>18.3.7</b> 感度分析</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="MethodValidity.html"><a href="MethodValidity.html#ohdsiメソッド評価ベンチマーク"><i class="fa fa-check"></i><b>18.4</b> OHDSIメソッド評価ベンチマーク</a></li>
<li class="chapter" data-level="18.5" data-path="MethodValidity.html"><a href="MethodValidity.html#まとめ-15"><i class="fa fa-check"></i><b>18.5</b> まとめ</a></li>
</ul></li>
<li class="part"><span><b>V OHDSI研究</b></span></li>
<li class="chapter" data-level="19" data-path="StudySteps.html"><a href="StudySteps.html"><i class="fa fa-check"></i><b>19</b> 研究の段階</a>
<ul>
<li class="chapter" data-level="19.1" data-path="StudySteps.html"><a href="StudySteps.html#一般的なベストプラクティスガイドライン"><i class="fa fa-check"></i><b>19.1</b> 一般的なベストプラクティスガイドライン</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="StudySteps.html"><a href="StudySteps.html#観察研究の定義"><i class="fa fa-check"></i><b>19.1.1</b> 観察研究の定義</a></li>
<li class="chapter" data-level="19.1.2" data-path="StudySteps.html"><a href="StudySteps.html#事前に規定した研究デザイン"><i class="fa fa-check"></i><b>19.1.2</b> 事前に規定した研究デザイン</a></li>
<li class="chapter" data-level="19.1.3" data-path="StudySteps.html"><a href="StudySteps.html#プロトコル"><i class="fa fa-check"></i><b>19.1.3</b> プロトコル</a></li>
<li class="chapter" data-level="19.1.4" data-path="StudySteps.html"><a href="StudySteps.html#標準化された分析"><i class="fa fa-check"></i><b>19.1.4</b> 標準化された分析</a></li>
<li class="chapter" data-level="19.1.5" data-path="StudySteps.html"><a href="StudySteps.html#研究パッケージ"><i class="fa fa-check"></i><b>19.1.5</b> 研究パッケージ</a></li>
<li class="chapter" data-level="19.1.6" data-path="StudySteps.html"><a href="StudySteps.html#cdmに基づくデータ"><i class="fa fa-check"></i><b>19.1.6</b> CDMに基づくデータ</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="StudySteps.html"><a href="StudySteps.html#詳細な研究手順"><i class="fa fa-check"></i><b>19.2</b> 詳細な研究手順</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="StudySteps.html"><a href="StudySteps.html#問いを定義する"><i class="fa fa-check"></i><b>19.2.1</b> 問いを定義する</a></li>
<li class="chapter" data-level="19.2.2" data-path="StudySteps.html"><a href="StudySteps.html#データの可用性と質を確認する"><i class="fa fa-check"></i><b>19.2.2</b> データの可用性と質を確認する</a></li>
<li class="chapter" data-level="19.2.3" data-path="StudySteps.html"><a href="StudySteps.html#研究対象集団-1"><i class="fa fa-check"></i><b>19.2.3</b> 研究対象集団</a></li>
<li class="chapter" data-level="19.2.4" data-path="StudySteps.html"><a href="StudySteps.html#Feasibility"><i class="fa fa-check"></i><b>19.2.4</b> 実施可能性と研究診断</a></li>
<li class="chapter" data-level="19.2.5" data-path="StudySteps.html"><a href="StudySteps.html#プロトコルと研究パッケージの最終化"><i class="fa fa-check"></i><b>19.2.5</b> プロトコルと研究パッケージの最終化</a></li>
<li class="chapter" data-level="19.2.6" data-path="StudySteps.html"><a href="StudySteps.html#研究の実施"><i class="fa fa-check"></i><b>19.2.6</b> 研究の実施</a></li>
<li class="chapter" data-level="19.2.7" data-path="StudySteps.html"><a href="StudySteps.html#解釈と報告"><i class="fa fa-check"></i><b>19.2.7</b> 解釈と報告</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="StudySteps.html"><a href="StudySteps.html#まとめ-16"><i class="fa fa-check"></i><b>19.3</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="NetworkResearch.html"><a href="NetworkResearch.html"><i class="fa fa-check"></i><b>20</b> OHDSI ネットワーク研究</a>
<ul>
<li class="chapter" data-level="20.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi-研究ネットワークとして"><i class="fa fa-check"></i><b>20.1</b> OHDSI 研究ネットワークとして</a></li>
<li class="chapter" data-level="20.2" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究"><i class="fa fa-check"></i><b>20.2</b> OHDSIネットワーク研究</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究を実施する動機"><i class="fa fa-check"></i><b>20.2.1</b> OHDSIネットワーク研究を実施する動機</a></li>
<li class="chapter" data-level="20.2.2" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究の定義"><i class="fa fa-check"></i><b>20.2.2</b> OHDSIネットワーク研究の定義</a></li>
<li class="chapter" data-level="20.2.3" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究の設計上の考慮事項"><i class="fa fa-check"></i><b>20.2.3</b> OHDSIネットワーク研究の設計上の考慮事項</a></li>
<li class="chapter" data-level="20.2.4" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究のためのロジスティクスに関する考察"><i class="fa fa-check"></i><b>20.2.4</b> OHDSIネットワーク研究のためのロジスティクスに関する考察</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究の実行"><i class="fa fa-check"></i><b>20.3</b> OHDSIネットワーク研究の実行</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#研究デザインと実現可能性"><i class="fa fa-check"></i><b>20.3.1</b> 研究デザインと実現可能性</a></li>
<li class="chapter" data-level="20.3.2" data-path="NetworkResearch.html"><a href="NetworkResearch.html#研究の実行-1"><i class="fa fa-check"></i><b>20.3.2</b> 研究の実行</a></li>
<li class="chapter" data-level="20.3.3" data-path="NetworkResearch.html"><a href="NetworkResearch.html#結果の普及と公開"><i class="fa fa-check"></i><b>20.3.3</b> 結果の普及と公開</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="NetworkResearch.html"><a href="NetworkResearch.html#展望-ネットワーク研究の自動化を利用する"><i class="fa fa-check"></i><b>20.4</b> 展望: ネットワーク研究の自動化を利用する</a></li>
<li class="chapter" data-level="20.5" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究のベストプラクティス"><i class="fa fa-check"></i><b>20.5</b> OHDSIネットワーク研究のベストプラクティス</a></li>
<li class="chapter" data-level="20.6" data-path="NetworkResearch.html"><a href="NetworkResearch.html#まとめ-17"><i class="fa fa-check"></i><b>20.6</b> まとめ</a></li>
</ul></li>
<li class="appendix"><span><b>付録</b></span></li>
<li class="chapter" data-level="A" data-path="Glossary.html"><a href="Glossary.html"><i class="fa fa-check"></i><b>A</b> 用語集</a></li>
<li class="chapter" data-level="B" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html"><i class="fa fa-check"></i><b>B</b> コホート定義</a>
<ul>
<li class="chapter" data-level="B.1" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#AceInhibitors"><i class="fa fa-check"></i><b>B.1</b> ACE阻害薬</a></li>
<li class="chapter" data-level="B.2" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#AceInhibitorsMono"><i class="fa fa-check"></i><b>B.2</b> ACE阻害薬単剤療法新規ユーザー</a></li>
<li class="chapter" data-level="B.3" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#Ami"><i class="fa fa-check"></i><b>B.3</b> 急性心筋梗塞（AMI）</a></li>
<li class="chapter" data-level="B.4" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#Angioedema"><i class="fa fa-check"></i><b>B.4</b> 血管性浮腫</a></li>
<li class="chapter" data-level="B.5" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ThiazidesMono"><i class="fa fa-check"></i><b>B.5</b> サイアザイド様利尿薬単剤療法の新規ユーザー使用者</a></li>
<li class="chapter" data-level="B.6" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#HTN1yrFO"><i class="fa fa-check"></i><b>B.6</b> 高血圧のための第一選択治療を開始する患者</a></li>
<li class="chapter" data-level="B.7" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#HTN3yrFO"><i class="fa fa-check"></i><b>B.7</b> 追跡期間が3年以上ある高血圧のための第一選択治療を開始する患者</a></li>
<li class="chapter" data-level="B.8" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ACEiUse"><i class="fa fa-check"></i><b>B.8</b> ACE阻害薬の使用</a></li>
<li class="chapter" data-level="B.9" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ARBUse"><i class="fa fa-check"></i><b>B.9</b> アンジオテンシン受容体拮抗薬（ARB）の使用</a></li>
<li class="chapter" data-level="B.10" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#THZUse"><i class="fa fa-check"></i><b>B.10</b> サイアザイドおよびサイアザイド様利尿薬の使用</a></li>
<li class="chapter" data-level="B.11" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#dCCBUse"><i class="fa fa-check"></i><b>B.11</b> ジヒドロピリジン系カルシウムチャネル遮断薬（DCCB）の使用</a></li>
<li class="chapter" data-level="B.12" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ndCCBUse"><i class="fa fa-check"></i><b>B.12</b> 非ジヒドロピリジン系カルシウムチャネル遮断薬（NDCCB）の使用</a></li>
<li class="chapter" data-level="B.13" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#BBUse"><i class="fa fa-check"></i><b>B.13</b> ベータ遮断薬使用</a></li>
<li class="chapter" data-level="B.14" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#DLoopUse"><i class="fa fa-check"></i><b>B.14</b> ループ利尿薬使用</a></li>
<li class="chapter" data-level="B.15" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#DPUse"><i class="fa fa-check"></i><b>B.15</b> カリウム保持性利尿薬使用</a></li>
<li class="chapter" data-level="B.16" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#A1BUse"><i class="fa fa-check"></i><b>B.16</b> アルファ1遮断薬使用</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="NegativeControlsAppendix.html"><a href="NegativeControlsAppendix.html"><i class="fa fa-check"></i><b>C</b> ネガティブコントロール</a>
<ul>
<li class="chapter" data-level="C.1" data-path="NegativeControlsAppendix.html"><a href="NegativeControlsAppendix.html#AceiThzNsc"><i class="fa fa-check"></i><b>C.1</b> ACE阻害薬とサイアザイド・サイアザイド様利尿薬</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="ProtocolTemplate.html"><a href="ProtocolTemplate.html"><i class="fa fa-check"></i><b>D</b> プロトコルテンプレート</a></li>
<li class="chapter" data-level="E" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html"><i class="fa fa-check"></i><b>E</b> 解答例</a>
<ul>
<li class="chapter" data-level="E.1" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Cdmanswers"><i class="fa fa-check"></i><b>E.1</b> 共通データモデル</a></li>
<li class="chapter" data-level="E.2" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Vocabanswers"><i class="fa fa-check"></i><b>E.2</b> 標準化ボキャブラリ</a></li>
<li class="chapter" data-level="E.3" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Etlanswers"><i class="fa fa-check"></i><b>E.3</b> ETL (Extract-Transform-Load)</a></li>
<li class="chapter" data-level="E.4" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#UseCasesanswers"><i class="fa fa-check"></i><b>E.4</b> データ分析のユースケース</a></li>
<li class="chapter" data-level="E.5" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#SqlAndRanswers"><i class="fa fa-check"></i><b>E.5</b> SQLとR</a></li>
<li class="chapter" data-level="E.6" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Cohortsanswers"><i class="fa fa-check"></i><b>E.6</b> コホートの定義</a></li>
<li class="chapter" data-level="E.7" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Characterizationanswers"><i class="fa fa-check"></i><b>E.7</b> 特性評価</a></li>
<li class="chapter" data-level="E.8" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Pleanswers"><i class="fa fa-check"></i><b>E.8</b> 集団レベルの推定</a></li>
<li class="chapter" data-level="E.9" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Plpanswers"><i class="fa fa-check"></i><b>E.9</b> 患者レベルの予測</a></li>
<li class="chapter" data-level="E.10" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#DataQualityanswers"><i class="fa fa-check"></i><b>E.10</b> データ品質</a></li>
<li class="chapter" data-level="E.11" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#section"><i class="fa fa-check"></i><b>E.11</b> </a></li>
</ul></li>
<li class="chapter" data-level="" data-path="参考文献.html"><a href="参考文献.html"><i class="fa fa-check"></i>参考文献</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">–翻訳作業中–　OHDSIの本</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="PatientLevelPrediction" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">第 13 章</span> 患者レベルの予測<a href="PatientLevelPrediction.html#PatientLevelPrediction" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><em>著者: Peter Rijnbeek &amp; Jenna Reps</em></p>
<p></p>
<p>臨床判断は、臨床医が患者の入手可能な病歴と現在の臨床ガイドラインに基づいて診断や治療方針を推測しなければならない複雑な作業です。この意思決定プロセスをサポートするために臨床予測モデルが開発され、幅広い専門分野の臨床現場で使用されています。これらのモデルは、人口統計学的情報、病歴、治療歴などの患者特性の組み合わせに基づいて診断結果や予後を予測します。 </p>
<p>臨床予測モデルに関する論文の数は、過去10年間で大幅に増加しています。現在使用されているモデルのほとんどは、小規模なデータセットを使用して推定され、患者特性の小規模なセットのみを考慮しています。このサンプルサイズの小ささ、つまり統計的なパワーの弱さにより、データ分析者は強いモデリング仮定を立てざるを得なくなります。患者特性の限定的なセットの選択は、手元にある専門知識に強く影響されます。これは、患者が豊富なデジタル履歴を残している現代医療の現実とは大きく対照的です。医療従事者がそのすべてを完全に把握することは不可能です。現在、医療は膨大な量の患者固有の情報を電子的健康記録（EHR）に保存しています。これには、診断、投薬、臨床検査結果などの構造化データと、臨床記録に含まれる非構造化データが含まれます。患者の完全なEHRから得られる大量のデータを活用することで、予測精度がどの程度向上するのかは不明です。 </p>
<p>大規模データセット分析のための機械学習の進歩により、この種のデータに患者レベルの予測を適用することへの関心が高まっています。しかし、患者レベルの予測に関する多くの公開された取り組みは、モデル開発ガイドラインに従っておらず、広範な外部検証を実施していないか、またはモデルの詳細が不十分であるため、独立した研究者がモデルを再現し、外部検証を行う能力が制限されています。そのため、モデルの予測性能を公平に評価することが難しくなり、臨床現場でモデルが適切に使用される可能性が低くなります。 基準を改善するために、予測モデルの開発と報告におけるベストプラクティスのガイドラインを詳細に説明した論文がいくつか発表されています。 例えば、多変量予測モデルの透明性報告に関する声明（TRIPOD）声明<a href="#fn55" class="footnote-ref" id="fnref55"><sup>55</sup></a> では、予測モデルの開発と検証の報告に関する明確な推奨事項が提示されており、透明性に関する懸念の一部に対処しています。 </p>
<p>OHDSI により、大規模かつ患者固有の予測モデリングが現実のものとなりました。共通データモデル（CDM）により、前例のない規模で一貫性のある透明性の高い分析が可能になりました。CDM に標準化されたデータベースのネットワークが拡大していることで、世界規模でさまざまな医療環境におけるモデルの外部検証が可能になっています。これにより、医療の質の向上を最も必要としている患者の大きなコミュニティに即座に貢献できる機会が得られると私たちは考えています。このようなモデルは、真に個別化された医療の実現につながり、患者の予後を大幅に改善できる可能性があります。 本章では、OHDSIの患者レベル予測のための標準化されたフレームワーク <span class="citation">(<a href="#ref-reps2018">Reps et al. 2018</a>)</span> について説明し、開発と検証のための確立されたベストプラクティスを実装した <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> Rパッケージについて議論します。まず、患者レベル予測の開発と評価に必要な理論を説明し、実装された機械学習アルゴリズムの概要を説明します。次に、予測問題の例を挙げ、ATLAS またはカスタム R コードを使用した定義と実装の手順を説明します。最後に、研究結果の普及に Shiny アプリケーションを使用する方法について説明します。</p>
<div id="予測課題" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> 予測課題<a href="PatientLevelPrediction.html#予測課題" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>図 <a href="PatientLevelPrediction.html#fig:figure1">13.1</a> ここで取り上げる予測問題を示しています。リスクのある集団において、定義された時点（t = 0）で、リスク期間中に何らかの結果を経験する患者を予測することを目的としています。予測は、その時点以前の観察期間における患者の情報のみを使用して行われます。</p>
<div class="figure"><span style="display:block;" id="fig:figure1"></span>
<img src="images/PatientLevelPrediction/Figure1.png" alt="予測課題" width="100%" />
<p class="caption">
図 13.1: 予測課題
</p>
</div>
<p>表 <a href="PatientLevelPrediction.html#tab:plpDesign">13.1</a> に示すように、予測課題を定義するには、対象コホートによってt=0を定義し、アウトカムコホートによって予測したいアウトカムを定義し、リスク期間も定義する必要があります。標準的な予測問題は次のように定義されます： </p>
<blockquote>
<p><em>[対象コホートの定義]</em>の中で、<em><a href="SqlAndR.html#リスク期間">リスク期間</a></em>内に<em>[アウトカムコホートの定義]</em>を持つのは誰ですか？</p>
</blockquote>
<p>さらに、開発したいモデルのデザインオプションを検討し、内部および外部検証を行うための観察データセットを決定する必要があります。</p>
<table>
<caption><span id="tab:plpDesign">表 13.1: </span> 予測デザインにおける主要なデザインオプション</caption>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">選択肢</th>
<th align="left">説明</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">対象コホート</td>
<td align="left">予測したい対象者のコホートをどのように定義しますか？</td>
</tr>
<tr class="even">
<td align="left">アウトカムコホート</td>
<td align="left">予測したいアウトカムをどのように定義しますか？</td>
</tr>
<tr class="odd">
<td align="left">リスク期間</td>
<td align="left">t=0に対してどの時間枠で予測を行いますか？</td>
</tr>
<tr class="even">
<td align="left">モデル</td>
<td align="left">どのアルゴリズムを使用し、どの潜在的な予測変数を含めますか？</td>
</tr>
</tbody>
</table>
<p>この概念的フレームワークは、あらゆる種類の予測課題に適用できます。例えば：</p>
<ul>
<li>疾病の発症と進行
<ul>
<li><strong>構造</strong>: <em>[病気]</em>と新たに診断された患者のうち、<em>[診断から見た時間枠内]</em>に<em>[別の疾患または合併症]</em>を発症するのは誰ですか？</li>
<li><strong>例</strong>: 心房細動と新たに診断された患者のうち、次の3年以内に虚血性脳卒中を発症するのは誰ですか？</li>
</ul></li>
<li>治療選択
<ul>
<li><strong>構造</strong>: <em>[対象疾患]</em>と診断された患者で<em>、</em>[治療1]<em>または</em>[治療2]<em>で治療された患者うち、</em>[治療1]*で治療された患者は？</li>
<li><strong>例</strong>: ワルファリンまたはリバロキサバンを服用した心房細動患者のうち、ワルファリンを服用した患者は誰ですか？（傾向スコアモデルの場合など）</li>
</ul></li>
<li>治療反応
<ul>
<li><strong>構造</strong>: <em>[治療]</em>の新規使用者のうち、<em>[時間枠内]</em>に<em>[何らかの効果]</em>を経験するのは誰ですか？</li>
<li><strong>例</strong>: メトホルミンを開始した糖尿病患者のうち、3年間メトホルミンを継続するのは誰ですか？</li>
</ul></li>
<li>治療安全性
<ul>
<li><strong>構造</strong>: <em>[治療]</em>の新規使用者の中で、<em>[時間枠内]</em>に<em>[有害事象]</em>を経験するのは誰ですか？</li>
<li><strong>例</strong>: ワルファリンの新規使用者の中で、1年以内に消化管出血を起こすのは誰ですか？</li>
</ul></li>
<li>治療遵守
<ul>
<li><strong>構造</strong>: <em>[治療]</em>の新規使用者の中で、<em>[時間枠]</em>で<em>[遵守指標]</em>を達成するのは誰ですか？</li>
<li><strong>例</strong>: メトホルミンを開始した糖尿病患者のうち、1年以内に80%以上の遵守率を達成するのは誰ですか？</li>
</ul></li>
</ul>
</div>
<div id="データ抽出-2" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> データ抽出<a href="PatientLevelPrediction.html#データ抽出-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>予測モデルを作成する際には、機械学習の一種であると呼ばれるプロセスを使用します。これは、ラベル付けされたサンプルセットに基づいて、共変量とアウトカムの状態の間の関係を推測するものです。したがって、対象コホートに属する人について、CDMから共変量を抽出する方法が必要であり、またアウトカムのラベルを取得する必要があります。</p>
<p><strong>共変量</strong>（「予測因子」、「特徴量」、「独立変数」とも呼ばれる）は、患者の特徴を説明します。共変量には、年齢、性別、特定のコンディションの有無、患者記録内の曝露コードなどが含まれます。共変量は一般に、<a href="https://ohdsi.github.io/FeatureExtraction/">FeatureExtraction</a>パッケージを使用して構築され、詳細は第 <a href="Characterization.html#Characterization">11</a> 章で説明しています。予測には、その人が対象コホートに入る日付（本書ではこれをインデックス日と呼びます）の前および当日のデータのみ使用できます。</p>
<p>また、リスク期間中の全ての患者の<strong>アウトカムステータス</strong>（「ラベル」または「クラス」とも呼ばれる）も取得する必要があります。リスク期間中にアウトカムが発生した場合、アウトカムステータスは「陽性」と定義されます。 </p>
<div id="データ抽出の例" class="section level3 hasAnchor" number="13.2.1">
<h3><span class="header-section-number">13.2.1</span> データ抽出の例<a href="PatientLevelPrediction.html#データ抽出の例" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>表 <a href="PatientLevelPrediction.html#tab:plpExampleCohorts">13.2</a> は、2つのコホートが含まれたCOHORTテーブルの例を示しています。コホート定義IDが1のコホートは対象コホート（例：「最近、心房細動と診断された人」）です。コホート定義IDが2は、アウトカムコホートを定義します（例：「脳卒中」）。</p>
<table>
<caption><span id="tab:plpExampleCohorts">表 13.2: </span> 例示的なCOHORTテーブル。簡潔のためにCOHORT_END_DATEは省略しています。</caption>
<thead>
<tr class="header">
<th align="center">COHORT_DEFINITION_ID</th>
<th align="center">SUBJECT_ID</th>
<th align="center">COHORT_START_DATE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1</td>
<td align="center">2000-06-01</td>
</tr>
<tr class="even">
<td align="center">1</td>
<td align="center">2</td>
<td align="center">2001-06-01</td>
</tr>
<tr class="odd">
<td align="center">2</td>
<td align="center">2</td>
<td align="center">2001-07-01</td>
</tr>
</tbody>
</table>
<p>表 <a href="PatientLevelPrediction.html#tab:plpExampleConditions">13.3</a> は、例示的なCONDITION_OCCURRENCEテーブルを示しています。Concept ID <a href="http://athena.ohdsi.org/search-terms/terms/320128">320128</a> は「本態性高血圧」に該当します。</p>
<table>
<caption><span id="tab:plpExampleConditions">表 13.3: </span> 例示的なCONDITION_OCCURRENCEテーブル。簡潔のため、3つの列のみ表示しています。</caption>
<thead>
<tr class="header">
<th align="center">PERSON_ID</th>
<th align="center">CONDITION_CONCEPT_ID</th>
<th align="center">CONDITION_START_DATE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">320128</td>
<td align="center">2000-10-01</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">320128</td>
<td align="center">2001-05-01</td>
</tr>
</tbody>
</table>
<p>この例示的なデータに基づき、リスク期間をインデックス日（対象コホートの開始日）から1年間と仮定すると、共変量とアウトカムステータスを構築できます。「前年の本態性高血圧」を示す共変量は、個人ID 1に対して0（非該当）（アウトカムがインデックス日の後に発生）と、個人ID 2に対して1（該当）となります。同様に、アウトカムステータスは個人ID 1に対して0（この人はアウトカムコホートに該当しない）、個人ID 2に対して1（インデックス日から1年以内にアウトカムが発生）となります。</p>
</div>
<div id="負の値と欠損" class="section level3 hasAnchor" number="13.2.2">
<h3><span class="header-section-number">13.2.2</span> 負の値と欠損<a href="PatientLevelPrediction.html#負の値と欠損" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>観察医療データは、値が負であるか欠損であるかを反映することはまれです。先の例では、ID 1 の人物にはインデックス日以前に本態性高血圧症の発生がなかったことを単純に観察しました。これは、その時点ではその状態が存在していなかった（負）ためであるか、あるいは記録されていなかった（欠損）ためである可能性があります。機械学習アルゴリズムは負と欠損を区別できず、利用可能なデータにおける予測値を単純に評価することに留意することが重要です。</p>
</div>
</div>
<div id="modelFitting" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> モデルの適合<a href="PatientLevelPrediction.html#modelFitting" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>予測モデルの適合を行う際には、ラベル付けされた例から、共変量と観測されたアウトカムの状態の関係を学習しようとしています。例えば、共変量が2つしかない場合、収縮期血圧と拡張期血圧だとすると、各患者を2次元空間のプロットとして表現できます（図 <a href="PatientLevelPrediction.html#fig:decisionBoundary">13.2</a> を参照）。この図では、データポイントの形が患者のアウトカム状態（例：脳卒中）に対応しています。</p>
<p>教師あり学習モデルは、2つのアウトカムクラスを最適に分離する決定境界を見つけようとします。異なる教師あり学習手法は異なる決定境界をもたらし、決定境界の複雑性に影響を与えるハイパーパラメータが存在することがよくあります。 </p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:decisionBoundary"></span>
<img src="images/PatientLevelPrediction/decisionBoundary.png" alt="決定境界" width="80%" />
<p class="caption">
図 13.2: 決定境界
</p>
</div>
<p>図 <a href="PatientLevelPrediction.html#fig:decisionBoundary">13.2</a> では、3つの異なる決定境界線を見ることができます。この境界線は、新しいデータポイントの結果の状態を推測するために使用されます。新しいデータポイントが影の部分に該当する場合、モデルは「結果あり」と予測し、それ以外は「結果なし」と予測します。理想的には、決定境界線は2つのクラスを完全に分割するべきです。しかし、あまりにも複雑なモデルはデータに「過剰適合」するリスクがあります。これは、未確認データに対するモデルの汎用性に悪影響を及ぼす可能性があります。例えば、データにノイズが含まれている場合、つまりラベル付けが誤っていたり、データポイントの位置が不正確であったりする場合には、そのノイズにモデルを適合させることは望ましくありません。そのため、トレーニングデータでは完全に識別しないが、「実際の」複雑さを捉える決定境界を定義することが望ましい場合があります。正則化などの手法は、複雑さを最小限に抑えながらモデルのパフォーマンスを最大化することを目的としています。</p>
<p>各教師あり学習アルゴリズムは、決定境界を学習する方法が異なり、どのアルゴリズムがデータに最適であるかは一概には言えません。「No Free Lunch」定理が示すように、すべての予測問題において常に他のアルゴリズムよりも優れたアルゴリズムは存在しません。 そのため、患者レベルの予測モデルを開発する際には、さまざまなハイパーパラメータ設定で複数の教師あり学習アルゴリズムを試すことをお勧めします。</p>
<p>この後に示すアルゴリズムは以下から取得可能です： <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> パッケージ</p>
<div id="正則化ロジスティック回帰" class="section level3 hasAnchor" number="13.3.1">
<h3><span class="header-section-number">13.3.1</span> 正則化ロジスティック回帰<a href="PatientLevelPrediction.html#正則化ロジスティック回帰" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>LASSO（最小絶対値収縮選択オペレーター）ロジスティック回帰は一般化線形モデルに属し、変数の線形結合が学習され、最終的にロジスティック関数がその線形結合を0から1の間の値に写像します。 LASSO正則化では、モデルをトレーニングする際に、目的関数にモデルの複雑さに基づくコストが追加されます。 このコストは係数の線形結合の絶対値の合計です。 モデルは、このコストを最小化することで自動的に特徴量の選択を行います。大規模な正則化ロジスティック回帰を行うために、 <a href="https://ohdsi.github.io/Cyclops/">Cyclops</a> （ロジスティック、ポアソン、生存時間分析のための循環座標降下法）パッケージを使用しています。 </p>
<table>
<caption><span id="tab:lassoParameters">表 13.4: </span> 正則化ロジスティック回帰のハイパーパラメータ</caption>
<thead>
<tr class="header">
<th align="left">パラメータ</th>
<th align="left">説明</th>
<th align="left">典型的な値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">初期分散</td>
<td align="left">事前分布の初期分散</td>
<td align="left">0.1</td>
</tr>
</tbody>
</table>
<p>分散はクロスバリデーションでのサンプル外の尤度を最大化して最適化されるため、初期分散はアウトカムとして得られるモデルの性能にはほとんど影響しません。ただし、最適値からあまりに離れた初期分散を選択すると、適合時間が長くなる可能性があります。 </p>
</div>
<div id="勾配ブースティングマシン" class="section level3 hasAnchor" number="13.3.2">
<h3><span class="header-section-number">13.3.2</span> 勾配ブースティングマシン<a href="PatientLevelPrediction.html#勾配ブースティングマシン" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>勾配ブースティングマシンはブースティングアンサンブル手法であり、この枠組みでは複数の決定ツリーを組み合わせます。ブースティングは、繰り返し決定ツリーを追加し、前の決定ツリーで誤分類されたデータポイントにより多くの重みをコスト関数に追加して次のツリーをトレーニングします。高効率の勾配ブースティングフレームワークを実装した、CRANで利用可能なxgboost Rパッケージを使用しています。 </p>
<table>
<caption><span id="tab:gbmParameters">表 13.5: </span> 勾配ブースティングマシンのハイパーパラメータ</caption>
<thead>
<tr class="header">
<th align="left">パラメータ</th>
<th align="left">説明</th>
<th align="left">典型的な値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">earlyStopRound</td>
<td align="left">改善がない場合の停止ラウンド数</td>
<td align="left">25</td>
</tr>
<tr class="even">
<td align="left">learningRate</td>
<td align="left">ブースティングの学習率</td>
<td align="left">0.005,0.01,0.1</td>
</tr>
<tr class="odd">
<td align="left">maxDepth</td>
<td align="left">ツリーの最大深さ</td>
<td align="left">4,6,17</td>
</tr>
<tr class="even">
<td align="left">minRows</td>
<td align="left">ノード内の最小データポイント数</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">ntrees</td>
<td align="left">ツリーの数</td>
<td align="left">100,1000</td>
</tr>
</tbody>
</table>
</div>
<div id="ランダムフォレスト" class="section level3 hasAnchor" number="13.3.3">
<h3><span class="header-section-number">13.3.3</span> ランダムフォレスト<a href="PatientLevelPrediction.html#ランダムフォレスト" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ランダムフォレストは複数の決定ツリーを組み合わせるバギング法の集合手法です。バギング法の背景にある考え方は、弱い分類器を使用し、それを強力な分類器に組み合わせることで、過剰適合の可能性を低減することです。ランダムフォレストは、複数の決定ツリーをトレーニングすることでこれを実現しますが、各ツリーでは変数のサブセットのみを使用し、ツリーごとに変数のサブセットが異なります。当社のパッケージでは、Pythonのランダムフォレストの実装であるsklearnを使用しています。 </p>
<table>
<caption><span id="tab:randomForestParameters">表 13.6: </span> ランダムフォレストのハイパーパラメータ</caption>
<thead>
<tr class="header">
<th align="left">パラメータ</th>
<th align="left">説明</th>
<th align="left">典型的な値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">maxDepth</td>
<td align="left">ツリーの最大深さ</td>
<td align="left">4,10,17</td>
</tr>
<tr class="even">
<td align="left">mtries</td>
<td align="left">各ツリーの特徴量数</td>
<td align="left">-1 = 総特徴量数の平方根,5,20</td>
</tr>
<tr class="odd">
<td align="left">ntrees</td>
<td align="left">ツリーの数</td>
<td align="left">500</td>
</tr>
</tbody>
</table>
</div>
<div id="k-近傍法" class="section level3 hasAnchor" number="13.3.4">
<h3><span class="header-section-number">13.3.4</span> K-近傍法<a href="PatientLevelPrediction.html#k-近傍法" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>K-近傍法 (K-nearest neighbors; KNN) は、ある距離尺度を使用して、新しいラベルのないデータポイントに最も近いラベル付きデータポイントをK個見つけるアルゴリズムです。新しいデータポイントの予測は、K個の最も近いラベル付きデータポイントの中で最も一般的なクラスとなります。KNNには共有に関する制限があり、新しいデータの予測を行うにはラベル付きデータが必要となるため、このデータをデータサイト間で共有できないことがよくあります。OHDSIで開発された大規模KNN分類器である <a href="https://github.com/OHDSI/BigKnn">BigKnn</a> パッケージを組み込んでいます。 </p>
<table>
<caption><span id="tab:knnParameters">表 13.7: </span> K-近傍法のハイパーパラメータ</caption>
<thead>
<tr class="header">
<th align="left">パラメータ</th>
<th align="left">説明</th>
<th align="left">典型的な値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">k</td>
<td align="left">近傍数</td>
<td align="left">1000</td>
</tr>
</tbody>
</table>
</div>
<div id="ナイーブベイズ" class="section level3 hasAnchor" number="13.3.5">
<h3><span class="header-section-number">13.3.5</span> ナイーブベイズ<a href="PatientLevelPrediction.html#ナイーブベイズ" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ナイーブベイズアルゴリズムは、クラス変数の値を考慮した際の特徴量の各ペア間の条件付き独立性という単純な仮定を適用したベイズの定理です。 データがクラスに属する可能性とクラスの事前分布に基づいて事後分布が取得されます。 ナイーブベイズにはハイパーパラメータがありません。 </p>
</div>
<div id="adaboost" class="section level3 hasAnchor" number="13.3.6">
<h3><span class="header-section-number">13.3.6</span> AdaBoost<a href="PatientLevelPrediction.html#adaboost" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>AdaBoostはブースティングのアンサンブル手法です。ブースティングは分類器を繰り返し追加することで機能しますが、次の分類器をトレーニングする際には、コスト関数において、先行する分類器によって誤分類されたデータポイントにより大きな重みを追加します。Pythonでは、sklearnのAdaboostClassifier実装を使用します。 </p>
<table>
<caption><span id="tab:adaBoostParameters">表 13.8: </span> AdaBoostのハイパーパラメータ</caption>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">パラメータ</th>
<th align="left">説明</th>
<th align="left">典型的な値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">nEstimators</td>
<td align="left">ブースティングを終了する最大推定器数</td>
<td align="left">4</td>
</tr>
<tr class="even">
<td align="left">learningRate</td>
<td align="left">learningRate learning_rate によって各分類器の寄与を縮小する学習率。 learningRate と nEstimators にはトレードオフの関係がある。</td>
<td align="left">1</td>
</tr>
</tbody>
</table>
</div>
<div id="決定ツリー" class="section level3 hasAnchor" number="13.3.7">
<h3><span class="header-section-number">13.3.7</span> 決定ツリー<a href="PatientLevelPrediction.html#決定ツリー" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>決定ツリーは、貪欲法で選択された個々のテストを使用して変数空間を分割する分類器です。クラスを分離する際に、最も高い情報量を持つ分割を見つけることを目的としています。決定ツリーは、多数の分割（ツリーの深さ）を有効にすることで簡単に過学習状態になるため、多くの場合、正則化（例えば、枝刈りやモデルの複雑性を制限するハイパーパラメータの指定）が必要です。Pythonでは、sklearnのDecisionTreeClassifier実装を使用します。 </p>
<table>
<caption><span id="tab:decisionTreeParameters">表 13.9: </span> 決定ツリーのハイパーパラメータ</caption>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">パラメータ</th>
<th align="left">説明</th>
<th align="left">典型的な値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">classWeight</td>
<td align="left">「Balance」または「None」</td>
<td align="left">None</td>
</tr>
<tr class="even">
<td align="left">maxDepth</td>
<td align="left">木の最大深さ</td>
<td align="left">10</td>
</tr>
<tr class="odd">
<td align="left">minImpuritySplit</td>
<td align="left">ツリーの成長中に早期停止するための閾値。ノードの不純物が閾値を上回る場合は分割され、そうでない場合はリーフとなります</td>
<td align="left">10^-7</td>
</tr>
<tr class="even">
<td align="left">minSamplesLeaf</td>
<td align="left">各リーフの最小サンプル数</td>
<td align="left">10</td>
</tr>
<tr class="odd">
<td align="left">minSamplesSplit</td>
<td align="left">各分割の最小サンプル数</td>
<td align="left">2</td>
</tr>
</tbody>
</table>
</div>
<div id="多層パーセプトロン" class="section level3 hasAnchor" number="13.3.8">
<h3><span class="header-section-number">13.3.8</span> 多層パーセプトロン<a href="PatientLevelPrediction.html#多層パーセプトロン" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>多層パーセプトロンは、非線形関数を使用して入力を重み付けする複数のノード層を含むニューラルネットワークです。最初の層は入力層、最後の層は出力層であり、その間にあるのが隠れ層です。ニューラルネットワークは一般にバックプロパゲーションを用いて訓練されます。これは、訓練入力がネットワークを通じて順方向に伝搬され、出力が生成されることを意味します。出力とアウトカムの状態の間の誤差が計算され、この誤差がネットワークを通じて逆方向に伝搬され、線形関数の重みが更新されます。 </p>
<table>
<caption><span id="tab:mpParameters">表 13.10: </span> 多層パーセプトロン用のハイパーパラメータ</caption>
<thead>
<tr class="header">
<th align="left">パラメータ</th>
<th align="left">説明</th>
<th align="left">典型的な値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">alpha</td>
<td align="left">l2正則化</td>
<td align="left">0.00001</td>
</tr>
<tr class="even">
<td align="left">size</td>
<td align="left">隠れノードの数</td>
<td align="left">4</td>
</tr>
</tbody>
</table>
</div>
<div id="深層学習" class="section level3 hasAnchor" number="13.3.9">
<h3><span class="header-section-number">13.3.9</span> 深層学習<a href="PatientLevelPrediction.html#深層学習" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ディープネット、畳み込みニューラルネットワーク、再帰型ニューラルネットワークなどのディープラーニングは、多層パーセプトロンと類似していますが、予測に役立つ潜在的な表現を学習することを目的とした複数の隠れ層を持っています。<a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> パッケージの別の<a href="https://ohdsi.github.io/PatientLevelPrediction/articles/BuildingDeepLearningModels.html">ビネット</a>で、これらのモデルとハイパーパラメータの詳細について説明しています。 </p>
</div>
<div id="その他のアルゴリズム" class="section level3 hasAnchor" number="13.3.10">
<h3><span class="header-section-number">13.3.10</span> その他のアルゴリズム<a href="PatientLevelPrediction.html#その他のアルゴリズム" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>患者レベルの予測フレームワークには他のアルゴリズムを追加できますが、これは本章の範囲外です。詳細は、<a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> パッケージの<a href="https://ohdsi.github.io/PatientLevelPrediction/articles/AddingCustomAlgorithms.html">「Adding Custom Patient-Level Prediction Algorithms」ビネット</a>を参照ください。</p>
</div>
</div>
<div id="予測モデルの評価" class="section level2 hasAnchor" number="13.4">
<h2><span class="header-section-number">13.4</span> 予測モデルの評価<a href="PatientLevelPrediction.html#予測モデルの評価" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="評価の種類" class="section level3 hasAnchor" number="13.4.1">
<h3><span class="header-section-number">13.4.1</span> 評価の種類<a href="PatientLevelPrediction.html#評価の種類" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>予測モデルの評価は、モデルの予測と観測されたアウトカムの一致度を測定することによって行うことができます。これには、アウトカムのステータスが既知であるデータが必要です。 </p>

<div class="rmdimportant">
評価には、モデル開発に使用されたデータセットとは異なるデータセットを使用しなければなりません。そうしないと、過剰適合したモデルを支持してしまう可能性があり（セクション <a href="PatientLevelPrediction.html#modelFitting">13.3</a> を参照）、新規患者に対して良好な結果が得られない可能性があります。
</div>
<p>評価の種類には、以下のものがあります：</p>
<ul>
<li><strong>内部検証</strong>：同じデータベースから抽出された異なるデータセットを使用してモデルを開発および評価します。</li>
<li><strong>外部検証</strong>：一つのデータベースでモデルを開発し、別のデータベースで評価します。 </li>
</ul>
<p>内部検証の方法には、次の2つがあります：</p>
<ul>
<li><strong>ホールドアウトセット</strong>アプローチ：ラベル付けされたデータを2つの独立したセット（トレーニングセットとテストセット（ホールドアウトセット））に分割します。トレーニングセットはモデルの学習に使用され、テストセットはモデルの評価に使用されます。患者をランダムに訓練用とテスト用に単純に分割することもできますが、以下のような方法も選択できます。：
<ul>
<li>時間に基づいた分割（時間的検証）：例えば、特定の日付以前のデータで訓練を行い、その日付以降のデータで評価を行う。これにより、モデルが異なる期間に一般化できるかどうかを判断できる可能性があります。</li>
<li>地理的位置に基づいた分割（空間的検証）。 </li>
</ul></li>
<li><strong>クロスバリデーション</strong>：データが限られている場合に有用です。データを等しいサイズに分割し、<span class="math inline">\(n\)</span>にプレ設定されたセットに分割します（例：<span class="math inline">\(n=10\)</span>）。各セットでは、そのセットデータ以外のすべてのデータを使用してモデルがトレーニングされ、保留セットの予測を生成するために使用されます。このように、すべてのデータが一度使用されてモデル構築アルゴリズムが評価されます。患者レベルの予測フレームワークでは、最適なハイパーパラメータを選択するためにクロスバリデーションを使用します。</li>
</ul>
<p>外部検証は、別のデータベースのデータ（すなわち、開発された環境以外のデータ）でモデルのパフォーマンスを評価することを目的としています。モデルの移植性を評価するこの手法は重要です。なぜなら、モデルをトレーニングしたデータベースのみでなく、他のデータベースにも適用したいからです。異なるデータベースは、異なる患者集団、異なる医療システム、異なるデータ収集プロセスを表している可能性があります。多数のデータベースにおける予測モデルのクロスバリデーションは、モデルの受容と臨床現場への導入において重要なステップであると考えています。</p>
</div>
<div id="performance" class="section level3 hasAnchor" number="13.4.2">
<h3><span class="header-section-number">13.4.2</span> 性能指標<a href="PatientLevelPrediction.html#performance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="閾値測定" class="section level4 unnumbered hasAnchor">
<h4>閾値測定<a href="PatientLevelPrediction.html#閾値測定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>予測モデルは、リスク期間中にアウトカムが起こる患者のリスクに対応する各患者に0から1の間の値を割り当てます。値が0の場合はリスクが0%、0.5の場合は50%のリスク、1の場合は100%のリスクを意味します。 リスク期間にアウトカムが得られるリスクを患者に分類するために使用する閾値を最初に指定することで、一般的な測定基準である正確度、感度、特異度、陽性的中率を計算することができます。例えば、表 <a href="PatientLevelPrediction.html#tab:tabletheorytab">13.11</a> にあるように閾値を0.5と設定すると、患者1、3、7、10は閾値0.5以上の予測リスクを持つため、アウトカムを持つと予測されます。他のすべての患者は0.5未満の予測リスクを持つため、アウトカムを持たないと予測されます。 </p>
<table>
<caption><span id="tab:tabletheorytab">表 13.11: </span> 予測確率に対する閾値の利用例</caption>
<colgroup>
<col width="20%" />
<col width="20%" />
<col width="20%" />
<col width="20%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">患者ID</th>
<th align="center">予測リスク</th>
<th align="center">0.5閾値での予測クラス</th>
<th align="center">リスク期間中にアウトカムを持つ</th>
<th align="center">タイプ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">0.8</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">TP</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">0.1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">0.7</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">FP</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">0.05</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">0.1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">0.9</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">TP</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">0.2</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">FN</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">0.3</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">TN</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">0.5</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">FP</td>
</tr>
</tbody>
</table>
<p>患者が予測されたアウトカムを持ち、実際にアウトカムを持つ場合、それを真陽性（TP）と呼びます。患者が予測されたアウトカムを持っているが実際にはアウトカムを持っていない場合、それを偽陽性（FP）と呼びます。患者がアウトカムを持たないと予測され、実際にアウトカムを持っていない場合、それを真陰性（TN）と呼びます。最後に、患者がアウトカムを持たないと予測され、実際にアウトカムを持っている場合、それを偽陰性（FN）と呼びます。 </p>
<p>以下の閾値ベースの指標を計算できます：</p>
<ul>
<li>正解率: <span class="math inline">\((TP+TN)/(TP+TN+FP+FN)\)</span></li>
<li>感度: <span class="math inline">\(TP/(TP+FN)\)</span></li>
<li>特異度: <span class="math inline">\(TN/(TN+FP)\)</span></li>
<li>陽性的中率: <span class="math inline">\(TP/(TP+FP)\)</span></li>
</ul>
<p>これらの値は、閾値が下げられると増減する可能性があります。分類器の閾値を下げると、アウトカムの数を増やすことで分母を増やすことができます。以前の閾値が高すぎた場合、新しいアウトカムはすべて真陽性である可能性があり、これにより陽性的中率が増加します。以前の閾値が適切であったか低すぎた場合、さらなる閾値の低下は偽陽性をもたらすため、陽性的中率が減少する可能性があります。感度の場合、分母は分類器の閾値に依存しません（<span class="math inline">\(TP+FN\)</span>は一定です）。このため、分類器の閾値を下げることで真陽性のアウトカム数を増やし、感度を向上させる可能性があります。また、閾値を下げても感度が変わらない一方で、陽性的中率が変動することもあります。</p>
</div>
<div id="識別力" class="section level4 unnumbered hasAnchor">
<h4>識別力<a href="PatientLevelPrediction.html#識別力" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>識別力とは、リスク期間中にアウトカムを経験する患者に対して、より高いリスクを割り当てる能力のことですROC（Receiver Operating Characteristics）曲線は、すべての可能な閾値において、1 – 特異度をx軸に、感度をy軸にプロットして作成されます。ROCプロットの例は、本章の後のほうの図 <a href="PatientLevelPrediction.html#fig:shinyROC">13.17</a> で示されています。ROC曲線下面積（AUC）は、判別能の全体的な尺度であり、0.5はリスクをランダムに割り当てることを意味し、1は完璧な判別を意味します。ほとんどの公表された予測モデルは、0.6～0.8 の AUC を取得しています。 </p>
<p>AUCは、リスク期間中にアウトカムを経験する患者と経験しない患者との間で予測リスク分布がどれだけ異なるかを判断する方法を提供します。AUCが高い場合、分布はほとんど重ならないのに対し、重なりが多い場合はAUCが0.5に近くなります。図 <a href="PatientLevelPrediction.html#fig:figuretheoryroctheory">13.3</a> に示されている通りです。</p>
<div class="figure"><span style="display:block;" id="fig:figuretheoryroctheory"></span>
<img src="images/PatientLevelPrediction/theory/roctheory.png" alt="識別力に関連するROCプロット。2つのクラスの予測リスクの分布が類似している場合、ROCは対角線に近く、AUCは0.5に近くなります。" width="100%" />
<p class="caption">
図 13.3: 識別力に関連するROCプロット。2つのクラスの予測リスクの分布が類似している場合、ROCは対角線に近く、AUCは0.5に近くなります。
</p>
</div>
<p>非常に稀なアウトカムに対しては、AUCが高くても実際には実用的でない場合があります。なぜなら、閾値を超えるすべての陽性の背後には多くの陰性が存在し、陽性的中率が低くなる可能性があるからです。アウトカムの重大性や介入のコスト（健康リスクまたは金銭的）によっては、高い偽陽性率は望ましくないかもしれません。そのため、稀なアウトカムに対しては、適合率-再現率曲線下面積（AUPRC）と呼ばれる別の測定値が推奨されます。AUPRCは感度をx軸（再現率としても知られる）に、陽性的中率（適合率としても知られる）をy軸にプロットして生成される曲線の下の面積です。 </p>
</div>
<div id="キャリブレーション" class="section level4 unnumbered hasAnchor">
<h4>キャリブレーション<a href="PatientLevelPrediction.html#キャリブレーション" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>キャリブレーションは、モデルが正しいリスクを割り当てる能力です。例えば、モデルが100人の患者に10％のリスクを割り当てた場合、そのうち10人がリスク期間中にアウトカムを経験するべきです。同様に、モデルが100人の患者に80％のリスクを割り当てた場合、そのうち80人がリスク期間中にアウトカムを経験するべきです。キャリブレーションは、一般に予測リスクに基づいて患者を十分位に分割し、各グループで平均予測リスクとリスク期間中にアウトカムを経験した患者の割合を計算することによって測定されます。次に、これらの10点（予測リスクをy軸、観測リスクをx軸にプロット）をプロットし、それらがx = yの線上に位置するかどうかを確認します。これがモデルが適切にキャリブレーションされていることを示します。キャリブレーションプロットの例は、本章の後半に図 <a href="PatientLevelPrediction.html#fig:shinyCal">13.18</a> で示されています。また、これらの点を使用して線形モデルをフィットし、切片（ゼロに近いはず）と傾き（1に近いはず）を計算します。もし、傾きが1より大きい場合、モデルは実際のリスクよりも高いリスクを割り当てており、傾きが1より小さい場合、モデルは実際のリスクよりも低いリスクを割り当てていることを意味します。非線形関係をよりよく捕捉するために、Smooth Calibration Curvesも実装しています。 </p>
</div>
</div>
</div>
<div id="患者レベル予測研究のデザイン" class="section level2 hasAnchor" number="13.5">
<h2><span class="header-section-number">13.5</span> 患者レベル予測研究のデザイン<a href="PatientLevelPrediction.html#患者レベル予測研究のデザイン" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>本セクションでは予測研究のデザイン方法について説明します。最初のステップは、予測問題を明確に定義することです。興味深いことに、多くの発表論文では予測問題の定義が不十分であり、例えば、インデックス日（対象コホートの開始日）がどのように定義されているのかが不明確です。予測問題の定義が不十分であると、他者による外部検証はおろか、臨床現場での実施も不可能になります。患者レベルの予測フレームワークでは、表 <a href="PatientLevelPrediction.html#tab:plpDesign">13.1</a>で定義された主要な選択肢を明示的に定義することを要求することで、予測問題の適切な仕様を強制しています。ここでは、「治療の安全性」タイプの予測問題を例に、このプロセスを説明します。</p>
<div id="問題の定義-2" class="section level3 hasAnchor" number="13.5.1">
<h3><span class="header-section-number">13.5.1</span> 問題の定義<a href="PatientLevelPrediction.html#問題の定義-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>血管性浮腫はACE阻害薬のよく知られた副作用であり、ACE阻害薬のラベルに記載されている血管性浮腫の発生率は0.1％から0.7％の範囲です <span class="citation">(<a href="#ref-byrd_2006">Byrd, Adam, and Brown 2006</a>)</span>。 この副作用をモニタリングすることは重要です。なぜなら、血管性浮腫は稀であるものの、生命を脅かす可能性があり、呼吸停止や死亡に至ることがあるからです <span class="citation">(<a href="#ref-norman_2013">Norman et al. 2013</a>)</span>。 さらに、血管性浮腫が最初に認識されないと、その原因を特定するまでに広範かつ高額な検査が必要となる可能性があります　<span class="citation">(<a href="#ref-norman_2013">Norman et al. 2013</a>; <a href="#ref-thompson_1993">Thompson and Frable 1993</a>)</span>。 アフリカ系アメリカ人患者におけるリスクの増加以外に、ACE阻害薬関連の血管性浮腫の発症に対する既知の素因は知られていません <span class="citation">(<a href="#ref-byrd_2006">Byrd, Adam, and Brown 2006</a>)</span>。 ほとんどの反応は初めての治療の最初の週または１か月以内に発生し、最初の投与から数時間以内に発生することもあります <span class="citation">(<a href="#ref-circardi_2004">Cicardi et al. 2004</a>)</span>。 しかし、一部の症例は治療開始から数年後に発生することもあります <span class="citation">(<a href="#ref-mara_1996">O’Mara and O’Mara 1996</a>)</span>。 リスクのある人を特定する特定の診断テストはありません。もしリスクのある人を特定できれば、医師は例えばACE阻害薬を別の降圧薬に切り替えるなどの対応が可能になります。 </p>
<p>患者レベル予測フレームワークを観察医療データに適用して、次の患者レベルの予測問題に取り組みます：</p>
<blockquote>
<p>初めてACE阻害薬を開始した患者のうち、１年以内に血管性浮腫を発症するのは誰か？</p>
</blockquote>
</div>
<div id="研究集団の定義-1" class="section level3 hasAnchor" number="13.5.2">
<h3><span class="header-section-number">13.5.2</span> 研究集団の定義<a href="PatientLevelPrediction.html#研究集団の定義-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>モデルを開発する最終的な研究対象集団は、対象コホートのサブセットとなることがよくあります。例えば、アウトカムに依存する基準を適用する場合や、対象コホートのサブグループで感度分析を行いたい場合などです。この場合、以下の問いに答えなければなりません。：</p>
<ul>
<li><p><em>対象コホートの開始前にどの程度の観察期間が必要ですか？</em> この選択は、トレーニングデータで利用可能な患者の時間にも依存しますが、将来的にモデルを適用したいデータソースで利用可能な時間にも依存します。 最小の観察期間が長ければ長いほど、各人の特徴量抽出に使用できるベースライン期間を得られますが、分析対象となる患者数は少なくなります。さらに、短いまたは長い観察期間を選択する臨床的な理由がある場合もあります。今回の例では、365日間をルックバック期間（ウォッシュアウト期間）として使用します。</p></li>
<li><p><em>患者が対象コホートに複数回組み入れられますか？</em> 対象コホートの定義では、例えば、異なる病気のエピソードや医療製品への曝露期間が異なる場合など、異なる期間に複数回、その集団に適格となる可能性があります。コホート定義は、患者が一度だけ参加できるように制限を適用するとは限りませんが、特定の患者レベルの予測問題の文脈では、最初の適格エピソードにコホートを限定したい場合もあります。 例では、ACE阻害薬の初回使用を基準としているため、患者は一度だけ対象コホートに参加できます。</p></li>
<li><p><em>以前にアウトカムを経験した人をコホートに含めることができますか？</em> 対象コホートに適格となる前にアウトカムを経験した人をコホートに含めるかどうかを決める必要があります。特定の患者レベルの予測問題によっては、初回のアウトカムの発生を予測したい場合があるため、以前にアウトカムを経験した患者はリスクがないため、ターゲットコホートから除外する必要があります。他の状況では、前回エピソードの予測を希望しているため、以前のアウトカムが将来のアウトカムの予測要因になる可能性もあります。私たちの予測例では、以前に血管性浮腫を持つ人を含めないことにします。</p></li>
<li><p><em>対象コホート開始日に対してアウトカムを予測する期間をどう定義しますか？</em> この質問に答えるために、2つの決定を下す必要があります。まず、リスク期間の開始日を対象コホートの開始日またはそれ以降に設定するかどうかの議論があります。開始日を遅らせる理由には、記録が遅れて入力された結果を避けたい場合や、結果を予防する介入が理論上実施可能であった期間を空けておきたい場合などが考えられます。次に、リスク期間の終了日を設定して、対象コホートの開始日または終了日からの相対的な日数オフセットをある程度指定することで、リスク期間を定義する必要があります。今回の問題では、対象コホートの開始日の1日後から365日後までの期間をリスク期間として予測します。</p></li>
<li><p><em>最小限のリスク期間は必要でしょうか？</em> アウトカムが発生しなかったが、リスク期間終了前にデータベースを離脱した患者を含めるかどうかを決める必要があります。これらの患者は観察期間が終わった後にアウトカムを経験する可能性があります。この予測問題では、この質問に「はい」と答え、その理由で最小のリスク期間を必要とします。さらに、この制約がアウトカムを経験した人に適用されるかどうか、リスク期間の長短に関わらず、アウトカムを経験した人全員を対象とするのかを決定しなければなりません。アウトカムが死亡の場合、リスク期間が完了する前に打ち切られる可能性が高いでしょう。</p></li>
</ul>
</div>
<div id="モデル開発の設定" class="section level3 hasAnchor" number="13.5.3">
<h3><span class="header-section-number">13.5.3</span> モデル開発の設定<a href="PatientLevelPrediction.html#モデル開発の設定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>予測モデルを開発するには、どのアルゴリズムをトレーニングするか決定しなければなりません。特定の予測問題に対する最良のアルゴリズムの選択は経験的な問題であると捉え、すなわち、データに語らせ、最良のものを発見するためにさまざまなアプローチを試みることを好みます。そのため、私たちのフレームワークでは、セクション <a href="PatientLevelPrediction.html#modelFitting">13.3</a>に記載されているように多くのアルゴリズムを実装しており、他のアルゴリズムを追加することも可能です。この例では、シンプルにするために、Gradient Boosting Machines（GBM）を一つのアルゴリズムとして選択します。</p>
<p>さらに、モデルのトレーニングに使用する共変量も決定する必要があります。この例では、性別、年齢、コンディションすべて、薬剤および薬剤グループ、来院回数などを追加したいと思います。これらの臨床イベントは、インデックス日の1年前から、それ以前の任意の期間にわたって検索します。</p>
</div>
<div id="モデル評価" class="section level3 hasAnchor" number="13.5.4">
<h3><span class="header-section-number">13.5.4</span> モデル評価<a href="PatientLevelPrediction.html#モデル評価" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>最後に、モデルの評価方法を定義する必要があります。ここでは、単純化のため、内部検証を選択します。データセットをトレーニング用とテスト用に分割する方法、患者をこれら2つのセットに割り当てる方法を決定する必要があります。ここでは、典型的な75% - 25%分割を使用します。非常に大規模なデータセットの場合は、トレーニング用にさらに多くのデータを使用できます。</p>
</div>
<div id="研究概要" class="section level3 hasAnchor" number="13.5.5">
<h3><span class="header-section-number">13.5.5</span> 研究概要<a href="PatientLevelPrediction.html#研究概要" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>これで、表 <a href="PatientLevelPrediction.html#tab:plpSummary">13.12</a> に示されるように、研究を完全に定義しました。</p>
<table>
<caption><span id="tab:plpSummary">表 13.12: </span> この研究の主なデザイン選択</caption>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">選択</th>
<th align="left">値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">対象コホート</td>
<td align="left">初めてACE阻害薬を開始した患者。観察期間が365日未満、または血管性浮腫の既往がある患者は除外されます。</td>
</tr>
<tr class="even">
<td align="left">アウトカムコホート</td>
<td align="left">血管性浮腫。</td>
</tr>
<tr class="odd">
<td align="left">リスク期間</td>
<td align="left">コホート開始日の1日後から365日後。少なくとも364日のリスク期間が必要。</td>
</tr>
<tr class="even">
<td align="left">モデル</td>
<td align="left">Gradient Boosting Machine with hyper-parameters ntree: 5000, max depth: 4 or 7 or 10 and learning rate: 0.001 or 0.01 or 0.1 or 0.9. Covariates will include gender, age, conditions, drugs, drug groups, and visit count. データ分割: 75％トレーニング - 25％テスト、個人ごとにランダムに割り当てられます。</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="atlasでの研究の実装" class="section level2 hasAnchor" number="13.6">
<h2><span class="header-section-number">13.6</span> ATLASでの研究の実装<a href="PatientLevelPrediction.html#atlasでの研究の実装" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>予測研究をデザインするインターフェースは、ATLASメニューの左側にある<img src="images/PatientLevelPrediction/predictionButton.png" />ボタンをクリックすることで開くことができます。新しい予測研究を作成しましょう。研究にわかりやすい名前をつけておくことを忘れないでください。研究のデザインはいつでも<img src="images/PopulationLevelEstimation/save.png" />ボタンをクリックして保存できます。</p>
<p>予測デザイン機能には、予測の問題設定、分析設定、実行設定、トレーニング設定の4つのセクションがあります。それぞれのセクションについて説明します。</p>
<div id="予測の問題設定" class="section level3 hasAnchor" number="13.6.1">
<h3><span class="header-section-number">13.6.1</span> 予測の問題設定<a href="PatientLevelPrediction.html#予測の問題設定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ここでは、分析の対象となる母集団コホートとアウトカムコホートを選択します。予測モデルは、対象となる母集団コホートとアウトカムコホートのすべての組み合わせに対して作成されます。例えば、2つの対象集団と2つのアウトカムを指定すると、4つの予測問題が指定されたことになります。</p>
<p>対象となる母集団コホートを選択するには、事前にATLASで定義しておく必要があります。コホートのインスタンス化については、第 <a href="Cohorts.html#Cohorts">10</a> 章で説明しています。この例で使用する対象（付録 <a href="CohortDefinitions.html#AceInhibitors">B.1</a>）およびアウトカム（付録 <a href="CohortDefinitions.html#Angioedema">B.4</a>）コホートの完全な定義は付録に掲載しています。対象集団をコホートに追加するには、「Add Target Cohort」ボタンをクリックします。アウトカムコホートの追加も同様に、「Add Outcome Cohort」ボタンをクリックすることで行います。完了すると、ダイアログが図 <a href="PatientLevelPrediction.html#fig:problemSettings">13.4</a> のようになります。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:problemSettings"></span>
<img src="images/PatientLevelPrediction/problemSettings.png" alt="予測問題の設定" width="100%" />
<p class="caption">
図 13.4: 予測問題の設定
</p>
</div>
</div>
<div id="分析設定" class="section level3 hasAnchor" number="13.6.2">
<h3><span class="header-section-number">13.6.2</span> 分析設定<a href="PatientLevelPrediction.html#分析設定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>分析設定では、教師あり学習アルゴリズム、共変量と母集団の設定を選択できます。</p>
<div id="モデル設定" class="section level4 unnumbered hasAnchor">
<h4>モデル設定<a href="PatientLevelPrediction.html#モデル設定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>モデル開発には、1つまたは複数の教師あり学習アルゴリズムを選択することができます。教師あり学習アルゴリズムを追加するには、「Add Model Settings」ボタンをクリックします。ATLASインターフェースで現在サポートされているすべてのモデルを含むドロップダウンが表示されます。ドロップダウンメニューから名前をクリックして、調査に含めたい教師あり学習モデルを選択します。これにより、その特定のモデルのビューが表示され、ハイパーパラメータ値の選択が可能になります。複数の値が指定されている場合、グリッドサーチがすべての値の組み合わせに対して実行され、クロスヴァリデーションを使用して最適な組み合わせが選択されます。</p>
<p>今回の例では、勾配ブースティングマシンを選択し、図 <a href="PatientLevelPrediction.html#fig:gbmSettings">13.5</a> に示すようにハイパーパラメータを設定します。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:gbmSettings"></span>
<img src="images/PatientLevelPrediction/gbmSettings.png" alt="勾配ブースティングマシンの設定" width="100%" />
<p class="caption">
図 13.5: 勾配ブースティングマシンの設定
</p>
</div>
</div>
<div id="共変量設定" class="section level4 unnumbered hasAnchor">
<h4>共変量設定<a href="PatientLevelPrediction.html#共変量設定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>私たちは、CDM形式の観察データから抽出できる標準共変量のセットを定義しました。共変量設定ビューでは、どの標準共変量を含めるかを選択できます。異なるタイプの共変量設定を定義でき、各モデルは指定された共変量設定ごとに個別に作成されます。</p>
<p>研究に共変量設定を追加するには、「Add Covariate Settings」をクリックします。これで共変量設定ビューが開きます。</p>
<p>共変量設定ビューの最初の部分は除外/包括オプションです。共変量は一般に任意のコンセプトに対して構築されますが、例えば対象コホート定義にリンクされている場合、特定のコンセプトを除外または含めることができます。特定のコンセプトのみを含めるには、ATLASでコンセプトセットを作成し、 「<strong>What concepts do you want to include in baseline covariates in the patient-level prediction model? (Leave blank if you want to include everything) (患者レベルの予測モデルにおけるベースライン共変量として、どのようなコンセプトを含めたいですか？（すべてを含めたい場合は空白のままにしてください）)</strong>」 の下で<img src="images/PopulationLevelEstimation/open.png" />をクリックしてコンセプトセットを選択します。コンセプトセット内のコンセプトに下位層のコンセプトを自動的に追加するには、「<strong>Should descendant concepts be added to the list of included concepts? (含まれるコンセプトのリストに下位層コンセプトを追加すべきでしょうか？)</strong>」の質問に「yes」と答えます。同じプロセスを、共変量に対応する選択されたコンセプトを除外する「<strong>What concepts do you want to exclude in baseline covariates in the patient-level prediction model? (Leave blank if you want to include everything) (患者レベルの予測モデルにおけるベースライン共変量から除外したいコンセプトは何ですか？（すべてを含める場合は空白のままにしてください）)</strong>」の質問にも繰り返します。最後のオプション 「<strong>A comma delimited list of covariate IDs that should be restricted to (制限すべき共変数IDのコンマ区切りリスト)</strong>」では、共変量ID（コンセプトIDではなく）をカンマ区切りで追加し、これらがモデルに含まれるようにすることができます。このオプションは上級ユーザ向けです。完了すると、適格基準設定と除外基準設定は図 <a href="PatientLevelPrediction.html#fig:covariateSettings1">13.6</a>のようになります。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:covariateSettings1"></span>
<img src="images/PatientLevelPrediction/covariateSettings1.png" alt="共変量の包括と除外設定" width="100%" />
<p class="caption">
図 13.6: 共変量の包括と除外設定
</p>
</div>
<p>次のセクションでは、時間に依存しない変数の選択ができます：</p>
<ul>
<li><p>性別： 男性または女性の性別を示す二値変数</p></li>
<li><p>年齢： 年単位の連続変数</p></li>
<li><p>年齢グループ： 5年ごとのバイナリ変数（0-4、5-9、…、95+）</p></li>
<li><p>人種： 各人種に関するバイナリ変数で、1は患者がその人種を記録していることを意味し、0はそうでないことを意味します。</p></li>
<li><p>民族： 各民族性に関するバイナリ変数で、1は患者がその民族性を記録していることを意味し、0はそうでないことを意味します。</p></li>
<li><p>インデックス年： 各コホート開始日の年を表すバイナリ変数で、1は患者のコホート開始年、0はそれ以外を表します。<strong>インデックス年を含めることは、しばしば意味をなさないことがあります。なぜなら、私たちは将来にわたってモデルを適用したいからです</strong>。</p></li>
<li><p>インデックス月： 各コホート開始日の月を表すバイナリ変数で、1は患者のコホート開始日の月を表し、0はそれ以外を表します。</p></li>
<li><p>前観察期間： [予測には推奨されません] コホート開始日以前に患者がデータベースに存在した日数を示す連続変数</p></li>
<li><p>後観察期間： [予測には推奨されません] コホート開始日以降に患者がデータベースに存在した日数を示す連続変数</p></li>
<li><p>コホート時間： 患者がコホートに属していた日数（コホート終了日－コホート開始日）に対応する連続変数</p></li>
<li><p>インデックス年と月： [予測には推奨されません] 各コホート開始日の年と月の組み合わせを表すバイナリ変数。1は患者のコホート開始日の年と月であることを表し、0はそれ以外を表します。</p></li>
</ul>
<p>これが完了すると、このセクションは図 <a href="PatientLevelPrediction.html#fig:covariateSettings2">13.7</a> のようになるはずです。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:covariateSettings2"></span>
<img src="images/PatientLevelPrediction/covariateSettings2.png" alt="共変量の選択" width="100%" />
<p class="caption">
図 13.7: 共変量の選択
</p>
</div>
<p>標準の共変量は共変量に対して柔軟な3つの時間間隔を設定できます：</p>
<ul>
<li>終了日までの日数: コホート開始日からの終了日まで[デフォルトは0]</li>
<li>長期 [デフォルトはコホート開始前365日から終了日まで]</li>
<li>中期 [デフォルトはコホート開始前180日から終了日まで]</li>
<li>短期 [デフォルトはコホート開始前30日から終了日まで]</li>
</ul>
<p>これが完了すると、このセクションは図 <a href="PatientLevelPrediction.html#fig:covariateSettings3">13.8</a> のようになるはずです。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:covariateSettings3"></span>
<img src="images/PatientLevelPrediction/covariateSettings3.png" alt="時間に依存する共変量" width="100%" />
<p class="caption">
図 13.8: 時間に依存する共変量
</p>
</div>
<p>次のオプションは、期間テーブルから抽出される共変量です：</p>
<ul>
<li><p>コンディション： 選択された各コンディションのコンセプトIDと時間間隔ごとに共変量を構築し、CONDITON_ERAテーブルにおいて、選択されたコホート開始日前の時間間隔の間に、患者にコンディション期間をもつ（すなわち、その時間間隔の間にそのコンディションが開始または終了するか、またはその時間間隔の前に開始し、その時間間隔の後に終了する）コンセプトIDがある場合、共変量の値は 1、そうでない場合は 0。</p></li>
<li><p>コンディショングループ： 選択されたコンディションのコンセプトIDと時間間隔について共変量を構築し、CONDITON_ERAテーブルにおいて、選択されたコホート開始日前の時間間隔の間に、患者にコンディション期間を持つコンセプトID<strong>またはその下位層のコンセプトID</strong>がある場合、共変量値は 1、そうでない場合は 0。</p></li>
<li><p>薬剤：選択された各薬剤コンセプトIDと時間間隔ごとに共変量を構築し、DRUG_ERAテーブルにおいて、選択されたコホート開始日前の時間間隔の間に、患者に薬剤（曝露）期間をもつコンセプトIDがある場合、共変量の値は 1、そうでない場合は 0。</p></li>
<li><p>薬剤グループ：選択された各薬剤コンセプトIDと時間間隔ごとに共変量を構築し、DRUG_ERAテーブルにおいて、選択されたコホート開始日前の時間間隔の間に、患者に薬剤（曝露）期間をもつコンセプトID<strong>またはその下位層のコンセプトID</strong>がある場合、共変量の値は 1、そうでない場合は 0。</p></li>
</ul>
<p>重複する時間間隔の設定は、薬剤または症状がコホート開始日以前に開始し、終了がコホート開始日以後に続くものが含まれます。<strong>期間の開始</strong>オプションは時間間隔内に開始したものに限定します。</p>
<p>これが完了すると、このセクションは図 <a href="PatientLevelPrediction.html#fig:covariateSettings4">13.9</a> のようになるはずです。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:covariateSettings4"></span>
<img src="images/PatientLevelPrediction/covariateSettings4.png" alt="期間時間共変量." width="100%" />
<p class="caption">
図 13.9: 期間時間共変量.
</p>
</div>
<p>次のオプションは、さまざまな時間間隔について、各ドメインのコンセプト ID に対応する共変量を選択します。：</p>
<ul>
<li><p>コンディション： 選択されたコンディションコンセプトIDと時間間隔ごとに共変量を構築し、CONDITION_OCCURRENCテーブルのコホート開始日前の指定された時間間隔に、患者がそのコンセプトIDを記録している場合、共変量の値は1、そうでない場合は0。</p></li>
<li><p>主たる入院コンディション（Condition Primary Inpatient）： condition_occurrenceテーブルで入院患者の主たる診断として、CONDITION_OCCURRENCテーブル中に観察されたコンディションごとのバイナリ共変量。</p></li>
<li><p>薬剤： 選択された薬剤コンセプトIDと時間間隔ごとに共変量を構築し、DRUG_EXPOSUREテーブルのコホート開始日前の指定された時間間隔に、患者がコンセプトIDを記録している場合、共変量の値は 1 、そうでない場合は 0。</p></li>
<li><p>処置（プロシージャー）：選択されたプロシージャ―コンセプトIDと時間間隔ごとに共変量を構築し、PROCEDURE_OCCURRENCEテーブルのコホート開始日前の指定された時間間隔に、患者がコンセプトIDを記録している場合、共変量の値は 1 、そうでない場合は 0。</p></li>
<li><p>測定（メジャーメント）：選択されたメジャーメントコンセプトIDと時間間隔ごとに共変量を構築し、MEASUREMENTテーブルのコホート開始日前の指定された時間間隔に、患者がコンセプトIDを記録している場合、共変量の値は 1 、そうでない場合は 0。</p></li>
<li><p>測定値： 測定値が伴う選択された測定値コンセプトIDと時間間隔ごとに共変量を構築し、MEASUREMENTテーブルのコホート開始日前の指定された時間間隔に、患者がコンセプトIDを記録している場合、共変量の値は 1 、そうでない場合は 0。</p></li>
<li><p>測定値範囲グループ： 測定値が正常範囲以下、範囲内、または正常範囲以上であるかを示すバイナリ共変量。</p></li>
<li><p>観察（オブザベーション）：選択された観察コンセプトIDと時間間隔ごとに共変量を構築し、OBSERVATIONテーブルのコホート開始日前の指定された時間間隔に、患者がそのコンセプトIDを記録している場合、共変量の値は1、そうでない場合は0。</p></li>
<li><p>デバイス：選択されたデバイスコンセプトIDと時間間隔ごとに共変量を構築し、DEVICEテーブルのコホート開始日前の指定された時間間隔に、患者がそのコンセプトIDを記録している場合、共変量の値は1、そうでない場合は0。</p></li>
<li><p>ビジット回数：選択されたビジット回数と時間間隔ごとに共変量を構築し、その時間間隔に記録されたビジット回数を共 変量値としてカウント。</p></li>
<li><p>ビジットコンセプト数： 選択された各ビジット、ドメイン、時間間隔ごとに共変量を構築し、その時間間隔に記録されたレコード数を、各ドメインのビジットタイプと時間間隔ごとに共変量値としてカウント。</p></li>
</ul>
<p>「distinct count (重複を除いたカウント)」オプションは、ドメインと時間間隔ごとに、異なるコンセプトIDの数をカウントします。</p>
<p>これらが完了すると、このセクションは下図 <a href="PatientLevelPrediction.html#fig:covariateSettings5">13.10</a> のようになっているはずです。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:covariateSettings5"></span>
<img src="images/PatientLevelPrediction/covariateSettings5.png" alt="時間制約共変量" width="100%" />
<p class="caption">
図 13.10: 時間制約共変量
</p>
</div>
<p>最後のオプションは、一般に使われるリスクスコアを共変量として含めるかどうかです。設定が完了すると、リスクスコアの設定は図 <a href="PatientLevelPrediction.html#fig:covariateSettings6">13.11</a> のようになります。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:covariateSettings6"></span>
<img src="images/PatientLevelPrediction/covariateSettings6.png" alt="リスクスコア共変量設定" width="100%" />
<p class="caption">
図 13.11: リスクスコア共変量設定
</p>
</div>
</div>
<div id="研究対象集団の設定" class="section level4 unnumbered hasAnchor">
<h4>研究対象集団の設定<a href="PatientLevelPrediction.html#研究対象集団の設定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>対象集団の設定は、追加の適格基準を対象集団に適用できる場所であり、また、リスク期間もここで定義されます。 研究に対象集団の設定を追加するには、「Add Population Settings (対象集団の追加)」ボタンをクリックします。 これにより、対象集団の設定ビューが表示されます。</p>
<p>最初のオプションセットでは、リスク期間を指定することができます。これは、対象とするアウトカムが起こるかどうかを観察する時間間隔です。リスク期間中に患者にアウトカムが起きた場合は「Has outcome (アウトカムあり)」に分類し、そうでない場合は「No outcome (アウトカムなし)」 に分類します。「<strong>Define the time-at-risk window start, relative to target cohort entry: (ターゲットコホート組入れを基準に、リスク時間ウインドウの開始を定義します。)</strong>」 は、ターゲットコホートの開始または終了日を基準としたリスク期間の開始を定義します。同様に、「<strong>Define the time-at-risk window end: (対象コホートの開始または終了日を基準とした、リスク期間の終了を定義します。)</strong>」は、リスク期間の終了を定義します。</p>
<p>「<strong>Minimum lookback period applied to target cohort (対象コホートに適用される最小のルックバック期間)</strong>」 は、患者がコホート開始日より前の継続的に観察された日数の最低値である、最小のベースライン期間を指定します。デフォルトは365日です。最小のルックバック期間を長くすると、患者の全体像がより明確になりますが（より長い期間観察されているはずであるため）、開始日前の観察が最低日数に満たない患者は除外されます。</p>
<p>「<strong>Should subjects without time at risk be removed? (リスク期間がない対象は除外すべきですか。)</strong>」 が 「Yes (はい)」 に設定されている場合、「<strong>Minimum time at risk: (最低リスク時間：)</strong>」 の値も必要となります。これにより、追跡不能となった人（すなわち、リスク期間中にデータベースから離脱した人）を除外することができます。例えば、リスク期間がコホート開始後1日からコホート開始後365日までであった場合、リスク期間は364日間（365-1）となります。もし、その全期間にわたって観察された患者のみを含めたいのであれば、最小リスク時間を364に設定します。最初の100日間リスク期間に該当していればよいのであれば、最小リスク期間を100に設定します。この場合、リスク期間の開始はコホート開始から1日後なので、コホート開始日から少なくとも101日間データベースに存在する患者が対象となります。「Should subjects without time at risk be removed? (リスク期間がない対象は削除すべきですか。）」を「No (いいえ)」に設定すると、リスク期間中にデータベースから離脱した患者も含め、すべての患者が対象となります。</p>
<p>「<strong>Include people with outcomes who are not observed for the whole at risk period? (全リスク期間で観察されていないアウトカムを持つ人を含めますか。)</strong>」 というオプションは、前のオプションに関連しています。「Yes (はい)」に設定すると、指定された最低リスク期間で観察されていない場合でも、リスク期間中にアウトカムを経験した人は常にコホートに保持されます。</p>
<p>「<strong>Should only the first exposure per subject be included? (対象ごとに最初の曝露のみを含めるべきですか)</strong>」というオプションは、対象コホートに異なるコホート開始日で複数回含まれる患者がいる場合にのみ有用です。この状況で “Yes (はい)」を選択すると、分析では患者ごとに最も早い対象コホートの日付のみが保持されます。そうでない場合、患者はデータセットに複数回含まれる可能性があります。</p>
<p>「<strong>Remove patients who have observed the outcome prior to cohort entry? (コホート組入れの前にアウトカムが観察された患者を除外しますか)</strong>」を「Yes (はい)」 に設定すると、リスク期間開始日より前にアウトカムを経験した患者を除外するため、そのモデルは以前にアウトカムを経験したことがない患者を対象とします。もし “No (いいえ)」が選択されると、患者は以前にアウトカムを持つ可能性があります。患者が以前にアウトカムを経験したことが、リスク期間中にアウトカムが起きることを非常に高い確率で予測することが多いです。</p>
<p>完了すると、対象集団の設定のダイアログは図 <a href="PatientLevelPrediction.html#fig:populationSettings">13.12</a> のようになります。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:populationSettings"></span>
<img src="images/PatientLevelPrediction/populationSettings.png" alt="対象集団の設定" width="100%" />
<p class="caption">
図 13.12: 対象集団の設定
</p>
</div>
<p>これで分析の設定が終わり、ダイアログ全体が図 <a href="PatientLevelPrediction.html#fig:analysisSettings">13.13</a> のようになります。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:analysisSettings"></span>
<img src="images/PatientLevelPrediction/analysisSettings.png" alt="分析の設定" width="100%" />
<p class="caption">
図 13.13: 分析の設定
</p>
</div>
</div>
</div>
<div id="実行の設定" class="section level3 hasAnchor" number="13.6.3">
<h3><span class="header-section-number">13.6.3</span> 実行の設定<a href="PatientLevelPrediction.html#実行の設定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>オプションは3つあります：</p>
<ul>
<li><p><strong>Perform sampling (サンプリングの実行)</strong> ： ここでサンプリングを実行するかどうかを選択します（デフォルトは 「no (いいえ)」）。「yes (はい)」 を選択すると、別のオプションが表示されます： 「<strong>How many patients to use for a subset? (サブセットに何人の患者を含めますか。)</strong>」で、サンプルの大きさを指定できます。サンプリングは、大規模な母集団（例えば1000万人の患者）のモデルが予測可能かどうかを判断する効率的な手段となり得ます。例えば、サンプルにおける AUC が 0.5 に近い場合、そのモデルは破棄されるかもしれません。</p></li>
<li><p>「<strong>Minimum covariate occurrence: If a covariate occurs in a fraction of the target population less than this value, it will be removed: (最小共変量出現率： もし共変量がこの値より小さい割合で対象集団に出現する場合、その共変量は除外されます:)</strong>」: ここでは共変量の出現率の最小値を選択します（デフォルトは0.001）。共変量出現の最小閾値は、全体集団を代表しないまれなイベントを除外するために必要です。</p></li>
<li><p>「<strong>Normalize covariate (共変量を正規化する)</strong>」： ここで共変量を正規化するかどうかを選択します（デフォルトは「yes (はい)」）。共変量の正規化は、通常、LASSOモデルをうまく実行するために必要です。</p></li>
</ul>
<p>この例では、図 <a href="PatientLevelPrediction.html#fig:executionSettings">13.14</a> のように選択します。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:executionSettings"></span>
<img src="images/PatientLevelPrediction/executionSettings.png" alt="実行の設定" width="100%" />
<p class="caption">
図 13.14: 実行の設定
</p>
</div>
</div>
<div id="トレーニングの設定" class="section level3 hasAnchor" number="13.6.4">
<h3><span class="header-section-number">13.6.4</span> トレーニングの設定<a href="PatientLevelPrediction.html#トレーニングの設定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>4つのオプションがあります：</p>
<ul>
<li><p>「<strong>Specify how to split the test/train set (テストセットとトレーニングセットをどのように分けるかを指定します。)</strong>」： トレーニング/テストデータを人別（アウトカムで層別化）または時間別（古いデータをトレーニングに、新しいデータは評価に）に分割するかを選択します。</p></li>
<li><p>「<strong>Percentage of the data to be used as the test set (0-100%) (テストセットとして使用するデータの割合(0-100%))</strong>」： テストデータとして使用するデータの割合を選択します（デフォルトは25%）。</p></li>
<li><p>「<strong>The number of folds used in the cross validation (クロスバリデーションで使用するフォールド数)</strong>」： 最適なハイパーパラメータを選択するために使用するクロスバリデーションのフォールド数を選択します（デフォルトは3）。</p></li>
<li><p>「<strong>The seed used to split the test/train set when using a person type testSplit (optional): (人単位で testSplit を使う場合の、テストセットとトレーニングセットを分割するためのシード (オプション)：)</strong>」： 人単位でテストセットとトレーニングセットを分割する場合に、分割に使用するランダムシードを選択します。</p></li>
</ul>
<p>この例では、図 <a href="PatientLevelPrediction.html#fig:trainingSettings">13.15</a> のように選択します。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:trainingSettings"></span>
<img src="images/PatientLevelPrediction/trainingSettings.png" alt="トレーニングの設定" width="100%" />
<p class="caption">
図 13.15: トレーニングの設定
</p>
</div>
</div>
<div id="研究のインポートとエクスポート" class="section level3 hasAnchor" number="13.6.5">
<h3><span class="header-section-number">13.6.5</span> 研究のインポートとエクスポート<a href="PatientLevelPrediction.html#研究のインポートとエクスポート" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>研究をエクスポートするには、「Utilities (ユーティリティ)」の下にある 「Export (エクスポート)」タブをクリックします。ATLASは、研究の名称、コホート定義、選択したモデル、共変量、設定など、研究実行に必要なすべてのデータを含むファイルに直接コピー＆ペーストできるJSONを作成します。</p>
<p>研究をインポートするには、「Utilities (ユーティリティ)」の下にある「Import (インポート)」タブをクリックします。患者レベルの予測研究のJSONの内容をこのウィンドウに貼り付け、他のタブボタンの下にある「Import (インポート)」ボタンをクリックします。これにより、その研究の以前の設定がすべて上書きされることに注意してください。通常は、新しい空の研究デザインを使用して実行します。</p>
</div>
<div id="研究パッケージのダウンロード" class="section level3 hasAnchor" number="13.6.6">
<h3><span class="header-section-number">13.6.6</span> 研究パッケージのダウンロード<a href="PatientLevelPrediction.html#研究パッケージのダウンロード" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>「Utilities (ユーティリティ)」 の下にある「Review &amp; Download (レビューとダウンロード)」タブをクリックします。「Download Study Package (研究パッケージをダウンロード)」セクションで、Rパッケージのわかりやすい名前を入力します。Rで使えない文字は、ATLASによって自動的にファイル名から削除されることに注意してください。<img src="images/PatientLevelPrediction/download.png" /> をクリックして、Rパッケージをローカルフォルダにダウンロードします。</p>
</div>
<div id="研究の実行" class="section level3 hasAnchor" number="13.6.7">
<h3><span class="header-section-number">13.6.7</span> 研究の実行<a href="PatientLevelPrediction.html#研究の実行" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>セクション <a href="OhdsiAnalyticsTools.html#installR">8.4.5</a> の説明のように、Rパッケージを実行するには、R、RStudio、Javaがインストールされている必要があります。また、Rで下記のようにインストールできる <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> パッケージも必要です：</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="PatientLevelPrediction.html#cb116-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;drat&quot;</span>)</span>
<span id="cb116-2"><a href="PatientLevelPrediction.html#cb116-2" tabindex="-1"></a>drat<span class="sc">::</span><span class="fu">addRepo</span>(<span class="st">&quot;OHDSI&quot;</span>)</span>
<span id="cb116-3"><a href="PatientLevelPrediction.html#cb116-3" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;PatientLevelPrediction&quot;</span>)</span></code></pre></div>
<p>機械学習アルゴリズムの中には、追加ソフトウェアのインストールが必要なものがあります。<a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> パッケージのインストール方法の詳細については、<a href="https://ohdsi.github.io/PatientLevelPrediction/articles/InstallationGuide.html">「Patient-Level Prediction Installation Guide」vignette</a>を参照ください。</p>
<p>study Rパッケージを使用するには、R Studioの使用をお勧めします。R Studioをローカルで実行している場合は、ATLASで生成されたファイルを解凍し、.RprojファイルをダブルクリックしてR Studioで開きます。RスタジオをRスタジオサーバーで実行している場合は、<img src="images/PopulationLevelEstimation/upload.png" />をクリックしてファイルをアップロードし、解凍した後、.Rprojファイルをクリックしてプロジェクトを開きます。</p>
<p>R Studioでプロジェクトを開いたら、READMEファイルを開き、指示に従ってください。すべてのファイルのパスを、システム上の既存のパスに変更してください。</p>
</div>
</div>
<div id="rでの研究実施" class="section level2 hasAnchor" number="13.7">
<h2><span class="header-section-number">13.7</span> Rでの研究実施<a href="PatientLevelPrediction.html#rでの研究実施" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>研究デザインをATLASで実装する代わりに、Rで直接コードを記述して実施することもできます。ここでは、<a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a>パッケージを利用します。このパッケージは、OMOP CDMに変換されたデータベースからデータを抽出し、モデルを構築し、評価することができます。</p>
<div id="コホートのインスタンス化-2" class="section level3 hasAnchor" number="13.7.1">
<h3><span class="header-section-number">13.7.1</span> コホートのインスタンス化<a href="PatientLevelPrediction.html#コホートのインスタンス化-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>まず、ターゲットコホートとアウトカムコホートをインスタンス化する必要があります。コホートのインスタンス化については、第 <a href="Cohorts.html#Cohorts">10</a> 章で説明しています。付録にはターゲットコホート(付録 <a href="CohortDefinitions.html#AceInhibitors">B.1</a>)とアウトカムコホート(付録 <a href="CohortDefinitions.html#Angioedema">B.4</a>)の完全な定義があります。この例では、ACE阻害薬コホートのIDが1、血管性浮腫コホートのIDが2であると仮定します。</p>
</div>
<div id="データ抽出-3" class="section level3 hasAnchor" number="13.7.2">
<h3><span class="header-section-number">13.7.2</span> データ抽出<a href="PatientLevelPrediction.html#データ抽出-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>まず、Rにサーバへの接続方法を伝える必要があります。<a href="https://ohdsi.github.io/PatientLevelPrediction/"><code>PatientLevelPrediction</code></a>は、<a href="https://ohdsi.github.io/DatabaseConnector/"><code>DatabaseConnector</code></a>パッケージを使用します。このパッケージには<code>createConnectionDetails</code>という関数があります。さまざまなデータベース管理システム(DBMS)の設定については、<code>?createConnectionDetails</code>と入力してください。例えば、次のようにPostgreSQLデータベースに接続できます：</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="PatientLevelPrediction.html#cb117-1" tabindex="-1"></a><span class="fu">library</span>(PatientLevelPrediction)</span>
<span id="cb117-2"><a href="PatientLevelPrediction.html#cb117-2" tabindex="-1"></a>connDetails <span class="ot">&lt;-</span> <span class="fu">createConnectionDetails</span>(<span class="at">dbms =</span> <span class="st">&quot;postgresql&quot;</span>,</span>
<span id="cb117-3"><a href="PatientLevelPrediction.html#cb117-3" tabindex="-1"></a>                                       <span class="at">server =</span> <span class="st">&quot;localhost/ohdsi&quot;</span>,</span>
<span id="cb117-4"><a href="PatientLevelPrediction.html#cb117-4" tabindex="-1"></a>                                       <span class="at">user =</span> <span class="st">&quot;joe&quot;</span>,</span>
<span id="cb117-5"><a href="PatientLevelPrediction.html#cb117-5" tabindex="-1"></a>                                       <span class="at">password =</span> <span class="st">&quot;supersecret&quot;</span>)</span>
<span id="cb117-6"><a href="PatientLevelPrediction.html#cb117-6" tabindex="-1"></a></span>
<span id="cb117-7"><a href="PatientLevelPrediction.html#cb117-7" tabindex="-1"></a>cdmDbSchema <span class="ot">&lt;-</span> <span class="st">&quot;my_cdm_data&quot;</span></span>
<span id="cb117-8"><a href="PatientLevelPrediction.html#cb117-8" tabindex="-1"></a>cohortsDbSchema <span class="ot">&lt;-</span> <span class="st">&quot;scratch&quot;</span></span>
<span id="cb117-9"><a href="PatientLevelPrediction.html#cb117-9" tabindex="-1"></a>cohortsDbTable <span class="ot">&lt;-</span> <span class="st">&quot;my_cohorts&quot;</span></span>
<span id="cb117-10"><a href="PatientLevelPrediction.html#cb117-10" tabindex="-1"></a>cdmVersion <span class="ot">&lt;-</span> <span class="st">&quot;5&quot;</span></span></code></pre></div>
<p>最後の4行は<code>cdmDbSchema</code>、<code>cohortsDbSchema</code>、<code>cohortsDbTable</code>変数の定義と、CDMバージョンを指定しています。これらを使用してCDMフォーマットのデータが存在する場所、関心のあるコホートが作成された場所、および使用されているCDMバージョンをRに伝えます。Microsoft SQL Serverの場合、データベーススキーマはデータベースとスキーマの両方を指定する必要があることに注意してください。例えば、<code>cdmDbSchema &lt;- "my_cdm_data.dbo"</code>のように指定します。</p>
<p>まず、コホート作成が成功したかを確認するために、コホート組入れの数をカウントします：</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="PatientLevelPrediction.html#cb118-1" tabindex="-1"></a>sql <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">&quot;SELECT cohort_definition_id, COUNT(*) AS count&quot;</span>,</span>
<span id="cb118-2"><a href="PatientLevelPrediction.html#cb118-2" tabindex="-1"></a><span class="st">&quot;FROM @cohortsDbSchema.cohortsDbTable&quot;</span>,</span>
<span id="cb118-3"><a href="PatientLevelPrediction.html#cb118-3" tabindex="-1"></a><span class="st">&quot;GROUP BY cohort_definition_id&quot;</span>)</span>
<span id="cb118-4"><a href="PatientLevelPrediction.html#cb118-4" tabindex="-1"></a>conn <span class="ot">&lt;-</span> <span class="fu">connect</span>(connDetails)</span>
<span id="cb118-5"><a href="PatientLevelPrediction.html#cb118-5" tabindex="-1"></a><span class="fu">renderTranslateQuerySql</span>(<span class="at">connection =</span> conn,</span>
<span id="cb118-6"><a href="PatientLevelPrediction.html#cb118-6" tabindex="-1"></a>                        <span class="at">sql =</span> sql,</span>
<span id="cb118-7"><a href="PatientLevelPrediction.html#cb118-7" tabindex="-1"></a>                        <span class="at">cohortsDbSchema =</span> cohortsDbSchema,</span>
<span id="cb118-8"><a href="PatientLevelPrediction.html#cb118-8" tabindex="-1"></a>                        <span class="at">cohortsDbTable =</span> cohortsDbTable)</span></code></pre></div>
<pre><code>##   cohort_definition_id  count
## 1                    1 527616
## 2                    2   3201</code></pre>
<p><a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a>に我々の分析に必要なすべてのデータを抽出するように指示します。共変量は<a href="https://ohdsi.github.io/FeatureExtraction/"><code>FeatureExtraction</code></a>パッケージを使用して抽出します。FeatureExtractionパッケージの詳細については、そのビネットを参照してください。今回の研究例では次の設定を使用しました：</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="PatientLevelPrediction.html#cb120-1" tabindex="-1"></a>covariateSettings <span class="ot">&lt;-</span> <span class="fu">createCovariateSettings</span>(</span>
<span id="cb120-2"><a href="PatientLevelPrediction.html#cb120-2" tabindex="-1"></a>  <span class="at">useDemographicsGender =</span> <span class="cn">TRUE</span>,</span>
<span id="cb120-3"><a href="PatientLevelPrediction.html#cb120-3" tabindex="-1"></a>  <span class="at">useDemographicsAge =</span> <span class="cn">TRUE</span>,</span>
<span id="cb120-4"><a href="PatientLevelPrediction.html#cb120-4" tabindex="-1"></a>  <span class="at">useConditionGroupEraLongTerm =</span> <span class="cn">TRUE</span>,</span>
<span id="cb120-5"><a href="PatientLevelPrediction.html#cb120-5" tabindex="-1"></a>  <span class="at">useConditionGroupEraAnyTimePrior =</span> <span class="cn">TRUE</span>,</span>
<span id="cb120-6"><a href="PatientLevelPrediction.html#cb120-6" tabindex="-1"></a>  <span class="at">useDrugGroupEraLongTerm =</span> <span class="cn">TRUE</span>,</span>
<span id="cb120-7"><a href="PatientLevelPrediction.html#cb120-7" tabindex="-1"></a>  <span class="at">useDrugGroupEraAnyTimePrior =</span> <span class="cn">TRUE</span>,</span>
<span id="cb120-8"><a href="PatientLevelPrediction.html#cb120-8" tabindex="-1"></a>  <span class="at">useVisitConceptCountLongTerm =</span> <span class="cn">TRUE</span>,</span>
<span id="cb120-9"><a href="PatientLevelPrediction.html#cb120-9" tabindex="-1"></a>  <span class="at">longTermStartDays =</span> <span class="sc">-</span><span class="dv">365</span>,</span>
<span id="cb120-10"><a href="PatientLevelPrediction.html#cb120-10" tabindex="-1"></a>  <span class="at">endDays =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div>
<p>データ抽出の最終ステップは、<code>getPlpData</code>関数を実行し、接続の詳細、コホートが保存されているデータベーススキーマ、コホートと結果のコホート定義ID、およびコホートインデックス日付の前にデータに含めるために観察されなければならない最低日数であるウォッシュアウト期間を入力し、最後に以前に構築した共変量設定を入力することです。</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="PatientLevelPrediction.html#cb121-1" tabindex="-1"></a>plpData <span class="ot">&lt;-</span> <span class="fu">getPlpData</span>(<span class="at">connectionDetails =</span> connDetails,</span>
<span id="cb121-2"><a href="PatientLevelPrediction.html#cb121-2" tabindex="-1"></a>                      <span class="at">cdmDatabaseSchema =</span> cdmDbSchema,</span>
<span id="cb121-3"><a href="PatientLevelPrediction.html#cb121-3" tabindex="-1"></a>                      <span class="at">cohortDatabaseSchema =</span> cohortsDbSchema,</span>
<span id="cb121-4"><a href="PatientLevelPrediction.html#cb121-4" tabindex="-1"></a>                      <span class="at">cohortTable =</span> cohortsDbSchema,</span>
<span id="cb121-5"><a href="PatientLevelPrediction.html#cb121-5" tabindex="-1"></a>                      <span class="at">cohortId =</span> <span class="dv">1</span>,</span>
<span id="cb121-6"><a href="PatientLevelPrediction.html#cb121-6" tabindex="-1"></a>                      <span class="at">covariateSettings =</span> covariateSettings,</span>
<span id="cb121-7"><a href="PatientLevelPrediction.html#cb121-7" tabindex="-1"></a>                      <span class="at">outcomeDatabaseSchema =</span> cohortsDbSchema,</span>
<span id="cb121-8"><a href="PatientLevelPrediction.html#cb121-8" tabindex="-1"></a>                      <span class="at">outcomeTable =</span> cohortsDbSchema,</span>
<span id="cb121-9"><a href="PatientLevelPrediction.html#cb121-9" tabindex="-1"></a>                      <span class="at">outcomeIds =</span> <span class="dv">2</span>,</span>
<span id="cb121-10"><a href="PatientLevelPrediction.html#cb121-10" tabindex="-1"></a>                      <span class="at">sampleSize =</span> <span class="dv">10000</span></span>
<span id="cb121-11"><a href="PatientLevelPrediction.html#cb121-11" tabindex="-1"></a>)</span></code></pre></div>
<p><code>getPlpData</code>関数には多くの追加パラメータがあります。これらはすべて<a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a>マニュアルに詳細に記載されています。生成された<code>plpData</code>オブジェクトは<code>ff</code>パッケージを使用し、大量のデータでもRのメモリ不足を避けるようにデザインされています。</p>
<p><code>plpData</code>オブジェクトの生成にはかなりの計算時間がかかります。おそらく、今後のセッション用に保存しておくのが良いでしょう。plpDataはffを使用しているため、Rの通常の保存機能を使用することはできません。代わりに、<code>savePlpData</code>関数を使用します：</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="PatientLevelPrediction.html#cb122-1" tabindex="-1"></a><span class="fu">savePlpData</span>(plpData, <span class="st">&quot;angio_in_ace_data&quot;</span>)</span></code></pre></div>
<p><code>loadPlpData()</code>関数を使用して、今後のセッションでデータを読み込むことができます。</p>
</div>
<div id="追加の適格基準" class="section level3 hasAnchor" number="13.7.3">
<h3><span class="header-section-number">13.7.3</span> 追加の適格基準<a href="PatientLevelPrediction.html#追加の適格基準" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>最終的な研究対象集団は、先に定義した2つのコホートに追加の制約を適用することによって得られます。例えば、最小リスク期間を設定することができます（<code>requireTimeAtRisk</code>、<code>minTimeAtRisk</code>）し、これがアウトカムを持つ患者にも適用されるかどうかを指定できます（<code>includeAllOutcomes</code>）。ここでは、ターゲットコホートの開始時点を基準としたリスク期間の開始と終了も指定します。例えば、リスクのあるコホート開始から30日後にリスク期間を開始し、1年後に終了したい場合は、<code>riskWindowStart = 30</code>、<code>riskWindowEnd = 365</code>と設定します。場合によっては、リスク期間をコホート終了日に開始する必要があります。これは、<code>addExposureToStart = TRUE</code>を設定し、コホート（曝露）期間を開始日に加算することで実現できます。</p>
<p>以下の例では、研究用に定義したすべての設定を適用しています：</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="PatientLevelPrediction.html#cb123-1" tabindex="-1"></a>population <span class="ot">&lt;-</span> <span class="fu">createStudyPopulation</span>(<span class="at">plpData =</span> plpData,</span>
<span id="cb123-2"><a href="PatientLevelPrediction.html#cb123-2" tabindex="-1"></a>                                    <span class="at">outcomeId =</span> <span class="dv">2</span>,</span>
<span id="cb123-3"><a href="PatientLevelPrediction.html#cb123-3" tabindex="-1"></a>                                    <span class="at">washoutPeriod =</span> <span class="dv">364</span>,</span>
<span id="cb123-4"><a href="PatientLevelPrediction.html#cb123-4" tabindex="-1"></a>                                    <span class="at">firstExposureOnly =</span> <span class="cn">FALSE</span>,</span>
<span id="cb123-5"><a href="PatientLevelPrediction.html#cb123-5" tabindex="-1"></a>                                    <span class="at">removeSubjectsWithPriorOutcome =</span> <span class="cn">TRUE</span>,</span>
<span id="cb123-6"><a href="PatientLevelPrediction.html#cb123-6" tabindex="-1"></a>                                    <span class="at">priorOutcomeLookback =</span> <span class="dv">9999</span>,</span>
<span id="cb123-7"><a href="PatientLevelPrediction.html#cb123-7" tabindex="-1"></a>                                    <span class="at">riskWindowStart =</span> <span class="dv">1</span>,</span>
<span id="cb123-8"><a href="PatientLevelPrediction.html#cb123-8" tabindex="-1"></a>                                    <span class="at">riskWindowEnd =</span> <span class="dv">365</span>,</span>
<span id="cb123-9"><a href="PatientLevelPrediction.html#cb123-9" tabindex="-1"></a>                                    <span class="at">addExposureDaysToStart =</span> <span class="cn">FALSE</span>,</span>
<span id="cb123-10"><a href="PatientLevelPrediction.html#cb123-10" tabindex="-1"></a>                                    <span class="at">addExposureDaysToEnd =</span> <span class="cn">FALSE</span>,</span>
<span id="cb123-11"><a href="PatientLevelPrediction.html#cb123-11" tabindex="-1"></a>                                    <span class="at">minTimeAtRisk =</span> <span class="dv">364</span>,</span>
<span id="cb123-12"><a href="PatientLevelPrediction.html#cb123-12" tabindex="-1"></a>                                    <span class="at">requireTimeAtRisk =</span> <span class="cn">TRUE</span>,</span>
<span id="cb123-13"><a href="PatientLevelPrediction.html#cb123-13" tabindex="-1"></a>                                    <span class="at">includeAllOutcomes =</span> <span class="cn">TRUE</span>,</span>
<span id="cb123-14"><a href="PatientLevelPrediction.html#cb123-14" tabindex="-1"></a>                                    <span class="at">verbosity =</span> <span class="st">&quot;DEBUG&quot;</span></span>
<span id="cb123-15"><a href="PatientLevelPrediction.html#cb123-15" tabindex="-1"></a>)</span></code></pre></div>
</div>
<div id="モデル開発" class="section level3 hasAnchor" number="13.7.4">
<h3><span class="header-section-number">13.7.4</span> モデル開発<a href="PatientLevelPrediction.html#モデル開発" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>アルゴリズムのセット関数では、ユーザーは各ハイパーパラメータの有効な値のリストを指定することができます。ハイパーパラメータのすべての可能な組み合わせは、トレーニングセットのクロスバリデーションを使用したいわゆるグリッドサーチに含まれます。ユーザーが値を指定しない場合は、代わりにデフォルト値が使用されます。</p>
<p>例えば、次の設定を勾配ブースティングマシン（Gradient Boosting Machine）で使用するとします：<code>ntrees = c(100,200)</code>, <code>maxDepth = 4</code>。このグリッドサーチは、<code>ntrees = 100</code>および<code>maxDepth = 4</code>、または<code>ntrees = 200</code>および<code>maxDepth = 4</code>の設定でデフォルトの他のハイパーパラメータ設定を含めて勾配ブースティングマシンアルゴリズムを適用します。クロスバリデーションの性能が最も高いハイパーパラメータが最終モデルに選ばれます。この課題では、いくつかのハイパーパラメータ値で勾配ブースティングマシンを構築することにしました：</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="PatientLevelPrediction.html#cb124-1" tabindex="-1"></a>gbmModel <span class="ot">&lt;-</span> <span class="fu">setGradientBoostingMachine</span>(<span class="at">ntrees =</span> <span class="dv">5000</span>,</span>
<span id="cb124-2"><a href="PatientLevelPrediction.html#cb124-2" tabindex="-1"></a>                                       <span class="at">maxDepth =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">10</span>),</span>
<span id="cb124-3"><a href="PatientLevelPrediction.html#cb124-3" tabindex="-1"></a>                                       <span class="at">learnRate =</span> <span class="fu">c</span>(<span class="fl">0.001</span>,<span class="fl">0.01</span>,<span class="fl">0.1</span>,<span class="fl">0.9</span>))</span></code></pre></div>
<p><code>runPlP</code>関数は集団、<code>plpData</code>、モデル設定を使用してモデルをトレーニングし評価します。データを75%-25%に分割して患者レベルの予測パイプラインを実行するために<code>testSplit</code>（人/時間）および<code>testFraction</code>パラメータを使用できます：</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="PatientLevelPrediction.html#cb125-1" tabindex="-1"></a>gbmResults <span class="ot">&lt;-</span> <span class="fu">runPlp</span>(<span class="at">population =</span> population,</span>
<span id="cb125-2"><a href="PatientLevelPrediction.html#cb125-2" tabindex="-1"></a>                     <span class="at">plpData =</span> plpData,</span>
<span id="cb125-3"><a href="PatientLevelPrediction.html#cb125-3" tabindex="-1"></a>                     <span class="at">modelSettings =</span> gbmModel,</span>
<span id="cb125-4"><a href="PatientLevelPrediction.html#cb125-4" tabindex="-1"></a>                     <span class="at">testSplit =</span> <span class="st">&#39;person&#39;</span>,</span>
<span id="cb125-5"><a href="PatientLevelPrediction.html#cb125-5" tabindex="-1"></a>                     <span class="at">testFraction =</span> <span class="fl">0.25</span>,</span>
<span id="cb125-6"><a href="PatientLevelPrediction.html#cb125-6" tabindex="-1"></a>                     <span class="at">nfold =</span> <span class="dv">2</span>,</span>
<span id="cb125-7"><a href="PatientLevelPrediction.html#cb125-7" tabindex="-1"></a>                     <span class="at">splitSeed =</span> <span class="dv">1234</span>)</span></code></pre></div>
<p>このパッケージは内部的にRのxgboostパッケージを使用して、75%のデータを用いて勾配ブースティングマシンモデルを適合させ、残りの25%のデータでモデルを評価します。アウトカムデータ構造には、モデルやその性能などに関する情報が含まれます。</p>
<p><code>runPlp</code>関数には、<code>plpData</code>、<code>plpResults</code>、<code>plpPlots</code>、<code>evaluation</code>などのオブジェクトを保存するためのいくつかのパラメータがあり、デフォルトで<code>TRUE</code>に設定されています。</p>
<p>モデルを保存するには：</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="PatientLevelPrediction.html#cb126-1" tabindex="-1"></a><span class="fu">savePlpModel</span>(gbmResults<span class="sc">$</span>model, <span class="at">dirPath =</span> <span class="st">&quot;model&quot;</span>)</span></code></pre></div>
<p>モデルを読み込むには：</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="PatientLevelPrediction.html#cb127-1" tabindex="-1"></a>plpModel <span class="ot">&lt;-</span> <span class="fu">loadPlpModel</span>(<span class="st">&quot;model&quot;</span>)</span></code></pre></div>
<p>完全なアウトカム構造を保存することもできます：</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="PatientLevelPrediction.html#cb128-1" tabindex="-1"></a><span class="fu">savePlpResult</span>(gbmResults, <span class="at">location =</span> <span class="st">&quot;gbmResults&quot;</span>)</span></code></pre></div>
<p>完全なアウトカム構造を読み込むには：</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="PatientLevelPrediction.html#cb129-1" tabindex="-1"></a>gbmResults <span class="ot">&lt;-</span> <span class="fu">loadPlpResult</span>(<span class="st">&quot;gbmResults&quot;</span>)</span></code></pre></div>
</div>
<div id="内部バリデーション" class="section level3 hasAnchor" number="13.7.5">
<h3><span class="header-section-number">13.7.5</span> 内部バリデーション<a href="PatientLevelPrediction.html#内部バリデーション" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>学習を実行すると、<code>runPlp</code>関数は学習済みのモデルと、学習用/テスト用セットにおけるモデルの評価を返します。<code>viewPlp(runPlp = gbmResults)</code>を実行すると、結果をインタラクティブに表示できます。これにより、Shiny Appが開き、フレームワークによって作成されたすべてのパフォーマンス指標（インタラクティブなプロットを含む）を表示できます（Shiny Applicationのセクションの図 <a href="PatientLevelPrediction.html#fig:shinySummary">13.16</a>を参照）。</p>
<p>すべての評価プロットをフォルダーに生成して保存するには、次のコードを実行します：</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="PatientLevelPrediction.html#cb130-1" tabindex="-1"></a><span class="fu">plotPlp</span>(gbmResults, <span class="st">&quot;plots&quot;</span>)</span></code></pre></div>
<p>プロットの詳細については、セクション <a href="PatientLevelPrediction.html#performance">13.4.2</a>を参照ください。</p>
</div>
<div id="外部バリデーション" class="section level3 hasAnchor" number="13.7.6">
<h3><span class="header-section-number">13.7.6</span> 外部バリデーション<a href="PatientLevelPrediction.html#外部バリデーション" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>常に外部バリデーションを行うことをお勧めします。すなわち、最終モデルを可能な限り多くの新しいデータセットに適用し、そのパフォーマンスを評価します。ここでは、データ抽出がすでに2番目のデータベース上で実行され、<code>newData</code>フォルダに格納されていると仮定します。以前にフィッティングしたモデルを<code>model</code>フォルダーから読込みます：</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="PatientLevelPrediction.html#cb131-1" tabindex="-1"></a><span class="co"># トレーニング済みモデルをロード</span></span>
<span id="cb131-2"><a href="PatientLevelPrediction.html#cb131-2" tabindex="-1"></a>plpModel <span class="ot">&lt;-</span> <span class="fu">loadPlpModel</span>(<span class="st">&quot;model&quot;</span>)</span>
<span id="cb131-3"><a href="PatientLevelPrediction.html#cb131-3" tabindex="-1"></a></span>
<span id="cb131-4"><a href="PatientLevelPrediction.html#cb131-4" tabindex="-1"></a><span class="co"># 新しいplpDataをロードし、集団を作成</span></span>
<span id="cb131-5"><a href="PatientLevelPrediction.html#cb131-5" tabindex="-1"></a>plpData <span class="ot">&lt;-</span> <span class="fu">loadPlpData</span>(<span class="st">&quot;newData&quot;</span>)</span>
<span id="cb131-6"><a href="PatientLevelPrediction.html#cb131-6" tabindex="-1"></a></span>
<span id="cb131-7"><a href="PatientLevelPrediction.html#cb131-7" tabindex="-1"></a>population <span class="ot">&lt;-</span> <span class="fu">createStudyPopulation</span>(<span class="at">plpData =</span> plpData,</span>
<span id="cb131-8"><a href="PatientLevelPrediction.html#cb131-8" tabindex="-1"></a>                                    <span class="at">outcomeId =</span> <span class="dv">2</span>,</span>
<span id="cb131-9"><a href="PatientLevelPrediction.html#cb131-9" tabindex="-1"></a>                                    <span class="at">washoutPeriod =</span> <span class="dv">364</span>,</span>
<span id="cb131-10"><a href="PatientLevelPrediction.html#cb131-10" tabindex="-1"></a>                                    <span class="at">firstExposureOnly =</span> <span class="cn">FALSE</span>,</span>
<span id="cb131-11"><a href="PatientLevelPrediction.html#cb131-11" tabindex="-1"></a>                                    <span class="at">removeSubjectsWithPriorOutcome =</span> <span class="cn">TRUE</span>,</span>
<span id="cb131-12"><a href="PatientLevelPrediction.html#cb131-12" tabindex="-1"></a>                                    <span class="at">priorOutcomeLookback =</span> <span class="dv">9999</span>,</span>
<span id="cb131-13"><a href="PatientLevelPrediction.html#cb131-13" tabindex="-1"></a>                                    <span class="at">riskWindowStart =</span> <span class="dv">1</span>,</span>
<span id="cb131-14"><a href="PatientLevelPrediction.html#cb131-14" tabindex="-1"></a>                                    <span class="at">riskWindowEnd =</span> <span class="dv">365</span>,</span>
<span id="cb131-15"><a href="PatientLevelPrediction.html#cb131-15" tabindex="-1"></a>                                    <span class="at">addExposureDaysToStart =</span> <span class="cn">FALSE</span>,</span>
<span id="cb131-16"><a href="PatientLevelPrediction.html#cb131-16" tabindex="-1"></a>                                    <span class="at">addExposureDaysToEnd =</span> <span class="cn">FALSE</span>,</span>
<span id="cb131-17"><a href="PatientLevelPrediction.html#cb131-17" tabindex="-1"></a>                                    <span class="at">minTimeAtRisk =</span> <span class="dv">364</span>,</span>
<span id="cb131-18"><a href="PatientLevelPrediction.html#cb131-18" tabindex="-1"></a>                                    <span class="at">requireTimeAtRisk =</span> <span class="cn">TRUE</span>,</span>
<span id="cb131-19"><a href="PatientLevelPrediction.html#cb131-19" tabindex="-1"></a>                                    <span class="at">includeAllOutcomes =</span> <span class="cn">TRUE</span></span>
<span id="cb131-20"><a href="PatientLevelPrediction.html#cb131-20" tabindex="-1"></a>)</span>
<span id="cb131-21"><a href="PatientLevelPrediction.html#cb131-21" tabindex="-1"></a></span>
<span id="cb131-22"><a href="PatientLevelPrediction.html#cb131-22" tabindex="-1"></a><span class="co"># apply the trained model on the new data</span></span>
<span id="cb131-23"><a href="PatientLevelPrediction.html#cb131-23" tabindex="-1"></a>validationResults <span class="ot">&lt;-</span> <span class="fu">applyModel</span>(population, plpData, plpModel)</span></code></pre></div>
<p>さらに簡単にできるように、必要なデータの抽出も行う外部検証を行うための <code>externalValidatePlp</code> 関数も提供しています。 <code>result &lt;- runPlp(...)</code> を実行したと仮定すると、モデルに必要なデータを抽出して、新しいデータで評価することができます。検証対象集団が ID 1 と 2 のテーブル <code>mainschema.dob.cohort</code> にあり、CDM データがスキーマ <code>cdmschema.dob</code> にあると仮定すると：</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="PatientLevelPrediction.html#cb132-1" tabindex="-1"></a>valResult <span class="ot">&lt;-</span> <span class="fu">externalValidatePlp</span>(</span>
<span id="cb132-2"><a href="PatientLevelPrediction.html#cb132-2" tabindex="-1"></a>    <span class="at">plpResult =</span> result,</span>
<span id="cb132-3"><a href="PatientLevelPrediction.html#cb132-3" tabindex="-1"></a>    <span class="at">connectionDetails =</span> connectionDetails,</span>
<span id="cb132-4"><a href="PatientLevelPrediction.html#cb132-4" tabindex="-1"></a>    <span class="at">validationSchemaTarget =</span> <span class="st">&#39;mainschema.dob&#39;</span>,</span>
<span id="cb132-5"><a href="PatientLevelPrediction.html#cb132-5" tabindex="-1"></a>    <span class="at">validationSchemaOutcome =</span> <span class="st">&#39;mainschema.dob&#39;</span>,</span>
<span id="cb132-6"><a href="PatientLevelPrediction.html#cb132-6" tabindex="-1"></a>    <span class="at">validationSchemaCdm =</span> <span class="st">&#39;cdmschema.dbo&#39;</span>,</span>
<span id="cb132-7"><a href="PatientLevelPrediction.html#cb132-7" tabindex="-1"></a>    <span class="at">databaseNames =</span> <span class="st">&#39;new database&#39;</span>,</span>
<span id="cb132-8"><a href="PatientLevelPrediction.html#cb132-8" tabindex="-1"></a>    <span class="at">validationTableTarget =</span> <span class="st">&#39;cohort&#39;</span>,</span>
<span id="cb132-9"><a href="PatientLevelPrediction.html#cb132-9" tabindex="-1"></a>    <span class="at">validationTableOutcome =</span> <span class="st">&#39;cohort&#39;</span>,</span>
<span id="cb132-10"><a href="PatientLevelPrediction.html#cb132-10" tabindex="-1"></a>    <span class="at">validationIdTarget =</span> <span class="dv">1</span>,</span>
<span id="cb132-11"><a href="PatientLevelPrediction.html#cb132-11" tabindex="-1"></a>    <span class="at">validationIdOutcome =</span> <span class="dv">2</span></span>
<span id="cb132-12"><a href="PatientLevelPrediction.html#cb132-12" tabindex="-1"></a>)</span></code></pre></div>
<p>モデルを検証する複数のデータベースがある場合、以下を実行できます：</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="PatientLevelPrediction.html#cb133-1" tabindex="-1"></a>valResults <span class="ot">&lt;-</span> <span class="fu">externalValidatePlp</span>(</span>
<span id="cb133-2"><a href="PatientLevelPrediction.html#cb133-2" tabindex="-1"></a>    <span class="at">plpResult =</span> result,</span>
<span id="cb133-3"><a href="PatientLevelPrediction.html#cb133-3" tabindex="-1"></a>    <span class="at">connectionDetails =</span> connectionDetails,</span>
<span id="cb133-4"><a href="PatientLevelPrediction.html#cb133-4" tabindex="-1"></a>    <span class="at">validationSchemaTarget =</span> <span class="fu">list</span>(<span class="st">&#39;mainschema.dob&#39;</span>,</span>
<span id="cb133-5"><a href="PatientLevelPrediction.html#cb133-5" tabindex="-1"></a>                                <span class="st">&#39;difschema.dob&#39;</span>,</span>
<span id="cb133-6"><a href="PatientLevelPrediction.html#cb133-6" tabindex="-1"></a>                                <span class="st">&#39;anotherschema.dob&#39;</span>),</span>
<span id="cb133-7"><a href="PatientLevelPrediction.html#cb133-7" tabindex="-1"></a>    <span class="at">validationSchemaOutcome =</span> <span class="fu">list</span>(<span class="st">&#39;mainschema.dob&#39;</span>,</span>
<span id="cb133-8"><a href="PatientLevelPrediction.html#cb133-8" tabindex="-1"></a>                                 <span class="st">&#39;difschema.dob&#39;</span>,</span>
<span id="cb133-9"><a href="PatientLevelPrediction.html#cb133-9" tabindex="-1"></a>                                 <span class="st">&#39;anotherschema.dob&#39;</span>),</span>
<span id="cb133-10"><a href="PatientLevelPrediction.html#cb133-10" tabindex="-1"></a>    <span class="at">validationSchemaCdm =</span> <span class="fu">list</span>(<span class="st">&#39;cdms1chema.dbo&#39;</span>,</span>
<span id="cb133-11"><a href="PatientLevelPrediction.html#cb133-11" tabindex="-1"></a>                             <span class="st">&#39;cdm2schema.dbo&#39;</span>,</span>
<span id="cb133-12"><a href="PatientLevelPrediction.html#cb133-12" tabindex="-1"></a>                             <span class="st">&#39;cdm3schema.dbo&#39;</span>),</span>
<span id="cb133-13"><a href="PatientLevelPrediction.html#cb133-13" tabindex="-1"></a>    <span class="at">databaseNames =</span> <span class="fu">list</span>(<span class="st">&#39;new database 1&#39;</span>,</span>
<span id="cb133-14"><a href="PatientLevelPrediction.html#cb133-14" tabindex="-1"></a>                       <span class="st">&#39;new database 2&#39;</span>,</span>
<span id="cb133-15"><a href="PatientLevelPrediction.html#cb133-15" tabindex="-1"></a>                       <span class="st">&#39;new database 3&#39;</span>),</span>
<span id="cb133-16"><a href="PatientLevelPrediction.html#cb133-16" tabindex="-1"></a>    <span class="at">validationTableTarget =</span> <span class="fu">list</span>(<span class="st">&#39;cohort1&#39;</span>,</span>
<span id="cb133-17"><a href="PatientLevelPrediction.html#cb133-17" tabindex="-1"></a>                               <span class="st">&#39;cohort2&#39;</span>,</span>
<span id="cb133-18"><a href="PatientLevelPrediction.html#cb133-18" tabindex="-1"></a>                               <span class="st">&#39;cohort3&#39;</span>),</span>
<span id="cb133-19"><a href="PatientLevelPrediction.html#cb133-19" tabindex="-1"></a>    <span class="at">validationTableOutcome =</span> <span class="fu">list</span>(<span class="st">&#39;cohort1&#39;</span>,</span>
<span id="cb133-20"><a href="PatientLevelPrediction.html#cb133-20" tabindex="-1"></a>                                <span class="st">&#39;cohort2&#39;</span>,</span>
<span id="cb133-21"><a href="PatientLevelPrediction.html#cb133-21" tabindex="-1"></a>                                <span class="st">&#39;cohort3&#39;</span>),</span>
<span id="cb133-22"><a href="PatientLevelPrediction.html#cb133-22" tabindex="-1"></a>    <span class="at">validationIdTarget =</span> <span class="fu">list</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>),</span>
<span id="cb133-23"><a href="PatientLevelPrediction.html#cb133-23" tabindex="-1"></a>    <span class="at">validationIdOutcome =</span> <span class="fu">list</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>)</span>
<span id="cb133-24"><a href="PatientLevelPrediction.html#cb133-24" tabindex="-1"></a>)</span></code></pre></div>
</div>
</div>
<div id="結果の公表" class="section level2 hasAnchor" number="13.8">
<h2><span class="header-section-number">13.8</span> 結果の公表<a href="PatientLevelPrediction.html#結果の公表" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="モデル性能" class="section level3 hasAnchor" number="13.8.1">
<h3><span class="header-section-number">13.8.1</span> モデル性能<a href="PatientLevelPrediction.html#モデル性能" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>予測モデルのパフォーマンスを調査するには、<code>viewPlp</code>関数が最も簡単です。この関数には、結果オブジェクトを入力として指定する必要があります。Rでモデルを開発している場合は、<code>runPLp</code>の結果を入力として使用できます。 ATLASで生成されたスタディパッケージを使用している場合は、モデルの1つを読み込む必要があります（この例では、Analysis_1を読み込みます）。</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="PatientLevelPrediction.html#cb134-1" tabindex="-1"></a>plpResult <span class="ot">&lt;-</span> <span class="fu">loadPlpResult</span>(<span class="fu">file.path</span>(outputFolder,</span>
<span id="cb134-2"><a href="PatientLevelPrediction.html#cb134-2" tabindex="-1"></a>                                     <span class="st">&#39;Analysis_1&#39;</span>,</span>
<span id="cb134-3"><a href="PatientLevelPrediction.html#cb134-3" tabindex="-1"></a>                                     <span class="st">&#39;plpResult&#39;</span>))</span></code></pre></div>
<p>ここで「Analysis_1」は先に特定した分析に対応しています。</p>
<p>次に、以下を実行してShinyアプリケーションを起動します。</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="PatientLevelPrediction.html#cb135-1" tabindex="-1"></a><span class="fu">viewPlp</span>(plpResult)</span></code></pre></div>
<p>Shinyアプリケーションはテストセットとトレインセットの性能指標の要約から始まります（図 <a href="PatientLevelPrediction.html#fig:shinySummary">13.16</a> 参照）。結果を見ると、トレーニングセットの AUC は0.78であり、テストセットではこれが 0.74に低下しています。テストセットの AUC の方がより正確な指標です。全体的には、このモデルはACE阻害薬の新規ユーザーで結果がどうなるかを予測できそうですが、トレーニングセットのパフォーマンスがテストセットよりも高いことから、やや過適合しているようです。ROC プロットは図 <a href="PatientLevelPrediction.html#fig:shinyROC">13.17</a>に示されています。</p>
<div class="figure"><span style="display:block;" id="fig:shinySummary"></span>
<img src="images/PatientLevelPrediction/shinysummary.png" alt="Shinyアプリケーションにおける評価統計の要約" width="100%" />
<p class="caption">
図 13.16: Shinyアプリケーションにおける評価統計の要約
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyROC"></span>
<img src="images/PatientLevelPrediction/shiny/singleShiny/singleShinyRoc.png" alt="ROCプロット" width="100%" />
<p class="caption">
図 13.17: ROCプロット
</p>
</div>
<p>図 <a href="PatientLevelPrediction.html#fig:shinyCal">13.18</a> のキャリブレーションプロットでは、一般的に観測されたリスクと予測されたリスクが一致していることが、点が対角線付近に位置していることから分かります。しかし、図 <a href="PatientLevelPrediction.html#fig:shinyDemo">13.19</a> の人口統計学的キャリブレーションプロットでは、40歳未満の患者については、青線（予測リスク）が赤線（観測リスク）と異なっていることから、モデルのキャリブレーションがうまくいっていないことが分かります。これは、40歳未満の患者をターゲット集団から除外する必要があることを示しているのかもしれません（若い患者の観察されたリスクはほぼゼロだからです）。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyCal"></span>
<img src="images/PatientLevelPrediction/shiny/singleShiny/singleShinyCal.png" alt="モデルのキャリブレーション" width="100%" />
<p class="caption">
図 13.18: モデルのキャリブレーション
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyDemo"></span>
<img src="images/PatientLevelPrediction/shiny/singleShiny/singleShinyDemo.png" alt="モデルの人口統計学的キャリブレーション" width="100%" />
<p class="caption">
図 13.19: モデルの人口統計学的キャリブレーション
</p>
</div>
<p>最後に、適格基準に基づくラベル付きデータからの患者の脱落を示すattritionプロットがあります（図 <a href="PatientLevelPrediction.html#fig:shinyAtt">13.20</a>参照）。このプロットは、リスク期間（1年間の追跡調査）全体にわたって観察されなかったために、対象集団の大部分を失ったことを示しています。興味深いことに、結果の患者の多くは、リスク期間全体を欠損していませんでした。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyAtt"></span>
<img src="images/PatientLevelPrediction/shiny/singleShiny/singleShinyAtt.png" alt="予測問題におけるattritionプロット" width="100%" />
<p class="caption">
図 13.20: 予測問題におけるattritionプロット
</p>
</div>
</div>
<div id="モデルの比較" class="section level3 hasAnchor" number="13.8.2">
<h3><span class="header-section-number">13.8.2</span> モデルの比較<a href="PatientLevelPrediction.html#モデルの比較" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ATLASによって生成されたスタディパッケージでは、さまざまな予測問題に対して、多くの異なる予測モデルを生成および評価することができます。そのため、特にスタディパッケージによって生成された出力用に、複数のモデルを表示するための追加のShinyアプリが開発されました。このアプリを起動するには、<code>viewMultiplePlp(outputFolder)</code>を実行します。ここで<code>outputFolder</code>は、<code>execute</code>コマンドを実行する際に指定した分析結果を含むパスです（例えば、「Analysis_1」という名前のサブフォルダを含む必要があります）。</p>
<div id="モデルの要約と設定の表示" class="section level4 unnumbered hasAnchor">
<h4>モデルの要約と設定の表示<a href="PatientLevelPrediction.html#モデルの要約と設定の表示" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>インタラクティブなShinyアプリは、図 <a href="PatientLevelPrediction.html#fig:multiShinySummary">13.21</a>に示す要約ページで起動します。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:multiShinySummary"></span>
<img src="images/PatientLevelPrediction/shiny/shinyFilter.png" alt="各モデルの訓練に使用されたホールドアウトセットの主要な性能指標を含むShinyの要約ページ" width="100%" />
<p class="caption">
図 13.21: 各モデルの訓練に使用されたホールドアウトセットの主要な性能指標を含むShinyの要約ページ
</p>
</div>
<p>この要約ページの表には以下が含まれています：</p>
<ul>
<li>モデルに関する基本情報（例：データベース情報、分類器タイプ、リスク期間設定、対象母集団、アウトカム名）</li>
<li>ホールドアウトｎ対象母集団の数とアウトカム発生率</li>
<li>判別指標：AUC、AUPRC</li>
</ul>
<p>表の左側にはフィルターオプションがあり、開発/検証データベース、モデルの種類、リスク期間の設定および/または対象とするコホートを指定できます。例えば、対象集団「高血圧症の第一選択の単剤療法としてのACE阻害薬の新規ユーザー」に対応するモデルを選択するには、「Target Cohort」オプションでこれを選択します。</p>
<p>モデルを詳細に調査するには、該当する行をクリックします。選択された行はハイライト表示されます。行が選択された状態で「Model Settings」タブをクリックしてモデルを開発する際に使用した設定を調べることができます。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyModel"></span>
<img src="images/PatientLevelPrediction/shiny/shinyModel.png" alt="モデルを開発する際に使用した設定を表示する" width="100%" />
<p class="caption">
図 13.22: モデルを開発する際に使用した設定を表示する
</p>
</div>
<p>同様に、他のタブでモデルを生成するために使用された母集団および共変量の設定を調べることもできます。</p>
</div>
<div id="モデル性能の表示" class="section level4 unnumbered hasAnchor">
<h4>モデル性能の表示<a href="PatientLevelPrediction.html#モデル性能の表示" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>モデル行が選択されると、モデル性能も表示できます。<img src="images/PatientLevelPrediction/performance.png" /> をクリックして閾値の性能評価の要約を表示できます（図 <a href="PatientLevelPrediction.html#fig:shinyPerformanceSum">13.23</a>参照）。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyPerformanceSum"></span>
<img src="images/PatientLevelPrediction/shiny/shinyPerformanceSum.png" alt="特定の閾値における性能評価の要約" width="100%" />
<p class="caption">
図 13.23: 特定の閾値における性能評価の要約
</p>
</div>
<p>このサマリー表示は標準形式で選択された予測問題を表示し、閾値セレクタと陽性的中率（PPV）、陰性的中率（NPV）、感度、特異度（セクション <a href="PatientLevelPrediction.html#performance">13.4.2</a> を参照）などの重要な閾値ベースのメトリクスを含むダッシュボードを表示します。図 <a href="PatientLevelPrediction.html#fig:shinyPerformanceSum">13.23</a> では、感度が83.4%（翌年に結果が判明する患者の 83.4% が0.00482以上のリスクを持つ）で、PPV が 1.2%（0.00482以上のリスクを持つ患者の 1.2%が翌年に結果が判明する）であることが示されています。1年以内のアウトカム発生率が0.741%であるため、0.00482以上のリスクを持つ患者を特定すると、集団平均リスクのほぼ2倍のリスクを持つ患者サブグループが見つかります。スライダーを使用して閾値を調整し、他の値でのパフォーマンスを表示することができます。</p>
<p>モデル全体の識別力を確認するには、「Discrimination」タブをクリックしてROCプロット、精度-再現プロット、分布プロットを表示します。プロットの線は選択された閾値ポイントに対応しています。図 <a href="PatientLevelPrediction.html#fig:shinyPerformanceDisc">13.24</a> はROCおよび精度-再現プロットを示しています。ROCプロットは、モデルが１年以内にアウトカムが発生する人と発生しない人を区別できることを示しています。しかし、精度-再現プロットを見ると性能はそれほど印象的でないように見えます。なぜなら、結果の発生率が低いということは、偽陽性率が高いことを意味するからです。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyPerformanceDisc"></span>
<img src="images/PatientLevelPrediction/shiny/shinyPerformanceDisc.png" alt="ROCおよび精度-再現プロットを使用してモデルの判別能力全体を評価する" width="100%" />
<p class="caption">
図 13.24: ROCおよび精度-再現プロットを使用してモデルの判別能力全体を評価する
</p>
</div>
<p>図 <a href="PatientLevelPrediction.html#fig:shinyPerformanceDist">13.25</a> は予測リスクおよび選好スコア分布を示しています。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyPerformanceDist"></span>
<img src="images/PatientLevelPrediction/shiny/shinyPerformanceDist.png" alt="アウトカム有およびアoutingの患者に対する予測リスク分布。重なりが多いほど、判別が悪化します。" width="100%" />
<p class="caption">
図 13.25: アウトカム有およびアoutingの患者に対する予測リスク分布。重なりが多いほど、判別が悪化します。
</p>
</div>
<p>最後に、「Calibration」タブをクリックしてモデルのキャリブレーションを確認することもできます。これにより、図 <a href="PatientLevelPrediction.html#fig:shinyPerformanceCal">13.26</a> に示されるキャリブレーションプロットおよび人口統計学的キャリブレーションが表示されます。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyPerformanceCal"></span>
<img src="images/PatientLevelPrediction/shiny/shinyPerformanceCal.png" alt="リスク層別キャリブレーションおよび人口統計学的キャリブレーション" width="100%" />
<p class="caption">
図 13.26: リスク層別キャリブレーションおよび人口統計学的キャリブレーション
</p>
</div>
<p>1年以内にアウトカムを経験したグループの予測リスクと観察されたアウトカムの割合が一致しているように見えるので、モデルはよくキャリブレーションされています。興味深いことに、人口統計学的キャリブレーションは、若年患者の場合、予測されたリスクが観察されたリスクよりも高いことを示しています。逆に80歳以上の患者の場合、モデルは観察されたリスクよりも低いリスクを予測しています。これは、若年および高齢者のために別々のモデルを開発する必要があることを示唆しているかもしれません。</p>
</div>
<div id="モデルの表示" class="section level4 unnumbered hasAnchor">
<h4>モデルの表示<a href="PatientLevelPrediction.html#モデルの表示" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>最終モデルを検査するには、左側のメニューから<img src="images/PatientLevelPrediction/modelButton.png" />オプションを選択します。これにより、図 <a href="PatientLevelPrediction.html#fig:shinyModelPlots">13.27</a> に示すモデル内の各変数のプロットと図 <a href="PatientLevelPrediction.html#fig:shinyModelTable">13.28</a> に示すすべての候補の共変量を要約するテーブルが表示されます。変数プロットはバイナリ変数と連続変数に分かれています。X軸はアウトカムがない患者の中での有病率/平均値、Y軸はアウトカムがある患者の中での有病率/平均値です。従って、変数の点が対角線の上にある場合、その変数はアウトカムがある患者の方が一般的であり、点が対角線の下にある場合、その変数はアウトカムがない患者の方が一般的です。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyModelPlots"></span>
<img src="images/PatientLevelPrediction/shiny/shinyModelPlots.png" alt="モデル要約プロット。各点はモデルに含まれる変数に対応します。" width="100%" />
<p class="caption">
図 13.27: モデル要約プロット。各点はモデルに含まれる変数に対応します。
</p>
</div>
<p>図 <a href="PatientLevelPrediction.html#fig:shinyModelTable">13.28</a>に示すテーブルでは、すべての候補の共変量の名前、値（一般線形モデルを使用する場合は係数、その他の場合は変数の重要性）、アウトカム平均（アウトカムがある患者の平均値）、非アウトカム平均（アウトカムがない患者の平均値）が表示されます。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:shinyModelTable"></span>
<img src="images/PatientLevelPrediction/shiny/shinyModelTable.png" alt="モデル詳細テーブル" width="100%" />
<p class="caption">
図 13.28: モデル詳細テーブル
</p>
</div>

<div class="rmdimportant">
<p>予測モデルは因果モデルではなく、予測変数を原因と誤解しないようにしてください。図 <a href="PatientLevelPrediction.html#fig:shinyModelTable">13.28</a> のいずれかの変数を変更することでアウトカムのリスクが影響を受ける保証はありません。</p>
</div>
</div>
</div>
</div>
<div id="患者レベルの予測に関する追加の機能" class="section level2 hasAnchor" number="13.9">
<h2><span class="header-section-number">13.9</span> 患者レベルの予測に関する追加の機能<a href="PatientLevelPrediction.html#患者レベルの予測に関する追加の機能" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="学術誌論文の生成" class="section level3 hasAnchor" number="13.9.1">
<h3><span class="header-section-number">13.9.1</span> 学術誌論文の生成<a href="PatientLevelPrediction.html#学術誌論文の生成" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>自動的にワードドキュメントを生成する機能を追加しました。このドキュメントは学術誌の草稿として利用でき、多くの生成された研究の詳細とアウトカムを含みます。外部検証を行った場合、そのアウトカムも追加することができます。また、ターゲット集団の多くの共変量に関するデータを含む 「Table 1」を任意で追加することもできます。この機能を実行することで学術誌の草稿を作成できます：</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="PatientLevelPrediction.html#cb136-1" tabindex="-1"></a> <span class="fu">createPlpJournalDocument</span>(<span class="at">plpResult =</span> <span class="sc">&lt;</span>your plp results<span class="sc">&gt;</span>,</span>
<span id="cb136-2"><a href="PatientLevelPrediction.html#cb136-2" tabindex="-1"></a>             <span class="at">plpValidation =</span> <span class="sc">&lt;</span>your validation results<span class="sc">&gt;</span>,</span>
<span id="cb136-3"><a href="PatientLevelPrediction.html#cb136-3" tabindex="-1"></a>             <span class="at">plpData =</span> <span class="sc">&lt;</span>your plp data<span class="sc">&gt;</span>,</span>
<span id="cb136-4"><a href="PatientLevelPrediction.html#cb136-4" tabindex="-1"></a>             <span class="at">targetName =</span> <span class="st">&quot;&lt;target population&gt;&quot;</span>,</span>
<span id="cb136-5"><a href="PatientLevelPrediction.html#cb136-5" tabindex="-1"></a>             <span class="at">outcomeName =</span> <span class="st">&quot;&lt;outcome&gt;&quot;</span>,</span>
<span id="cb136-6"><a href="PatientLevelPrediction.html#cb136-6" tabindex="-1"></a>             <span class="at">table1 =</span> F,</span>
<span id="cb136-7"><a href="PatientLevelPrediction.html#cb136-7" tabindex="-1"></a>             <span class="at">connectionDetails =</span> <span class="cn">NULL</span>,</span>
<span id="cb136-8"><a href="PatientLevelPrediction.html#cb136-8" tabindex="-1"></a>             <span class="at">includeTrain =</span> <span class="cn">FALSE</span>,</span>
<span id="cb136-9"><a href="PatientLevelPrediction.html#cb136-9" tabindex="-1"></a>             <span class="at">includeTest =</span> <span class="cn">TRUE</span>,</span>
<span id="cb136-10"><a href="PatientLevelPrediction.html#cb136-10" tabindex="-1"></a>             <span class="at">includePredictionPicture =</span> <span class="cn">TRUE</span>,</span>
<span id="cb136-11"><a href="PatientLevelPrediction.html#cb136-11" tabindex="-1"></a>             <span class="at">includeAttritionPlot =</span> <span class="cn">TRUE</span>,</span>
<span id="cb136-12"><a href="PatientLevelPrediction.html#cb136-12" tabindex="-1"></a>             <span class="at">outputLocation =</span> <span class="st">&quot;&lt;your location&gt;&quot;</span>)</span></code></pre></div>
<p>詳細は関数のヘルプページを参照してください。</p>
</div>
</div>
<div id="まとめ-10" class="section level2 hasAnchor" number="13.10">
<h2><span class="header-section-number">13.10</span> まとめ<a href="PatientLevelPrediction.html#まとめ-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>

<div class="rmdsummary">
<ul>
<li><p>患者レベルの予測は、過去のデータを使用して将来の出来事を予測するモデルを開発することを目的としています。</p></li>
<li><p>モデル開発に最適な機械学習アルゴリズムの選択は経験的な問題であり、手元の問題とデータによって決定されるべきです。</p></li>
<li><p>PatientLevelPredictionパッケージは、OMOP CDMに格納されたデータを使用した予測モデルの開発と検証のためのベストプラクティスを実装しています。</p></li>
<li><p>モデルとその性能指標の公表はインタラクティブなダッシュボードを通じて実装されています。</p></li>
<li><p>OHDSIの予測フレームワークは、臨床応用の前提条件である予測モデルの大規模な外部検証を可能にします。</p></li>
</ul>
</div>
</div>
<div id="演習-8" class="section level2 hasAnchor" number="13.11">
<h2><span class="header-section-number">13.11</span> 演習<a href="PatientLevelPrediction.html#演習-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="前提条件-8" class="section level4 unnumbered hasAnchor">
<h4>前提条件<a href="PatientLevelPrediction.html#前提条件-8" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>これらの演習では、セクション <a href="OhdsiAnalyticsTools.html#installR">8.4.5</a> で説明されているように、R、R-Studio、およびJavaがインストールされていることを前提としています。また、<a href="https://ohdsi.github.io/SqlRender/">SqlRender</a>、<a href="https://ohdsi.github.io/DatabaseConnector/">DatabaseConnector</a>、<a href="https://ohdsi.github.io/Eunomia/">Eunomia</a>および<a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a>パッケージも必要です。これらは以下のコマンドでインストールできます：</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="PatientLevelPrediction.html#cb137-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;SqlRender&quot;</span>, <span class="st">&quot;DatabaseConnector&quot;</span>, <span class="st">&quot;remotes&quot;</span>))</span>
<span id="cb137-2"><a href="PatientLevelPrediction.html#cb137-2" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;ohdsi/Eunomia&quot;</span>, <span class="at">ref =</span> <span class="st">&quot;v1.0.0&quot;</span>)</span>
<span id="cb137-3"><a href="PatientLevelPrediction.html#cb137-3" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;ohdsi/PatientLevelPrediction&quot;</span>)</span></code></pre></div>
<p>Eunomiaパッケージは、ローカルのRセッション内で実行されるCDM内のシミュレーションデータセットを提供します。接続の詳細は、以下のようにして取得できます。：</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="PatientLevelPrediction.html#cb138-1" tabindex="-1"></a>connectionDetails <span class="ot">&lt;-</span> Eunomia<span class="sc">::</span><span class="fu">getEunomiaConnectionDetails</span>()</span></code></pre></div>
<p>CDMデータベースのスキーマは「main」です。これらの演習ではいくつかのコホートも使用します。Eunomiaパッケージの<code>createCohorts</code>関数は、これをCOHORTテーブルに作成します：</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="PatientLevelPrediction.html#cb139-1" tabindex="-1"></a>Eunomia<span class="sc">::</span><span class="fu">createCohorts</span>(connectionDetails)</span></code></pre></div>
</div>
<div id="問題定義-1" class="section level4 unnumbered hasAnchor">
<h4>問題定義<a href="PatientLevelPrediction.html#問題定義-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<blockquote>
<p>初めてNSAIDs（非ステロイド性抗炎症剤）を使用し始めた患者において、今後 1 年間に消化管（GI）出血を発症する患者を予測します。</p>
</blockquote>
<p>NSAIDの新規ユーザーコホートのCOHORT_DEFINITION_IDは4です。GI出血コホートのCOHORT_DEFINITION_IDは3です。</p>
<div class="exercise">
<p><span id="exr:exercisePlp1" class="exercise"><strong>演習 13.1  </strong></span>PatientLevelPrediction RパッケージのPatientLevelPredictionを使用して、予測に使用する共変量を定義し、CDMからPLPデータを抽出します。PLPデータの要約を作成します。</p>
</div>
<div class="exercise">
<p><span id="exr:exercisePlp2" class="exercise"><strong>演習 13.2  </strong></span>最終的な標本母集団を定義するために行う必要があるデザインの選択を再検討し、createStudyPopulation関数を使用してこれらを指定します。選択した内容が標本母集団の最終的なサイズにどのような影響を与えるでしょうか？</p>
</div>
<div class="exercise">
<p><span id="exr:exercisePlp3" class="exercise"><strong>演習 13.3  </strong></span>LASSOを使用して予測モデルを構築し、Shinyアプリケーションを使用してその性能を評価します。モデルの性能はどの程度ですか？</p>
</div>
<p>解答例は付録 <a href="SuggestedAnswers.html#Plpanswers">E.9</a>を参照のこと。</p>

</div>
</div>
</div>



<h3>参考文献<a href="参考文献.html#参考文献" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-byrd_2006" class="csl-entry">
Byrd, J. B., A. Adam, and N. J. Brown. 2006. <span>“<span class="nocase"><span>A</span>ngiotensin-converting enzyme inhibitor-associated angioedema</span>.”</span> <em>Immunol Allergy Clin North Am</em> 26 (4): 725–37.
</div>
<div id="ref-circardi_2004" class="csl-entry">
Cicardi, M., L. C. Zingale, L. Bergamaschini, and A. Agostoni. 2004. <span>“<span class="nocase"><span>A</span>ngioedema associated with angiotensin-converting enzyme inhibitor use: outcome after switching to a different treatment</span>.”</span> <em>Arch. Intern. Med.</em> 164 (8): 910–13.
</div>
<div id="ref-norman_2013" class="csl-entry">
Norman, J. L., W. L. Holmes, W. A. Bell, and S. W. Finks. 2013. <span>“<span class="nocase"><span>L</span>ife-threatening <span>A</span><span>C</span><span>E</span> inhibitor-induced angioedema after eleven years on lisinopril</span>.”</span> <em>J Pharm Pract</em> 26 (4): 382–88.
</div>
<div id="ref-mara_1996" class="csl-entry">
O’Mara, N. B., and E. M. O’Mara. 1996. <span>“<span class="nocase"><span>D</span>elayed onset of angioedema with angiotensin-converting enzyme inhibitors: case report and review of the literature</span>.”</span> <em>Pharmacotherapy</em> 16 (4): 675–79.
</div>
<div id="ref-reps2018" class="csl-entry">
Reps, J. M., M. J. Schuemie, M. A. Suchard, P. B. Ryan, and P. R. Rijnbeek. 2018. <span>“<span class="nocase"><span>D</span>esign and implementation of a standardized framework to generate and evaluate patient-level prediction models using observational healthcare data</span>.”</span> <em>Journal of the American Medical Informatics Association</em> 25 (8): 969–75. <a href="https://doi.org/10.1093/jamia/ocy032">https://doi.org/10.1093/jamia/ocy032</a>.
</div>
<div id="ref-thompson_1993" class="csl-entry">
Thompson, T., and M. A. Frable. 1993. <span>“<span class="nocase"><span>D</span>rug-induced, life-threatening angioedema revisited</span>.”</span> <em>Laryngoscope</em> 103 (1 Pt 1): 10–12.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="55">
<li id="fn55"><p><a href="https://www.equator-network.org/reporting-guidelines/tripod-statement/" class="uri">https://www.equator-network.org/reporting-guidelines/tripod-statement/</a><a href="PatientLevelPrediction.html#fnref55" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="PopulationLevelEstimation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="EvidenceQuality.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/OHDSI/TheBookOfOhdsiInJapanese/edit/main/PatientLevelPrediction.Rmd",
    "text": "エディション"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["TheBookOfOhdsi.pdf", "TheBookOfOhdsi.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
