<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>章 12 集団レベルの推定 | –翻訳作業中–　OHDSIの本</title>
  <meta name="description" content="The Observational Health Data Sciences and Informatics (OHDSI) についての本。OHDSIのコミュニティ、オープンスタンダードとオープンソースソフトウェアについて詳述しています。" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="章 12 集団レベルの推定 | –翻訳作業中–　OHDSIの本" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://ohdsi.github.io/TheBookOfOhdsiInJapanese/images/Cover/Cover.png" />
  <meta property="og:description" content="The Observational Health Data Sciences and Informatics (OHDSI) についての本。OHDSIのコミュニティ、オープンスタンダードとオープンソースソフトウェアについて詳述しています。" />
  <meta name="github-repo" content="OHDSI/TheBookOfOhdsiInJapanese" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="章 12 集団レベルの推定 | –翻訳作業中–　OHDSIの本" />
  
  <meta name="twitter:description" content="The Observational Health Data Sciences and Informatics (OHDSI) についての本。OHDSIのコミュニティ、オープンスタンダードとオープンソースソフトウェアについて詳述しています。" />
  <meta name="twitter:image" content="https://ohdsi.github.io/TheBookOfOhdsiInJapanese/images/Cover/Cover.png" />

<meta name="author" content="Observational Health Data Sciences and Informatics (OHDSI)" />


<meta name="date" content="2025-03-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="Characterization.html"/>
<link rel="next" href="PatientLevelPrediction.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104086677-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-104086677-2');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">OHDSIの本 </a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>序章</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#この本の目標"><i class="fa fa-check"></i>この本の目標</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#本書の構成"><i class="fa fa-check"></i>本書の構成</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#貢献者"><i class="fa fa-check"></i>貢献者</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ソフトウェアのバージョン"><i class="fa fa-check"></i>ソフトウェアのバージョン</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ライセンス"><i class="fa fa-check"></i>ライセンス</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#本書が作成された方法"><i class="fa fa-check"></i>本書が作成された方法</a></li>
</ul></li>
<li class="part"><span><b>I OHDSI コミュニティ</b></span></li>
<li class="chapter" data-level="1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html"><i class="fa fa-check"></i><b>1</b> OHDSI コミュニティ</a>
<ul>
<li class="chapter" data-level="1.1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#データからエビデンスへの旅"><i class="fa fa-check"></i><b>1.1</b> データからエビデンスへの旅</a></li>
<li class="chapter" data-level="1.2" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#観察医療アウトカムパートナーシップomop"><i class="fa fa-check"></i><b>1.2</b> 観察医療アウトカムパートナーシップ（OMOP）</a></li>
<li class="chapter" data-level="1.3" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#オープンサイエンスの協働組織としてのohdsi"><i class="fa fa-check"></i><b>1.3</b> オープンサイエンスの協働組織としてのOHDSI</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#我々の使命"><i class="fa fa-check"></i><b>1.3.1</b> 我々の使命</a></li>
<li class="chapter" data-level="1.3.2" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#我々のビジョン"><i class="fa fa-check"></i><b>1.3.2</b> 我々のビジョン</a></li>
<li class="chapter" data-level="1.3.3" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#我々の目標"><i class="fa fa-check"></i><b>1.3.3</b> 我々の目標</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#ohdsiの進展"><i class="fa fa-check"></i><b>1.4</b> OHDSIの進展</a></li>
<li class="chapter" data-level="1.5" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#ohdsiにおける協力"><i class="fa fa-check"></i><b>1.5</b> OHDSIにおける協力</a></li>
<li class="chapter" data-level="1.6" data-path="OhdsiCommunity.html"><a href="OhdsiCommunity.html#まとめ"><i class="fa fa-check"></i><b>1.6</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="WhereToBegin.html"><a href="WhereToBegin.html"><i class="fa fa-check"></i><b>2</b> どこから始めようか</a>
<ul>
<li class="chapter" data-level="2.1" data-path="WhereToBegin.html"><a href="WhereToBegin.html#旅に参加しよう"><i class="fa fa-check"></i><b>2.1</b> 旅に参加しよう</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiフォーラム"><i class="fa fa-check"></i><b>2.1.1</b> OHDSIフォーラム</a></li>
<li class="chapter" data-level="2.1.2" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiイベント"><i class="fa fa-check"></i><b>2.1.2</b> OHDSIイベント</a></li>
<li class="chapter" data-level="2.1.3" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiコミュニティコール"><i class="fa fa-check"></i><b>2.1.3</b> OHDSIコミュニティコール</a></li>
<li class="chapter" data-level="2.1.4" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiワークグループ"><i class="fa fa-check"></i><b>2.1.4</b> OHDSIワークグループ</a></li>
<li class="chapter" data-level="2.1.5" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsi地域支部"><i class="fa fa-check"></i><b>2.1.5</b> OHDSI地域支部</a></li>
<li class="chapter" data-level="2.1.6" data-path="WhereToBegin.html"><a href="WhereToBegin.html#ohdsiリサーチネットワーク"><i class="fa fa-check"></i><b>2.1.6</b> OHDSIリサーチネットワーク</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="WhereToBegin.html"><a href="WhereToBegin.html#どこにフィットするか"><i class="fa fa-check"></i><b>2.2</b> どこにフィットするか</a></li>
<li class="chapter" data-level="2.3" data-path="WhereToBegin.html"><a href="WhereToBegin.html#まとめ-1"><i class="fa fa-check"></i><b>2.3</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="OpenScience.html"><a href="OpenScience.html"><i class="fa fa-check"></i><b>3</b> オープンサイエンス</a>
<ul>
<li class="chapter" data-level="3.1" data-path="OpenScience.html"><a href="OpenScience.html#オープンサイエンス"><i class="fa fa-check"></i><b>3.1</b> オープンサイエンス</a></li>
<li class="chapter" data-level="3.2" data-path="OpenScience.html"><a href="OpenScience.html#オープンサイエンスの実践-the-study-a-thon"><i class="fa fa-check"></i><b>3.2</b> オープンサイエンスの実践: the Study-a-Thon</a></li>
<li class="chapter" data-level="3.3" data-path="OpenScience.html"><a href="OpenScience.html#オープンスタンダード"><i class="fa fa-check"></i><b>3.3</b> オープンスタンダード</a></li>
<li class="chapter" data-level="3.4" data-path="OpenScience.html"><a href="OpenScience.html#オープンソース"><i class="fa fa-check"></i><b>3.4</b> オープンソース</a></li>
<li class="chapter" data-level="3.5" data-path="OpenScience.html"><a href="OpenScience.html#オープンデータ"><i class="fa fa-check"></i><b>3.5</b> オープンデータ</a></li>
<li class="chapter" data-level="3.6" data-path="OpenScience.html"><a href="OpenScience.html#オープンな議論"><i class="fa fa-check"></i><b>3.6</b> オープンな議論</a></li>
<li class="chapter" data-level="3.7" data-path="OpenScience.html"><a href="OpenScience.html#ohdsiとfairガイディングプリンシプルズ"><i class="fa fa-check"></i><b>3.7</b> OHDSIとFAIRガイディングプリンシプルズ</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="OpenScience.html"><a href="OpenScience.html#序論"><i class="fa fa-check"></i><b>3.7.1</b> 序論</a></li>
<li class="chapter" data-level="3.7.2" data-path="OpenScience.html"><a href="OpenScience.html#検索可能性"><i class="fa fa-check"></i><b>3.7.2</b> 検索可能性</a></li>
<li class="chapter" data-level="3.7.3" data-path="OpenScience.html"><a href="OpenScience.html#アクセシビリティ"><i class="fa fa-check"></i><b>3.7.3</b> アクセシビリティ</a></li>
<li class="chapter" data-level="3.7.4" data-path="OpenScience.html"><a href="OpenScience.html#相互運用性"><i class="fa fa-check"></i><b>3.7.4</b> 相互運用性</a></li>
<li class="chapter" data-level="3.7.5" data-path="OpenScience.html"><a href="OpenScience.html#再利用性"><i class="fa fa-check"></i><b>3.7.5</b> 再利用性</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II 共通データモデル</b></span></li>
<li class="chapter" data-level="4" data-path="CommonDataModel.html"><a href="CommonDataModel.html"><i class="fa fa-check"></i><b>4</b> 共通データモデル</a>
<ul>
<li class="chapter" data-level="4.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#デザインの原則"><i class="fa fa-check"></i><b>4.1</b> デザインの原則</a></li>
<li class="chapter" data-level="4.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#データモデルの規約"><i class="fa fa-check"></i><b>4.2</b> データモデルの規約</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#model-Conv"><i class="fa fa-check"></i><b>4.2.1</b> モデルの一般的な規約</a></li>
<li class="chapter" data-level="4.2.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#スキーマの一般的な規約"><i class="fa fa-check"></i><b>4.2.2</b> スキーマの一般的な規約</a></li>
<li class="chapter" data-level="4.2.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#データテーブルの一般的な規約"><i class="fa fa-check"></i><b>4.2.3</b> データテーブルの一般的な規約</a></li>
<li class="chapter" data-level="4.2.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#domains"><i class="fa fa-check"></i><b>4.2.4</b> ドメインの一般的な規約</a></li>
<li class="chapter" data-level="4.2.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#コンテンツのコンセプトによる表現"><i class="fa fa-check"></i><b>4.2.5</b> コンテンツのコンセプトによる表現</a></li>
<li class="chapter" data-level="4.2.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#フィールドの一般的な命名規約"><i class="fa fa-check"></i><b>4.2.6</b> フィールドの一般的な命名規約</a></li>
<li class="chapter" data-level="4.2.7" data-path="CommonDataModel.html"><a href="CommonDataModel.html#concepts-Sources"><i class="fa fa-check"></i><b>4.2.7</b> コンセプトとソース値の違い</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#cdm標準化テーブル"><i class="fa fa-check"></i><b>4.3</b> CDM標準化テーブル</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#実行例-子宮内膜症"><i class="fa fa-check"></i><b>4.3.1</b> 実行例: 子宮内膜症</a></li>
<li class="chapter" data-level="4.3.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#person"><i class="fa fa-check"></i><b>4.3.2</b> PERSONテーブル</a></li>
<li class="chapter" data-level="4.3.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#observationPeriod"><i class="fa fa-check"></i><b>4.3.3</b> OBSERVATION_PERIODテーブル</a></li>
<li class="chapter" data-level="4.3.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#visitOccurrence"><i class="fa fa-check"></i><b>4.3.4</b> VISIT_OCCURRENCE</a></li>
<li class="chapter" data-level="4.3.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#conditionOccurrence"><i class="fa fa-check"></i><b>4.3.5</b> CONDITION_OCCURRENCE</a></li>
<li class="chapter" data-level="4.3.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#drugExposure"><i class="fa fa-check"></i><b>4.3.6</b> DRUG_EXPOSURE</a></li>
<li class="chapter" data-level="4.3.7" data-path="CommonDataModel.html"><a href="CommonDataModel.html#procedureOccurrence"><i class="fa fa-check"></i><b>4.3.7</b> PROCEDURE_OCCURRENCE</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#追加情報"><i class="fa fa-check"></i><b>4.4</b> 追加情報</a></li>
<li class="chapter" data-level="4.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#まとめ-2"><i class="fa fa-check"></i><b>4.5</b> まとめ</a></li>
<li class="chapter" data-level="4.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#演習"><i class="fa fa-check"></i><b>4.6</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html"><i class="fa fa-check"></i><b>5</b> 標準化ボキャブラリ</a>
<ul>
<li class="chapter" data-level="5.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#なぜボキャブラリが必要でなぜ標準化が必要なのか"><i class="fa fa-check"></i><b>5.1</b> なぜボキャブラリが必要で、なぜ標準化が必要なのか</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#標準化ボキャブラリの構築"><i class="fa fa-check"></i><b>5.1.1</b> 標準化ボキャブラリの構築</a></li>
<li class="chapter" data-level="5.1.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#accessVocabularies"><i class="fa fa-check"></i><b>5.1.2</b> 標準化ボキャブラリへのアクセス</a></li>
<li class="chapter" data-level="5.1.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#ボキャブラリの元-採用するか構築するか"><i class="fa fa-check"></i><b>5.1.3</b> ボキャブラリの元: 採用するか構築するか</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプト"><i class="fa fa-check"></i><b>5.2</b> コンセプト</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプトid"><i class="fa fa-check"></i><b>5.2.1</b> コンセプトID</a></li>
<li class="chapter" data-level="5.2.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプト名"><i class="fa fa-check"></i><b>5.2.2</b> コンセプト名</a></li>
<li class="chapter" data-level="5.2.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptDomains"><i class="fa fa-check"></i><b>5.2.3</b> ドメイン</a></li>
<li class="chapter" data-level="5.2.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#ボキャブラリ"><i class="fa fa-check"></i><b>5.2.4</b> ボキャブラリ</a></li>
<li class="chapter" data-level="5.2.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプトクラス"><i class="fa fa-check"></i><b>5.2.5</b> コンセプトクラス</a></li>
<li class="chapter" data-level="5.2.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#standardConcepts"><i class="fa fa-check"></i><b>5.2.6</b> 標準コンセプト</a></li>
<li class="chapter" data-level="5.2.7" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#非標準コンセプト"><i class="fa fa-check"></i><b>5.2.7</b> 非標準コンセプト</a></li>
<li class="chapter" data-level="5.2.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#分類コンセプト"><i class="fa fa-check"></i><b>5.2.8</b> 分類コンセプト</a></li>
<li class="chapter" data-level="5.2.9" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#コンセプトコード"><i class="fa fa-check"></i><b>5.2.9</b> コンセプトコード</a></li>
<li class="chapter" data-level="5.2.10" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptLifeCycle"><i class="fa fa-check"></i><b>5.2.10</b> ライフサイクル</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#関係"><i class="fa fa-check"></i><b>5.3</b> 関係</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptMapping"><i class="fa fa-check"></i><b>5.3.1</b> マッピング関係</a></li>
<li class="chapter" data-level="5.3.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#階層関係"><i class="fa fa-check"></i><b>5.3.2</b> 階層関係</a></li>
<li class="chapter" data-level="5.3.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#異なるボキャブラリーのコンセプト間の関係"><i class="fa fa-check"></i><b>5.3.3</b> 異なるボキャブラリーのコンセプト間の関係</a></li>
<li class="chapter" data-level="5.3.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#同一ボキャブラリーのコンセプト間の関係"><i class="fa fa-check"></i><b>5.3.4</b> 同一ボキャブラリーのコンセプト間の関係</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#conceptAncestor"><i class="fa fa-check"></i><b>5.4</b> 階層</a></li>
<li class="chapter" data-level="5.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#内部参照テーブル"><i class="fa fa-check"></i><b>5.5</b> 内部参照テーブル</a></li>
<li class="chapter" data-level="5.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#specialSituations"><i class="fa fa-check"></i><b>5.6</b> 特別な状況</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#性別"><i class="fa fa-check"></i><b>5.6.1</b> 性別</a></li>
<li class="chapter" data-level="5.6.2" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#人種と民族"><i class="fa fa-check"></i><b>5.6.2</b> 人種と民族</a></li>
<li class="chapter" data-level="5.6.3" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#診断コーディングシステムとomop条件"><i class="fa fa-check"></i><b>5.6.3</b> 診断コーディングシステムとOMOP条件</a></li>
<li class="chapter" data-level="5.6.4" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#処置コードシステム"><i class="fa fa-check"></i><b>5.6.4</b> 処置コードシステム</a></li>
<li class="chapter" data-level="5.6.5" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#医療機器"><i class="fa fa-check"></i><b>5.6.5</b> 医療機器</a></li>
<li class="chapter" data-level="5.6.6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#ビジットとサービス"><i class="fa fa-check"></i><b>5.6.6</b> ビジットとサービス</a></li>
<li class="chapter" data-level="5.6.7" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#医療提供者と専門分野"><i class="fa fa-check"></i><b>5.6.7</b> 医療提供者と専門分野</a></li>
<li class="chapter" data-level="5.6.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#特別な要件を持つ治療領域"><i class="fa fa-check"></i><b>5.6.8</b> 特別な要件を持つ治療領域</a></li>
<li class="chapter" data-level="5.6.9" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#rxNormExtension"><i class="fa fa-check"></i><b>5.6.9</b> 薬剤ドメインにおける標準コンセプト</a></li>
<li class="chapter" data-level="5.6.10" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#nullのバリエーション"><i class="fa fa-check"></i><b>5.6.10</b> NULLのバリエーション</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#まとめ-3"><i class="fa fa-check"></i><b>5.7</b> まとめ</a></li>
<li class="chapter" data-level="5.8" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html#演習-1"><i class="fa fa-check"></i><b>5.8</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html"><i class="fa fa-check"></i><b>6</b> ETL（抽出-変換-読込）</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#はじめに"><i class="fa fa-check"></i><b>6.1</b> はじめに</a></li>
<li class="chapter" data-level="6.2" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#ステップ-1-etlのデザイン"><i class="fa fa-check"></i><b>6.2</b> ステップ 1: ETLのデザイン</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#white-rabbit"><i class="fa fa-check"></i><b>6.2.1</b> White Rabbit</a></li>
<li class="chapter" data-level="6.2.2" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#rabbit-in-a-hat"><i class="fa fa-check"></i><b>6.2.2</b> Rabbit-In-a-Hat</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#ステップ2-コードマッピングの作成"><i class="fa fa-check"></i><b>6.3</b> ステップ2: コードマッピングの作成</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#usagi"><i class="fa fa-check"></i><b>6.3.1</b> Usagi</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#ステップ-3-etlの実装"><i class="fa fa-check"></i><b>6.4</b> ステップ 3: ETLの実装</a></li>
<li class="chapter" data-level="6.5" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#ステップ-4-品質管理"><i class="fa fa-check"></i><b>6.5</b> ステップ 4: 品質管理</a></li>
<li class="chapter" data-level="6.6" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#etlの規約とthemis"><i class="fa fa-check"></i><b>6.6</b> ETLの規約とTHEMIS</a></li>
<li class="chapter" data-level="6.7" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#CDMandETLMaintenance"><i class="fa fa-check"></i><b>6.7</b> CDMおよびETLのメンテナンス</a></li>
<li class="chapter" data-level="6.8" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#etlに関する最終的な考察"><i class="fa fa-check"></i><b>6.8</b> ETLに関する最終的な考察</a></li>
<li class="chapter" data-level="6.9" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#まとめ-4"><i class="fa fa-check"></i><b>6.9</b> まとめ</a></li>
<li class="chapter" data-level="6.10" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html#演習-2"><i class="fa fa-check"></i><b>6.10</b> 演習</a></li>
</ul></li>
<li class="part"><span><b>III データ解析</b></span></li>
<li class="chapter" data-level="7" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html"><i class="fa fa-check"></i><b>7</b> データ解析の使用例</a>
<ul>
<li class="chapter" data-level="7.1" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#特性評価"><i class="fa fa-check"></i><b>7.1</b> 特性評価</a></li>
<li class="chapter" data-level="7.2" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#集団レベルの推定"><i class="fa fa-check"></i><b>7.2</b> 集団レベルの推定</a></li>
<li class="chapter" data-level="7.3" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#患者レベルの予測"><i class="fa fa-check"></i><b>7.3</b> 患者レベルの予測</a></li>
<li class="chapter" data-level="7.4" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#高血圧症におけるユースケース"><i class="fa fa-check"></i><b>7.4</b> 高血圧症におけるユースケース</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#特性評価に関する問い"><i class="fa fa-check"></i><b>7.4.1</b> 特性評価に関する問い</a></li>
<li class="chapter" data-level="7.4.2" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#集団レベルの推定問題"><i class="fa fa-check"></i><b>7.4.2</b> 集団レベルの推定問題</a></li>
<li class="chapter" data-level="7.4.3" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#患者レベルの予測問題"><i class="fa fa-check"></i><b>7.4.3</b> 患者レベルの予測問題</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#観察研究の限界"><i class="fa fa-check"></i><b>7.5</b> 観察研究の限界</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#誤ったデータ"><i class="fa fa-check"></i><b>7.5.1</b> 誤ったデータ</a></li>
<li class="chapter" data-level="7.5.2" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#欠損データ"><i class="fa fa-check"></i><b>7.5.2</b> 欠損データ</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#まとめ-5"><i class="fa fa-check"></i><b>7.6</b> まとめ</a></li>
<li class="chapter" data-level="7.7" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#演習-3"><i class="fa fa-check"></i><b>7.7</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html"><i class="fa fa-check"></i><b>8</b> OHDSI 分析ツール</a>
<ul>
<li class="chapter" data-level="8.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#analysisImplementation"><i class="fa fa-check"></i><b>8.1</b> 分析の実装</a></li>
<li class="chapter" data-level="8.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#分析戦略"><i class="fa fa-check"></i><b>8.2</b> 分析戦略</a></li>
<li class="chapter" data-level="8.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#atlas"><i class="fa fa-check"></i><b>8.3</b> ATLAS</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#セキュリティ"><i class="fa fa-check"></i><b>8.3.1</b> セキュリティ</a></li>
<li class="chapter" data-level="8.3.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#ドキュメント"><i class="fa fa-check"></i><b>8.3.2</b> ドキュメント</a></li>
<li class="chapter" data-level="8.3.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#インストール方法"><i class="fa fa-check"></i><b>8.3.3</b> インストール方法</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#methods-library"><i class="fa fa-check"></i><b>8.4</b> Methods Library</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#大規模分析サポート"><i class="fa fa-check"></i><b>8.4.1</b> 大規模分析サポート</a></li>
<li class="chapter" data-level="8.4.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#BigDataSupport"><i class="fa fa-check"></i><b>8.4.2</b> ビッグデータ対応</a></li>
<li class="chapter" data-level="8.4.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#ドキュメント-1"><i class="fa fa-check"></i><b>8.4.3</b> ドキュメント</a></li>
<li class="chapter" data-level="8.4.4" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#システム要件"><i class="fa fa-check"></i><b>8.4.4</b> システム要件</a></li>
<li class="chapter" data-level="8.4.5" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#installR"><i class="fa fa-check"></i><b>8.4.5</b> インストール方法</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#展開戦略"><i class="fa fa-check"></i><b>8.5</b> 展開戦略</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#broadsea"><i class="fa fa-check"></i><b>8.5.1</b> Broadsea</a></li>
<li class="chapter" data-level="8.5.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#amazon-aws"><i class="fa fa-check"></i><b>8.5.2</b> Amazon AWS</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#まとめ-6"><i class="fa fa-check"></i><b>8.6</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="SqlAndR.html"><a href="SqlAndR.html"><i class="fa fa-check"></i><b>9</b> SQLとR</a>
<ul>
<li class="chapter" data-level="9.1" data-path="SqlAndR.html"><a href="SqlAndR.html#SqlRender"><i class="fa fa-check"></i><b>9.1</b> SqlRender</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="SqlAndR.html"><a href="SqlAndR.html#sqlのパラメータ設定"><i class="fa fa-check"></i><b>9.1.1</b> SQLのパラメータ設定</a></li>
<li class="chapter" data-level="9.1.2" data-path="SqlAndR.html"><a href="SqlAndR.html#他のsql表現への置換"><i class="fa fa-check"></i><b>9.1.2</b> 他のSQL表現への置換</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="SqlAndR.html"><a href="SqlAndR.html#DatabaseConnector"><i class="fa fa-check"></i><b>9.2</b> DatabaseConnector</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="SqlAndR.html"><a href="SqlAndR.html#接続の作成"><i class="fa fa-check"></i><b>9.2.1</b> 接続の作成</a></li>
<li class="chapter" data-level="9.2.2" data-path="SqlAndR.html"><a href="SqlAndR.html#クエリの実行"><i class="fa fa-check"></i><b>9.2.2</b> クエリの実行</a></li>
<li class="chapter" data-level="9.2.3" data-path="SqlAndR.html"><a href="SqlAndR.html#ffdfオブジェクトを使用したクエリの実行"><i class="fa fa-check"></i><b>9.2.3</b> ffdfオブジェクトを使用したクエリの実行</a></li>
<li class="chapter" data-level="9.2.4" data-path="SqlAndR.html"><a href="SqlAndR.html#同じsqlを用いて異なるプラットフォームにクエリを実行する"><i class="fa fa-check"></i><b>9.2.4</b> 同じSQLを用いて異なるプラットフォームにクエリを実行する</a></li>
<li class="chapter" data-level="9.2.5" data-path="SqlAndR.html"><a href="SqlAndR.html#テーブルの挿入"><i class="fa fa-check"></i><b>9.2.5</b> テーブルの挿入</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="SqlAndR.html"><a href="SqlAndR.html#QueryTheCdm"><i class="fa fa-check"></i><b>9.3</b> CDMへのクエリ</a></li>
<li class="chapter" data-level="9.4" data-path="SqlAndR.html"><a href="SqlAndR.html#クエリ実行時にボキャブラリを使用する"><i class="fa fa-check"></i><b>9.4</b> クエリ実行時にボキャブラリを使用する</a></li>
<li class="chapter" data-level="9.5" data-path="SqlAndR.html"><a href="SqlAndR.html#querylibrary"><i class="fa fa-check"></i><b>9.5</b> QueryLibrary</a></li>
<li class="chapter" data-level="9.6" data-path="SqlAndR.html"><a href="SqlAndR.html#簡単な研究のデザイン"><i class="fa fa-check"></i><b>9.6</b> 簡単な研究のデザイン</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="SqlAndR.html"><a href="SqlAndR.html#問題の定義"><i class="fa fa-check"></i><b>9.6.1</b> 問題の定義</a></li>
<li class="chapter" data-level="9.6.2" data-path="SqlAndR.html"><a href="SqlAndR.html#曝露"><i class="fa fa-check"></i><b>9.6.2</b> 曝露</a></li>
<li class="chapter" data-level="9.6.3" data-path="SqlAndR.html"><a href="SqlAndR.html#アウトカム"><i class="fa fa-check"></i><b>9.6.3</b> アウトカム</a></li>
<li class="chapter" data-level="9.6.4" data-path="SqlAndR.html"><a href="SqlAndR.html#リスク期間"><i class="fa fa-check"></i><b>9.6.4</b> リスク期間</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="SqlAndR.html"><a href="SqlAndR.html#sqlとrを使用した研究の実施"><i class="fa fa-check"></i><b>9.7</b> SQLとRを使用した研究の実施</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="SqlAndR.html"><a href="SqlAndR.html#曝露コホート"><i class="fa fa-check"></i><b>9.7.1</b> 曝露コホート</a></li>
<li class="chapter" data-level="9.7.2" data-path="SqlAndR.html"><a href="SqlAndR.html#アウトカムコホート"><i class="fa fa-check"></i><b>9.7.2</b> アウトカムコホート</a></li>
<li class="chapter" data-level="9.7.3" data-path="SqlAndR.html"><a href="SqlAndR.html#発症率の計算"><i class="fa fa-check"></i><b>9.7.3</b> 発症率の計算</a></li>
<li class="chapter" data-level="9.7.4" data-path="SqlAndR.html"><a href="SqlAndR.html#クリーンアップ"><i class="fa fa-check"></i><b>9.7.4</b> クリーンアップ</a></li>
<li class="chapter" data-level="9.7.5" data-path="SqlAndR.html"><a href="SqlAndR.html#互換性"><i class="fa fa-check"></i><b>9.7.5</b> 互換性</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="SqlAndR.html"><a href="SqlAndR.html#まとめ-7"><i class="fa fa-check"></i><b>9.8</b> まとめ</a></li>
<li class="chapter" data-level="9.9" data-path="SqlAndR.html"><a href="SqlAndR.html#演習-4"><i class="fa fa-check"></i><b>9.9</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="Cohorts.html"><a href="Cohorts.html"><i class="fa fa-check"></i><b>10</b> コホートの定義</a>
<ul>
<li class="chapter" data-level="10.1" data-path="Cohorts.html"><a href="Cohorts.html#コホートとは"><i class="fa fa-check"></i><b>10.1</b> コホートとは？</a></li>
<li class="chapter" data-level="10.2" data-path="Cohorts.html"><a href="Cohorts.html#ルールベースのコホート定義"><i class="fa fa-check"></i><b>10.2</b> ルールベースのコホート定義</a></li>
<li class="chapter" data-level="10.3" data-path="Cohorts.html"><a href="Cohorts.html#conceptSets"><i class="fa fa-check"></i><b>10.3</b> コンセプトセット</a></li>
<li class="chapter" data-level="10.4" data-path="Cohorts.html"><a href="Cohorts.html#確率的コホート定義"><i class="fa fa-check"></i><b>10.4</b> 確率的コホート定義</a></li>
<li class="chapter" data-level="10.5" data-path="Cohorts.html"><a href="Cohorts.html#コホート定義の妥当性"><i class="fa fa-check"></i><b>10.5</b> コホート定義の妥当性</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="Cohorts.html"><a href="Cohorts.html#ohdsi-ゴールドスタンダードフェノタイプライブラリ"><i class="fa fa-check"></i><b>10.5.1</b> OHDSI ゴールドスタンダードフェノタイプライブラリ</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="Cohorts.html"><a href="Cohorts.html#高血圧のコホート定義"><i class="fa fa-check"></i><b>10.6</b> 高血圧のコホート定義</a></li>
<li class="chapter" data-level="10.7" data-path="Cohorts.html"><a href="Cohorts.html#atlasを用いたコホートの実装"><i class="fa fa-check"></i><b>10.7</b> ATLASを用いたコホートの実装</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="Cohorts.html"><a href="Cohorts.html#初期イベント基準"><i class="fa fa-check"></i><b>10.7.1</b> 初期イベント基準</a></li>
<li class="chapter" data-level="10.7.2" data-path="Cohorts.html"><a href="Cohorts.html#コンセプトセットの定義"><i class="fa fa-check"></i><b>10.7.2</b> コンセプトセットの定義</a></li>
<li class="chapter" data-level="10.7.3" data-path="Cohorts.html"><a href="Cohorts.html#初期イベントの追加基準"><i class="fa fa-check"></i><b>10.7.3</b> 初期イベントの追加基準</a></li>
<li class="chapter" data-level="10.7.4" data-path="Cohorts.html"><a href="Cohorts.html#適格基準"><i class="fa fa-check"></i><b>10.7.4</b> 適格基準</a></li>
<li class="chapter" data-level="10.7.5" data-path="Cohorts.html"><a href="Cohorts.html#コホート離脱基準"><i class="fa fa-check"></i><b>10.7.5</b> コホート離脱基準</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="Cohorts.html"><a href="Cohorts.html#sqlを使用したコホートの実装"><i class="fa fa-check"></i><b>10.8</b> SQLを使用したコホートの実装</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="Cohorts.html"><a href="Cohorts.html#データベースへの接続-1"><i class="fa fa-check"></i><b>10.8.1</b> データベースへの接続</a></li>
<li class="chapter" data-level="10.8.2" data-path="Cohorts.html"><a href="Cohorts.html#コンセプトの指定"><i class="fa fa-check"></i><b>10.8.2</b> コンセプトの指定</a></li>
<li class="chapter" data-level="10.8.3" data-path="Cohorts.html"><a href="Cohorts.html#初回使用の発見"><i class="fa fa-check"></i><b>10.8.3</b> 初回使用の発見</a></li>
<li class="chapter" data-level="10.8.4" data-path="Cohorts.html"><a href="Cohorts.html#日の事前観察が必要"><i class="fa fa-check"></i><b>10.8.4</b> 365日の事前観察が必要</a></li>
<li class="chapter" data-level="10.8.5" data-path="Cohorts.html"><a href="Cohorts.html#高血圧の前診断が必要"><i class="fa fa-check"></i><b>10.8.5</b> 高血圧の前診断が必要</a></li>
<li class="chapter" data-level="10.8.6" data-path="Cohorts.html"><a href="Cohorts.html#治療の無前使用が必要"><i class="fa fa-check"></i><b>10.8.6</b> 治療の無前使用が必要</a></li>
<li class="chapter" data-level="10.8.7" data-path="Cohorts.html"><a href="Cohorts.html#単剤療法"><i class="fa fa-check"></i><b>10.8.7</b> 単剤療法</a></li>
<li class="chapter" data-level="10.8.8" data-path="Cohorts.html"><a href="Cohorts.html#コホート離脱"><i class="fa fa-check"></i><b>10.8.8</b> コホート離脱</a></li>
<li class="chapter" data-level="10.8.9" data-path="Cohorts.html"><a href="Cohorts.html#クリーンアップ-1"><i class="fa fa-check"></i><b>10.8.9</b> クリーンアップ</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="Cohorts.html"><a href="Cohorts.html#要約"><i class="fa fa-check"></i><b>10.9</b> 要約</a></li>
<li class="chapter" data-level="10.10" data-path="Cohorts.html"><a href="Cohorts.html#演習-5"><i class="fa fa-check"></i><b>10.10</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Characterization.html"><a href="Characterization.html"><i class="fa fa-check"></i><b>11</b> 特性評価</a>
<ul>
<li class="chapter" data-level="11.1" data-path="Characterization.html"><a href="Characterization.html#データベースレベルの特性評価"><i class="fa fa-check"></i><b>11.1</b> データベースレベルの特性評価</a></li>
<li class="chapter" data-level="11.2" data-path="Characterization.html"><a href="Characterization.html#コホート特性評価"><i class="fa fa-check"></i><b>11.2</b> コホート特性評価</a></li>
<li class="chapter" data-level="11.3" data-path="Characterization.html"><a href="Characterization.html#治療経路"><i class="fa fa-check"></i><b>11.3</b> 治療経路</a></li>
<li class="chapter" data-level="11.4" data-path="Characterization.html"><a href="Characterization.html#発生率"><i class="fa fa-check"></i><b>11.4</b> 発生率</a></li>
<li class="chapter" data-level="11.5" data-path="Characterization.html"><a href="Characterization.html#高血圧症患者の特性評価"><i class="fa fa-check"></i><b>11.5</b> 高血圧症患者の特性評価</a></li>
<li class="chapter" data-level="11.6" data-path="Characterization.html"><a href="Characterization.html#atlasにおけるデータベースの特性評価"><i class="fa fa-check"></i><b>11.6</b> ATLASにおけるデータベースの特性評価</a></li>
<li class="chapter" data-level="11.7" data-path="Characterization.html"><a href="Characterization.html#atlasにおけるコホート特性分析"><i class="fa fa-check"></i><b>11.7</b> ATLASにおけるコホート特性分析</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="Characterization.html"><a href="Characterization.html#デザイン"><i class="fa fa-check"></i><b>11.7.1</b> デザイン</a></li>
<li class="chapter" data-level="11.7.2" data-path="Characterization.html"><a href="Characterization.html#実行"><i class="fa fa-check"></i><b>11.7.2</b> 実行</a></li>
<li class="chapter" data-level="11.7.3" data-path="Characterization.html"><a href="Characterization.html#結果"><i class="fa fa-check"></i><b>11.7.3</b> 結果</a></li>
<li class="chapter" data-level="11.7.4" data-path="Characterization.html"><a href="Characterization.html#カスタム特性の定義"><i class="fa fa-check"></i><b>11.7.4</b> カスタム特性の定義</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="Characterization.html"><a href="Characterization.html#rでのコホートの特性評価"><i class="fa fa-check"></i><b>11.8</b> Rでのコホートの特性評価</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="Characterization.html"><a href="Characterization.html#コホートのインスタンス化"><i class="fa fa-check"></i><b>11.8.1</b> コホートのインスタンス化</a></li>
<li class="chapter" data-level="11.8.2" data-path="Characterization.html"><a href="Characterization.html#データ抽出"><i class="fa fa-check"></i><b>11.8.2</b> データ抽出</a></li>
<li class="chapter" data-level="11.8.3" data-path="Characterization.html"><a href="Characterization.html#事前に指定された分析の使用"><i class="fa fa-check"></i><b>11.8.3</b> 事前に指定された分析の使用</a></li>
<li class="chapter" data-level="11.8.4" data-path="Characterization.html"><a href="Characterization.html#集計された共変量の作成"><i class="fa fa-check"></i><b>11.8.4</b> 集計された共変量の作成</a></li>
<li class="chapter" data-level="11.8.5" data-path="Characterization.html"><a href="Characterization.html#出力形式"><i class="fa fa-check"></i><b>11.8.5</b> 出力形式</a></li>
<li class="chapter" data-level="11.8.6" data-path="Characterization.html"><a href="Characterization.html#カスタム共変量"><i class="fa fa-check"></i><b>11.8.6</b> カスタム共変量</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="Characterization.html"><a href="Characterization.html#atlasにおけるコホート経路分析"><i class="fa fa-check"></i><b>11.9</b> ATLASにおけるコホート経路分析</a>
<ul>
<li class="chapter" data-level="11.9.1" data-path="Characterization.html"><a href="Characterization.html#デザイン-1"><i class="fa fa-check"></i><b>11.9.1</b> デザイン</a></li>
<li class="chapter" data-level="11.9.2" data-path="Characterization.html"><a href="Characterization.html#実行-1"><i class="fa fa-check"></i><b>11.9.2</b> 実行</a></li>
<li class="chapter" data-level="11.9.3" data-path="Characterization.html"><a href="Characterization.html#結果の表示"><i class="fa fa-check"></i><b>11.9.3</b> 結果の表示</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="Characterization.html"><a href="Characterization.html#atlas-における発生率分析"><i class="fa fa-check"></i><b>11.10</b> ATLAS における発生率分析</a>
<ul>
<li class="chapter" data-level="11.10.1" data-path="Characterization.html"><a href="Characterization.html#デザイン-2"><i class="fa fa-check"></i><b>11.10.1</b> デザイン</a></li>
<li class="chapter" data-level="11.10.2" data-path="Characterization.html"><a href="Characterization.html#実行-2"><i class="fa fa-check"></i><b>11.10.2</b> 実行</a></li>
<li class="chapter" data-level="11.10.3" data-path="Characterization.html"><a href="Characterization.html#結果の表示-1"><i class="fa fa-check"></i><b>11.10.3</b> 結果の表示</a></li>
</ul></li>
<li class="chapter" data-level="11.11" data-path="Characterization.html"><a href="Characterization.html#まとめ-8"><i class="fa fa-check"></i><b>11.11</b> まとめ</a></li>
<li class="chapter" data-level="11.12" data-path="Characterization.html"><a href="Characterization.html#演習-6"><i class="fa fa-check"></i><b>11.12</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html"><i class="fa fa-check"></i><b>12</b> 集団レベルの推定</a>
<ul>
<li class="chapter" data-level="12.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#CohortMethod"><i class="fa fa-check"></i><b>12.1</b> コホートメソッドの設計</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#傾向スコア"><i class="fa fa-check"></i><b>12.1.1</b> 傾向スコア</a></li>
<li class="chapter" data-level="12.1.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#VariableSelection"><i class="fa fa-check"></i><b>12.1.2</b> 変数選択</a></li>
<li class="chapter" data-level="12.1.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#カリパー"><i class="fa fa-check"></i><b>12.1.3</b> カリパー</a></li>
<li class="chapter" data-level="12.1.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#オーバーラップ選好スコア"><i class="fa fa-check"></i><b>12.1.4</b> オーバーラップ：選好スコア</a></li>
<li class="chapter" data-level="12.1.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#バランス"><i class="fa fa-check"></i><b>12.1.5</b> バランス</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#自己対照コホートデザイン"><i class="fa fa-check"></i><b>12.2</b> 自己対照コホートデザイン</a></li>
<li class="chapter" data-level="12.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#症例対照デザイン"><i class="fa fa-check"></i><b>12.3</b> 症例対照デザイン</a></li>
<li class="chapter" data-level="12.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#ケースクロスオーバーデザイン"><i class="fa fa-check"></i><b>12.4</b> ケース・クロスオーバーデザイン</a></li>
<li class="chapter" data-level="12.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#自己対照症例シリーズデザイン"><i class="fa fa-check"></i><b>12.5</b> 自己対照症例シリーズデザイン</a></li>
<li class="chapter" data-level="12.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#高血圧症研究のデザイン"><i class="fa fa-check"></i><b>12.6</b> 高血圧症研究のデザイン</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#問題の定義-1"><i class="fa fa-check"></i><b>12.6.1</b> 問題の定義</a></li>
<li class="chapter" data-level="12.6.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#対象および比較対照"><i class="fa fa-check"></i><b>12.6.2</b> 対象および比較対照</a></li>
<li class="chapter" data-level="12.6.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#アウトカム-1"><i class="fa fa-check"></i><b>12.6.3</b> アウトカム</a></li>
<li class="chapter" data-level="12.6.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#リスク期間-1"><i class="fa fa-check"></i><b>12.6.4</b> リスク期間</a></li>
<li class="chapter" data-level="12.6.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#モデル"><i class="fa fa-check"></i><b>12.6.5</b> モデル</a></li>
<li class="chapter" data-level="12.6.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#研究要約"><i class="fa fa-check"></i><b>12.6.6</b> 研究要約</a></li>
<li class="chapter" data-level="12.6.7" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#コントロールクエスチョン"><i class="fa fa-check"></i><b>12.6.7</b> コントロールクエスチョン</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#PleAtlas"><i class="fa fa-check"></i><b>12.7</b> ATLASを使用した研究の実施</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#ComparisonSettings"><i class="fa fa-check"></i><b>12.7.1</b> 比較コホート設定</a></li>
<li class="chapter" data-level="12.7.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#効果推定の分析設定"><i class="fa fa-check"></i><b>12.7.2</b> 効果推定の分析設定</a></li>
<li class="chapter" data-level="12.7.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#evaluationSettings"><i class="fa fa-check"></i><b>12.7.3</b> 評価の設定</a></li>
<li class="chapter" data-level="12.7.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#研究パッケージの実行"><i class="fa fa-check"></i><b>12.7.4</b> 研究パッケージの実行</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#pleR"><i class="fa fa-check"></i><b>12.8</b> Rを使用した研究の実施</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#コホートのインスタンス化-1"><i class="fa fa-check"></i><b>12.8.1</b> コホートのインスタンス化</a></li>
<li class="chapter" data-level="12.8.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#データ抽出-1"><i class="fa fa-check"></i><b>12.8.2</b> データ抽出</a></li>
<li class="chapter" data-level="12.8.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#研究集団の定義"><i class="fa fa-check"></i><b>12.8.3</b> 研究集団の定義</a></li>
<li class="chapter" data-level="12.8.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#傾向スコア-1"><i class="fa fa-check"></i><b>12.8.4</b> 傾向スコア</a></li>
<li class="chapter" data-level="12.8.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#アウトカムモデル"><i class="fa fa-check"></i><b>12.8.5</b> アウトカムモデル</a></li>
<li class="chapter" data-level="12.8.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#MultipleAnalyses"><i class="fa fa-check"></i><b>12.8.6</b> 複数の分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#studyOutputs"><i class="fa fa-check"></i><b>12.9</b> 研究の結果</a>
<ul>
<li class="chapter" data-level="12.9.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#傾向スコアとモデル"><i class="fa fa-check"></i><b>12.9.1</b> 傾向スコアとモデル</a></li>
<li class="chapter" data-level="12.9.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#共変量のバランス"><i class="fa fa-check"></i><b>12.9.2</b> 共変量のバランス</a></li>
<li class="chapter" data-level="12.9.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#フォローアップとパワー"><i class="fa fa-check"></i><b>12.9.3</b> フォローアップとパワー</a></li>
<li class="chapter" data-level="12.9.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#カプランマイヤー"><i class="fa fa-check"></i><b>12.9.4</b> カプラン・マイヤー</a></li>
<li class="chapter" data-level="12.9.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#効果量の推定"><i class="fa fa-check"></i><b>12.9.5</b> 効果量の推定</a></li>
</ul></li>
<li class="chapter" data-level="12.10" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#まとめ-9"><i class="fa fa-check"></i><b>12.10</b> まとめ</a></li>
<li class="chapter" data-level="12.11" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#演習-7"><i class="fa fa-check"></i><b>12.11</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html"><i class="fa fa-check"></i><b>13</b> 患者レベル予測</a>
<ul>
<li class="chapter" data-level="13.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#予測課題"><i class="fa fa-check"></i><b>13.1</b> 予測課題</a></li>
<li class="chapter" data-level="13.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#データ抽出-2"><i class="fa fa-check"></i><b>13.2</b> データ抽出</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#データ抽出の例"><i class="fa fa-check"></i><b>13.2.1</b> データ抽出の例</a></li>
<li class="chapter" data-level="13.2.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#否定-vs-欠損"><i class="fa fa-check"></i><b>13.2.2</b> 否定 vs 欠損</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#modelFitting"><i class="fa fa-check"></i><b>13.3</b> モデルの適合</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#正則化ロジスティック回帰"><i class="fa fa-check"></i><b>13.3.1</b> 正則化ロジスティック回帰</a></li>
<li class="chapter" data-level="13.3.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#勾配ブースティングマシン"><i class="fa fa-check"></i><b>13.3.2</b> 勾配ブースティングマシン</a></li>
<li class="chapter" data-level="13.3.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#ランダムフォレスト"><i class="fa fa-check"></i><b>13.3.3</b> ランダムフォレスト</a></li>
<li class="chapter" data-level="13.3.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#k-近傍法"><i class="fa fa-check"></i><b>13.3.4</b> K-近傍法</a></li>
<li class="chapter" data-level="13.3.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#ナイーブベイズ"><i class="fa fa-check"></i><b>13.3.5</b> ナイーブベイズ</a></li>
<li class="chapter" data-level="13.3.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#adaboost"><i class="fa fa-check"></i><b>13.3.6</b> AdaBoost</a></li>
<li class="chapter" data-level="13.3.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#決定木"><i class="fa fa-check"></i><b>13.3.7</b> 決定木</a></li>
<li class="chapter" data-level="13.3.8" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#多層パーセプトロン"><i class="fa fa-check"></i><b>13.3.8</b> 多層パーセプトロン</a></li>
<li class="chapter" data-level="13.3.9" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#ディープラーニング"><i class="fa fa-check"></i><b>13.3.9</b> ディープラーニング</a></li>
<li class="chapter" data-level="13.3.10" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#その他のアルゴリズム"><i class="fa fa-check"></i><b>13.3.10</b> その他のアルゴリズム</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#予測モデルの評価"><i class="fa fa-check"></i><b>13.4</b> 予測モデルの評価</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#評価の種類"><i class="fa fa-check"></i><b>13.4.1</b> 評価の種類</a></li>
<li class="chapter" data-level="13.4.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#performance"><i class="fa fa-check"></i><b>13.4.2</b> パフォーマンス指標</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#患者レベル予測研究の設計"><i class="fa fa-check"></i><b>13.5</b> 患者レベル予測研究の設計</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#問題の定義-2"><i class="fa fa-check"></i><b>13.5.1</b> 問題の定義</a></li>
<li class="chapter" data-level="13.5.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究集団の定義-1"><i class="fa fa-check"></i><b>13.5.2</b> 研究集団の定義</a></li>
<li class="chapter" data-level="13.5.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデル開発設定"><i class="fa fa-check"></i><b>13.5.3</b> モデル開発設定</a></li>
<li class="chapter" data-level="13.5.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデル評価"><i class="fa fa-check"></i><b>13.5.4</b> モデル評価</a></li>
<li class="chapter" data-level="13.5.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究概要"><i class="fa fa-check"></i><b>13.5.5</b> 研究概要</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#atlasでの研究の実装"><i class="fa fa-check"></i><b>13.6</b> ATLASでの研究の実装</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#予測の問題設定"><i class="fa fa-check"></i><b>13.6.1</b> 予測の問題設定</a></li>
<li class="chapter" data-level="13.6.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#分析設定"><i class="fa fa-check"></i><b>13.6.2</b> 分析設定</a></li>
<li class="chapter" data-level="13.6.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#実行の設定"><i class="fa fa-check"></i><b>13.6.3</b> 実行の設定</a></li>
<li class="chapter" data-level="13.6.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#トレーニングの設定"><i class="fa fa-check"></i><b>13.6.4</b> トレーニングの設定</a></li>
<li class="chapter" data-level="13.6.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究のインポートとエクスポート"><i class="fa fa-check"></i><b>13.6.5</b> 研究のインポートとエクスポート</a></li>
<li class="chapter" data-level="13.6.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究パッケージのダウンロード"><i class="fa fa-check"></i><b>13.6.6</b> 研究パッケージのダウンロード</a></li>
<li class="chapter" data-level="13.6.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#研究の実行"><i class="fa fa-check"></i><b>13.6.7</b> 研究の実行</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#rでの研究実施"><i class="fa fa-check"></i><b>13.7</b> Rでの研究実施</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#コホートのインスタンス化-2"><i class="fa fa-check"></i><b>13.7.1</b> コホートのインスタンス化</a></li>
<li class="chapter" data-level="13.7.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#データ抽出-3"><i class="fa fa-check"></i><b>13.7.2</b> データ抽出</a></li>
<li class="chapter" data-level="13.7.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#追加選択基準"><i class="fa fa-check"></i><b>13.7.3</b> 追加選択基準</a></li>
<li class="chapter" data-level="13.7.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデル開発"><i class="fa fa-check"></i><b>13.7.4</b> モデル開発</a></li>
<li class="chapter" data-level="13.7.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#内部バリデーション"><i class="fa fa-check"></i><b>13.7.5</b> 内部バリデーション</a></li>
<li class="chapter" data-level="13.7.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#外部バリデーション"><i class="fa fa-check"></i><b>13.7.6</b> 外部バリデーション</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#アウトカム普及"><i class="fa fa-check"></i><b>13.8</b> アウトカム普及</a>
<ul>
<li class="chapter" data-level="13.8.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデルパフォーマンス"><i class="fa fa-check"></i><b>13.8.1</b> モデルパフォーマンス</a></li>
<li class="chapter" data-level="13.8.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#モデルの比較"><i class="fa fa-check"></i><b>13.8.2</b> モデルの比較</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#患者レベル予測機能の追加"><i class="fa fa-check"></i><b>13.9</b> 患者レベル予測機能の追加</a>
<ul>
<li class="chapter" data-level="13.9.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#ジャーナル論文の生成"><i class="fa fa-check"></i><b>13.9.1</b> ジャーナル論文の生成</a></li>
</ul></li>
<li class="chapter" data-level="13.10" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#まとめ-10"><i class="fa fa-check"></i><b>13.10</b> まとめ</a></li>
<li class="chapter" data-level="13.11" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#演習-8"><i class="fa fa-check"></i><b>13.11</b> 演習</a></li>
</ul></li>
<li class="part"><span><b>IV エビデンスの質</b></span></li>
<li class="chapter" data-level="14" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html"><i class="fa fa-check"></i><b>14</b> エビデンスの質</a>
<ul>
<li class="chapter" data-level="14.1" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#信頼できるエビデンスの属性"><i class="fa fa-check"></i><b>14.1</b> 信頼できるエビデンスの属性</a></li>
<li class="chapter" data-level="14.2" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#エビデンスの質の理解"><i class="fa fa-check"></i><b>14.2</b> エビデンスの質の理解</a></li>
<li class="chapter" data-level="14.3" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#エビデンスの質の伝達"><i class="fa fa-check"></i><b>14.3</b> エビデンスの質の伝達</a></li>
<li class="chapter" data-level="14.4" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html#まとめ-11"><i class="fa fa-check"></i><b>14.4</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="DataQuality.html"><a href="DataQuality.html"><i class="fa fa-check"></i><b>15</b> データ品質</a>
<ul>
<li class="chapter" data-level="15.1" data-path="DataQuality.html"><a href="DataQuality.html#データ品質問題の原因"><i class="fa fa-check"></i><b>15.1</b> データ品質問題の原因</a></li>
<li class="chapter" data-level="15.2" data-path="DataQuality.html"><a href="DataQuality.html#一般的なデータ品質"><i class="fa fa-check"></i><b>15.2</b> 一般的なデータ品質</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="DataQuality.html"><a href="DataQuality.html#データ品質チェック"><i class="fa fa-check"></i><b>15.2.1</b> データ品質チェック</a></li>
<li class="chapter" data-level="15.2.2" data-path="DataQuality.html"><a href="DataQuality.html#etlUnitTests"><i class="fa fa-check"></i><b>15.2.2</b> ETL（抽出-変換-読込）単体テスト</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="DataQuality.html"><a href="DataQuality.html#研究特有のチェック"><i class="fa fa-check"></i><b>15.3</b> 研究特有のチェック</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="DataQuality.html"><a href="DataQuality.html#マッピングのチェック"><i class="fa fa-check"></i><b>15.3.1</b> マッピングのチェック</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="DataQuality.html"><a href="DataQuality.html#achillesInPractice"><i class="fa fa-check"></i><b>15.4</b> 実践におけるACHILLES</a></li>
<li class="chapter" data-level="15.5" data-path="DataQuality.html"><a href="DataQuality.html#dqdInPractice"><i class="fa fa-check"></i><b>15.5</b> Data Quality Dashboardの実践</a></li>
<li class="chapter" data-level="15.6" data-path="DataQuality.html"><a href="DataQuality.html#特定の研究チェックの実践"><i class="fa fa-check"></i><b>15.6</b> 特定の研究チェックの実践</a></li>
<li class="chapter" data-level="15.7" data-path="DataQuality.html"><a href="DataQuality.html#まとめ-12"><i class="fa fa-check"></i><b>15.7</b> まとめ</a></li>
<li class="chapter" data-level="15.8" data-path="DataQuality.html"><a href="DataQuality.html#演習-9"><i class="fa fa-check"></i><b>15.8</b> 演習</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html"><i class="fa fa-check"></i><b>16</b> 臨床的妥当性</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#CharacteristicsOfDatabase"><i class="fa fa-check"></i><b>16.1</b> 医療データベースの特性</a></li>
<li class="chapter" data-level="16.2" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#CohortValidation"><i class="fa fa-check"></i><b>16.2</b> コホートバリデーション</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#コホート評価指標"><i class="fa fa-check"></i><b>16.2.1</b> コホート評価指標</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#ソースレコード検証"><i class="fa fa-check"></i><b>16.3</b> ソースレコード検証</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#ソースレコード検証の例"><i class="fa fa-check"></i><b>16.3.1</b> ソースレコード検証の例</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#phevaluator"><i class="fa fa-check"></i><b>16.4</b> PheValuator</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#phevaluatorによる検証例"><i class="fa fa-check"></i><b>16.4.1</b> PheValuatorによる検証例</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#GeneralizabilityOfEvidence"><i class="fa fa-check"></i><b>16.5</b> エビデンスの一般化可能性</a></li>
<li class="chapter" data-level="16.6" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html#まとめ-13"><i class="fa fa-check"></i><b>16.6</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html"><i class="fa fa-check"></i><b>17</b> ソフトウェアの妥当性</a>
<ul>
<li class="chapter" data-level="17.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#研究コードの妥当性"><i class="fa fa-check"></i><b>17.1</b> 研究コードの妥当性</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#automation"><i class="fa fa-check"></i><b>17.1.1</b> 再現性のための自動化の必要性</a></li>
<li class="chapter" data-level="17.1.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#プログラミングのベストプラクティス"><i class="fa fa-check"></i><b>17.1.2</b> プログラミングのベストプラクティス</a></li>
<li class="chapter" data-level="17.1.3" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#コードの検証"><i class="fa fa-check"></i><b>17.1.3</b> コードの検証</a></li>
<li class="chapter" data-level="17.1.4" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#methods-libraryの使用"><i class="fa fa-check"></i><b>17.1.4</b> Methods Libraryの使用</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#methods-librarのソフトウェア開発プロセス"><i class="fa fa-check"></i><b>17.2</b> Methods Librarのソフトウェア開発プロセス</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#ソースコード管理"><i class="fa fa-check"></i><b>17.2.1</b> ソースコード管理</a></li>
<li class="chapter" data-level="17.2.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#ドキュメンテーション"><i class="fa fa-check"></i><b>17.2.2</b> ドキュメンテーション</a></li>
<li class="chapter" data-level="17.2.3" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#現行および過去のアーカイブバージョンの利用可能性"><i class="fa fa-check"></i><b>17.2.3</b> 現行および過去のアーカイブバージョンの利用可能性</a></li>
<li class="chapter" data-level="17.2.4" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#メンテナンスサポートおよびリタイアメント"><i class="fa fa-check"></i><b>17.2.4</b> メンテナンス、サポート、およびリタイアメント</a></li>
<li class="chapter" data-level="17.2.5" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#有資格者"><i class="fa fa-check"></i><b>17.2.5</b> 有資格者</a></li>
<li class="chapter" data-level="17.2.6" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#物理的および論理的セキュリティ"><i class="fa fa-check"></i><b>17.2.6</b> 物理的および論理的セキュリティ</a></li>
<li class="chapter" data-level="17.2.7" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#災害復旧"><i class="fa fa-check"></i><b>17.2.7</b> 災害復旧</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#methods-libraryのテスト"><i class="fa fa-check"></i><b>17.3</b> Methods Libraryのテスト</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#ユニットテスト"><i class="fa fa-check"></i><b>17.3.1</b> ユニットテスト</a></li>
<li class="chapter" data-level="17.3.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#シミュレーション"><i class="fa fa-check"></i><b>17.3.2</b> シミュレーション</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#まとめ-14"><i class="fa fa-check"></i><b>17.4</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="MethodValidity.html"><a href="MethodValidity.html"><i class="fa fa-check"></i><b>18</b> 方法の妥当性</a>
<ul>
<li class="chapter" data-level="18.1" data-path="MethodValidity.html"><a href="MethodValidity.html#デザイン特有の診断"><i class="fa fa-check"></i><b>18.1</b> デザイン特有の診断</a></li>
<li class="chapter" data-level="18.2" data-path="MethodValidity.html"><a href="MethodValidity.html#推定のための診断"><i class="fa fa-check"></i><b>18.2</b> 推定のための診断</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="MethodValidity.html"><a href="MethodValidity.html#NegativeControls"><i class="fa fa-check"></i><b>18.2.1</b> ネガティブコントロール</a></li>
<li class="chapter" data-level="18.2.2" data-path="MethodValidity.html"><a href="MethodValidity.html#PositiveControls"><i class="fa fa-check"></i><b>18.2.2</b> ポジティブコントロール</a></li>
<li class="chapter" data-level="18.2.3" data-path="MethodValidity.html"><a href="MethodValidity.html#metrics"><i class="fa fa-check"></i><b>18.2.3</b> 実証的評価</a></li>
<li class="chapter" data-level="18.2.4" data-path="MethodValidity.html"><a href="MethodValidity.html#p値のキャリブレーション"><i class="fa fa-check"></i><b>18.2.4</b> P値のキャリブレーション</a></li>
<li class="chapter" data-level="18.2.5" data-path="MethodValidity.html"><a href="MethodValidity.html#信頼区間のキャリブレーション"><i class="fa fa-check"></i><b>18.2.5</b> 信頼区間のキャリブレーション</a></li>
<li class="chapter" data-level="18.2.6" data-path="MethodValidity.html"><a href="MethodValidity.html#医療機関をまたいだ複製"><i class="fa fa-check"></i><b>18.2.6</b> 医療機関をまたいだ複製</a></li>
<li class="chapter" data-level="18.2.7" data-path="MethodValidity.html"><a href="MethodValidity.html#感度分析"><i class="fa fa-check"></i><b>18.2.7</b> 感度分析</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="MethodValidity.html"><a href="MethodValidity.html#実践におけるメソッド検証"><i class="fa fa-check"></i><b>18.3</b> 実践におけるメソッド検証</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="MethodValidity.html"><a href="MethodValidity.html#ネガティブコントロールの選択"><i class="fa fa-check"></i><b>18.3.1</b> ネガティブコントロールの選択</a></li>
<li class="chapter" data-level="18.3.2" data-path="MethodValidity.html"><a href="MethodValidity.html#コントロールを含めること"><i class="fa fa-check"></i><b>18.3.2</b> コントロールを含めること</a></li>
<li class="chapter" data-level="18.3.3" data-path="MethodValidity.html"><a href="MethodValidity.html#実証されたパフォーマンス"><i class="fa fa-check"></i><b>18.3.3</b> 実証されたパフォーマンス</a></li>
<li class="chapter" data-level="18.3.4" data-path="MethodValidity.html"><a href="MethodValidity.html#p値のキャリブレーション-1"><i class="fa fa-check"></i><b>18.3.4</b> P値のキャリブレーション</a></li>
<li class="chapter" data-level="18.3.5" data-path="MethodValidity.html"><a href="MethodValidity.html#信頼区間のキャリブレーション-1"><i class="fa fa-check"></i><b>18.3.5</b> 信頼区間のキャリブレーション</a></li>
<li class="chapter" data-level="18.3.6" data-path="MethodValidity.html"><a href="MethodValidity.html#データベース間の異質性"><i class="fa fa-check"></i><b>18.3.6</b> データベース間の異質性</a></li>
<li class="chapter" data-level="18.3.7" data-path="MethodValidity.html"><a href="MethodValidity.html#感度分析-1"><i class="fa fa-check"></i><b>18.3.7</b> 感度分析</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="MethodValidity.html"><a href="MethodValidity.html#ohdsiメソッド評価ベンチマーク"><i class="fa fa-check"></i><b>18.4</b> OHDSIメソッド評価ベンチマーク</a></li>
<li class="chapter" data-level="18.5" data-path="MethodValidity.html"><a href="MethodValidity.html#まとめ-15"><i class="fa fa-check"></i><b>18.5</b> まとめ</a></li>
</ul></li>
<li class="part"><span><b>V OHDSI研究</b></span></li>
<li class="chapter" data-level="19" data-path="StudySteps.html"><a href="StudySteps.html"><i class="fa fa-check"></i><b>19</b> 研究の段階</a>
<ul>
<li class="chapter" data-level="19.1" data-path="StudySteps.html"><a href="StudySteps.html#一般的なベストプラクティスガイドライン"><i class="fa fa-check"></i><b>19.1</b> 一般的なベストプラクティスガイドライン</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="StudySteps.html"><a href="StudySteps.html#観察研究の定義"><i class="fa fa-check"></i><b>19.1.1</b> 観察研究の定義</a></li>
<li class="chapter" data-level="19.1.2" data-path="StudySteps.html"><a href="StudySteps.html#事前に規定した研究デザイン"><i class="fa fa-check"></i><b>19.1.2</b> 事前に規定した研究デザイン</a></li>
<li class="chapter" data-level="19.1.3" data-path="StudySteps.html"><a href="StudySteps.html#プロトコル"><i class="fa fa-check"></i><b>19.1.3</b> プロトコル</a></li>
<li class="chapter" data-level="19.1.4" data-path="StudySteps.html"><a href="StudySteps.html#標準化された分析"><i class="fa fa-check"></i><b>19.1.4</b> 標準化された分析</a></li>
<li class="chapter" data-level="19.1.5" data-path="StudySteps.html"><a href="StudySteps.html#研究パッケージ"><i class="fa fa-check"></i><b>19.1.5</b> 研究パッケージ</a></li>
<li class="chapter" data-level="19.1.6" data-path="StudySteps.html"><a href="StudySteps.html#cdmに基づくデータ"><i class="fa fa-check"></i><b>19.1.6</b> CDMに基づくデータ</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="StudySteps.html"><a href="StudySteps.html#詳細な研究手順"><i class="fa fa-check"></i><b>19.2</b> 詳細な研究手順</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="StudySteps.html"><a href="StudySteps.html#問いを定義する"><i class="fa fa-check"></i><b>19.2.1</b> 問いを定義する</a></li>
<li class="chapter" data-level="19.2.2" data-path="StudySteps.html"><a href="StudySteps.html#データの可用性と質を確認する"><i class="fa fa-check"></i><b>19.2.2</b> データの可用性と質を確認する</a></li>
<li class="chapter" data-level="19.2.3" data-path="StudySteps.html"><a href="StudySteps.html#研究対象集団-1"><i class="fa fa-check"></i><b>19.2.3</b> 研究対象集団</a></li>
<li class="chapter" data-level="19.2.4" data-path="StudySteps.html"><a href="StudySteps.html#Feasibility"><i class="fa fa-check"></i><b>19.2.4</b> 実施可能性と研究診断</a></li>
<li class="chapter" data-level="19.2.5" data-path="StudySteps.html"><a href="StudySteps.html#プロトコルと研究パッケージの最終化"><i class="fa fa-check"></i><b>19.2.5</b> プロトコルと研究パッケージの最終化</a></li>
<li class="chapter" data-level="19.2.6" data-path="StudySteps.html"><a href="StudySteps.html#研究の実施"><i class="fa fa-check"></i><b>19.2.6</b> 研究の実施</a></li>
<li class="chapter" data-level="19.2.7" data-path="StudySteps.html"><a href="StudySteps.html#解釈と報告"><i class="fa fa-check"></i><b>19.2.7</b> 解釈と報告</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="StudySteps.html"><a href="StudySteps.html#まとめ-16"><i class="fa fa-check"></i><b>19.3</b> まとめ</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="NetworkResearch.html"><a href="NetworkResearch.html"><i class="fa fa-check"></i><b>20</b> OHDSI ネットワーク研究</a>
<ul>
<li class="chapter" data-level="20.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi-研究ネットワークとして"><i class="fa fa-check"></i><b>20.1</b> OHDSI 研究ネットワークとして</a></li>
<li class="chapter" data-level="20.2" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究"><i class="fa fa-check"></i><b>20.2</b> OHDSIネットワーク研究</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究を実施する動機"><i class="fa fa-check"></i><b>20.2.1</b> OHDSIネットワーク研究を実施する動機</a></li>
<li class="chapter" data-level="20.2.2" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究の定義"><i class="fa fa-check"></i><b>20.2.2</b> OHDSIネットワーク研究の定義</a></li>
<li class="chapter" data-level="20.2.3" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究の設計上の考慮事項"><i class="fa fa-check"></i><b>20.2.3</b> OHDSIネットワーク研究の設計上の考慮事項</a></li>
<li class="chapter" data-level="20.2.4" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究のためのロジスティクスに関する考察"><i class="fa fa-check"></i><b>20.2.4</b> OHDSIネットワーク研究のためのロジスティクスに関する考察</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究の実行"><i class="fa fa-check"></i><b>20.3</b> OHDSIネットワーク研究の実行</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#研究デザインと実現可能性"><i class="fa fa-check"></i><b>20.3.1</b> 研究デザインと実現可能性</a></li>
<li class="chapter" data-level="20.3.2" data-path="NetworkResearch.html"><a href="NetworkResearch.html#研究の実行-1"><i class="fa fa-check"></i><b>20.3.2</b> 研究の実行</a></li>
<li class="chapter" data-level="20.3.3" data-path="NetworkResearch.html"><a href="NetworkResearch.html#結果の普及と公開"><i class="fa fa-check"></i><b>20.3.3</b> 結果の普及と公開</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="NetworkResearch.html"><a href="NetworkResearch.html#展望-ネットワーク研究の自動化を利用する"><i class="fa fa-check"></i><b>20.4</b> 展望: ネットワーク研究の自動化を利用する</a></li>
<li class="chapter" data-level="20.5" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsiネットワーク研究のベストプラクティス"><i class="fa fa-check"></i><b>20.5</b> OHDSIネットワーク研究のベストプラクティス</a></li>
<li class="chapter" data-level="20.6" data-path="NetworkResearch.html"><a href="NetworkResearch.html#まとめ-17"><i class="fa fa-check"></i><b>20.6</b> まとめ</a></li>
</ul></li>
<li class="appendix"><span><b>付録</b></span></li>
<li class="chapter" data-level="A" data-path="Glossary.html"><a href="Glossary.html"><i class="fa fa-check"></i><b>A</b> 用語集</a></li>
<li class="chapter" data-level="B" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html"><i class="fa fa-check"></i><b>B</b> コホート定義</a>
<ul>
<li class="chapter" data-level="B.1" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#AceInhibitors"><i class="fa fa-check"></i><b>B.1</b> ACE阻害薬</a></li>
<li class="chapter" data-level="B.2" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#AceInhibitorsMono"><i class="fa fa-check"></i><b>B.2</b> ACE阻害薬単剤療法新規ユーザー</a></li>
<li class="chapter" data-level="B.3" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#Ami"><i class="fa fa-check"></i><b>B.3</b> 急性心筋梗塞（AMI）</a></li>
<li class="chapter" data-level="B.4" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#Angioedema"><i class="fa fa-check"></i><b>B.4</b> 血管性浮腫</a></li>
<li class="chapter" data-level="B.5" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ThiazidesMono"><i class="fa fa-check"></i><b>B.5</b> サイアザイド様利尿薬単剤療法の新規ユーザー使用者</a></li>
<li class="chapter" data-level="B.6" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#HTN1yrFO"><i class="fa fa-check"></i><b>B.6</b> 高血圧のための第一選択治療を開始する患者</a></li>
<li class="chapter" data-level="B.7" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#HTN3yrFO"><i class="fa fa-check"></i><b>B.7</b> 追跡期間が3年以上ある高血圧のための第一選択治療を開始する患者</a></li>
<li class="chapter" data-level="B.8" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ACEiUse"><i class="fa fa-check"></i><b>B.8</b> ACE阻害薬の使用</a></li>
<li class="chapter" data-level="B.9" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ARBUse"><i class="fa fa-check"></i><b>B.9</b> アンジオテンシン受容体拮抗薬（ARB）の使用</a></li>
<li class="chapter" data-level="B.10" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#THZUse"><i class="fa fa-check"></i><b>B.10</b> サイアザイドおよびサイアザイド様利尿薬の使用</a></li>
<li class="chapter" data-level="B.11" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#dCCBUse"><i class="fa fa-check"></i><b>B.11</b> ジヒドロピリジン系カルシウムチャネル遮断薬（DCCB）の使用</a></li>
<li class="chapter" data-level="B.12" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ndCCBUse"><i class="fa fa-check"></i><b>B.12</b> 非ジヒドロピリジン系カルシウムチャネル遮断薬（NDCCB）の使用</a></li>
<li class="chapter" data-level="B.13" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#BBUse"><i class="fa fa-check"></i><b>B.13</b> ベータ遮断薬使用</a></li>
<li class="chapter" data-level="B.14" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#DLoopUse"><i class="fa fa-check"></i><b>B.14</b> ループ利尿薬使用</a></li>
<li class="chapter" data-level="B.15" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#DPUse"><i class="fa fa-check"></i><b>B.15</b> カリウム保持性利尿薬使用</a></li>
<li class="chapter" data-level="B.16" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#A1BUse"><i class="fa fa-check"></i><b>B.16</b> アルファ1遮断薬使用</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="NegativeControlsAppendix.html"><a href="NegativeControlsAppendix.html"><i class="fa fa-check"></i><b>C</b> ネガティブコントロール</a>
<ul>
<li class="chapter" data-level="C.1" data-path="NegativeControlsAppendix.html"><a href="NegativeControlsAppendix.html#AceiThzNsc"><i class="fa fa-check"></i><b>C.1</b> ACE阻害薬とサイアザイド・サイアザイド様利尿薬</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="ProtocolTemplate.html"><a href="ProtocolTemplate.html"><i class="fa fa-check"></i><b>D</b> プロトコルテンプレート</a></li>
<li class="chapter" data-level="E" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html"><i class="fa fa-check"></i><b>E</b> 回答例</a>
<ul>
<li class="chapter" data-level="E.1" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Cdmanswers"><i class="fa fa-check"></i><b>E.1</b> 共通データモデル</a></li>
<li class="chapter" data-level="E.2" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Vocabanswers"><i class="fa fa-check"></i><b>E.2</b> 標準化されたボキャブラリ</a></li>
<li class="chapter" data-level="E.3" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Etlanswers"><i class="fa fa-check"></i><b>E.3</b> ETL (Extract-Transform-Load)</a></li>
<li class="chapter" data-level="E.4" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#UseCasesanswers"><i class="fa fa-check"></i><b>E.4</b> データ分析のユースケース</a></li>
<li class="chapter" data-level="E.5" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#SqlAndRanswers"><i class="fa fa-check"></i><b>E.5</b> SQLとR</a></li>
<li class="chapter" data-level="E.6" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Cohortsanswers"><i class="fa fa-check"></i><b>E.6</b> コホートの定義</a></li>
<li class="chapter" data-level="E.7" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Characterizationanswers"><i class="fa fa-check"></i><b>E.7</b> 特性評価</a></li>
<li class="chapter" data-level="E.8" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Pleanswers"><i class="fa fa-check"></i><b>E.8</b> 集団レベルの推定</a></li>
<li class="chapter" data-level="E.9" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#Plpanswers"><i class="fa fa-check"></i><b>E.9</b> 患者レベルの予測</a></li>
<li class="chapter" data-level="E.10" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#DataQualityanswers"><i class="fa fa-check"></i><b>E.10</b> データ品質</a></li>
<li class="chapter" data-level="E.11" data-path="SuggestedAnswers.html"><a href="SuggestedAnswers.html#section"><i class="fa fa-check"></i><b>E.11</b> </a></li>
</ul></li>
<li class="chapter" data-level="" data-path="参考文献.html"><a href="参考文献.html"><i class="fa fa-check"></i>参考文献</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">–翻訳作業中–　OHDSIの本</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="PopulationLevelEstimation" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">章 12</span> 集団レベルの推定<a href="PopulationLevelEstimation.html#PopulationLevelEstimation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><em>著者: Martijn Schuemie, David Madigan, Marc Suchard &amp; Patrick Ryan</em></p>
<p></p>
<p>保険請求データや電子的健康記録などの観察的な医療データは、治療の効果に関するリアルワールドのエビデンスを生成する機会を提供し、患者の生活を有意に改善することができます。本章では、特定の健康アウトカムに対する曝露（例えば、薬剤曝露や処置（プロシージャー）などの医療介入）の平均的な因果効果の推定を指す集団レベルの効果推定に焦点を当てます。以下では、2つの異なる推定タスクを検討します：</p>
<ul>
<li><strong>直接効果推定</strong>: アウトカムのリスクに対する曝露の効果を、曝露なしと比較して推定する。 </li>
<li><strong>比較効果推定</strong>: アウトカムのリスクに対する曝露（ターゲット曝露）の効果を、別の曝露（比較対照の曝露）と比較して推定する。 </li>
</ul>
<p>いずれの場合でも、患者レベルの因果効果は事実のアウトカム、すなわち曝露を受けた患者に何が起こったかと、反事実のアウトカム、すなわち曝露がなかった場合（直接）や異なる曝露があった場合（比較）に何が起こったかを対比させます。各患者は事実のアウトカムのみを明らかにするため（因果推論の基本問題）、さまざまな効果推定デザインは異なる分析デバイスを用いて反事実のアウトカムを明らかにします。 </p>
<p>集団レベルの効果推定のユースケースには、治療選択、安全性監視、および比較効果が含まれます。方法論は、特定の仮説を一度に1つずつテストすること（例：「シグナル評価」）や、複数の仮説を一度に探索すること（例：「シグナル検出」）ができます。いずれの場合も、目的は同じです：因果効果の高品質な推定を生成することです。 </p>
<p>本章ではまず、<a href="https://ohdsi.github.io/MethodsLibrary/">OHDSI Methods Library</a>としてRパッケージで実装されているさまざまな集団レベルの推定研究デザインについて説明します。次に、具体的な推定研究の設計を詳細に説明し、ATLASおよびRを使用してデザインを実装する手順ガイドを提供します。最後に、研究から生成されるさまざまな出力、包括的な研究診断と効果サイズの推定についてレビューします。</p>
<div id="CohortMethod" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> コホートメソッドの設計<a href="PopulationLevelEstimation.html#CohortMethod" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:cohortMethod"></span>
<img src="images/PopulationLevelEstimation/cohortMethod.png" alt="新規ユーザーコホートデザイン。ターゲット治療を開始した対象は比較対照治療を開始した対象と比較されます。2つの治療グループ間の違いを調整するために、傾向スコアによる層化、マッチング、重み付け、あるいはベースライン特性をアウトカムモデルに追加するなど、いくつかの調整戦略が使用されます。傾向スコアモデルまたはアウトカムモデルに含まれる特性は治療開始前に取得されます。" width="90%" />
<p class="caption">
図 12.1: 新規ユーザーコホートデザイン。ターゲット治療を開始した対象は比較対照治療を開始した対象と比較されます。2つの治療グループ間の違いを調整するために、傾向スコアによる層化、マッチング、重み付け、あるいはベースライン特性をアウトカムモデルに追加するなど、いくつかの調整戦略が使用されます。傾向スコアモデルまたはアウトカムモデルに含まれる特性は治療開始前に取得されます。
</p>
</div>
<p>コホートメソッドはランダム化臨床試験を模倣することを試みます <span class="citation">(<a href="#ref-hernan_2016">Hernan and Robins 2016</a>)</span>。 ある治療（ターゲット）を開始した対象は別の治療（比較対照）を開始した対象と比較され、治療開始後の特定の期間、例えば治療を継続する期間にわたって追跡されます。コホート研究において私たちが答えたい問いは、表 <a href="PopulationLevelEstimation.html#tab:cmChoices">12.1</a> にハイライトされた5つの選択を行うことで具体化されます。 </p>
<table>
<caption><span id="tab:cmChoices">表 12.1: </span> 比較コホートデザインの主要なデザイン選択</caption>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">選択</th>
<th align="left">説明</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ターゲットコホート</td>
<td align="left">対象とする治療を代表するコホート</td>
</tr>
<tr class="even">
<td align="left">比較対照コホート</td>
<td align="left">比較対照の治療を代表するコホート</td>
</tr>
<tr class="odd">
<td align="left">アウトカムコホート</td>
<td align="left">対象とするアウトカムを代表するコホート</td>
</tr>
<tr class="even">
<td align="left">リスク期間</td>
<td align="left">どの時点で（通常はターゲットおよび比較対照コホートの開始および終了日）アウトカムのリスクを考慮するか</td>
</tr>
<tr class="odd">
<td align="left">モデル</td>
<td align="left">ターゲットと比較対照の間の違いを調整しながら効果を推定するために使用されるモデル</td>
</tr>
</tbody>
</table>
<p>モデルの選択には、他の要素の中でも、アウトカムモデルの種類が含まれます。例えば、ロジスティック回帰を使用することができ、これはアウトカムが発生したかどうかを評価し、オッズ比を生成します。ロジスティック回帰はリスク期間がターゲットと比較対照で同じ長さであるか、または関係がないと仮定します。あるいは、一定の発生率を仮定するポアソン回帰を選択することもできます。多くの場合、対象と比較対照の間で比例ハザードを仮定し、最初のアウトカムまでの時間を考慮してハザード比を推定するコックス回帰が使用されます。 </p>

<div class="rmdimportant">
<p>新規ユーザーコホートメソッドは本質的に比較効果推定の方法であり、治療を比較対照と比較します。この方法を使用して治療対未治療を比較するのは難しいです。なぜなら、未曝露群と曝露群が比較可能となる群を定義するのが難しいからです。このデザインを直接的な効果推定に使用したい場合は、対象とする曝露に対する比較対照として、同じ適応症の治療を選択するのが望ましいです。ただし、必ずしもそのような比較対照が利用可能であるとは限りません。</p>
</div>
<p>重要な懸念事項は、ターゲット治療を受ける患者が比較対照治療を受ける患者と系統的に異なる可能性があることです。例えば、ターゲットコホートが平均60歳であり、比較対照コホートが平均40歳であるとします。年齢に関連する健康アウトカム（例：脳卒中）に関してターゲットと比較対照を比較する場合、コホート間で顕著な違いが見られるかもしれません。無知な研究者は、ターゲット治療と比較対照に比べて脳卒中の間に因果関係があると結論づけるかもしれません。もっと平凡な、あるいはありふれた結論として、ターゲット患者が脳卒中を経験したことが、比較対照を受けていたらそうならなかったであろうと結論づけるかもしれません。この結論は完全に間違っている可能性があります！おそらくこれらのターゲット患者は、ただ年を取っているだけで脳卒中が発生したかもしれません。治療を受けていたとしても同様であった可能性があります。この文脈では、年齢は「交絡因子」です。観察研究で交絡因子に対処する一つのメカニズムは傾向スコアを介することです。 </p>
<div id="傾向スコア" class="section level3 hasAnchor" number="12.1.1">
<h3><span class="header-section-number">12.1.1</span> 傾向スコア<a href="PopulationLevelEstimation.html#傾向スコア" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p></p>
<p>ランダム化試験では、（仮想的な）コイントスが患者を各グループに割り当てます。したがって、デザインによって、患者がターゲット治療を受ける確率は患者の特性（例：年齢）とは無関係です。コインは患者を知りませんし、何よりも、曝露を受ける患者の確率は確実に分かっています。その結果、試験の患者数が増えるにつれて、両方のグループの患者はどのような患者特性においても系統的に異なることは基本的にありえません。この保証されたバランスは、試験で測定された特性（例：年齢）と試験で特定されなかった特性（例：患者の遺伝的要因）にも適用されます。 </p>
<p>ある患者に対する<em>傾向スコア（PS）</em>は、その患者が比較対照群に対して対象治療をを受ける確率です <span class="citation">(<a href="#ref-rosenbaum_1983">Rosenbaum and Rubin 1983</a>)</span>。 バランスの取れたランダム化試験では、傾向スコアはすべての患者で0.5です。傾向スコアで補正された観察研究では、治療開始時とその前のデータに基づいて患者が対象治療を受ける確率を推定します（実際に受けた治療に関係なく）。これは単純な予測モデリングの応用です。ロジスティック回帰などのモデルを適合させ、患者が対象治療を受けるかどうかを予測し、各対象者の予測確率（PS）を生成するためにこのモデルを使用します。標準的なランダム化試験とは異なり、各患者は異なる確率で対象治療を受けることになります。PSは、PSが似たターゲット対象者と比較対照の対象者をマッチングする、PSに基づいて研究集団を層化する、PSから導き出された治療重み付けの逆確率（IPTW）を使うなど、いくつかの方法で使用できます。マッチングの場合、各対象者に対して一人の比較対照者だけを選択することも、一人以上の比較対照者を許容することもできます。これは可変比率マッチングと呼ばれる手法です <span class="citation">(<a href="#ref-rassen_2012">Rassen et al. 2012</a>)</span>。 </p>
<p>例えば、1対1のPSマッチングを使用し、ヤンが対象治療を受ける事前確率が0.4で、実際に対象治療を受けたとします。もし、対象治療を受ける事前確率が0.4で、実際には比較治療を受けた患者（ジュンと名付けます）を見つけることができれば、少なくとも測定された交絡因子に関しては、ヤンとジュンの結果の比較はミニ無作為化試験のようなものとなります。この比較により、無作為化で得られたものと同等のヤンとジュンの因果コントラストの推定値が得られます。推定は以下のように行われます。対象治療を受けた患者ごとに、比較対象治療を受けたが対象治療を受ける以前の確率が同じであった1人以上の適合患者を見つけます。対象患者のアウトカムと、これらの適合グループ内の比較対象患者のアウトカムを比較します。</p>
<p>傾向スコアは、測定された交絡因子を制御します。実際、測定された特性を考慮して治療割り当てが「無視できる」場合、傾向スコアは因果効果の偏りのない推定値を導きます。「無視できる」とは、本質的には、未測定の交絡因子が存在せず、測定された交絡因子が適切に調整されていることを意味します。残念ながら、これは検証可能な仮定ではありません。この問題に関するさらなる議論については、第 <a href="MethodValidity.html#MethodValidity">18</a> 章で説明します。 </p>
</div>
<div id="VariableSelection" class="section level3 hasAnchor" number="12.1.2">
<h3><span class="header-section-number">12.1.2</span> 変数選択<a href="PopulationLevelEstimation.html#VariableSelection" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
以前は、PSは手動で選択された特性に基づいて計算されていましたが、OHDSIツールはそのような実践をサポートする一方で、特定の曝露やアウトカムに基づいて選択されていない、より多くの汎用特性を使用することを好みます <span class="citation">(<a href="#ref-tian_2018">Tian, Schuemie, and Suchard 2018</a>)</span> 。これらの特性には、人口統計学的特性に加え、治療開始前および当日に観察された診断、薬剤曝露、測定値、医療処置が含まれます。通常、モデルには10,000から100,000の固有の特性が含まれ、これらを大規模な正則化回帰 <span class="citation">(<a href="#ref-suchard_2013">Suchard et al. 2013</a>)</span> を使用して適合させ、<a href="https://ohdsi.github.io/Cyclops/">Cyclops</a>パッケージで実装します。本質的には、どの特性が治療割り当ての予測に関連するかをデータに決定させ、モデルに含めます。</p>

<div class="rmdimportant">
<p>通常、治療開始日の特性は治療の原因となる診断などの多くの関連データがその日に記録されているため、共変量捕捉のウィンドウに含まれるべきです。この日には、対象および比較対照の治療自体も記録されていますが、これらは傾向スコアモデルに含まれるべきではありません。なぜなら、私たちはまさにこれらを予測しようとしているからです。したがって、対象と比較対照治療は共変量セットから明示的に除外する必要があります。</p>
</div>
<p>「正しい」因果構造を特定する際に臨床的専門知識に依存しないデータ主導型の共変量選択アプローチは、いわゆる操作変数や共変変数を誤って含めるリスクがあり、その結果、分散が増加し、潜在的にバイアスがもたらされる可能性があるという意見もあります <span class="citation">(<a href="#ref-hernan_2002">Hernan et al. 2002</a>)</span>。しかし、このような懸念は現実のシナリオでは大きな影響を与える可能性は低いでしょう<span class="citation">(<a href="#ref-schneeweiss_2018">Schneeweiss 2018</a>)</span>。さらに、医学においては真の因果構造が判明することはほとんどなく、異なる研究者が特定の研究課題に対して「正しい」共変量を特定するように求められると、それぞれの研究者は必ず異なるリストを作成し、そのプロセスを再現不能にします。最も重要なのは、傾向スコアモデルの確認、すべての共変量のバランス評価、およびネガティブコントロールの組み込みなどの診断によって、コライダーや操作変数に関連するほとんどの問題を特定できることです。 </p>
</div>
<div id="カリパー" class="section level3 hasAnchor" number="12.1.3">
<h3><span class="header-section-number">12.1.3</span> カリパー<a href="PopulationLevelEstimation.html#カリパー" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p></p>
<p>傾向スコアは 0 から 1 の範囲で連続的に変化するため、厳密なマッチングはほとんど不可能です。その代わり、マッチングプロセスでは、「カリパー」として知られるある程度の許容範囲内で、対象患者の傾向スコアに一致する患者を見つけます <span class="citation">Austin (<a href="#ref-austin_2011">2011</a>)</span> に従い、ロジットスケールにおける標準偏差の0.2倍をデフォルトのキャピラとして使用します。</p>
</div>
<div id="オーバーラップ選好スコア" class="section level3 hasAnchor" number="12.1.4">
<h3><span class="header-section-number">12.1.4</span> オーバーラップ：選好スコア<a href="PopulationLevelEstimation.html#オーバーラップ選好スコア" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p></p>
<p>傾向スコア方法は一致する患者が存在することを必要とします。このため、主要な診断は二つのグループの傾向スコアの分布を示します。解釈を容易にするために、OHDSIツールは「選好スコア」<a href="mailto:と呼ばれる傾向スコアの変換をプロットします@walker" class="email">と呼ばれる傾向スコアの変換をプロットします@walker</a>_2013。選好スコアは二つの治療の「市場占有率」を調整します。例えば、10%の患者が対象治療を受け（90%の患者が比較対照治療を受ける）、選好スコアが0.5の患者は、対象治療を受ける確率が10%です。数学的には、選好スコアは</p>
<p><span class="math display">\[\ln\left(\frac{F}{1-F}\right)=\ln\left(\frac{S}{1-S}\right)-\ln\left(\frac{P}{1-P}\right)\]</span></p>
<p>ここで <span class="math inline">\(F\)</span> は選好スコア、<span class="math inline">\(S\)</span> は傾向スコア、<span class="math inline">\(P\)</span> は対象治療を受ける患者の割合です。</p>
<p><span class="citation">Walker et al. (<a href="#ref-walker_2013">2013</a>)</span> は「経験的均衡」の概念を述べています。彼らは、少なくとも半数の曝露が選好スコアの0.3から0.7の間にある場合、これらの曝露ペアを経験的均衡にあると見なします。 </p>
</div>
<div id="バランス" class="section level3 hasAnchor" number="12.1.5">
<h3><span class="header-section-number">12.1.5</span> バランス<a href="PopulationLevelEstimation.html#バランス" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p> </p>
<p>優れた実践では常にPS調整がバランスの取れた患者群を生成するかどうかをチェックします。図 <a href="PopulationLevelEstimation.html#fig:balance">12.19</a>はバランスをチェックするための標準的なOHDSI出力を示しています。各患者特性について、曝露グループ間の平均の標準化差をPS調整前後でプロットします。いくつかのガイドラインは、PS調整後の標準化差の上限を0.1とすることを推奨しています <span class="citation">(<a href="#ref-rubin_2001">Rubin 2001</a>)</span>。</p>
</div>
</div>
<div id="自己対照コホートデザイン" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> 自己対照コホートデザイン<a href="PopulationLevelEstimation.html#自己対照コホートデザイン" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:scc"></span>
<img src="images/PopulationLevelEstimation/selfControlledCohort.png" alt="自己対照コホートデザイン。対象への曝露中のアウトカムの発生率を曝露前の期間中の発生率と比較します。" width="90%" />
<p class="caption">
図 12.2: 自己対照コホートデザイン。対象への曝露中のアウトカムの発生率を曝露前の期間中の発生率と比較します。
</p>
</div>
<p>自己対照コホート（SCC）デザイン <span class="citation">(<a href="#ref-ryan_2013">Ryan, Schuemie, and Madigan 2013</a>)</span> は曝露中のアウトカムの発生率を、曝露直前の期間におけるアウトカムの発生率と比較します。表 <a href="PopulationLevelEstimation.html#tab:sccChoices">12.2</a> に示す4つの選択肢が、自己対照コホートの問いを定義します。 </p>
<table>
<caption><span id="tab:sccChoices">表 12.2: </span>自己対照コホートデザインの主要なデザイン選択肢。</caption>
<colgroup>
<col width="16%" />
<col width="83%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">選択</th>
<th align="left">説明</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">対象コホート</td>
<td align="left">治療を表すコホート</td>
</tr>
<tr class="even">
<td align="left">アウトカムコホート</td>
<td align="left">対象とするアウトカムを表すコホート</td>
</tr>
<tr class="odd">
<td align="left">リスク時間</td>
<td align="left">アウトカムのリスクをどのタイミング（通常対象コホートの開始および終了日が基準）で考慮するか？</td>
</tr>
<tr class="even">
<td align="left">対照時間</td>
<td align="left">対照時間として使用される期間</td>
</tr>
</tbody>
</table>
<p>曝露群を構成する同じ対象者が対照群としても使用されるため、対象者間の差異を調整する必要はありません。ただし、この方法は、異なる期間間におけるアウ トカムのベースラインリスクの差異など、その他の違いには脆弱です。</p>
</div>
<div id="症例対照デザイン" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> 症例対照デザイン<a href="PopulationLevelEstimation.html#症例対照デザイン" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:caseControl"></span>
<img src="images/PopulationLevelEstimation/caseControl.png" alt="症例対照デザイン。アウトカムを持つ対象者（「症例」）は、アウトカムを持たない対象者（「対照」）との曝露状況の観点から比較されます。通常、症例と対照は年齢や性別などの様々な特性で一致するようにします。" width="90%" />
<p class="caption">
図 12.3: 症例対照デザイン。アウトカムを持つ対象者（「症例」）は、アウトカムを持たない対象者（「対照」）との曝露状況の観点から比較されます。通常、症例と対照は年齢や性別などの様々な特性で一致するようにします。
</p>
</div>
<p>症例対照研究 <span class="citation">(<a href="#ref-vandenbroucke_2012">Vandenbroucke and Pearce 2012</a>)</span> は、「特定の疾患のアウトカムを持つ人が、その疾患を持たない人よりも特定の因子により曝露される頻度が高いかどうか」を検討します。このため、中心となる考え方は、対象とするアウトカムを経験した対象者（「症例」）を、対象とするアウトカムを経験していない対象者（「対照」）と比較することです。表 <a href="PopulationLevelEstimation.html#tab:ccChoices">12.3</a> の選択肢が、症例対照の問いを定義しています。 </p>
<table>
<caption><span id="tab:ccChoices">表 12.3: </span>症例対照デザインの主要なデザイン選択オプション</caption>
<colgroup>
<col width="19%" />
<col width="80%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">選択</th>
<th align="left">説明</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">アウトカムコホート</td>
<td align="left">症例（対象とするアウトカム）を表すコホート</td>
</tr>
<tr class="even">
<td align="left">対照コホート</td>
<td align="left">対照を表すコホート。通常、選択ロジックを使用してアウトカムコホートから自動的に導出される</td>
</tr>
<tr class="odd">
<td align="left">対象コホート</td>
<td align="left">治療を表すコホート</td>
</tr>
<tr class="even">
<td align="left">ネスティングコホート</td>
<td align="left">任意で症例および対照が抽出されるサブポピュレーションを定義するコホートを指定</td>
</tr>
<tr class="odd">
<td align="left">リスク時間</td>
<td align="left">曝露状況をどのタイミング（通常、インデックス日が基準）で考慮するか？</td>
</tr>
</tbody>
</table>
<p>通常、症例を年齢や性別などの特性で一致させて対照を選択し、症例と対照を比較しやすくします。もう1つの広く行われている方法は、対象とする曝露のいずれかの適応症と診断されたすべての人々など、特定のサブグループに分けて分析を行うことです。</p>
</div>
<div id="ケースクロスオーバーデザイン" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> ケース・クロスオーバーデザイン<a href="PopulationLevelEstimation.html#ケースクロスオーバーデザイン" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:caseCrossover"></span>
<img src="images/PopulationLevelEstimation/caseCrossover.png" alt="ケース・クロスオーバーデザイン。アウトカムの周りの時間を、アウトカムの日付より前の事前に決められた間隔のコントロール日と比較します。" width="90%" />
<p class="caption">
図 12.4: ケース・クロスオーバーデザイン。アウトカムの周りの時間を、アウトカムの日付より前の事前に決められた間隔のコントロール日と比較します。
</p>
</div>
<p>ケース・クロスオーバー <span class="citation">(<a href="#ref-maclure_1991">Maclure 1991</a>)</span> デザインは、アウトカムのタイミングでの曝露率が、アウトカムよりも前の事前に決められた日数での曝露率と異なるかどうかを評価します。これは、アウトカムが発生した日に特別な理由があるかどうかを判断しようとするものです。表 <a href="PopulationLevelEstimation.html#tab:ccrChoices">12.4</a> は、ケース・クロスオーバーの質問を定義するオプションを示します。 </p>
<table>
<caption><span id="tab:ccrChoices">表 12.4: </span>ケース・クロスオーバーデザインの主要なデザインオプション</caption>
<colgroup>
<col width="22%" />
<col width="77%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">選択</th>
<th align="left">説明</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">アウトカムコホート</td>
<td align="left">症例（対象とするアウトカム）を表すコホート</td>
</tr>
<tr class="even">
<td align="left">対象コホート</td>
<td align="left">治療を表すコホート</td>
</tr>
<tr class="odd">
<td align="left">リスク時間</td>
<td align="left">曝露状況をどのタイミング（通常インデックス日が基準）で考慮するか</td>
</tr>
<tr class="even">
<td align="left">対照時間</td>
<td align="left">対照時間として使用される期間</td>
</tr>
</tbody>
</table>
<p>症例は自分自身が対照として機能します。自己対照デザインであるため、個人間の差異による交絡に対して頑健であるはずです。ただし、アウトカムの日付が常に対照の日付よりも後であるため、曝露の全体的な頻度が時間とともに増加する（または減少する）場合には、この方法がポジティブにバイアスを受ける可能性があります。この問題に対処するために、ケース-タイム-コントロールデザイン <span class="citation">(<a href="#ref-suissa_1995">Suissa 1995</a>)</span> が開発され、例えば年齢や性別で一致させた対照をケース・クロスオーバーデザインに追加して、曝露のトレンドを調整します。</p>
</div>
<div id="自己対照症例シリーズデザイン" class="section level2 hasAnchor" number="12.5">
<h2><span class="header-section-number">12.5</span> 自己対照症例シリーズデザイン<a href="PopulationLevelEstimation.html#自己対照症例シリーズデザイン" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:selfControlledCaseSeries"></span>
<img src="images/PopulationLevelEstimation/selfControlledCaseSeries.png" alt="自己対照症例シリーズデザイン。曝露期間中のアウトカム発生率と非曝露期間中のアウトカム発生率を比較する。" width="90%" />
<p class="caption">
図 12.5: 自己対照症例シリーズデザイン。曝露期間中のアウトカム発生率と非曝露期間中のアウトカム発生率を比較する。
</p>
</div>
<p>自己対照症例シリーズ（SCCS）デザイン <span class="citation">(<a href="#ref-farrington_1995">Farrington 1995</a>; <a href="#ref-whitaker_2006">Whitaker et al. 2006</a>)</span> は、曝露期間中のアウトカム発生率を、曝露前、曝露中、曝露後のすべての非曝露期間中の発生率と比較します。これは、個人に依存したポアソン回帰であり、「患者がアウトカムを有する場合、曝露期間中の方が非曝露期間中よりもアウトカムが発生しやすいか？」という問い対する答えを導きだそうとします。表 <a href="PopulationLevelEstimation.html#tab:sccsChoices">12.5</a>のオプションは SCCS の問いを定義しています。 </p>
<table>
<caption><span id="tab:sccsChoices">表 12.5: </span>自己対照症例シリーズデザインの主なデザインオプション</caption>
<colgroup>
<col width="15%" />
<col width="84%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">選択</th>
<th align="left">説明</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">対象コホート</td>
<td align="left">治療を代表するコホート</td>
</tr>
<tr class="even">
<td align="left">アウトカムコホート</td>
<td align="left">対象とするアウトカムを代表するコホート</td>
</tr>
<tr class="odd">
<td align="left">リスク期間</td>
<td align="left">どの時点（多くの場合、対象コホートの開始日または終了日と関連のある時点）でアウトカムのリスクを考慮するか？</td>
</tr>
<tr class="even">
<td align="left">モデル</td>
<td align="left">時間変動する交絡因子の調整を含む効果の推定モデル</td>
</tr>
</tbody>
</table>
<p>他の自己対照デザインと同様に、SCCS は個人間の差異による交絡に対して頑健ですが、時間変動する影響による交絡には脆弱です。これらを考慮するためのいくつかの調整が可能であり、たとえば年齢や季節を含めることができます。SCCSの特別なバリアントでは、対象とする曝露だけでなく、データベースに記録された他の薬剤すべての曝露を含める <span class="citation">(<a href="#ref-simpson_2013">Simpson et al. 2013</a>)</span>ことで、モデルに数千の追加変数が追加されます。この場合、対象とする曝露以外のすべての曝露の係数に、正則化ハイパーパラメータをクロスバリデーションで選択するL1正則化が適用されます。</p>
<p>SCCSの重要な仮定の一つは、観察期間の終了がアウトカムの日付とは独立していることです。一部のアウトカム、特に心筋梗塞などの致命的なアウトカムにおいては、この仮定が当てはまらないことがあります。SCCSの拡張版が開発されており、このような依存関係を修正できるものがあります <span class="citation">(<a href="#ref-farrington_2011">Farrington et al. 2011</a>)</span>。</p>
</div>
<div id="高血圧症研究のデザイン" class="section level2 hasAnchor" number="12.6">
<h2><span class="header-section-number">12.6</span> 高血圧症研究のデザイン<a href="PopulationLevelEstimation.html#高血圧症研究のデザイン" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="問題の定義-1" class="section level3 hasAnchor" number="12.6.1">
<h3><span class="header-section-number">12.6.1</span> 問題の定義<a href="PopulationLevelEstimation.html#問題の定義-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ACE 阻害薬（ACEi）は、高血圧症や虚血性心疾患を持つ患者、特にうっ血性心不全、糖尿病、慢性腎臓病などの併存疾患を持つ患者によく使用されます <span class="citation">(<a href="#ref-zaman_2002">Zaman, Oparil, and Calhoun 2002</a>)</span>。血管性浮腫は、唇、舌、口、喉頭、咽頭、または眼窩周囲の腫れとして現れる、深刻で時には命に関わる有害事象であり、これらの薬剤の使用と関連付けられています <span class="citation">(<a href="#ref-sabroe_1997">Sabroe and Black 1997</a>)</span>。しかし、これらの薬剤使用に関連する血管性浮腫の絶対および相対リスクについての情報は限られています。既存のエビデンスは、主に特定のコホート（例えば、主に男性の退役軍人やメディケイド受給者）に基づいたものであり、他の集団に一般化できない可能性があります。また、イベント数が少ない研究に基づくものであり、不安定なリスク推定しかえられません <span class="citation">(<a href="#ref-powers_2012">Powers et al. 2012</a>)</span>。いくつかの観察研究は、ACEiをβ遮断薬と比較して血管性浮腫のリスクを評価しています <span class="citation">(<a href="#ref-magid_2010">Magid et al. 2010</a>; <a href="#ref-toh_2012">Toh et al. 2012</a>)</span>が、β遮断薬はもはや高血圧症の第一選択治療役としては推奨されていません <span class="citation">(<a href="#ref-whelton_2018">Whelton et al. 2018</a>)</span>。代替治療法として有効なのは、サイアザイド系およびサイアザイド様利尿薬（THZ）が考えられます。これらは高血圧症や急性心筋梗塞（AMI）などの関連リスクを管理する上で同等に有効であり、血管性浮腫のリスクを増加させない可能性があります。</p>
<p>以下では、観察医療データに集団レベル推定フレームワークを適用し、次の比較推定に関する疑問に対処する方法を示します：</p>
<blockquote>
<p>ACE阻害薬の新規使用者とサイアザイド系およびサイアザイド様利尿薬の新規使用者を比較した場合の血管性浮腫のリスクはどれくらいですか？</p>
</blockquote>
<blockquote>
<p>ACE阻害薬の新規使用者とサイアザイド系およびサイアザイド様利尿薬の新規使用者を比較した場合の急性心筋梗塞のリスクはどれくらいですか？</p>
</blockquote>
<p>これらは比較効果推定の問題であるため、セクション @ref (CohortMethod) で説明されたコホート方法を適用します。</p>
</div>
<div id="対象および比較対照" class="section level3 hasAnchor" number="12.6.2">
<h3><span class="header-section-number">12.6.2</span> 対象および比較対照<a href="PopulationLevelEstimation.html#対象および比較対照" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>高血圧症に対する最初の治療が、ACEi または THZ クラスのいずれかの有効成分による単剤療法であった患者を、新規患者と見なします。治療開始後7日以内に他の抗高血圧薬を開始しない患者を単剤療法と定義します。患者は最初の曝露前に少なくとも1年間の継続的な観察期間および治療開始前１年以内に高血圧症と診断された記録が必要です。</p>
</div>
<div id="アウトカム-1" class="section level3 hasAnchor" number="12.6.3">
<h3><span class="header-section-number">12.6.3</span> アウトカム<a href="PopulationLevelEstimation.html#アウトカム-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>血管性浮腫は、入院または救急外来（ER）訪問中の血管性浮腫のコンセプトに該当するコンディションが発生した場合と定義し、その7日前までには血管性浮腫の診断が記録されていないことを必要とします。AMIは、入院またはER訪問中のAMIコンディションコンセプトの発生として定義し、180日前までにAMI診断が記録されていないことを必要とします。</p>
</div>
<div id="リスク期間-1" class="section level3 hasAnchor" number="12.6.4">
<h3><span class="header-section-number">12.6.4</span> リスク期間<a href="PopulationLevelEstimation.html#リスク期間-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>リスク期間を治療開始の翌日から開始し、曝露が終了するまでと定義し、後続の薬剤曝露の間に30日間のギャップを許容します。</p>
</div>
<div id="モデル" class="section level3 hasAnchor" number="12.6.5">
<h3><span class="header-section-number">12.6.5</span> モデル<a href="PopulationLevelEstimation.html#モデル" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>デフォルトの共変量セットを使用してPSモデルを適合させます。このセットには、人口統計、病状、薬剤、処置、測定値、観察、いくつかの併存疾患スコアが含まれます。ACEiとTHZを共変量から除外します。変数比率マッチングを行い、マッチングセットに条件付けてコックス回帰を行います。</p>
</div>
<div id="研究要約" class="section level3 hasAnchor" number="12.6.6">
<h3><span class="header-section-number">12.6.6</span> 研究要約<a href="PopulationLevelEstimation.html#研究要約" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<caption><span id="tab:aceChoices">表 12.6: </span> 比較コホート研究の主なデザインオプション</caption>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">選択肢</th>
<th align="left">値</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">対象コホート</td>
<td align="left">高血圧症の第一選択単剤療法としてのACE阻害薬の新規使用者。</td>
</tr>
<tr class="even">
<td align="left">比較コホート</td>
<td align="left">高血圧症の第一選択単剤療法としてのサイアザイド系およびサイアザイド様利尿薬の新規使用者。</td>
</tr>
<tr class="odd">
<td align="left">アウトカムコホート</td>
<td align="left">血管性浮腫または急性心筋梗塞。</td>
</tr>
<tr class="even">
<td align="left">リスク期間</td>
<td align="left">治療開始の翌日から開始し、曝露が終了するまで。</td>
</tr>
<tr class="odd">
<td align="left">モデル</td>
<td align="left">変数比率マッチングを用いたコックス比例ハザードモデル。</td>
</tr>
</tbody>
</table>
</div>
<div id="コントロールクエスチョン" class="section level3 hasAnchor" number="12.6.7">
<h3><span class="header-section-number">12.6.7</span> コントロールクエスチョン<a href="PopulationLevelEstimation.html#コントロールクエスチョン" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>研究デザインが真実に沿った推定を生成するかどうかを評価するために、真の効果量が既知であるコントロールクエスチョンのセットを追加で含めます。コントロールクエスチョンは、ハザード比が1であるネガティブコントロールと、ハザード比が1より大きいことが既知であるポジティブコントロールに分けることができます。いくつかの理由により、実際のネガティブコントロールを使用し、これらのネガティブコントロールに基づいてポジティブコントロールを合成します。コントロールクエスチョンの定義と使用方法については、第 <a href="MethodValidity.html#MethodValidity">18</a> 章で説明しています。</p>
</div>
</div>
<div id="PleAtlas" class="section level2 hasAnchor" number="12.7">
<h2><span class="header-section-number">12.7</span> ATLASを使用した研究の実施<a href="PopulationLevelEstimation.html#PleAtlas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>ここでは、ATLASの推定機能を使用してこの研究を実施する方法を示します。ATLASの左側のバーで <img src="images/PopulationLevelEstimation/estimation.png" /> をクリックし、新しい推定研究を作成します。研究に簡単に分かりやすい名前を付けてください。研究デザインは <img src="images/PopulationLevelEstimation/save.png" /> ボタンをクリックして保存できます。</p>
<p>推定デザイン機能には、比較、分析設定、評価設定の3つのセクションがあります。複数の比較と複数の分析設定を指定でき、ATLASはそれらのすべての組み合わせを個別の分析として実行します。ここでは、それぞれのセクションについて説明します。</p>
<div id="ComparisonSettings" class="section level3 hasAnchor" number="12.7.1">
<h3><span class="header-section-number">12.7.1</span> 比較コホート設定<a href="PopulationLevelEstimation.html#ComparisonSettings" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>研究には1つ以上の比較を含めることができます。「比較を追加」をクリックすると、新しいダイアログが開きます。 <img src="images/PopulationLevelEstimation/open.png" /> をクリックしてターゲットおよび比較コホートを選択します。「Add Outcome」をクリックして2つのアウトカムコホートを追加できます。コホートがすでにATLASで作成されていると仮定しています（第 <a href="Cohorts.html#Cohorts">10</a> 章を参照）。ターゲット（付録 <a href="CohortDefinitions.html#AceInhibitorsMono">B.2</a>）、比較（付録 <a href="CohortDefinitions.html#ThiazidesMono">B.5</a>）、アウトカム（付録 @ref(Angioedema）、付録 <a href="CohortDefinitions.html#Ami">B.3</a>）コホートの完全な定義は付録に記載されています。完了すると、ダイアログは図 <a href="PopulationLevelEstimation.html#fig:comparisons">12.6</a>のようになります。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:comparisons"></span>
<img src="images/PopulationLevelEstimation/comparisons.png" alt="比較ダイアログ" width="100%" />
<p class="caption">
図 12.6: 比較ダイアログ
</p>
</div>
<p>対象と比較コホートのペアに対して複数のアウトカムを選択できることに注意ください。各アウトカムは独立したものとして扱われ、別々の分析結果が得られます。</p>
<div id="ネガティブコントロールアウトカム" class="section level4 unnumbered hasAnchor">
<h4>ネガティブコントロールアウトカム<a href="PopulationLevelEstimation.html#ネガティブコントロールアウトカム" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>ネガティブコントロールのアウトカムは、対象または比較対照によって引き起こされていないと考えられるアウトカムであり、真のハザード比が1であると仮定されます。理想的には各アウトカムコホートの適切なコホート定義が必要ですが、通常は各ネガティブコントロールのアウトカムごとに1つのコンセプトセットと、それらをアウトカムコホートに変換するための標準的なロジックしか持ちません。ここではコンセプトセットが第 <a href="MethodValidity.html#MethodValidity">18</a> 章で説明されているとおり、すでに作成されていると仮定し、それを選択するだけです。ネガティブコントロールのコンセプトセットには、ネガティブコントロールごとに1つのコンセプトが含まれ、その下位層に含まれるものは含めるべきではありません。図 <a href="PopulationLevelEstimation.html#fig:ncConceptSet">12.7</a> は、この研究に使用されたネガティブコントロールのコンセプトセットを示しています。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ncConceptSet"></span>
<img src="images/PopulationLevelEstimation/ncConceptSet.png" alt="ネガティブコントロールのコンセプトセット" width="100%" />
<p class="caption">
図 12.7: ネガティブコントロールのコンセプトセット
</p>
</div>
</div>
<div id="含めるコンセプト" class="section level4 unnumbered hasAnchor">
<h4>含めるコンセプト<a href="PopulationLevelEstimation.html#含めるコンセプト" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>コンセプトを選択する際、生成したい共変量を指定できます。たとえば、傾向スコアモデルで使用するためです。ここで共変量を指定すると、それ以外の共変量（指定したもの以外）は除外されます。通常、ベースラインのすべての共変量を含め、正則化回帰モデルがすべての共変量をバランスさせるモデルを構築します。特定の共変量を指定する唯一の理由は、手動で共変量を選択した既存の研究を再現する場合です。これらの項目は、この比較セクションまたは分析セクションで指定できます。その理由は、特定の比較に関連する場合（たとえば、比較における既知の交絡因子）、または特定の共変量選択戦略を評価する場合など、分析に関連する場合があるからです。</p>
</div>
<div id="除外するコンセプト" class="section level4 unnumbered hasAnchor">
<h4>除外するコンセプト<a href="PopulationLevelEstimation.html#除外するコンセプト" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
含めるコンセプトを指定する代わりに、<em>除外</em>するコンセプトを指定することもできます。このフィールドにコンセプトセットを送信すると、送信したコンセプトを除くすべての共変量を使用します。デフォルトの共変量セット（治療開始日のすべての薬剤および処置を含む）を使用する場合、対象の治療と比較治療、およびそれらに直接関連するコンセプトを除外する必要があります。たとえば、対象とする曝露が注射薬である場合、薬剤だけでなく、プロペンシティモデルからその投与手技も除外する必要があります。この例では、除外したい共変量はACEiとTHZです。図 <a href="PopulationLevelEstimation.html#fig:covsToExclude">12.8</a> は、これらのコンセプトを含むコンセプトセットを示しています（その下位層も含まれます）。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:covsToExclude"></span>
<img src="images/PopulationLevelEstimation/covsToExclude.png" alt="除外するコンセプトを定義するコンセプトセット" width="100%" />
<p class="caption">
図 12.8: 除外するコンセプトを定義するコンセプトセット
</p>
</div>
<p>ネガティブコントロールと除外する共変量を選択した後、比較ダイアログの下半分は図 <a href="PopulationLevelEstimation.html#fig:comparisons2">12.9</a> のようになります。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:comparisons2"></span>
<img src="images/PopulationLevelEstimation/comparisons2.png" alt="ネガティブコントロールおよび除外するコンセプトセットを示す比較ウィンドウ" width="100%" />
<p class="caption">
図 12.9: ネガティブコントロールおよび除外するコンセプトセットを示す比較ウィンドウ
</p>
</div>
</div>
</div>
<div id="効果推定の分析設定" class="section level3 hasAnchor" number="12.7.2">
<h3><span class="header-section-number">12.7.2</span> 効果推定の分析設定<a href="PopulationLevelEstimation.html#効果推定の分析設定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>比較ダイアログを閉じた後、「Add Analysis Settings」をクリックできます。「Analysis Name」とラベル付けされたボックスには、今後、簡単に検索・参照できるよう固有の名前を入力します。たとえば、「傾向スコアマッチング」という名前を設定することもできます。</p>
<div id="研究対象集団" class="section level4 unnumbered hasAnchor">
<h4>研究対象集団<a href="PopulationLevelEstimation.html#研究対象集団" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>分析の対象となる対象者の集合である研究対象集団を指定するには、さまざまなオプションがあります。オプションの多くは、コホート定義ツールで対象および比較コホートを設計する際に利用可能なオプションと重複しています。Estimationのオプションを使用する理由の1つは再利用性です。ターゲット、比較、アウトカムコホートを完全に独立して定義し、後でそれらの間に依存関係を追加できます。例えば、治療開始前にアウトカムを持っていた人を除外したい場合、対象および比較コホートの定義でこれを行うことができますが、すべてのアウトカムごとに別のコホートを作成する必要があります。代わりに、分析設定で事前のアウトカムを持つ人々を除外することができ、これで興味のある2つのアウトカム（およびネガティブコントロールのアウトカム）に対して、対象および比較コホートを再利用できます。</p>
<p><strong>研究開始日と終了日</strong>を使用して、特定の期間に分析を制限できます。研究終了日はリスクウィンドウを切り詰めることになり、研究終了日以降のアウトカムは考慮されません。研究開始日を選択する理由の1つは、研究対象の薬剤の1つが新しく、以前の期間には存在しなかったことが考えられます。自動で調整するには、「両方の曝露がデータ内に存在する期間に分析を制限しますか？」の質問に「はい」と回答します。研究の開始日と終了日を調整するもう一つの理由は、医療行為が時とともに変化した（例えば、薬の警告による）場合で、特定の方法で医療行為が行われた期間のみに興味がある場合です。</p>
<p>オプション “<strong>Should only the first exposure per subject be included? (各対象者の初回の曝露のみを含まれるべきか)</strong>” を使用すると、患者ごとの最初の曝露に限定することができます。多くの場合、この例のようにコホート定義ですでに行われています。同様に、「<strong>The minimum required continuous observation time prior to index date for a person to be included in the cohort (コホートに含める対象者のインデックス日付以前の最小限必要な連続観察期間)</strong>」 というオプションは、コホート定義ですでに設定されていることが多いので、ここでは0のままにしておきます。インデックス日より前に観察時間がある(OBSERVATION_PERIODテーブルで定義されているように）ことは、傾向スコアを計算するのに十分な患者に関する情報があること、また患者が真の新規ユーザーであり、したがって以前に曝露されていないことを担保するためにもよく使われます。</p>
<p>“<strong>Remove subjects that are in both target and comparator cohort? (対象コホートと比較群コホートの両方に含まれる対象を除外しますか)</strong>”は、“<strong>If a subject is in multiple cohorts, should be censored time-at-risk when the new time-at-risk starts to prevent overlap? (対象が複数のコホートに含まれる場合、新しいリスク評価期間が開始された際に、重複を避けるためにリスク評価期間を打ち切りますか)</strong>” というオプションと併せて、対象が対象コホートと比較コホートの両方に存在する場合にどのように取り扱うかを定義します。最初の設定には3つの選択肢があります：</p>
<ul>
<li><p>“<strong>Keep All</strong> (すべて保持)” は、両方のコホートに対象を保持することを意味します。このオプションでは、対象者とアウトカムがダブルカウントされる可能性があります。</p></li>
<li><p>“<strong>Keep First</strong> (最初を保持)” は、最初に発生したコホートに対象者を残すことを意味します。</p></li>
<li><p>“<strong>Remove All</strong> (すべて除外)” は、すべてのコホートから対象者を除外することを意味します。</p></li>
</ul>
<p>もし “Keep All” または “Keep First” のオプションが選択された場合、ある対象が両方のコホートにいる時間を打ち切りたいと思うかもしれません。これを図 <a href="PopulationLevelEstimation.html#fig:tar">12.10</a> に示します。デフォルトでは、リスク期間はコホートの開始日と終了日を基準に定義されます。この例では、リスク期間はコホート開始の1日後に始まり、コホート終了までです。2つのコホートが重なる可能性があるリスク期間を打ち切らない場合、この重複したリスク期間に発生したアウトカムは、特に、すべてを保持することを選択した場合、（ここに示されているように）重複した時間に出現したアウトカムは2回カウントされるため、問題となります。打ち切りを選択した場合、最初のコホートのリスク期間は、2番目のコホートのリスク時間の開始時に終了します。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:tar"></span>
<img src="images/PopulationLevelEstimation/tar.png" alt="リスク時間（Time-at-risk (TAR)）が薬剤曝露開始日から薬剤曝露終了時までと仮定した場合の2つのコホートに含まれる対象のリスク期間" width="90%" />
<p class="caption">
図 12.10: リスク時間（Time-at-risk (TAR)）が薬剤曝露開始日から薬剤曝露終了時までと仮定した場合の2つのコホートに含まれる対象のリスク期間
</p>
</div>
<p>アウトカムの2回目の出現は1回目の継続であることが多いため、<strong>リスクウインドウが始まる前にアウトカムが出現した対象を除外する</strong>ことを選択できます。例えば、ある人が心不全を発症した場合、2回目の心不全の出現はよくあることでしょう、なぜなら1回目と2回目の心不全の間でその心不全は完全に治癒することがなかったということになるからです。一方、いくつかのアウトカムは間欠的なもので、上気道感染症のように、患者が複数の独立したアウトカムを持つことが予想されます。以前にそのアウトカムを経験した人を除外する場合、<strong>以前にアウトカムが出現したことを同定する際に何日前まで遡る</strong>かを選択できます。</p>
<p>、図 <a href="PopulationLevelEstimation.html#fig:studyPopulation">12.11</a> に、この研究例における選択を示します。対象コホートと比較対照コホートの定義は、すでに初回曝露に限定しており、治療開始前の観察時間が必要なので、ここではこれらの基準は適用しません。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:studyPopulation"></span>
<img src="images/PopulationLevelEstimation/studyPopulation.png" alt="研究対象集団の設定" width="100%" />
<p class="caption">
図 12.11: 研究対象集団の設定
</p>
</div>
</div>
<div id="共変量の設定" class="section level4 unnumbered hasAnchor">
<h4>共変量の設定<a href="PopulationLevelEstimation.html#共変量の設定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>ここでは構築する共変量を指定します。これらの共変量は通常、傾向スコアモデルで使用されますが、アウトカムモデル（この場合はCox比例ハザードモデル）にも含めることもできます。<strong>click to view details (詳細を見るにはここをクリック)</strong>をクリックすると、どの共変量の組み合わせを使用するか、選択することが出来ます。しかし、人口統計学的要素、コンディションすべて、薬剤、処置、測定値などを含むデフォルト</p>
<p><strong>include (組入れ)</strong>および/または<strong>exclude (除外)</strong>するコンセプトを指定することで、共変量のセットを変更できます。これらの設定は、セクション <a href="PopulationLevelEstimation.html#ComparisonSettings">12.7.1</a> にある比較のための設定と同じです。これらの設定が2つの場所にある理由は、これらの設定が特定の比較に関連している場合があるためです。特定の比較に対して特定の分析設定を使用して分析を実行する場合、OHDSIツールはこれらのセットの共通部分を使用します。</p>
<p>図 <a href="PopulationLevelEstimation.html#fig:covariateSettings">12.12</a> は、この研究で選択した内容を示しています。図 <a href="PopulationLevelEstimation.html#fig:comparisons2">12.9</a> に定義するように、比較の設定で除外するコンセプトに下位層を追加することを選択していることに注意ください。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:covariateSettings"></span>
<img src="images/PopulationLevelEstimation/covariateSettings.png" alt="共変量の設定" width="100%" />
<p class="caption">
図 12.12: 共変量の設定
</p>
</div>
</div>
<div id="リスク期間-2" class="section level4 unnumbered hasAnchor">
<h4>リスク期間<a href="PopulationLevelEstimation.html#リスク期間-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>リスク期間（Time-at-risk）は、対象コホートや比較コホートにおける開始日と終了日を基準に定義されます。例では、対象集団の開始日を治療開始日とし、終了日を曝露が停止した日（少なくとも30日間）としました。 リスクにさらされている期間の開始日を、対象集団の開始日の翌日、つまり治療開始日の翌日としました。コホート開始日よりも後の時点をリスク期間開始日とする理由は、生物学的にはその薬剤が原因である可能性が低いと考える場合、治療開始日に発生したアウトカム事象を除外したい場合があるからです。</p>
<p>リスク期間の終了日は、コホートの終了日、つまり曝露が停止した時点としました。例えば、治療終了直後の事象が依然として曝露に起因すると考えられる場合は、終了日を遅く設定することもできます。極端な例では、コホート終了日の後、長い日数を経て（例えば99999日）リスク期間の終了日に設定することもできます。このようなデザインは<em>intent-to-treat</em>デザインと呼ばれることもあります。</p>
<p>リスク時間がゼロの患者は何の情報も提供しないので、<strong>最小リスク日数</strong>は通常1日に設定されます。副作用の潜伏期間がわかっている場合は、より意味のある発生割合を得るため、この日数を増やすことができます。また、比較するランダム化試験に近いコホートを作成するために使用することもできます（例えば、ランダム化試験のすべての患者が少なくともN日間観察された）。</p>

<div class="rmdimportant">
コホート研究を計画する際の鉄則は、バイアスが含まれる可能性を排除するため、コホート開始日以降の情報を研究集団の定義に使用しないことです。例えば、全対象者に少なくとも1年間のリスク期間を要求した場合、解析対象は、治療に十分耐えられる人に限定することになります。そのため、この設定は細心の注意を払って行う必要があります。
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:timeAtRisk"></span>
<img src="images/PopulationLevelEstimation/timeAtRisk.png" alt="リスク期間の設定" width="100%" />
<p class="caption">
図 12.13: リスク期間の設定
</p>
</div>
</div>
<div id="傾向スコアによる調整" class="section level4 unnumbered hasAnchor">
<h4>傾向スコアによる調整<a href="PopulationLevelEstimation.html#傾向スコアによる調整" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>傾向スコア値が極端な人を除外して、研究対象集団を<strong>トリミングする</strong>ことができます。上位と下位の何パーセントを除外するか、または選好スコアが指定した範囲から外れる対象を除外するかを選択できます。コホートのトリミングは、一般的に推奨されません。なぜなら、観察を破棄する必要があり、統計的パワーが低下するからです。IPTWを使用する場合など、一部のケースではトリミングが望ましい場合があります。</p>
<p>トリミングに加えて、またはトリミングの代わりに、傾向スコアで<strong>層別化</strong>または<strong>マッチング</strong>を選択することができます。層別化する場合は、<strong>層数</strong>と、対象集団、比較対象集団、研究対象集団全体のいずれに基づいて層を選択するかを指定する必要があります。マッチングの際には、<strong>比較対照群から対象群の各人にマッチさせる最大人数</strong>を指定する必要があります。典型的な値は、1対1のマッチングの場合は1、変数比率マッチングの場合は大きな数（例えば100）になります。また、<strong>キャリパー</strong>、すなわちマッチングする傾向スコア間の最大許容差を指定する必要があります。キャリパーは差の<strong>キャリパー・スケール</strong>で定義できます：</p>
<ul>
<li><p><strong>傾向スコア尺度</strong>：傾向スコアそのもの</p></li>
<li><p><strong>標準化尺度</strong>：傾向スコア分布の標準偏差による</p></li>
<li><p><strong>標準化ロジット尺度</strong>：傾向スコアをより正規分布に近づけた後のプロスペクティブ・スコア分布の標準偏差。</p></li>
</ul>
<p>疑問がある場合は、デフォルト値を使用するか、 <a href="mailto:このトピックに関する@austin" class="email">このトピックに関する@austin</a>_2011 の研究を参照ください。</p>
<p>大規模な傾向スコアモデルの適合は計算コストがかかることがあるので、モデルの適合に使用するデータをデータのサンプルだけに制限することが望ましい場合があります。デフォルトでは、対象コホートと比較対照コホートの最大サイズは250,000に設定されています。ほとんどの研究では、この上限に達することはありません。また、データが多ければ多いほど、より良いモデルになることもまずありません。データのサンプルはモデルのフィットに適合させることはできますが、そのモデルは集団全体の傾向スコアを計算するために使用されることに注意してください。</p>
<p><strong>Test each covariate for correlation with the target assignment? (各共変量とターゲットの割付の相関を検定しますか。)</strong> 共変量が異常に高い相関（正または負）を持つ場合、エラーが発生します。これにより、完全に分離していることが判明するまで、傾向モデルの計算が長時間行われることを避けることができます。非常に高い単変量相関が見つかった場合は、その共変量を検証し、相関が高い理由と削除すべきかどうかを判断できます。</p>
<p><strong>Use regularization when fitting the model? (モデルを適合する際に正則化しますか。)</strong> 標準的な手順では、傾向モデルに多くの共変量（通常10,000以上）を含めます。このようなモデルを適合させるには何らかの正則化が必要です。少数の厳選された共変量のみが含まれる場合は、正則化なしでモデルを適合させることも可能です。</p>
<p>図 <a href="PopulationLevelEstimation.html#fig:psSettings">12.14</a> は、この研究での選択を示しています。最大マッチング人数を100人に設定することで、可変比率マッチングを選択していることに注意してください。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:psSettings"></span>
<img src="images/PopulationLevelEstimation/psSettings.png" alt="傾向スコアによる調整の設定" width="100%" />
<p class="caption">
図 12.14: 傾向スコアによる調整の設定
</p>
</div>
</div>
<div id="アウトカムモデルの設定" class="section level4 unnumbered hasAnchor">
<h4>アウトカムモデルの設定<a href="PopulationLevelEstimation.html#アウトカムモデルの設定" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>最初に、<strong>対象コホートと比較コホート間のアウトカムの相対リスクを推定するために使用する統計モデルを指定する</strong>必要があります。セクション <a href="PopulationLevelEstimation.html#CohortMethod">12.1</a> で簡単に述べたように、Cox、Poisson、ロジスティック回帰から選択できます。この例では、打ち切りの可能性がある最初のイベントまでの時間を考慮するCox比例ハザード・モデルを選択します。次に、回帰を<strong>層で条件付けるかどうか</strong>を指定する必要があります。条件づけを理解する1つの方法は、各層で別々の推定値が生成され、そして層で結合されること考えることです。1対1のマッチングでは、これは不要で、むしろ検出力を失うことになります。層別マッチングや可変比率マッチングでは必要です。 </p>
<p>また、<strong>共変量をアウトカムモデル</strong>に追加して分析を調整することもできます。これは傾向モデルを使うことに加えて、または代わりに行うことができます。しかし、傾向モデルに適合させるのに十分なデータが通常は存在し、両方の治療グループに多くの人が含まれる一方で、結果モデルに適合させるのに十分なデータは通常はほとんど存在せず、結果を持つ人はわずかしかいません。そのため、結果モデルはできるだけシンプルに保ち、追加の共変量を含めないことをお勧めします。</p>
<p>傾向スコアで層別化またはマッチングする代わりに、<strong>逆確率重み付け (IPTW)</strong>を用いることもできます。</p>
<p>アウトカムモデルにすべての共変量を含めることを選択した場合、共変量が多ければ、モデルを適合させるときに正則化を使用することが理にかなっているかもしれません。不偏推定を可能にするために、治療変数には正則化は適用されないことに注意してください。</p>
<p>図 <a href="PopulationLevelEstimation.html#fig:outcomeModelSettings">12.15</a> は、この研究での選択を示しています。可変比率マッチングを用いているため、回帰モデルでは層別条件付けをしなければなりません（マッチしたセットによって）。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:outcomeModelSettings"></span>
<img src="images/PopulationLevelEstimation/outcomeModelSettings.png" alt="アウトカムモデルの設定" width="100%" />
<p class="caption">
図 12.15: アウトカムモデルの設定
</p>
</div>
</div>
</div>
<div id="evaluationSettings" class="section level3 hasAnchor" number="12.7.3">
<h3><span class="header-section-number">12.7.3</span> 評価の設定<a href="PopulationLevelEstimation.html#evaluationSettings" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>第 <a href="MethodValidity.html#MethodValidity">18</a> 章にあるように、ネガティブコントロールとポジティブコントロールを検討し、操作特性を評価し、経験的キャリブレーションを行う必要があります。</p>
<div id="ネガティブコントロールのアウトカムコホートの定義" class="section level4 unnumbered hasAnchor">
<h4>ネガティブコントロールのアウトカムコホートの定義<a href="PopulationLevelEstimation.html#ネガティブコントロールのアウトカムコホートの定義" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>セクション <a href="PopulationLevelEstimation.html#ComparisonSettings">12.7.1</a> では、ネガティブコントロールのアウトカムを表すコンセプトセットを選択しました。しかし、分析でアウトカムとして使用するために、コンセプトをコホートに変換するロジックが必要です。ATLASは3つの選択肢を持つ標準ロジックを提供します。最初の選択肢は、<strong>コンセプトのすべての出現</strong>を使用するか、<strong>最初の出現</strong>のみを使用するかです。2番目の選択肢は、<strong>下位層のコンセプトの出現を考慮するかどうか</strong>を決定します。例えば、下位層の “ingrown nail of foot (足の陥入爪)” の出現も、上位層の “ingrown nail (陥入爪)” の出現として数えることができます。3番目の選択肢は、コンセプトを探すときにどのドメインを考慮するかを指定します。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ncSettings"></span>
<img src="images/PopulationLevelEstimation/ncSettings.png" alt="ネガティブコントロールのアウトカムコホートの定義の設定" width="100%" />
<p class="caption">
図 12.16: ネガティブコントロールのアウトカムコホートの定義の設定
</p>
</div>
</div>
<div id="ポジティブコントロールの合成" class="section level4 unnumbered hasAnchor">
<h4>ポジティブコントロールの合成<a href="PopulationLevelEstimation.html#ポジティブコントロールの合成" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>ネガティブコントロールに加えて、因果関係があると思われる曝露-アウトカムのペアで、効果量が既知であるポジティブコントロールも含めることができます。様々な理由から、実際のポジティブコントロールには問題があるため、代わりに、第 <a href="MethodValidity.html#MethodValidity">18</a> 章で説明したように、ネガティブコントロールから得られる合成ポジティブコントロールを用いることがあります。<strong>ポジティブコントロールの合成を行う</strong>かどうかを選択できます。もし 「はい」であれば、<strong>モデル・タイプ</strong>を選択しなければなりませんが、現在の選択は「Poisson」と 「survival」です。集団レベルの推定の研究では生存（Cox）モデルを使用するので、「survival」を選択します。ポジティブコントロール合成のためのリスク期間モデルを推定の設定と同じになるように定義し、同じく、<strong>曝露前に最低限必要な連続した観察期間</strong>、<strong>最初の曝露のみを含めるべきか</strong>、<strong>最初のアウトカムのみを含めるべきか</strong>、および<strong>過去にアウトカムを持つ人を除外する</strong>の選択肢を模倣します。図 <a href="PopulationLevelEstimation.html#fig:outcomeModelSettings">12.15</a>にポジティブコントロール合成の設定を示します。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:pcSynthesis"></span>
<img src="images/PopulationLevelEstimation/pcSynthesis.png" alt="ポジティブコントロールのアウトカムの定義の設定" width="100%" />
<p class="caption">
図 12.17: ポジティブコントロールのアウトカムの定義の設定
</p>
</div>
</div>
</div>
<div id="研究パッケージの実行" class="section level3 hasAnchor" number="12.7.4">
<h3><span class="header-section-number">12.7.4</span> 研究パッケージの実行<a href="PopulationLevelEstimation.html#研究パッケージの実行" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>これで研究の定義が完了したので、実行可能なRパッケージとしてエクスポートできます。このパッケージは、CDMにデータを持つ施設で研究を実行するために必要なすべての内容を含みます。これには、対象群、比較群、アウトカムのコホートをインスタンス化するために使用できるコホート定義、ネガティブコントロールのコンセプトセット、ネガティブコントロールのアウトカムコホートを作成するロジック、さらに分析を実行するRコードが含まれます。パッケージを生成する前に、必ず研究を保存し、<strong>Utilities (ユーティリティ)</strong> タブをクリックしてください。ここで、実行される一連の分析をレビューできます。前述したように、比較と分析設定のすべての組み合わせは、別々の分析になります。この例では、2つの解析を指定しています：AMIに対するACEi対THZ、血管性浮腫に対するACEi対THZ、両者とも傾向スコアマッチングを使用しています。</p>
<p>パッケージの名前を指定し、“Download (ダウンロード)” をクリックしてzipファイルをダウンロードします。zipファイルにはRパッケージが含まれており、Rパッケージに通常必要なフォルダ構成になっています <span class="citation">(<a href="#ref-Wickham_2015">Wickham 2015</a>)</span>。このパッケージを使用するには、R Studio の使用をお勧めします。R Studio をローカルで実行している場合は、ファイルを解凍し、.Rproj ファイルをダブルクリックして R Studio で開きます。RスタジオをRスタジオサーバーで実行している場合は、<img src="images/PopulationLevelEstimation/upload.png" />をクリックしてファイルをアップロードし、解凍した後、.Rprojファイルをクリックしてプロジェクトを開きます。</p>
<p>R Studioでプロジェクトを開いたら、READMEファイルを開き、指示に従ってください。すべてのファイルのパスを、システム上の既存のパスに変更してください。</p>
<p>研究の実行時に表示される一般的なエラーメッセージは、“High correlation between covariate(s) and treatment detected.”（共変量と治療の間に高い相関が検出されました。）” です。これは傾向モデルのフィッティングの際に、いくつかの共変量が曝露と高い相関があることが観察されたことを示します。エラーメッセージに記載されている共変量を確認し、適切に共変量セットから除外してください (セクション <a href="PopulationLevelEstimation.html#VariableSelection">12.1.2</a> 参照). </p>
</div>
</div>
<div id="pleR" class="section level2 hasAnchor" number="12.8">
<h2><span class="header-section-number">12.8</span> Rを使用した研究の実施<a href="PopulationLevelEstimation.html#pleR" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>ATLASを使用して研究を実行するRコードを記述する代わりに、Rコードを自分自身で書くこともできます。これを行う理由の一つは、RがATLASで公開されているものよりもはるかに柔軟性を提供するからです。例えば、カスタム共変量や線形アウトカムモデルを使用したい場合は、カスタムRコードを作成し、OHDSI Rパッケージが提供する機能と組み合わせる必要があります。</p>
<p>例として、<a href="https://ohdsi.github.io/CohortMethod/">CohortMethod</a>パッケージを使用して研究を実行します。CohortMethodは、CDMに含まれるデータベースから必要なデータを抽出し、プロペンシティモデルのための多数の共変量を利用できます。以下の例では、最初にアウトカムとして血管性浮腫のみを考慮します。セクション <a href="PopulationLevelEstimation.html#MultipleAnalyses">12.8.6</a>では、これを拡張してAMIとネガティブコントロールのアウトカムを含める方法を説明します。</p>
<div id="コホートのインスタンス化-1" class="section level3 hasAnchor" number="12.8.1">
<h3><span class="header-section-number">12.8.1</span> コホートのインスタンス化<a href="PopulationLevelEstimation.html#コホートのインスタンス化-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>最初に対象コホートおよびアウトカムコホートをインスタンス化する必要があります。コホートのインスタンス化は、セクション (<a href="Cohorts.html#Cohorts">10</a>)で説明しています。付録にはターゲット（付録 (<a href="CohortDefinitions.html#AceInhibitorsMono">B.2</a>)）、比較（付録 (<a href="CohortDefinitions.html#ThiazidesMono">B.5</a>)）、およびアウトカム（付録 (<a href="CohortDefinitions.html#Angioedema">B.4</a>)）コホートの完全な定義が示されています。ACEi、THZ、および血管性浮腫コホートが、それぞれコホート定義ID 1、2、3である <code>scratch.my_cohorts</code> という表にインスタンス化されていると仮定します。</p>
</div>
<div id="データ抽出-1" class="section level3 hasAnchor" number="12.8.2">
<h3><span class="header-section-number">12.8.2</span> データ抽出<a href="PopulationLevelEstimation.html#データ抽出-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>最初に、Rにサーバーへの接続方法を教える必要があります。 <a href="https://ohdsi.github.io/CohortMethod/">CohortMethod</a>は<a href="https://ohdsi.github.io/DatabaseConnector/">DatabaseConnector</a>パッケージを使用しており、<code>createConnectionDetails</code>という関数を提供しています。さまざまなデータベース管理システム（DBMS）に必要な特定の設定については、<code>?createConnectionDetails</code>と入力してください。たとえば、PostgreSQLデータベースに接続するには、以下のコードを使用します。：</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="PopulationLevelEstimation.html#cb92-1" tabindex="-1"></a><span class="fu">library</span>(CohortMethod)</span>
<span id="cb92-2"><a href="PopulationLevelEstimation.html#cb92-2" tabindex="-1"></a>connDetails <span class="ot">&lt;-</span> <span class="fu">createConnectionDetails</span>(<span class="at">dbms =</span> <span class="st">&quot;postgresql&quot;</span>,</span>
<span id="cb92-3"><a href="PopulationLevelEstimation.html#cb92-3" tabindex="-1"></a>                                       <span class="at">server =</span> <span class="st">&quot;localhost/ohdsi&quot;</span>,</span>
<span id="cb92-4"><a href="PopulationLevelEstimation.html#cb92-4" tabindex="-1"></a>                                       <span class="at">user =</span> <span class="st">&quot;joe&quot;</span>,</span>
<span id="cb92-5"><a href="PopulationLevelEstimation.html#cb92-5" tabindex="-1"></a>                                       <span class="at">password =</span> <span class="st">&quot;supersecret&quot;</span>)</span>
<span id="cb92-6"><a href="PopulationLevelEstimation.html#cb92-6" tabindex="-1"></a></span>
<span id="cb92-7"><a href="PopulationLevelEstimation.html#cb92-7" tabindex="-1"></a>cdmDbSchema <span class="ot">&lt;-</span> <span class="st">&quot;my_cdm_data&quot;</span></span>
<span id="cb92-8"><a href="PopulationLevelEstimation.html#cb92-8" tabindex="-1"></a>cohortDbSchema <span class="ot">&lt;-</span> <span class="st">&quot;scratch&quot;</span></span>
<span id="cb92-9"><a href="PopulationLevelEstimation.html#cb92-9" tabindex="-1"></a>cohortTable <span class="ot">&lt;-</span> <span class="st">&quot;my_cohorts&quot;</span></span>
<span id="cb92-10"><a href="PopulationLevelEstimation.html#cb92-10" tabindex="-1"></a>cdmVersion <span class="ot">&lt;-</span> <span class="st">&quot;5&quot;</span></span></code></pre></div>
<p>最後の4行は<code>cdmDbSchema</code>、<code>cohortDbSchema</code>、<code>cohortTable</code>変数とCDMバージョンを定義しています。これらは後ほどRにCDM形式のデータがどこに格納されているか、対象となるあるコホートがどこに作成されたか、そして使用されているCDMのバージョンを伝えるために使用します。Microsoft SQL Serverの場合、データベーススキーマはデータベースとスキーマの両方を指定する必要があるため、たとえば<code>cdmDbSchema &lt;- "my_cdm_data.dbo"</code>のようになります。</p>
<p>次に、CohortMethodにコホートを抽出し、共変量を構築し、分析に必要なすべてのデータを抽出するよう指示できます：</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="PopulationLevelEstimation.html#cb93-1" tabindex="-1"></a><span class="co"># ターゲットおよび比較対照薬剤の成分のコンセプト</span></span>
<span id="cb93-2"><a href="PopulationLevelEstimation.html#cb93-2" tabindex="-1"></a>aceI <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1335471</span>,<span class="dv">1340128</span>,<span class="dv">1341927</span>,<span class="dv">1363749</span>,<span class="dv">1308216</span>,<span class="dv">1310756</span>,<span class="dv">1373225</span>,</span>
<span id="cb93-3"><a href="PopulationLevelEstimation.html#cb93-3" tabindex="-1"></a>          <span class="dv">1331235</span>,<span class="dv">1334456</span>,<span class="dv">1342439</span>)</span>
<span id="cb93-4"><a href="PopulationLevelEstimation.html#cb93-4" tabindex="-1"></a>thz <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1395058</span>,<span class="dv">974166</span>,<span class="dv">978555</span>,<span class="dv">907013</span>)</span>
<span id="cb93-5"><a href="PopulationLevelEstimation.html#cb93-5" tabindex="-1"></a></span>
<span id="cb93-6"><a href="PopulationLevelEstimation.html#cb93-6" tabindex="-1"></a><span class="co"># 構築すべき共変量のタイプを定義</span></span>
<span id="cb93-7"><a href="PopulationLevelEstimation.html#cb93-7" tabindex="-1"></a>cs <span class="ot">&lt;-</span> <span class="fu">createDefaultCovariateSettings</span>(<span class="at">excludedCovariateConceptIds =</span> <span class="fu">c</span>(aceI,</span>
<span id="cb93-8"><a href="PopulationLevelEstimation.html#cb93-8" tabindex="-1"></a>                                                                     thz),</span>
<span id="cb93-9"><a href="PopulationLevelEstimation.html#cb93-9" tabindex="-1"></a>                                     <span class="at">addDescendantsToExclude =</span> <span class="cn">TRUE</span>)</span>
<span id="cb93-10"><a href="PopulationLevelEstimation.html#cb93-10" tabindex="-1"></a></span>
<span id="cb93-11"><a href="PopulationLevelEstimation.html#cb93-11" tabindex="-1"></a><span class="co"># データをロード</span></span>
<span id="cb93-12"><a href="PopulationLevelEstimation.html#cb93-12" tabindex="-1"></a>cmData <span class="ot">&lt;-</span> <span class="fu">getDbCohortMethodData</span>(<span class="at">connectionDetails =</span> connectionDetails,</span>
<span id="cb93-13"><a href="PopulationLevelEstimation.html#cb93-13" tabindex="-1"></a>                                <span class="at">cdmDatabaseSchema =</span> cdmDatabaseSchema,</span>
<span id="cb93-14"><a href="PopulationLevelEstimation.html#cb93-14" tabindex="-1"></a>                                <span class="at">oracleTempSchema =</span> <span class="cn">NULL</span>,</span>
<span id="cb93-15"><a href="PopulationLevelEstimation.html#cb93-15" tabindex="-1"></a>                                <span class="at">targetId =</span> <span class="dv">1</span>,</span>
<span id="cb93-16"><a href="PopulationLevelEstimation.html#cb93-16" tabindex="-1"></a>                                <span class="at">comparatorId =</span> <span class="dv">2</span>,</span>
<span id="cb93-17"><a href="PopulationLevelEstimation.html#cb93-17" tabindex="-1"></a>                                <span class="at">outcomeIds =</span> <span class="dv">3</span>,</span>
<span id="cb93-18"><a href="PopulationLevelEstimation.html#cb93-18" tabindex="-1"></a>                                <span class="at">studyStartDate =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb93-19"><a href="PopulationLevelEstimation.html#cb93-19" tabindex="-1"></a>                                <span class="at">studyEndDate =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb93-20"><a href="PopulationLevelEstimation.html#cb93-20" tabindex="-1"></a>                                <span class="at">exposureDatabaseSchema =</span> cohortDbSchema,</span>
<span id="cb93-21"><a href="PopulationLevelEstimation.html#cb93-21" tabindex="-1"></a>                                <span class="at">exposureTable =</span> cohortTable,</span>
<span id="cb93-22"><a href="PopulationLevelEstimation.html#cb93-22" tabindex="-1"></a>                                <span class="at">outcomeDatabaseSchema =</span> cohortDbSchema,</span>
<span id="cb93-23"><a href="PopulationLevelEstimation.html#cb93-23" tabindex="-1"></a>                                <span class="at">outcomeTable =</span> cohortTable,</span>
<span id="cb93-24"><a href="PopulationLevelEstimation.html#cb93-24" tabindex="-1"></a>                                <span class="at">cdmVersion =</span> cdmVersion,</span>
<span id="cb93-25"><a href="PopulationLevelEstimation.html#cb93-25" tabindex="-1"></a>                                <span class="at">firstExposureOnly =</span> <span class="cn">FALSE</span>,</span>
<span id="cb93-26"><a href="PopulationLevelEstimation.html#cb93-26" tabindex="-1"></a>                                <span class="at">removeDuplicateSubjects =</span> <span class="cn">FALSE</span>,</span>
<span id="cb93-27"><a href="PopulationLevelEstimation.html#cb93-27" tabindex="-1"></a>                                <span class="at">restrictToCommonPeriod =</span> <span class="cn">FALSE</span>,</span>
<span id="cb93-28"><a href="PopulationLevelEstimation.html#cb93-28" tabindex="-1"></a>                                <span class="at">washoutPeriod =</span> <span class="dv">0</span>,</span>
<span id="cb93-29"><a href="PopulationLevelEstimation.html#cb93-29" tabindex="-1"></a>                                <span class="at">covariateSettings =</span> cs)</span>
<span id="cb93-30"><a href="PopulationLevelEstimation.html#cb93-30" tabindex="-1"></a>cmData</span></code></pre></div>
<pre><code>## CohortMethodData オブジェクト
## 
## 治療コンセプトID：1
## 比較対照コンセプトID：2
## アウトカムコンセプトID(s)：3</code></pre>
<p>多くのパラメーターがありますが、すべて<a href="https://ohdsi.github.io/CohortMethod/reference/">CohortMethodマニュアル</a>に記載されています。<code>createDefaultCovariateSettings</code>関数は<a href="https://ohdsi.github.io/FeatureExtraction/">FeatureExtraction</a>パッケージで説明されています。簡単に言えば、コホートを含むテーブルを指定し、そのテーブル内で対象、比較対照、アウトカムを識別するコホート定義IDを指定します。デフォルトの共変量セットが構築される指示を行い、インデックス日前日までに見つかったすべてのコンディション、薬剤曝露、処置に関する共変量を含むようにします。セクション (<a href="PopulationLevelEstimation.html#CohortMethod">12.1</a>)で述べたように、共変量のセットから対象と比較対照の治療を除外する必要があり、ここでは、2つのクラスのすべての成分を一覧表示し、FeatureExtractionにこれらの成分を含む下位層のすべての薬剤を除外するように指示します。</p>
<p>コホート、アウトカム、共変量に関するすべてのデータはサーバーから抽出され、<code>cohortMethodData</code>オブジェクトに保存されます。このオブジェクトは<code>ff</code>パッケージを使用して情報を保存するため、データが大きくてもRがメモリ不足にならないようにします（セクション (<a href="OhdsiAnalyticsTools.html#BigDataSupport">8.4.2</a>)で述べた通りです）。</p>
<p>抽出したデータの詳細を確認するために、汎用<code>summary()</code>関数を使用できます：</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="PopulationLevelEstimation.html#cb95-1" tabindex="-1"></a><span class="fu">summary</span>(cmData)</span></code></pre></div>
<pre><code>## CohortMethodDataオブジェクトの要約
## 
## 治療コンセプトID：1
## 比較対照コンセプトID：2
## アウトカムコンセプトID(s)：3
## 
## 治療を受けた人数：67166
## 比較対照の人数：35333
## 
## アウトカウント：
##          イベント数         人数
## 3               980          891
## 
## 共変量：
## 共変量の数：58349
## ゼロでない共変量値の数：24484665</code></pre>
<p><code>cohortMethodData</code>ファイルの作成にはかなりの計算時間がかかる可能性がありますので、今後のセッションのために保存しておくのが良いでしょう。<code>cohortMethodData</code>は<code>ff</code>を使用するため、Rの通常の保存関数は使用できません。代わりに、<code>saveCohortMethodData()</code>関数を使用します：</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="PopulationLevelEstimation.html#cb97-1" tabindex="-1"></a><span class="fu">saveCohortMethodData</span>(cmData, <span class="st">&quot;AceiVsThzForAngioedema&quot;</span>)</span></code></pre></div>
<p>今後のセッションでデータをロードするには、<code>loadCohortMethodData()</code>関数を使用できます。</p>
<div id="新規ユーザーの定義" class="section level4 unnumbered hasAnchor">
<h4>新規ユーザーの定義<a href="PopulationLevelEstimation.html#新規ユーザーの定義" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>通常、新規ユーザーは薬剤（対象または比較対象）の初回使用として定義され、通常、ウォッシュアウト期間（初回使用前の最小日数）を使用して、それが本当に初回使用である可能性を高めます。CohortMethodパッケージを使用する場合、新規使用に必要な要件を3つの方法で適用できます。：</p>
<ol style="list-style-type: decimal">
<li>コホートを定義する場合。</li>
<li>コホートを<code>getDbCohortMethodData</code>関数を使用して読み込む際、<code>firstExposureOnly</code>、<code>removeDuplicateSubjects</code>、<code>restrictToCommonPeriod</code>、および<code>washoutPeriod</code>引数を使用。</li>
<li><code>createStudyPopulation</code>関数を使用して研究集団を定義する際（下記参照）。</li>
</ol>
<p>オプション1の利点は、入力コホートがすでにCohortMethodパッケージ外で完全に定義されているため、外部コホート特性化ツールをこの分析で使用するのと同じコホートに使用できることです。オプション2および3の利点は、DRUG_ERAテーブルを直接使用できるなど、自身で初回使用に制限する手間を省くことです。オプション2は3よりも効率的であるため、最初の使用に必要なデータを取得するだけで済みますが、オプション3は効率が低いものの、元のコホートと研究対象集団とを比較することができます。</p>
</div>
</div>
<div id="研究集団の定義" class="section level3 hasAnchor" number="12.8.3">
<h3><span class="header-section-number">12.8.3</span> 研究集団の定義<a href="PopulationLevelEstimation.html#研究集団の定義" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>通常、曝露コホートと結果コホートは互いに独立して定義されます。効果量の推定値を算出したい場合、これらのコホートをさらに制限し、まとめておく必要があります。例えば、曝露前に結果が判明している被験者を除外し、定義されたリスク期間内の結果のみを残すなどです。この目的には、createStudyPopulation関数を使用できます。：</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="PopulationLevelEstimation.html#cb98-1" tabindex="-1"></a>studyPop <span class="ot">&lt;-</span> <span class="fu">createStudyPopulation</span>(<span class="at">cohortMethodData =</span> cmData,</span>
<span id="cb98-2"><a href="PopulationLevelEstimation.html#cb98-2" tabindex="-1"></a>                                  <span class="at">outcomeId =</span> <span class="dv">3</span>,</span>
<span id="cb98-3"><a href="PopulationLevelEstimation.html#cb98-3" tabindex="-1"></a>                                  <span class="at">firstExposureOnly =</span> <span class="cn">FALSE</span>,</span>
<span id="cb98-4"><a href="PopulationLevelEstimation.html#cb98-4" tabindex="-1"></a>                                  <span class="at">restrictToCommonPeriod =</span> <span class="cn">FALSE</span>,</span>
<span id="cb98-5"><a href="PopulationLevelEstimation.html#cb98-5" tabindex="-1"></a>                                  <span class="at">washoutPeriod =</span> <span class="dv">0</span>,</span>
<span id="cb98-6"><a href="PopulationLevelEstimation.html#cb98-6" tabindex="-1"></a>                                  <span class="at">removeDuplicateSubjects =</span> <span class="st">&quot;remove all&quot;</span>,</span>
<span id="cb98-7"><a href="PopulationLevelEstimation.html#cb98-7" tabindex="-1"></a>                                  <span class="at">removeSubjectsWithPriorOutcome =</span> <span class="cn">TRUE</span>,</span>
<span id="cb98-8"><a href="PopulationLevelEstimation.html#cb98-8" tabindex="-1"></a>                                  <span class="at">minDaysAtRisk =</span> <span class="dv">1</span>,</span>
<span id="cb98-9"><a href="PopulationLevelEstimation.html#cb98-9" tabindex="-1"></a>                                  <span class="at">riskWindowStart =</span> <span class="dv">1</span>,</span>
<span id="cb98-10"><a href="PopulationLevelEstimation.html#cb98-10" tabindex="-1"></a>                                  <span class="at">startAnchor =</span> <span class="st">&quot;cohort start&quot;</span>,</span>
<span id="cb98-11"><a href="PopulationLevelEstimation.html#cb98-11" tabindex="-1"></a>                                  <span class="at">riskWindowEnd =</span> <span class="dv">0</span>,</span>
<span id="cb98-12"><a href="PopulationLevelEstimation.html#cb98-12" tabindex="-1"></a>                                  <span class="at">endAnchor =</span> <span class="st">&quot;cohort end&quot;</span>)</span></code></pre></div>
<p><code>firstExposureOnly</code>と<code>removeDuplicateSubjects</code>をFALSEに設定し、<code>washoutPeriod</code>を0に設定しているのは、コホート定義内でこれらの基準をすでに適用しているためです。使用するアウトカムIDを指定し、リスク期間の開始日より前にアウトカムがある対象者を削除するように指示します。リスク期間はコホート開始日の翌日から始まり（<code>riskWindowStart = 1</code>および<code>startAnchor = "cohort start"</code>）、リスク期間はコホート定義で定義された曝露終了時に終了します（<code>riskWindowEnd = 0</code>および<code>endAnchor = "cohort end"</code>）。リスク期間は自動的に観察終了時または研究終了日に切り捨てられます。リスクの時間がない対象者も削除します。研究集団に残っている人数を確認するには、<code>getAttritionTable</code>関数を使用できます：</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="PopulationLevelEstimation.html#cb99-1" tabindex="-1"></a><span class="fu">getAttritionTable</span>(studyPop)</span></code></pre></div>
<pre><code>##                  説明   ターゲット人数 　　　比較群人数 ...
## 1             元のコホート         67212             35379 ...
## 2     両コホートの重複削除         67166             35333 ...
## 3     　前のアウトカムなし         67061             35238 ...
## 4  リスク期間が1日以上有り         66780             35086 ...</code></pre>
</div>
<div id="傾向スコア-1" class="section level3 hasAnchor" number="12.8.4">
<h3><span class="header-section-number">12.8.4</span> 傾向スコア<a href="PopulationLevelEstimation.html#傾向スコア-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>getDbcohortMethodData()</code>で構築された共変量を使用してプロペンシティモデルを適合させ、各人に対して傾向スコア（PS）を計算します：</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="PopulationLevelEstimation.html#cb101-1" tabindex="-1"></a>ps <span class="ot">&lt;-</span> <span class="fu">createPs</span>(<span class="at">cohortMethodData =</span> cmData, <span class="at">population =</span> studyPop)</span></code></pre></div>
<p><code>createPs</code>関数は<a href="https://ohdsi.github.io/Cyclops/">Cyclops</a>パッケージを使用して大規模な正則化ロジスティック回帰を適合します。プロペンシティモデルを適合するために、Cyclopsは事前分布の分散を指定するハイパーパラメータ値を知る必要があります。デフォルトでは、Cyclopsはクロスバリデーションを使用して最適なハイパーパラメータを推定します。ただし、これには非常に長い時間がかかる場合があります。createPs関数の事前および制御パラメータを使用して、Cyclopsの動作を指定することができます。これには、クロスバリデーションを高速化するための複数のCPUの使用などが含まれます。</p>
<p>ここでは、変数比のマッチングを使用してPSを使用します：</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="PopulationLevelEstimation.html#cb102-1" tabindex="-1"></a>matchedPop <span class="ot">&lt;-</span> <span class="fu">matchOnPs</span>(<span class="at">population =</span> ps, <span class="at">caliper =</span> <span class="fl">0.2</span>,</span>
<span id="cb102-2"><a href="PopulationLevelEstimation.html#cb102-2" tabindex="-1"></a>                        <span class="at">caliperScale =</span> <span class="st">&quot;standardized logit&quot;</span>, <span class="at">maxRatio =</span> <span class="dv">100</span>)</span></code></pre></div>
<p>あるいは、PSを<code>trimByPs</code>、<code>trimByPsToEquipoise</code>、または<code>stratifyByPs</code>関数で使用することもできます。</p>
</div>
<div id="アウトカムモデル" class="section level3 hasAnchor" number="12.8.5">
<h3><span class="header-section-number">12.8.5</span> アウトカムモデル<a href="PopulationLevelEstimation.html#アウトカムモデル" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>アウトカムモデルは、どの変数がアウトカムと関連しているかを説明するモデルです。厳密な仮定の下では、治療変数の係数は因果効果として解釈できます。ここではマッチングに基づいたCox比例ハザードモデルを適合します：</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="PopulationLevelEstimation.html#cb103-1" tabindex="-1"></a>outcomeModel <span class="ot">&lt;-</span> <span class="fu">fitOutcomeModel</span>(<span class="at">population =</span> matchedPop,</span>
<span id="cb103-2"><a href="PopulationLevelEstimation.html#cb103-2" tabindex="-1"></a>                                <span class="at">modelType =</span> <span class="st">&quot;cox&quot;</span>,</span>
<span id="cb103-3"><a href="PopulationLevelEstimation.html#cb103-3" tabindex="-1"></a>                                <span class="at">stratified =</span> <span class="cn">TRUE</span>)</span>
<span id="cb103-4"><a href="PopulationLevelEstimation.html#cb103-4" tabindex="-1"></a>outcomeModel</span></code></pre></div>
<pre><code>## モデルタイプ：cox
## 階層化：TRUE
## 共変量の使用：FALSE
## 治療重量の逆確率：FALSE
## ステータス：OK
## 
##           推定値 下限95%  上限95%  logRr   seLogRr
## 治療     4.3203   2.4531   8.0771  1.4633  0.304</code></pre>
</div>
<div id="MultipleAnalyses" class="section level3 hasAnchor" number="12.8.6">
<h3><span class="header-section-number">12.8.6</span> 複数の分析の実行<a href="PopulationLevelEstimation.html#MultipleAnalyses" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>一般に、ネガティブコントロールを含む多くのアウトカムに対して複数の分析を行いたい場合がよくあります。<a href="https://ohdsi.github.io/CohortMethod/">CohortMethod</a>は、そのような研究を効率的に実行するための関数を提供します。これは<a href="https://ohdsi.github.io/CohortMethod/articles/MultipleAnalyses.html">複数の分析の実行に関するパッケージのビネット</a>で詳細に説明されています。要約すると、対象となるアウトカムとネガティブコントロールのコホートが既に作成されていると仮定し、分析したいすべての対象・比較対照・アウトカムの組み合わせを指定できます：</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="PopulationLevelEstimation.html#cb105-1" tabindex="-1"></a><span class="co"># 関心のあるアウトカム:</span></span>
<span id="cb105-2"><a href="PopulationLevelEstimation.html#cb105-2" tabindex="-1"></a>ois <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>) <span class="co"># Angioedema, AMI</span></span>
<span id="cb105-3"><a href="PopulationLevelEstimation.html#cb105-3" tabindex="-1"></a></span>
<span id="cb105-4"><a href="PopulationLevelEstimation.html#cb105-4" tabindex="-1"></a><span class="co"># ネガティブコントロール：</span></span>
<span id="cb105-5"><a href="PopulationLevelEstimation.html#cb105-5" tabindex="-1"></a>ncs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">434165</span>,<span class="dv">436409</span>,<span class="dv">199192</span>,<span class="dv">4088290</span>,<span class="dv">4092879</span>,<span class="dv">44783954</span>,<span class="dv">75911</span>,<span class="dv">137951</span>,<span class="dv">77965</span>,</span>
<span id="cb105-6"><a href="PopulationLevelEstimation.html#cb105-6" tabindex="-1"></a>         <span class="dv">376707</span>,<span class="dv">4103640</span>,<span class="dv">73241</span>,<span class="dv">133655</span>,<span class="dv">73560</span>,<span class="dv">434327</span>,<span class="dv">4213540</span>,<span class="dv">140842</span>,<span class="dv">81378</span>,</span>
<span id="cb105-7"><a href="PopulationLevelEstimation.html#cb105-7" tabindex="-1"></a>         <span class="dv">432303</span>,<span class="dv">4201390</span>,<span class="dv">46269889</span>,<span class="dv">134438</span>,<span class="dv">78619</span>,<span class="dv">201606</span>,<span class="dv">76786</span>,<span class="dv">4115402</span>,</span>
<span id="cb105-8"><a href="PopulationLevelEstimation.html#cb105-8" tabindex="-1"></a>         <span class="dv">45757370</span>,<span class="dv">433111</span>,<span class="dv">433527</span>,<span class="dv">4170770</span>,<span class="dv">4092896</span>,<span class="dv">259995</span>,<span class="dv">40481632</span>,<span class="dv">4166231</span>,</span>
<span id="cb105-9"><a href="PopulationLevelEstimation.html#cb105-9" tabindex="-1"></a>         <span class="dv">433577</span>,<span class="dv">4231770</span>,<span class="dv">440329</span>,<span class="dv">4012570</span>,<span class="dv">4012934</span>,<span class="dv">441788</span>,<span class="dv">4201717</span>,<span class="dv">374375</span>,</span>
<span id="cb105-10"><a href="PopulationLevelEstimation.html#cb105-10" tabindex="-1"></a>         <span class="dv">4344500</span>,<span class="dv">139099</span>,<span class="dv">444132</span>,<span class="dv">196168</span>,<span class="dv">432593</span>,<span class="dv">434203</span>,<span class="dv">438329</span>,<span class="dv">195873</span>,<span class="dv">4083487</span>,</span>
<span id="cb105-11"><a href="PopulationLevelEstimation.html#cb105-11" tabindex="-1"></a>         <span class="dv">4103703</span>,<span class="dv">4209423</span>,<span class="dv">377572</span>,<span class="dv">40480893</span>,<span class="dv">136368</span>,<span class="dv">140648</span>,<span class="dv">438130</span>,<span class="dv">4091513</span>,</span>
<span id="cb105-12"><a href="PopulationLevelEstimation.html#cb105-12" tabindex="-1"></a>         <span class="dv">4202045</span>,<span class="dv">373478</span>,<span class="dv">46286594</span>,<span class="dv">439790</span>,<span class="dv">81634</span>,<span class="dv">380706</span>,<span class="dv">141932</span>,<span class="dv">36713918</span>,</span>
<span id="cb105-13"><a href="PopulationLevelEstimation.html#cb105-13" tabindex="-1"></a>         <span class="dv">443172</span>,<span class="dv">81151</span>,<span class="dv">72748</span>,<span class="dv">378427</span>,<span class="dv">437264</span>,<span class="dv">194083</span>,<span class="dv">140641</span>,<span class="dv">440193</span>,<span class="dv">4115367</span>)</span>
<span id="cb105-14"><a href="PopulationLevelEstimation.html#cb105-14" tabindex="-1"></a></span>
<span id="cb105-15"><a href="PopulationLevelEstimation.html#cb105-15" tabindex="-1"></a>tcos <span class="ot">&lt;-</span> <span class="fu">createTargetComparatorOutcomes</span>(<span class="at">targetId =</span> <span class="dv">1</span>,</span>
<span id="cb105-16"><a href="PopulationLevelEstimation.html#cb105-16" tabindex="-1"></a>                                       <span class="at">comparatorId =</span> <span class="dv">2</span>,</span>
<span id="cb105-17"><a href="PopulationLevelEstimation.html#cb105-17" tabindex="-1"></a>                                       <span class="at">outcomeIds =</span> <span class="fu">c</span>(ois, ncs))</span>
<span id="cb105-18"><a href="PopulationLevelEstimation.html#cb105-18" tabindex="-1"></a></span>
<span id="cb105-19"><a href="PopulationLevelEstimation.html#cb105-19" tabindex="-1"></a>tcosList <span class="ot">&lt;-</span> <span class="fu">list</span>(tcos)</span></code></pre></div>
<p>次に、先ほどの例で説明した様々な関数を呼び出す際に、どのような引数を使うべきかを指定します：</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="PopulationLevelEstimation.html#cb106-1" tabindex="-1"></a>aceI <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1335471</span>,<span class="dv">1340128</span>,<span class="dv">1341927</span>,<span class="dv">1363749</span>,<span class="dv">1308216</span>,<span class="dv">1310756</span>,<span class="dv">1373225</span>,</span>
<span id="cb106-2"><a href="PopulationLevelEstimation.html#cb106-2" tabindex="-1"></a>          <span class="dv">1331235</span>,<span class="dv">1334456</span>,<span class="dv">1342439</span>)</span>
<span id="cb106-3"><a href="PopulationLevelEstimation.html#cb106-3" tabindex="-1"></a>thz <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1395058</span>,<span class="dv">974166</span>,<span class="dv">978555</span>,<span class="dv">907013</span>)</span>
<span id="cb106-4"><a href="PopulationLevelEstimation.html#cb106-4" tabindex="-1"></a></span>
<span id="cb106-5"><a href="PopulationLevelEstimation.html#cb106-5" tabindex="-1"></a>cs <span class="ot">&lt;-</span> <span class="fu">createDefaultCovariateSettings</span>(<span class="at">excludedCovariateConceptIds =</span> <span class="fu">c</span>(aceI,</span>
<span id="cb106-6"><a href="PopulationLevelEstimation.html#cb106-6" tabindex="-1"></a>                                                                     thz),</span>
<span id="cb106-7"><a href="PopulationLevelEstimation.html#cb106-7" tabindex="-1"></a>                                     <span class="at">addDescendantsToExclude =</span> <span class="cn">TRUE</span>)</span>
<span id="cb106-8"><a href="PopulationLevelEstimation.html#cb106-8" tabindex="-1"></a></span>
<span id="cb106-9"><a href="PopulationLevelEstimation.html#cb106-9" tabindex="-1"></a>cmdArgs <span class="ot">&lt;-</span> <span class="fu">createGetDbCohortMethodDataArgs</span>(</span>
<span id="cb106-10"><a href="PopulationLevelEstimation.html#cb106-10" tabindex="-1"></a>  <span class="at">studyStartDate =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb106-11"><a href="PopulationLevelEstimation.html#cb106-11" tabindex="-1"></a>  <span class="at">studyEndDate =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb106-12"><a href="PopulationLevelEstimation.html#cb106-12" tabindex="-1"></a>  <span class="at">firstExposureOnly =</span> <span class="cn">FALSE</span>,</span>
<span id="cb106-13"><a href="PopulationLevelEstimation.html#cb106-13" tabindex="-1"></a>  <span class="at">removeDuplicateSubjects =</span> <span class="cn">FALSE</span>,</span>
<span id="cb106-14"><a href="PopulationLevelEstimation.html#cb106-14" tabindex="-1"></a>  <span class="at">restrictToCommonPeriod =</span> <span class="cn">FALSE</span>,</span>
<span id="cb106-15"><a href="PopulationLevelEstimation.html#cb106-15" tabindex="-1"></a>  <span class="at">washoutPeriod =</span> <span class="dv">0</span>,</span>
<span id="cb106-16"><a href="PopulationLevelEstimation.html#cb106-16" tabindex="-1"></a>  <span class="at">covariateSettings =</span> cs)</span>
<span id="cb106-17"><a href="PopulationLevelEstimation.html#cb106-17" tabindex="-1"></a></span>
<span id="cb106-18"><a href="PopulationLevelEstimation.html#cb106-18" tabindex="-1"></a>spArgs <span class="ot">&lt;-</span> <span class="fu">createCreateStudyPopulationArgs</span>(</span>
<span id="cb106-19"><a href="PopulationLevelEstimation.html#cb106-19" tabindex="-1"></a>  <span class="at">firstExposureOnly =</span> <span class="cn">FALSE</span>,</span>
<span id="cb106-20"><a href="PopulationLevelEstimation.html#cb106-20" tabindex="-1"></a>  <span class="at">restrictToCommonPeriod =</span> <span class="cn">FALSE</span>,</span>
<span id="cb106-21"><a href="PopulationLevelEstimation.html#cb106-21" tabindex="-1"></a>  <span class="at">washoutPeriod =</span> <span class="dv">0</span>,</span>
<span id="cb106-22"><a href="PopulationLevelEstimation.html#cb106-22" tabindex="-1"></a>  <span class="at">removeDuplicateSubjects =</span> <span class="st">&quot;remove all&quot;</span>,</span>
<span id="cb106-23"><a href="PopulationLevelEstimation.html#cb106-23" tabindex="-1"></a>  <span class="at">removeSubjectsWithPriorOutcome =</span> <span class="cn">TRUE</span>,</span>
<span id="cb106-24"><a href="PopulationLevelEstimation.html#cb106-24" tabindex="-1"></a>  <span class="at">minDaysAtRisk =</span> <span class="dv">1</span>,</span>
<span id="cb106-25"><a href="PopulationLevelEstimation.html#cb106-25" tabindex="-1"></a>  <span class="at">startAnchor =</span> <span class="st">&quot;cohort start&quot;</span>,</span>
<span id="cb106-26"><a href="PopulationLevelEstimation.html#cb106-26" tabindex="-1"></a>  <span class="at">addExposureDaysToStart =</span> <span class="cn">FALSE</span>,</span>
<span id="cb106-27"><a href="PopulationLevelEstimation.html#cb106-27" tabindex="-1"></a>  <span class="at">endAnchor =</span> <span class="st">&quot;cohort end&quot;</span>,</span>
<span id="cb106-28"><a href="PopulationLevelEstimation.html#cb106-28" tabindex="-1"></a>  <span class="at">addExposureDaysToEnd =</span> <span class="cn">TRUE</span>)</span>
<span id="cb106-29"><a href="PopulationLevelEstimation.html#cb106-29" tabindex="-1"></a></span>
<span id="cb106-30"><a href="PopulationLevelEstimation.html#cb106-30" tabindex="-1"></a>psArgs <span class="ot">&lt;-</span> <span class="fu">createCreatePsArgs</span>()</span>
<span id="cb106-31"><a href="PopulationLevelEstimation.html#cb106-31" tabindex="-1"></a></span>
<span id="cb106-32"><a href="PopulationLevelEstimation.html#cb106-32" tabindex="-1"></a>matchArgs <span class="ot">&lt;-</span> <span class="fu">createMatchOnPsArgs</span>(</span>
<span id="cb106-33"><a href="PopulationLevelEstimation.html#cb106-33" tabindex="-1"></a>  <span class="at">caliper =</span> <span class="fl">0.2</span>,</span>
<span id="cb106-34"><a href="PopulationLevelEstimation.html#cb106-34" tabindex="-1"></a>  <span class="at">caliperScale =</span> <span class="st">&quot;standardized logit&quot;</span>,</span>
<span id="cb106-35"><a href="PopulationLevelEstimation.html#cb106-35" tabindex="-1"></a>  <span class="at">maxRatio =</span> <span class="dv">100</span>)</span>
<span id="cb106-36"><a href="PopulationLevelEstimation.html#cb106-36" tabindex="-1"></a></span>
<span id="cb106-37"><a href="PopulationLevelEstimation.html#cb106-37" tabindex="-1"></a>fomArgs <span class="ot">&lt;-</span> <span class="fu">createFitOutcomeModelArgs</span>(</span>
<span id="cb106-38"><a href="PopulationLevelEstimation.html#cb106-38" tabindex="-1"></a>  <span class="at">modelType =</span> <span class="st">&quot;cox&quot;</span>,</span>
<span id="cb106-39"><a href="PopulationLevelEstimation.html#cb106-39" tabindex="-1"></a>  <span class="at">stratified =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>次に、これらを1つの分析設定オブジェクトに結合し、一意の分析IDといくつかの説明を提供します。1つ以上の分析設定オブジェクトをリストにまとめることができます：</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="PopulationLevelEstimation.html#cb107-1" tabindex="-1"></a>cmAnalysis <span class="ot">&lt;-</span> <span class="fu">createCmAnalysis</span>(</span>
<span id="cb107-2"><a href="PopulationLevelEstimation.html#cb107-2" tabindex="-1"></a>  <span class="at">analysisId =</span> <span class="dv">1</span>,</span>
<span id="cb107-3"><a href="PopulationLevelEstimation.html#cb107-3" tabindex="-1"></a>  <span class="at">description =</span> <span class="st">&quot;Propensity score matching&quot;</span>,</span>
<span id="cb107-4"><a href="PopulationLevelEstimation.html#cb107-4" tabindex="-1"></a>  <span class="at">getDbCohortMethodDataArgs =</span> cmdArgs,</span>
<span id="cb107-5"><a href="PopulationLevelEstimation.html#cb107-5" tabindex="-1"></a>  <span class="at">createStudyPopArgs =</span> spArgs,</span>
<span id="cb107-6"><a href="PopulationLevelEstimation.html#cb107-6" tabindex="-1"></a>  <span class="at">createPs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb107-7"><a href="PopulationLevelEstimation.html#cb107-7" tabindex="-1"></a>  <span class="at">createPsArgs =</span> psArgs,</span>
<span id="cb107-8"><a href="PopulationLevelEstimation.html#cb107-8" tabindex="-1"></a>  <span class="at">matchOnPs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb107-9"><a href="PopulationLevelEstimation.html#cb107-9" tabindex="-1"></a>  <span class="at">matchOnPsArgs =</span> matchArgs</span>
<span id="cb107-10"><a href="PopulationLevelEstimation.html#cb107-10" tabindex="-1"></a>  <span class="at">fitOutcomeModel =</span> <span class="cn">TRUE</span>,</span>
<span id="cb107-11"><a href="PopulationLevelEstimation.html#cb107-11" tabindex="-1"></a>  <span class="at">fitOutcomeModelArgs =</span> fomArgs)</span>
<span id="cb107-12"><a href="PopulationLevelEstimation.html#cb107-12" tabindex="-1"></a></span>
<span id="cb107-13"><a href="PopulationLevelEstimation.html#cb107-13" tabindex="-1"></a>cmAnalysisList <span class="ot">&lt;-</span> <span class="fu">list</span>(cmAnalysis)</span></code></pre></div>
<p>これで、すべての比較と分析設定を含む研究を実行することができます：</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="PopulationLevelEstimation.html#cb108-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">runCmAnalyses</span>(<span class="at">connectionDetails =</span> connectionDetails,</span>
<span id="cb108-2"><a href="PopulationLevelEstimation.html#cb108-2" tabindex="-1"></a>                        <span class="at">cdmDatabaseSchema =</span> cdmDatabaseSchema,</span>
<span id="cb108-3"><a href="PopulationLevelEstimation.html#cb108-3" tabindex="-1"></a>                        <span class="at">exposureDatabaseSchema =</span> cohortDbSchema,</span>
<span id="cb108-4"><a href="PopulationLevelEstimation.html#cb108-4" tabindex="-1"></a>                        <span class="at">exposureTable =</span> cohortTable,</span>
<span id="cb108-5"><a href="PopulationLevelEstimation.html#cb108-5" tabindex="-1"></a>                        <span class="at">outcomeDatabaseSchema =</span> cohortDbSchema,</span>
<span id="cb108-6"><a href="PopulationLevelEstimation.html#cb108-6" tabindex="-1"></a>                        <span class="at">outcomeTable =</span> cohortTable,</span>
<span id="cb108-7"><a href="PopulationLevelEstimation.html#cb108-7" tabindex="-1"></a>                        <span class="at">cdmVersion =</span> cdmVersion,</span>
<span id="cb108-8"><a href="PopulationLevelEstimation.html#cb108-8" tabindex="-1"></a>                        <span class="at">outputFolder =</span> outputFolder,</span>
<span id="cb108-9"><a href="PopulationLevelEstimation.html#cb108-9" tabindex="-1"></a>                        <span class="at">cmAnalysisList =</span> cmAnalysisList,</span>
<span id="cb108-10"><a href="PopulationLevelEstimation.html#cb108-10" tabindex="-1"></a>                        <span class="at">targetComparatorOutcomesList =</span> tcosList)</span></code></pre></div>
<p><code>result</code>オブジェクトには、作成されたすべてのアーティファクトトへの参照が含まれます。例えば、AMIのアウトカムモデルを取得することができます：</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="PopulationLevelEstimation.html#cb109-1" tabindex="-1"></a>omFile <span class="ot">&lt;-</span> result<span class="sc">$</span>outcomeModelFile[result<span class="sc">$</span>targetId <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span></span>
<span id="cb109-2"><a href="PopulationLevelEstimation.html#cb109-2" tabindex="-1"></a>                                    result<span class="sc">$</span>comparatorId <span class="sc">==</span> <span class="dv">2</span> <span class="sc">&amp;</span></span>
<span id="cb109-3"><a href="PopulationLevelEstimation.html#cb109-3" tabindex="-1"></a>                                    result<span class="sc">$</span>outcomeId <span class="sc">==</span> <span class="dv">4</span> <span class="sc">&amp;</span></span>
<span id="cb109-4"><a href="PopulationLevelEstimation.html#cb109-4" tabindex="-1"></a>                                    result<span class="sc">$</span>analysisId <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb109-5"><a href="PopulationLevelEstimation.html#cb109-5" tabindex="-1"></a>outcomeModel <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(outputFolder, omFile))</span>
<span id="cb109-6"><a href="PopulationLevelEstimation.html#cb109-6" tabindex="-1"></a>outcomeModel</span></code></pre></div>
<pre><code>## Model type: cox
## Stratified: TRUE
## Use covariates: FALSE
## Use inverse probability of treatment weighting: FALSE
## Status: OK
## 
##           推定値 下限95%  上限95%  logRr   seLogRr
## 治療   1.1338    0.5921    2.1765 0.1256   0.332</code></pre>
<p>また、1つのコマンドですべてのアウトカムに対する効果量として推定値を取得することもできます：</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="PopulationLevelEstimation.html#cb111-1" tabindex="-1"></a>summ <span class="ot">&lt;-</span> <span class="fu">summarizeAnalyses</span>(result, <span class="at">outputFolder =</span> outputFolder)</span>
<span id="cb111-2"><a href="PopulationLevelEstimation.html#cb111-2" tabindex="-1"></a><span class="fu">head</span>(summ)</span></code></pre></div>
<pre><code>##     解析ID  ターゲットID 比較群ID  アウトカムID　リスク比 ...
## 1            1        1            2     72748   0.9734698 ...
## 2            1        1            2     73241   0.7067981 ...
## 3            1        1            2     73560   1.0623951 ...
## 4            1        1            2     75911   0.9952184 ...
## 5            1        1            2     76786   1.0861746 ...
## 6            1        1            2     77965   1.1439772 ...</code></pre>
</div>
</div>
<div id="studyOutputs" class="section level2 hasAnchor" number="12.9">
<h2><span class="header-section-number">12.9</span> 研究の結果<a href="PopulationLevelEstimation.html#studyOutputs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>推定値は、いくつかの仮定が満たされている場合にのみ有効です。これが満たされているかどうかを評価するために、幅広い診断ツールを使用します。これらはATLASによって生成されたRパッケージが生成したアウトカムで利用可能であり、特定のR関数を使用して随時生成することもできます。</p>
<div id="傾向スコアとモデル" class="section level3 hasAnchor" number="12.9.1">
<h3><span class="header-section-number">12.9.1</span> 傾向スコアとモデル<a href="PopulationLevelEstimation.html#傾向スコアとモデル" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>まず、対象コホートと比較対象コホートがある程度比較可能かどうかを評価する必要があります。そのために、傾向モデルのArea Under the Receiver Operator Curve（AUC）統計量を計算できます。AUCが1の場合、治療の割り当てはベースライン共変量に基づいて治療割り当てが完全に予測可能であり、したがって、2つのグループは比較不可能であることを示します。<code>computePsAuc</code>関数を使用してAUCを計算できます。この例では0.79です。<code>plotPs</code>関数を使用して、図 <a href="PopulationLevelEstimation.html#fig:ps">12.18</a>に示すような選好スコア分布も生成できます。この図から、多くの人にとって受けた治療が予測可能だったことがわかりますが、重複も多く、調整して比較可能なグループを選択できることがわかります。 </p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ps"></span>
<img src="images/PopulationLevelEstimation/ps.png" alt="選好スコアの分布" width="80%" />
<p class="caption">
図 12.18: 選好スコアの分布
</p>
</div>
<p>一般に、傾向モデル自体も検査することが望ましく、特にモデルが非常に予測的な場合はそのようにすべきです。そうすれば、どの変数が最も予測的であるかがわかるかもしれません。表 <a href="PopulationLevelEstimation.html#tab:psModel">12.7</a> は、この傾向モデルにおける主要な予測因子を示しています。変数があまりにも予測的である場合、CohortMethodパッケージは情報的なエラーを発生させますが、すでに完全に予測可能であることがわかっているモデルを適合させようとはしません。 </p>
<table>
<caption><span id="tab:psModel">表 12.7: </span> ACEiとTHZの傾向モデルにおける上位10の予測因子。正の値は、共変量を持つ対象が治療を受ける可能性が高いことを意味します。「(Intercept)」は、このロジスティック回帰モデルの切片を示します。</caption>
<colgroup>
<col width="10%" />
<col width="89%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">ベータ</th>
<th align="left">共変量</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-1.42</td>
<td align="left">基準日から-30日から0日までの期間の疾患エラ: 浮腫</td>
</tr>
<tr class="even">
<td align="right">-1.11</td>
<td align="left">基準日から0日から0日までの期間の薬剤エラ: 塩化カリウム</td>
</tr>
<tr class="odd">
<td align="right">0.68</td>
<td align="left">年齢グループ: 05-09</td>
</tr>
<tr class="even">
<td align="right">0.64</td>
<td align="left">基準日から-365日から0日までの期間のメジャーメント: レニン</td>
</tr>
<tr class="odd">
<td align="right">0.63</td>
<td align="left">基準日から-30日から0日までの期間の疾患エラ: 蕁麻疹</td>
</tr>
<tr class="even">
<td align="right">0.57</td>
<td align="left">基準日から-30日から0日までの期間の疾患エラ: タンパク尿</td>
</tr>
<tr class="odd">
<td align="right">0.55</td>
<td align="left">基準日から-365日から0日までの期間の薬剤エラ: インスリン及び類似体</td>
</tr>
<tr class="even">
<td align="right">-0.54</td>
<td align="left">人種: 黒人またはアフリカ系アメリカ人</td>
</tr>
<tr class="odd">
<td align="right">0.52</td>
<td align="left">(切片)</td>
</tr>
<tr class="even">
<td align="right">0.50</td>
<td align="left">性別: 男性</td>
</tr>
</tbody>
</table>

<div class="rmdimportant">
<p>変数が非常に予測的であると判明した場合、2つの可能な結論があります。変数が明らかに曝露の一部であると判明し、モデルを適合させる前に削除する必要があるか、または2つの集団が本当に比較不可能であり、解析を中止しなければならないという結論に達します。</p>
</div>
</div>
<div id="共変量のバランス" class="section level3 hasAnchor" number="12.9.2">
<h3><span class="header-section-number">12.9.2</span> 共変量のバランス<a href="PopulationLevelEstimation.html#共変量のバランス" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>PSを使用する目的は、2つのグループを比較可能にすることです（少なくとも比較可能なグループを選択すること）。これが達成されたかどうかを確認する必要があります。例えば、調整後のベースライン共変量が実際にバランスしているかどうかを確認することです。<code>computeCovariateBalance</code>および<code>plotCovariateBalanceScatterPlot</code>関数を使用して図 <a href="PopulationLevelEstimation.html#fig:balance">12.19</a> を生成できます。経験則として、傾向スコア調整後には、共変量間の平均値の標準化差の絶対値が0.1より大きくなってはならないというものがあります。ここでは、マッチング前にはかなりの不均衡があったものの、マッチング後にはこの基準を満たしていることがわかります。 </p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:balance"></span>
<img src="images/PopulationLevelEstimation/balance.png" alt="共変量バランスの図。傾向スコア マッチング前およびマッチング後の平均の絶対標準化差を示す。各ドットは共変量を表します。" width="70%" />
<p class="caption">
図 12.19: 共変量バランスの図。傾向スコア マッチング前およびマッチング後の平均の絶対標準化差を示す。各ドットは共変量を表します。
</p>
</div>
</div>
<div id="フォローアップとパワー" class="section level3 hasAnchor" number="12.9.3">
<h3><span class="header-section-number">12.9.3</span> フォローアップとパワー<a href="PopulationLevelEstimation.html#フォローアップとパワー" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>アウトカムモデルを適合させる前に、特定の効果量を検出するのに十分な検出力があるかどうかを知りたい場合があります。様々な適格基準および除外基準（例えば、事前のアウトカムなし）による脱落、マッチングおよび/またはトリミングによる脱落を考慮に入れるため、研究対象集団が完全に定義された時点で、これらの検出力の計算を行うことが理にかなっています。drawAttritionDiagram 関数を使用して、研究対象者の脱落を把握することができます。図 <a href="PopulationLevelEstimation.html#fig:attrition">12.20</a> を参照ください。 </p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:attrition"></span>
<img src="images/PopulationLevelEstimation/attrition.png" alt="脱落図。上部に示されているカウントは目標および比較対象コホートの定義を満たしているものです。下部に示されているカウントは、アウトカムモデルに入るものです。この場合、Cox回帰です。" width="70%" />
<p class="caption">
図 12.20: 脱落図。上部に示されているカウントは目標および比較対象コホートの定義を満たしているものです。下部に示されているカウントは、アウトカムモデルに入るものです。この場合、Cox回帰です。
</p>
</div>
<p>レトロスペクティブ研究ではサンプルサイズは固定されており（データはすでに収集されている）、真の効果サイズは不明であるため、期待される効果サイズに基づいて検出力を計算することに意味がありません。代わりに、CohortMethodパッケージは、最小検出相対リスク（MDRR）を計算するための<code>computeMdrr</code>関数を提供します。この研究例におけるMDRRは1.69です。 </p>
<p>追跡可能なフォローアップの量をよりよく理解するために、フォローアップ期間の分布を調査することもできます。追跡期間をリスクにさらされる期間と定義し、アウトカムが発生するまでの期間として検討できます。<code>getFollowUpDistribution</code>関数は簡単な概要を提供でき、図 <a href="PopulationLevelEstimation.html#fig:followUp">12.21</a> に示されるように、両コホートのフォローアップ期間が比較可能であることがわかります。</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:followUp"></span>
<img src="images/PopulationLevelEstimation/followUp.png" alt="対象および比較対照コホートのフォローアップ時間の分布" width="80%" />
<p class="caption">
図 12.21: 対象および比較対照コホートのフォローアップ時間の分布
</p>
</div>
</div>
<div id="カプランマイヤー" class="section level3 hasAnchor" number="12.9.4">
<h3><span class="header-section-number">12.9.4</span> カプラン・マイヤー<a href="PopulationLevelEstimation.html#カプランマイヤー" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>最後に、カプラン・マイヤー・プロットを確認し、両コホートの時間経過による生存率を示します。<code>plotKaplanMeier</code>関数を使用して <a href="PopulationLevelEstimation.html#fig:kmPlot">12.22</a> を作成し、ハザードの比例性の仮定が保持されているかどうかなどを確認できます。カプラン・マイヤー・プロットはPSによる層別化や重み付けを自動的に調整します。この場合、変比率マッチングが使用されるため、比較対象グループの生存曲線は、ターゲットグループが比較対照に曝露されていた場合に曲線がどのように見えたであろうかを模倣するように調整されます。 </p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:kmPlot"></span>
<img src="images/PopulationLevelEstimation/kmPlot.png" alt="カプラン・マイヤー・プロット" width="100%" />
<p class="caption">
図 12.22: カプラン・マイヤー・プロット
</p>
</div>
</div>
<div id="効果量の推定" class="section level3 hasAnchor" number="12.9.5">
<h3><span class="header-section-number">12.9.5</span> 効果量の推定<a href="PopulationLevelEstimation.html#効果量の推定" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>血管性浮腫に対するハザード比は4.32（95％信頼区間：2.45 - 8.08）でした。これは、ACEiがTHZと比較して血管性浮腫のリスクを増加させる可能性があることを示しています。同様に、AMIに対するハザード比は1.13（95％信頼区間：0.59 - 2.18）を観察し、AMIに対してはほとんどまたは全く影響がないことを示唆しています。前述の診断では、疑う理由がありません。しかし、最終的には、このエビデンスの質とそれを信頼するかどうかは、第 <a href="EvidenceQuality.html#EvidenceQuality">14</a> 章で説明されている研究診断ではカバーされていない多くの要因に依存します。</p>
</div>
</div>
<div id="まとめ-9" class="section level2 hasAnchor" number="12.10">
<h2><span class="header-section-number">12.10</span> まとめ<a href="PopulationLevelEstimation.html#まとめ-9" class="anchor-section" aria-label="Anchor link to header"></a></h2>

<div class="rmdsummary">
<ul>
<li><p>集団レベルの推定は、観察データから因果効果を推測することを目的としています。</p></li>
<li><p><strong>反事実</strong>とは、対象者が別の曝露または何も曝露を受けなかった場合に何が起こったかということですが、それは観察できません。</p></li>
<li><p>異なるデザインは、異なる方法で反事実を構築することを目的としています。</p></li>
<li><p>OHDSI Methods Libraryに実装されているさまざまなデザインは、適切な反事実を作成するための仮定が満たされているかどうかを評価するための診断を提供します。</p></li>
</ul>
</div>
</div>
<div id="演習-7" class="section level2 hasAnchor" number="12.11">
<h2><span class="header-section-number">12.11</span> 演習<a href="PopulationLevelEstimation.html#演習-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="前提条件-7" class="section level4 unnumbered hasAnchor">
<h4>前提条件<a href="PopulationLevelEstimation.html#前提条件-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>これらの演習を行うためには、R、R-Studio、およびJavaがセクション <a href="OhdsiAnalyticsTools.html#installR">8.4.5</a> で説明されているようにインストールされていることを前提とします。また、<a href="https://ohdsi.github.io/SqlRender/">SqlRender</a>、<a href="https://ohdsi.github.io/DatabaseConnector/">DatabaseConnector</a>、<a href="https://ohdsi.github.io/Eunomia/">Eunomia</a>、および<a href="https://ohdsi.github.io/CohortMethod/">CohortMethod</a>パッケージも必要です。これらは次のコマンドでインストールできます：</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="PopulationLevelEstimation.html#cb113-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;SqlRender&quot;</span>, <span class="st">&quot;DatabaseConnector&quot;</span>, <span class="st">&quot;remotes&quot;</span>))</span>
<span id="cb113-2"><a href="PopulationLevelEstimation.html#cb113-2" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;ohdsi/Eunomia&quot;</span>, <span class="at">ref =</span> <span class="st">&quot;v1.0.0&quot;</span>)</span>
<span id="cb113-3"><a href="PopulationLevelEstimation.html#cb113-3" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;ohdsi/CohortMethod&quot;</span>)</span></code></pre></div>
<p>Eunomiaパッケージは、ローカルのRセッション内で実行されるCDM内のシミュレートされたデータセットを提供します。接続の詳細は次のコマンドで取得できます：</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="PopulationLevelEstimation.html#cb114-1" tabindex="-1"></a>connectionDetails <span class="ot">&lt;-</span> Eunomia<span class="sc">::</span><span class="fu">getEunomiaConnectionDetails</span>()</span></code></pre></div>
<p>CDMデータベースのスキーマは「main」です。また、これらの演習ではいくつかのコホートも使用します。Eunomiaパッケージの<code>createCohorts</code>関数を使用して、これらをCOHORTテーブル内に作成できます：</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="PopulationLevelEstimation.html#cb115-1" tabindex="-1"></a>Eunomia<span class="sc">::</span><span class="fu">createCohorts</span>(connectionDetails)</span></code></pre></div>
</div>
<div id="問題定義" class="section level4 unnumbered hasAnchor">
<h4>問題定義<a href="PopulationLevelEstimation.html#問題定義" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<blockquote>
<p>セレコキシブの新規使用者とジクロフェナクの新規使用者における消化管（GI）出血のリスクは？</p>
</blockquote>
<p>セレコキシブ新規使用者コホートのCOHORT_DEFINITION_IDは1です。ジクロフェナク新規使用者コホートのCOHORT_DEFINITION_IDは2です。GI出血コホートのCOHORT_DEFINITION_IDは3です。セレコキシブとジクロフェナクの成分コンセプトIDは、それぞれ1118084と1124300です。リスク期間は治療開始の日から始まり、観察終了時に終了します（いわゆる治療意図分析）。</p>
<div class="exercise">
<p><span id="exr:exercisePle1" class="exercise"><strong>演習 12.1  </strong></span>CohortMethod Rパッケージを使用して、デフォルトの共変量セットを使用し、CDMからCohortMethodDataを抽出します。CohortMethodDataのサマリーを作成します。</p>
</div>
<div class="exercise">
<p><span id="exr:exercisePle2" class="exercise"><strong>演習 12.2  </strong></span><code>createStudyPopulation</code>関数を使用して、180日間のウォッシュアウト期間を必要とし、アウトカムの既往のある人を除外し、両方のコホートに出現する人は除外して、研究対象集団を作成します。脱落した人は何人ですか？</p>
</div>
<div class="exercise">
<p><span id="exr:exercisePle3" class="exercise"><strong>演習 12.3  </strong></span>調整を行わずにコックス比例ハザードモデルを適合させます。これを行うと何が問題になるでしょうか？</p>
</div>
<div class="exercise">
<p><span id="exr:exercisePle4" class="exercise"><strong>演習 12.4  </strong></span>傾向スコアモデルを適合させます。2つの群は比較可能ですか？</p>
</div>
<div class="exercise">
<p><span id="exr:exercisePle5" class="exercise"><strong>演習 12.5  </strong></span>5つの層を用いてPS層別化を行います。共変量のバランスは達成されましたか？</p>
</div>
<div class="exercise">
<p><span id="exr:exercisePle6" class="exercise"><strong>演習 12.6  </strong></span>PS層を使用してコックス比例ハザードモデルを適合させます。そのアウトカムが未調整モデルと異なる理由は何ですか？</p>
</div>
<p>解答例は付録 <a href="SuggestedAnswers.html#Pleanswers">E.8</a> を参照ください。</p>

</div>
</div>
</div>
<h3>参考文献<a href="参考文献.html#参考文献" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-austin_2011" class="csl-entry">
Austin, Peter C. 2011. <span>“Optimal Caliper Widths for Propensity-Score Matching When Estimating Differences in Means and Differences in Proportions in Observational Studies.”</span> <em>Pharmaceutical Statistics</em> 10 (2): 150–61.
</div>
<div id="ref-farrington_1995" class="csl-entry">
Farrington, C. P. 1995. <span>“<span class="nocase"><span>R</span>elative incidence estimation from case series for vaccine safety evaluation</span>.”</span> <em>Biometrics</em> 51 (1): 228–35.
</div>
<div id="ref-farrington_2011" class="csl-entry">
Farrington, C. P., Karim Anaya-Izquierdo, Heather J. Whitaker, Mounia N. Hocine, Ian Douglas, and Liam Smeeth. 2011. <span>“Self-Controlled Case Series Analysis with Event-Dependent Observation Periods.”</span> <em>Journal of the American Statistical Association</em> 106 (494): 417–26. <a href="https://doi.org/10.1198/jasa.2011.ap10108">https://doi.org/10.1198/jasa.2011.ap10108</a>.
</div>
<div id="ref-hernan_2002" class="csl-entry">
Hernan, M. A., S. Hernandez-Diaz, M. M. Werler, and A. A. Mitchell. 2002. <span>“<span class="nocase"><span>C</span>ausal knowledge as a prerequisite for confounding evaluation: an application to birth defects epidemiology</span>.”</span> <em>Am. J. Epidemiol.</em> 155 (2): 176–84.
</div>
<div id="ref-hernan_2016" class="csl-entry">
Hernan, M. A., and J. M. Robins. 2016. <span>“<span class="nocase"><span>U</span>sing <span>B</span>ig <span>D</span>ata to <span>E</span>mulate a <span>T</span>arget <span>T</span>rial <span>W</span>hen a <span>R</span>andomized <span>T</span>rial <span>I</span>s <span>N</span>ot <span>A</span>vailable</span>.”</span> <em>Am. J. Epidemiol.</em> 183 (8): 758–64.
</div>
<div id="ref-maclure_1991" class="csl-entry">
Maclure, M. 1991. <span>“<span class="nocase"><span>T</span>he case-crossover design: a method for studying transient effects on the risk of acute events</span>.”</span> <em>Am. J. Epidemiol.</em> 133 (2): 144–53.
</div>
<div id="ref-magid_2010" class="csl-entry">
Magid, D. J., S. M. Shetterly, K. L. Margolis, H. M. Tavel, P. J. O’Connor, J. V. Selby, and P. M. Ho. 2010. <span>“<span class="nocase"><span>C</span>omparative effectiveness of angiotensin-converting enzyme inhibitors versus beta-blockers as second-line therapy for hypertension</span>.”</span> <em>Circ Cardiovasc Qual Outcomes</em> 3 (5): 453–58.
</div>
<div id="ref-powers_2012" class="csl-entry">
Powers, B. J., R. R. Coeytaux, R. J. Dolor, V. Hasselblad, U. D. Patel, W. S. Yancy, R. N. Gray, R. J. Irvine, A. S. Kendrick, and G. D. Sanders. 2012. <span>“<span class="nocase"><span>U</span>pdated report on comparative effectiveness of <span>A</span><span>C</span><span>E</span> inhibitors, <span>A</span><span>R</span><span>B</span>s, and direct renin inhibitors for patients with essential hypertension: much more data, little new information</span>.”</span> <em>J Gen Intern Med</em> 27 (6): 716–29.
</div>
<div id="ref-rassen_2012" class="csl-entry">
Rassen, J. A., A. A. Shelat, J. Myers, R. J. Glynn, K. J. Rothman, and S. Schneeweiss. 2012. <span>“<span class="nocase"><span>O</span>ne-to-many propensity score matching in cohort studies</span>.”</span> <em>Pharmacoepidemiol Drug Saf</em> 21 Suppl 2 (May): 69–80.
</div>
<div id="ref-rosenbaum_1983" class="csl-entry">
Rosenbaum, P., and D. Rubin. 1983. <span>“The Central Role of the Propensity Score in Observational Studies for Causal Effects.”</span> <em>Biometrika</em> 70 (April): 41–55. <a href="https://doi.org/10.1093/biomet/70.1.41">https://doi.org/10.1093/biomet/70.1.41</a>.
</div>
<div id="ref-rubin_2001" class="csl-entry">
Rubin, Donald B. 2001. <span>“Using Propensity Scores to Help Design Observational Studies: Application to the Tobacco Litigation.”</span> <em>Health Services and Outcomes Research Methodology</em> 2 (3-4): 169–88.
</div>
<div id="ref-ryan_2013" class="csl-entry">
Ryan, P. B., M. J. Schuemie, and D. Madigan. 2013. <span>“<span class="nocase"><span>E</span>mpirical performance of a self-controlled cohort method: lessons for developing a risk identification and analysis system</span>.”</span> <em>Drug Saf</em> 36 Suppl 1 (October): 95–106.
</div>
<div id="ref-sabroe_1997" class="csl-entry">
Sabroe, R. A., and A. K. Black. 1997. <span>“<span class="nocase"><span>A</span>ngiotensin-converting enzyme (<span>A</span><span>C</span><span>E</span>) inhibitors and angio-oedema</span>.”</span> <em>Br. J. Dermatol.</em> 136 (2): 153–58.
</div>
<div id="ref-schneeweiss_2018" class="csl-entry">
Schneeweiss, S. 2018. <span>“<span class="nocase"><span>A</span>utomated data-adaptive analytics for electronic healthcare data to study causal treatment effects</span>.”</span> <em>Clin Epidemiol</em> 10: 771–88.
</div>
<div id="ref-simpson_2013" class="csl-entry">
Simpson, S. E., D. Madigan, I. Zorych, M. J. Schuemie, P. B. Ryan, and M. A. Suchard. 2013. <span>“<span class="nocase"><span>M</span>ultiple self-controlled case series for large-scale longitudinal observational databases</span>.”</span> <em>Biometrics</em> 69 (4): 893–902.
</div>
<div id="ref-suchard_2013" class="csl-entry">
Suchard, M. A., S. E. Simpson, Ivan Zorych, P. B. Ryan, and David Madigan. 2013. <span>“Massive Parallelization of Serial Inference Algorithms for a Complex Generalized Linear Model.”</span> <em>ACM Trans. Model. Comput. Simul.</em> 23 (1): 10:1–17. <a href="https://doi.org/10.1145/2414416.2414791">https://doi.org/10.1145/2414416.2414791</a>.
</div>
<div id="ref-suissa_1995" class="csl-entry">
Suissa, S. 1995. <span>“<span class="nocase"><span>T</span>he case-time-control design</span>.”</span> <em>Epidemiology</em> 6 (3): 248–53.
</div>
<div id="ref-tian_2018" class="csl-entry">
Tian, Y., M. J. Schuemie, and M. A. Suchard. 2018. <span>“<span class="nocase"><span>E</span>valuating large-scale propensity score performance through real-world and synthetic data experiments</span>.”</span> <em>Int J Epidemiol</em> 47 (6): 2005–14.
</div>
<div id="ref-toh_2012" class="csl-entry">
Toh, S., M. E. Reichman, M. Houstoun, M. Ross Southworth, X. Ding, A. F. Hernandez, M. Levenson, et al. 2012. <span>“<span class="nocase"><span>C</span>omparative risk for angioedema associated with the use of drugs that target the renin-angiotensin-aldosterone system</span>.”</span> <em>Arch. Intern. Med.</em> 172 (20): 1582–89.
</div>
<div id="ref-vandenbroucke_2012" class="csl-entry">
Vandenbroucke, J. P., and N. Pearce. 2012. <span>“<span class="nocase"><span>C</span>ase-control studies: basic concepts</span>.”</span> <em>Int J Epidemiol</em> 41 (5): 1480–89.
</div>
<div id="ref-walker_2013" class="csl-entry">
Walker, Alexander M, Amanda R Patrick, Michael S Lauer, Mark C Hornbrook, Matthew G Marin, Richard Platt, Véronique L Roger, Paul Stang, and Sebastian Schneeweiss. 2013. <span>“A Tool for Assessing the Feasibility of Comparative Effectiveness Research.”</span> <em>Comp Eff Res</em> 3: 11–20.
</div>
<div id="ref-whelton_2018" class="csl-entry">
Whelton, P. K., R. M. Carey, W. S. Aronow, D. E. Casey, K. J. Collins, C. Dennison Himmelfarb, S. M. DePalma, et al. 2018. <span>“<span class="nocase">2017 <span>A</span><span>C</span><span>C</span>/<span>A</span><span>H</span><span>A</span>/<span>A</span><span>A</span><span>P</span><span>A</span>/<span>A</span><span>B</span><span>C</span>/<span>A</span><span>C</span><span>P</span><span>M</span>/<span>A</span><span>G</span><span>S</span>/<span>A</span><span>P</span>h<span>A</span>/<span>A</span><span>S</span><span>H</span>/<span>A</span><span>S</span><span>P</span><span>C</span>/<span>N</span><span>M</span><span>A</span>/<span>P</span><span>C</span><span>N</span><span>A</span> <span>G</span>uideline for the <span>P</span>revention, <span>D</span>etection, <span>E</span>valuation, and <span>M</span>anagement of <span>H</span>igh <span>B</span>lood <span>P</span>ressure in <span>A</span>dults: <span>E</span>xecutive <span>S</span>ummary: <span>A</span> <span>R</span>eport of the <span>A</span>merican <span>C</span>ollege of <span>C</span>ardiology/<span>A</span>merican <span>H</span>eart <span>A</span>ssociation <span>T</span>ask <span>F</span>orce on <span>C</span>linical <span>P</span>ractice <span>G</span>uidelines</span>.”</span> <em>Circulation</em> 138 (17): e426–83.
</div>
<div id="ref-whitaker_2006" class="csl-entry">
Whitaker, H. J., C. P. Farrington, B. Spiessens, and P. Musonda. 2006. <span>“<span class="nocase"><span>T</span>utorial in biostatistics: the self-controlled case series method</span>.”</span> <em>Stat Med</em> 25 (10): 1768–97.
</div>
<div id="ref-Wickham_2015" class="csl-entry">
Wickham, Hadley. 2015. <em>R Packages</em>. 1st ed. O’Reilly Media, Inc.
</div>
<div id="ref-zaman_2002" class="csl-entry">
Zaman, M. A., S. Oparil, and D. A. Calhoun. 2002. <span>“<span class="nocase"><span>D</span>rugs targeting the renin-angiotensin-aldosterone system</span>.”</span> <em>Nat Rev Drug Discov</em> 1 (8): 621–36.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="Characterization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="PatientLevelPrediction.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/OHDSI/TheBookOfOhdsiInJapanese/edit/main/PopulationLevelEstimation.Rmd",
    "text": "エディション"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
